include:
  - project: 'software/conan/conan-ci-pipelines-common'
    ref: master
    file: 'mr/common.yaml'

variables:
  GIT_SUBMODULE_STRATEGY: none
  # https://docs.gitlab.com/ee/ci/runners/configure_runners.html#job-stages-attempts 
  ARTIFACT_DOWNLOAD_ATTEMPTS: 5
  EXECUTOR_JOB_SECTION_ATTEMPTS: 5
  GET_SOURCES_ATTEMPTS: 5
  RESTORE_CACHE_ATTEMPTS: 5


###############################################################################
###############################################################################
###############################################################################

gen_conan_build_pipeline:
  extends: .template_job_k8s_with_conan_ci_pipelines_common
  stage: .pre
  image: conanio/gcc7-ubuntu16.04
  script:

    # generate pipeline
    - |
      conan-ci-pipelines-common/gen-build-pipeline.py \
          ci/src/conan.yaml \
          conan-ci-pipelines-common/consumers.yaml \
          conan-ci-pipelines-common/configs.yaml \
          -o build-pipeline.yaml

    - sh -c -x "${CMD_AFTER_GENERATE_PIPELINE}"

###############################################################################
###############################################################################
###############################################################################

conan_build_pipeline:
  stage: build
  needs:
    - gen_conan_build_pipeline
  variables:
    UPSTREAM_PROJECT_NAME:      ${CI_PROJECT_NAME}
    UPSTREAM_CI_PIPELINE_ID:    ${CI_PIPELINE_ID}
    CONAN_CI_PIPELINES_COMMON_REF: ${CONAN_CI_PIPELINES_COMMON_REF}
    CONAN_CONFIG_EXTRA_ARGS: ${CONAN_CONFIG_EXTRA_ARGS}
  trigger:
    include:
      - artifact: build-pipeline.yaml
        job: gen_conan_build_pipeline
    strategy: depend

###############################################################################
###############################################################################
###############################################################################

on_success:promote:
  extends: .template_job_k8s_with_conan_ci_pipelines_common_on_success_perform_promote
  stage: deploy
  needs:
    - gen_conan_build_pipeline
    - conan_build_pipeline

on_failure:report:
  extends: .template_job_k8s_bare_minimum_on_failure_report
  stage: deploy
