include:
  - project: 'software/gitlab-ci-common'
    ref: ec8109263042925b169aa3c33cd6e7beaf185917
    file:
      - rules/generic-workflow-conan.yaml
      - pods/nano-pod.yaml
      - pods/large-pod.yaml
      - jobs/generic-k8s-job.yaml
      - jobs/sonarqube-job.yaml
      - rules/exec_maybe_interactively.yaml
      - jobs/check-top-of-master.yaml
      - jobs/sw-platform-trigger.yaml

  - project: 'software/gitlab-ci-common'
    ref: master
    file:
      - 'jobs/conan-jobs.yaml'

  - project: 'software/sw-platform'
    ref: develop/system-sw
    file:
      - 'gitlab-ci/system-sw/misc/verify-merge-request.yaml'

stages:
  - smoke
  - generate_build
  - build
  - test
  - deploy

default:
  interruptible: true

variables:
  # These two variables are consumed by the jobs from /jobs/sw-platform-trigger.yaml
  SW_PLATFORM_BRANCH: develop/system-sw
  PIPELINE_CI_SUBPROJECT: device-layer

###############################################################################
###############################################################################
###############################################################################

verify_project_changes:
  extends:
    - .template_job
    - .pod_nano
    - .verify_merge_request
  image: docker-sw-team.sc-artifactory1.esperanto.ai/convoke/centos-7.9.2009-et-sw-platform:0.3.7
  stage: .pre
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  variables:
    PROJ_VER_FILE_NAME: CMakeLists.txt

###############################################################################
###############################################################################
###############################################################################

smoke_tests:conan:sysemu:
  extends:
    - .pod_large
    - .template_job
    - .template-conan-linux-ubuntu18.04-gcc7
  
  stage: smoke

  parallel:
    matrix:
      - BUILD_TYPE: [ Release, Debug ]
  
  variables:
    TIMEOUT: 30m

    CMD_BUILD: |
      BUILD_TYPE_LOWER=$(echo "${BUILD_TYPE}" | tr '[:upper:]' '[:lower:]')
      sudo apt install ninja-build
      conan remote disable conan-tmp
      conan install . -pr:b default -pr:h linux-ubuntu18.04-x86_64-gcc7-${BUILD_TYPE_LOWER} -o deviceLayer:with_tests=True --build missing
      cmake --preset ${BUILD_TYPE} -G Ninja
      cmake --build --preset ${BUILD_TYPE}
      cd cmake-build-${BUILD_TYPE_LOWER}/tests/integration
      ctest --output-on-failure

###############################################################################
###############################################################################
###############################################################################

generate_build:conan:
  extends:
    - .pod_nano
    - .template_job
    - .template-conan-linux-ubuntu18.04-gcc7
  stage: generate_build

  variables:
    TIMEOUT: 15m

    CMD_BUILD: |
      cd conan
      python3 -m ci_build
  
  artifacts:
    expire_in: 1h 
    paths:
      - conan/build_pipeline.yml
      - conan/lockfiles_info.json

###############################################################################
###############################################################################
###############################################################################

build:conan:
  extends:
    - .exec_maybe_interactively
  stage: build
  needs:
    - generate_build:conan
  trigger:
    include:
    - artifact: conan/build_pipeline.yml
      job: generate_build:conan
    strategy: depend

###############################################################################
###############################################################################
###############################################################################

# integration testing with sw-platform
#
# This is automatically done thanks to this included file:
#   /jobs/sw-platform-trigger.yaml

###############################################################################
###############################################################################
###############################################################################

on_success:promote:
  extends:
    - .pod_nano
    - .template_job
    - .template-conan-linux-ubuntu18.04-gcc7
  
  stage: deploy

  needs:
    - generate_build:conan
    - build:conan
    - meta-trigger
  
  variables:
    PYTHONIOENCODING: utf-8
    CMD_BUILD: |
      cd conan
      python3 -m ci_promote
