include:
  - project: esperantotech/software/gitlab-ci-common
    ref: 1be8a1ec31da665910e1b2b193fcfa1d05866299
    file:
      - rules/generic-workflow-conan.yaml
      - pods/nano-pod.yaml
      - pods/large-pod.yaml
      - jobs/generic-k8s-job.yaml
      - jobs/sonarqube-job.yaml
      - rules/exec_maybe_interactively.yaml
      - /jobs/check-top-of-master-template.yaml
      - /jobs/sw-platform-trigger-template.yaml

  - project: esperantotech/software/gitlab-ci-common
    ref: master
    file:
      - 'jobs/conan-jobs.yaml'

  - project: esperantotech/software/sw-platform
    ref: develop/system-sw
    file:
      - 'gitlab-ci/system-sw/misc/verify-merge-request.yaml'

stages:
  - smoke
  - generate_build
  - build
  - test
  - deploy

default:
  interruptible: true

variables:
  # These two variables are consumed by the jobs from /jobs/sw-platform-trigger.yaml
  SW_PLATFORM_BRANCH: develop/system-sw
  PIPELINE_CI_SUBPROJECT: device-layer

# Only run job in these cases:
# - if it's a tag pipeline
# - if there is a commit pushed or merged to the default branch (pre-release)
.release_job:
  rules:
    - &release_job_rule
      if: $CI_COMMIT_TAG || ($CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH)

# Only run job in these cases:
# - if it's a tag pipeline
# - if there is a commit pushed or merged to the default branch (pre-release)
# - if there is a MR open (pre-release, unstable)
.release_or_development_job:
  rules:
    - &release_or_development_job_rule
      if: $CI_COMMIT_TAG || ($CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH) || ($CI_PIPELINE_SOURCE == "merge_request_event")

# Only run job in these cases:
# - if there is a MR open
.development_job:
  rules:
    - &development_job_rule
      if: ($CI_PIPELINE_SOURCE == "merge_request_event") && ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH)


###############################################################################
###############################################################################
###############################################################################

verify_project_changes:
  extends:
    - .template_job
    - .pod_nano
    - .verify_merge_request
  image: docker-sw-team.sc-artifactory1.esperanto.ai/convoke/centos-7.9.2009-et-sw-platform:0.3.7
  stage: .pre
  rules:
    - *development_job_rule
  variables:
    PROJ_VER_FILE_NAME: CMakeLists.txt

check-on-top-of-master:
  extends: .check-on-top-of-master
  stage: .pre
  needs: []
  rules:
    - *development_job_rule

###############################################################################
###############################################################################
###############################################################################

smoke_tests:conan:sysemu:
  extends:
    - .pod_large
    - .template_job
    - .template-conan-linux-ubuntu18.04-gcc7
  stage: smoke
  needs: 
    - job: verify_project_changes
      optional: true
  rules:
    - *development_job_rule
  parallel:
    matrix:
      - BUILD_TYPE: [ Release, Debug ]
  variables:
    TIMEOUT: 30m
    CMD_BUILD: |
      BUILD_TYPE_LOWER=$(echo "${BUILD_TYPE}" | tr '[:upper:]' '[:lower:]')
      sudo apt install ninja-build
      conan remote disable conan-tmp
      conan install . -pr:b default -pr:h linux-ubuntu18.04-x86_64-gcc7-$${BUILD_TYPE_LOWER} -o deviceLayer:with_tests=True --build missing
      cmake --preset $${BUILD_TYPE_LOWER} -G Ninja
      cmake --build --preset $${BUILD_TYPE_LOWER}
      cd build/${BUILD_TYPE}/tests/integration
      ctest --output-on-failure

###############################################################################
###############################################################################
###############################################################################

create-sw-platform-branch:
  extends: .create-sw-platform-branch
  stage: generate_build
  needs:
    - check-on-top-of-master
  rules:
    - *development_job_rule

generate_build:conan:
  extends:
    - .pod_nano
    - .template_job
    - .template-conan-linux-ubuntu18.04-gcc7
  stage: generate_build
  needs:
    - job: check-on-top-of-master
      optional: true
    - job: smoke_tests:conan:sysemu
      optional: true
  rules:
    - *release_or_development_job_rule
  variables:
    TIMEOUT: 15m
    CMD_BUILD: |
      cd conan
      python3 -m pip install "ecpt>=2.0.0,<3.0.0" --index-url https://sc-artifactory1.esperanto.ai/artifactory/api/pypi/pypi-virtual/simple
      python3 -m ci_build
  artifacts:
    expire_in: 6h 
    paths:
      - conan/build_pipeline.yml
      - conan/lockfiles_info.json

###############################################################################
###############################################################################
###############################################################################

create-sw-platform-trigger:
  extends: .create-sw-platform-trigger
  stage: build
  needs:
    - create-sw-platform-branch
  rules:
    - *development_job_rule

build:conan:
  extends:
    - .exec_maybe_interactively
  stage: build
  needs:
    - generate_build:conan
  rules:
    - *release_or_development_job_rule
  trigger:
    include:
    - artifact: conan/build_pipeline.yml
      job: generate_build:conan
    strategy: depend

###############################################################################
###############################################################################
###############################################################################

#
# This is automatically done thanks to this included file:
#   /jobs/sw-platform-trigger.yaml
tests:integration-repo:
  extends: .meta-trigger
  stage: test
  needs:
    - create-sw-platform-trigger
    - build:conan
  rules:
    - *development_job_rule
  trigger:
    strategy: depend
    include:
      - artifact: generated-trigger-job.yaml
        job: create-sw-platform-trigger

###############################################################################
###############################################################################
###############################################################################

on_success:promote:
  extends:
    - .pod_nano
    - .template_job
    - .template-conan-linux-ubuntu18.04-gcc7
  
  stage: deploy

  needs:
    - generate_build:conan
    - build:conan

  rules:
    - *release_job_rule

  variables:
    PYTHONIOENCODING: utf-8
    CMD_BUILD: |
      cd conan
      python3 -m pip install "ecpt>=2.0.0,<3.0.0" --index-url https://sc-artifactory1.esperanto.ai/artifactory/api/pypi/pypi-virtual/simple
      python3 -m ci_promote
