/* Auto-generated by top2h.py from top_cpu_mm.rdl. Do not edit. */
#ifndef _TOP_H_
#define _TOP_H_

/* ============================================================ */
/* Top map: ErbiumCPU_MemoryMap */
/* ============================================================ */

/* Instance: System_Reg system_registers */
#define ERBIUM_TOP_SYSTEM_REGISTERS_BASE 0x02000000ul
#define ERBIUM_TOP_SYSTEM_REGISTERS_SIZE 0x00000094ul
#define ERBIUM_TOP_SYSTEM_REGISTERS_END 0x02000094ul

/* Instance: axi2mram_bridge_registers mram_registers */
#define ERBIUM_TOP_MRAM_REGISTERS_BASE 0x02001000ul
#define ERBIUM_TOP_MRAM_REGISTERS_SIZE 0x00000470ul
#define ERBIUM_TOP_MRAM_REGISTERS_END 0x02001470ul

/* Instance: I2C_Reg i2c_registers */
#define ERBIUM_TOP_I2C_REGISTERS_BASE 0x02002000ul
#define ERBIUM_TOP_I2C_REGISTERS_SIZE 0x00000024ul
#define ERBIUM_TOP_I2C_REGISTERS_END 0x02002024ul

/* Instance: QSPI_Reg qspi_registers */
#define ERBIUM_TOP_QSPI_REGISTERS_BASE 0x02003000ul
#define ERBIUM_TOP_QSPI_REGISTERS_SIZE 0x00000064ul
#define ERBIUM_TOP_QSPI_REGISTERS_END 0x02003064ul

/* Instance: UART_Reg uart_registers */
#define ERBIUM_TOP_UART_REGISTERS_BASE 0x02004000ul
#define ERBIUM_TOP_UART_REGISTERS_SIZE 0x00000044ul
#define ERBIUM_TOP_UART_REGISTERS_END 0x02004044ul

/* Instance: memories ROMRAM */
#define ERBIUM_TOP_ROMRAM_BASE 0x02008000ul
#define ERBIUM_TOP_ROMRAM_SIZE 0x00005000ul
#define ERBIUM_TOP_ROMRAM_END 0x0200D000ul

/* Instance: external bootrom ROM */
#define ERBIUM_TOP_BOOTROM_BASE 0x02008000ul
#define ERBIUM_TOP_BOOTROM_SIZE 0x00002000ul
#define ERBIUM_TOP_BOOTROM_END 0x0200A000ul

/* Instance: external sram SRAM */
#define ERBIUM_TOP_SRAM_BASE 0x0200C000ul
#define ERBIUM_TOP_SRAM_SIZE 0x00001000ul
#define ERBIUM_TOP_SRAM_END 0x0200D000ul

/* Instance: SCCR_Reg xspi_registers */
#define ERBIUM_TOP_XSPI_REGISTERS_BASE 0x0200F000ul
#define ERBIUM_TOP_XSPI_REGISTERS_SIZE 0x0000001Cul
#define ERBIUM_TOP_XSPI_REGISTERS_END 0x0200F01Cul

/* Instance: config nic_config */
#define ERBIUM_TOP_NIC_CONFIG_BASE 0xFE000000ul
#define ERBIUM_TOP_NIC_CONFIG_SIZE 0x00016000ul
#define ERBIUM_TOP_NIC_CONFIG_END 0xFE016000ul

/* Instance: external ni700_registers ni700_registers */
#define ERBIUM_TOP_NI700_REGISTERS_BASE 0xFE000000ul
#define ERBIUM_TOP_NI700_REGISTERS_SIZE 0x00016000ul
#define ERBIUM_TOP_NI700_REGISTERS_END 0xFE016000ul

/* Instance: external mram mram */
#define ERBIUM_TOP_MRAM_BASE 0x40000000ul
#define ERBIUM_TOP_MRAM_SIZE 0x01000000ul
#define ERBIUM_TOP_MRAM_END 0x41000000ul

/* Instance: Erbium_ESR cpu_registers */
#define ERBIUM_TOP_CPU_REGISTERS_BASE 0x80000000ul
#define ERBIUM_TOP_CPU_REGISTERS_SIZE 0x00F40318ul
#define ERBIUM_TOP_CPU_REGISTERS_END 0x80F40318ul

/* Instance: PLIC_cpu plic */
#define ERBIUM_TOP_PLIC_BASE 0xA0000000ul
#define ERBIUM_TOP_PLIC_SIZE 0x0021F008ul
#define ERBIUM_TOP_PLIC_END 0xA021F008ul

#endif /* _TOP_H_ */
