#ifndef SYSCALL_INTERNAL_H
#define SYSCALL_INTERNAL_H

#define SYSCALL_BROADCAST_INT               1
#define SYSCALL_IPI_TRIGGER_INT             2
#define SYSCALL_ENABLE_THREAD1_INT          3
#define SYSCALL_PRE_KERNEL_SETUP_INT        4
#define SYSCALL_POST_KERNEL_CLEANUP_INT     5
#define SYSCALL_CACHE_CONTROL_INT           6
#define SYSCALL_FLUSH_L3_INT                7
#define SYSCALL_EVICT_L3_INT                8
#define SYSCALL_SHIRE_CACHE_BANK_OP_INT     9
#define SYSCALL_CONFIGURE_COMPUTE_MINION    10
#define SYSCALL_CACHE_OPS_EVICT_SW_INT      11
#define SYSCALL_CACHE_OPS_FLUSH_SW_INT      12
#define SYSCALL_CACHE_OPS_LOCK_SW_INT       13
#define SYSCALL_CACHE_OPS_UNLOCK_SW_INT     14
#define SYSCALL_CACHE_OPS_INVALIDATE_INT    15
#define SYSCALL_CACHE_OPS_EVICT_L1_INT      16
#define SYSCALL_UPDATE_MINION_PLL_FREQUENCY 17
#define SYSCALL_PMC_SC_SAMPLE_INT           18
#define SYSCALL_PMC_MS_SAMPLE_INT           19
#define SYSCALL_DISABLE_NEIGH               20
#define SYSCALL_ENABLE_NEIGH                21
#define SYSCALL_PMC_SC_SAMPLE_ALL_INT       22
#define SYSCALL_PMC_MS_SAMPLE_ALL_INT       23
#define SYSCALL_CACHE_OPS_EVICT_WHOLE_L1_L2_INT 24

/* SYSCALL error codes */
#define SYSCALL_INTERNAL_SUCCESS    0
#define SYSCALL_INTERNAL_INVALID_ID -1

#endif // SYSCALL_INTERNAL_H
