registers:
  ['x0', 'x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'x8', 'x9', 'x10', 'x11', 'x12', 'x13', 'x14', 'x15', 'x16', 'x17', 'x18', 'x19', 'x20', 'x21', 'x22', 'x23', 'x24', 'x25', 'x26', 'x27', 'x28', 'x29', 'x30', 'x31']

# rd/rs1/rs2: registers
# imm: immediate

categories: ['rv64i', 'rv64m']

rv64i:
  add: ['rd', 'rs1', 'rs2']
  addi: ['rd', 'rs1', 'imm']
  # addiw: ['rd', 'rs1', 'imm']
  and: ['rd', 'rs1', 'rs2']
  andi: ['rd', 'rs1', 'imm']

# zifencei:
#   fence_i: ['bit']

rv64m:
  div: ['rd', 'rs1', 'rs2']
  divu: ['rd', 'rs1', 'rs2']
  # divuw: ['rd', 'rs1', 'rs2']
  # divw: ['rd', 'rs1', 'rs2']
  mul: ['rd', 'rs1', 'rs2']
  rem: ['rd', 'rs1', 'rs2']
  remu: ['rd', 'rs1', 'rs2']