import:
  - path: '@ci@/ci-tools/templates/template-main-top-level.yaml'

parameters:
  SW_PLATFORM_BRANCH:
    description: SW-Platform branch to track
    type: string
    default_value: "origin/develop/system-sw"
  REPO_SSH_URL:
    description: Repository URL
    type: string
    default_value: "git@gitlab.esperanto.ai:software/sw-sysemu.git"
  REPO_NAME:
    description: Repository name
    type: string
    default_value: "sw-sysemu"

stages:
  JOB_RUNTIME:
    cmds:
      - job: sw-platform/runtime-integration/pipelines/runtime-checkin-tests-release
        parameters:
          BRANCH: "${SW_PLATFORM_BRANCH}"
          COMPONENT_COMMITS: "${COMPONENT_COMMITS},tools/sw-sysemu:${BRANCH}"

  JOB_DEVICE_MANAGEMENT:
    cmds:
      - job: sw-platform/system-sw-integration/pipelines/device-management-checkin-tests/
        parameters:
          BRANCH: "${SW_PLATFORM_BRANCH}"
          COMPONENT_COMMITS: "${COMPONENT_COMMITS},tools/sw-sysemu:${BRANCH}"
          PYTEST_RETRIES: "2"

  JOB_DEVICE_LAYER:
    cmds:
      - job: sw-platform/system-sw-integration/pipelines/device-layer-checkin-tests/
        parameters:
          BRANCH: "${SW_PLATFORM_BRANCH}"
          COMPONENT_COMMITS: "${COMPONENT_COMMITS},tools/sw-sysemu:${BRANCH}"

  JOB_CODE_QUALITY:
    cmds:
      - job: sw-platform/code-analysis/sw-sysemu-sonarqube
        parameters:
          BRANCH: "${SW_PLATFORM_BRANCH}"
          COMPONENT_COMMITS: "${COMPONENT_COMMITS},tools/sw-sysemu:${BRANCH}"
          GITLAB_SOURCE_BRANCH:
            raw_cmd: '"${env.gitlabSourceBranch}"'
          GITLAB_TARGET_BRANCH:
            raw_cmd: '"${env.gitlabTargetBranch}"'
          GITLAB_MR_ID:
            raw_cmd: '"${env.gitlabMergeRequestIid}"'