/*                                                                         */
/*                                                                         */
/* Generated by Semifore, Inc. csrCompile                                  */
/*    C Header output                                                      */

#ifndef _ETSOC_MEM_SHIRE_ESR_H_
#define _ETSOC_MEM_SHIRE_ESR_H_



/* ####################################################################### */
/*        ADDRESS MACROS                                                   */
/* ####################################################################### */

/* Address Space for Addressmap: etsoc_mem_shire_esr                       */
/* Source filename: etsoc_mem_shire_esr.csr, line: 246                     */
/* Register: etsoc_mem_shire_esr.ms_mem_ctl                                */
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ADDRESS 0x0u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_BYTE_ADDRESS 0x0u
/* Register: etsoc_mem_shire_esr.ms_atomic_sm_ctl                          */
#define ETSOC_MEM_SHIRE_ESR_MS_ATOMIC_SM_CTL_ADDRESS 0x1u
#define ETSOC_MEM_SHIRE_ESR_MS_ATOMIC_SM_CTL_BYTE_ADDRESS 0x8u
/* Register: etsoc_mem_shire_esr.ms_mem_revision_id                        */
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_ADDRESS 0x2u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_BYTE_ADDRESS 0x10u
/* Register: etsoc_mem_shire_esr.ms_clk_gate_ctl                           */
#define ETSOC_MEM_SHIRE_ESR_MS_CLK_GATE_CTL_ADDRESS 0x3u
#define ETSOC_MEM_SHIRE_ESR_MS_CLK_GATE_CTL_BYTE_ADDRESS 0x18u
/* Register: etsoc_mem_shire_esr.ms_mem_status                             */
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_STATUS_ADDRESS 0x4u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_STATUS_BYTE_ADDRESS 0x20u


/* ####################################################################### */
/*        TEMPLATE MACROS                                                  */
/* ####################################################################### */

/* Addressmap type: etsoc_mem_shire_esr                                    */
/* Addressmap template: etsoc_mem_shire_esr                                */
/* Source filename: etsoc_mem_shire_esr.csr, line: 24                      */
#define ETSOC_MEM_SHIRE_ESR_SIZE 0x8u
#define ETSOC_MEM_SHIRE_ESR_BYTE_SIZE 0x40u
/* Register member: etsoc_mem_shire_esr.ms_mem_ctl                         */
/* Register type referenced: etsoc_mem_shire_esr::ms_mem_ctl               */
/* Register template referenced: etsoc_mem_shire_esr::ms_mem_ctl           */
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_OFFSET 0x0u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_BYTE_OFFSET 0x0u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_READ_ACCESS 1u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_WRITE_ACCESS 1u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_RESET_VALUE 0x0000000000000000ull
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_RESET_MASK 0xfffc000000000000ull
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_READ_MASK 0xffffffffffffffffull
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_WRITE_MASK 0x0003ffffffffffffull
/* Register member: etsoc_mem_shire_esr.ms_atomic_sm_ctl                   */
/* Register type referenced: etsoc_mem_shire_esr::ms_atomic_sm_ctl         */
/* Register template referenced: etsoc_mem_shire_esr::ms_atomic_sm_ctl     */
#define ETSOC_MEM_SHIRE_ESR_MS_ATOMIC_SM_CTL_OFFSET 0x1u
#define ETSOC_MEM_SHIRE_ESR_MS_ATOMIC_SM_CTL_BYTE_OFFSET 0x8u
#define ETSOC_MEM_SHIRE_ESR_MS_ATOMIC_SM_CTL_READ_ACCESS 1u
#define ETSOC_MEM_SHIRE_ESR_MS_ATOMIC_SM_CTL_WRITE_ACCESS 1u
#define ETSOC_MEM_SHIRE_ESR_MS_ATOMIC_SM_CTL_RESET_VALUE 0x0000000000000000ull
#define ETSOC_MEM_SHIRE_ESR_MS_ATOMIC_SM_CTL_RESET_MASK 0xffffffffffffff0eull
#define ETSOC_MEM_SHIRE_ESR_MS_ATOMIC_SM_CTL_READ_MASK 0xffffffffffffffffull
#define ETSOC_MEM_SHIRE_ESR_MS_ATOMIC_SM_CTL_WRITE_MASK 0x00000000000000f1ull
/* Register member: etsoc_mem_shire_esr.ms_mem_revision_id                 */
/* Register type referenced: etsoc_mem_shire_esr::ms_mem_revision_id       */
/* Register template referenced: etsoc_mem_shire_esr::ms_mem_revision_id   */
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_OFFSET 0x2u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_BYTE_OFFSET 0x10u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_READ_ACCESS 1u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_WRITE_ACCESS 0u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_RESET_VALUE 0x0000000000000000ull
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_RESET_MASK 0xffff00ff00000000ull
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_READ_MASK 0xffffffffffffffffull
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_WRITE_MASK 0x0000000000000000ull
/* Register member: etsoc_mem_shire_esr.ms_clk_gate_ctl                    */
/* Register type referenced: etsoc_mem_shire_esr::ms_clk_gate_ctl          */
/* Register template referenced: etsoc_mem_shire_esr::ms_clk_gate_ctl      */
#define ETSOC_MEM_SHIRE_ESR_MS_CLK_GATE_CTL_OFFSET 0x3u
#define ETSOC_MEM_SHIRE_ESR_MS_CLK_GATE_CTL_BYTE_OFFSET 0x18u
#define ETSOC_MEM_SHIRE_ESR_MS_CLK_GATE_CTL_READ_ACCESS 1u
#define ETSOC_MEM_SHIRE_ESR_MS_CLK_GATE_CTL_WRITE_ACCESS 1u
#define ETSOC_MEM_SHIRE_ESR_MS_CLK_GATE_CTL_RESET_VALUE 0x0000000000000000ull
#define ETSOC_MEM_SHIRE_ESR_MS_CLK_GATE_CTL_RESET_MASK 0xfffffffffffffffeull
#define ETSOC_MEM_SHIRE_ESR_MS_CLK_GATE_CTL_READ_MASK 0xffffffffffffffffull
#define ETSOC_MEM_SHIRE_ESR_MS_CLK_GATE_CTL_WRITE_MASK 0x0000000000000001ull
/* Register member: etsoc_mem_shire_esr.ms_mem_status                      */
/* Register type referenced: etsoc_mem_shire_esr::ms_mem_status            */
/* Register template referenced: etsoc_mem_shire_esr::ms_mem_status        */
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_STATUS_OFFSET 0x4u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_STATUS_BYTE_OFFSET 0x20u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_STATUS_READ_ACCESS 1u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_STATUS_WRITE_ACCESS 0u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_STATUS_RESET_VALUE 0x0000000000000000ull
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_STATUS_RESET_MASK 0xfffffffffffffffcull
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_STATUS_READ_MASK 0xffffffffffffffffull
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_STATUS_WRITE_MASK 0x0000000000000000ull

/* Register type: etsoc_mem_shire_esr::ms_mem_ctl                          */
/* Register template: etsoc_mem_shire_esr::ms_mem_ctl                      */
/* Source filename: etsoc_mem_shire_esr.csr, line: 28                      */
/* Field member: etsoc_mem_shire_esr::ms_mem_ctl.esr_ms_mc_en              */
/* Source filename: etsoc_mem_shire_esr.csr, line: 107                     */
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_MC_EN_MSB 49u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_MC_EN_LSB 48u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_MC_EN_WIDTH 2u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_MC_EN_READ_ACCESS 1u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_MC_EN_WRITE_ACCESS 1u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_MC_EN_FIELD_MASK 0x0003000000000000ull
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_MC_EN_GET(x) \
   (((x) & 0x0003000000000000ull) >> 48)
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_MC_EN_SET(x) \
   (((x) << 48) & 0x0003000000000000ull)
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_MC_EN_MODIFY(r, x) \
   ((((x) << 48) & 0x0003000000000000ull) | ((r) & 0xfffcffffffffffffull))
/* Field member: etsoc_mem_shire_esr::ms_mem_ctl.esr_ms_addr_mask          */
/* Source filename: etsoc_mem_shire_esr.csr, line: 94                      */
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_MASK_MSB 47u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_MASK_LSB 36u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_MASK_WIDTH 12u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_MASK_READ_ACCESS 1u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_MASK_WRITE_ACCESS 1u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_MASK_FIELD_MASK 0x0000fff000000000ull
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_MASK_GET(x) \
   (((x) & 0x0000fff000000000ull) >> 36)
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_MASK_SET(x) \
   (((x) << 36) & 0x0000fff000000000ull)
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_MASK_MODIFY(r, x) \
   ((((x) << 36) & 0x0000fff000000000ull) | ((r) & 0xffff000fffffffffull))
/* Field member: etsoc_mem_shire_esr::ms_mem_ctl.esr_ms_addr_debug_mc_bit_sel */
/* Source filename: etsoc_mem_shire_esr.csr, line: 85                      */
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_DEBUG_MC_BIT_SEL_MSB 35u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_DEBUG_MC_BIT_SEL_LSB 30u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_DEBUG_MC_BIT_SEL_WIDTH 6u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_DEBUG_MC_BIT_SEL_READ_ACCESS 1u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_DEBUG_MC_BIT_SEL_WRITE_ACCESS 1u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_DEBUG_MC_BIT_SEL_FIELD_MASK 0x0000000fc0000000ull
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_DEBUG_MC_BIT_SEL_GET(x) \
   (((x) & 0x0000000fc0000000ull) >> 30)
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_DEBUG_MC_BIT_SEL_SET(x) \
   (((x) << 30) & 0x0000000fc0000000ull)
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_DEBUG_MC_BIT_SEL_MODIFY(r, x) \
   ((((x) << 30) & 0x0000000fc0000000ull) | ((r) & 0xfffffff03fffffffull))
/* Field member: etsoc_mem_shire_esr::ms_mem_ctl.esr_ms_addr_mc_bit_sel    */
/* Source filename: etsoc_mem_shire_esr.csr, line: 77                      */
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_MC_BIT_SEL_MSB 29u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_MC_BIT_SEL_LSB 24u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_MC_BIT_SEL_WIDTH 6u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_MC_BIT_SEL_READ_ACCESS 1u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_MC_BIT_SEL_WRITE_ACCESS 1u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_MC_BIT_SEL_FIELD_MASK 0x000000003f000000ull
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_MC_BIT_SEL_GET(x) \
   (((x) & 0x000000003f000000ull) >> 24)
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_MC_BIT_SEL_SET(x) \
   (((x) << 24) & 0x000000003f000000ull)
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_MC_BIT_SEL_MODIFY(r, x) \
   ((((x) << 24) & 0x000000003f000000ull) | ((r) & 0xffffffffc0ffffffull))
/* Field member: etsoc_mem_shire_esr::ms_mem_ctl.esr_ms_addr_remove_bit_sel3 */
/* Source filename: etsoc_mem_shire_esr.csr, line: 66                      */
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_REMOVE_BIT_SEL3_MSB 23u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_REMOVE_BIT_SEL3_LSB 18u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_REMOVE_BIT_SEL3_WIDTH 6u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_REMOVE_BIT_SEL3_READ_ACCESS 1u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_REMOVE_BIT_SEL3_WRITE_ACCESS 1u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_REMOVE_BIT_SEL3_FIELD_MASK 0x0000000000fc0000ull
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_REMOVE_BIT_SEL3_GET(x) \
   (((x) & 0x0000000000fc0000ull) >> 18)
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_REMOVE_BIT_SEL3_SET(x) \
   (((x) << 18) & 0x0000000000fc0000ull)
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_REMOVE_BIT_SEL3_MODIFY(r, x) \
   ((((x) << 18) & 0x0000000000fc0000ull) | ((r) & 0xffffffffff03ffffull))
/* Field member: etsoc_mem_shire_esr::ms_mem_ctl.esr_ms_addr_remove_bit_sel2 */
/* Source filename: etsoc_mem_shire_esr.csr, line: 55                      */
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_REMOVE_BIT_SEL2_MSB 17u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_REMOVE_BIT_SEL2_LSB 12u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_REMOVE_BIT_SEL2_WIDTH 6u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_REMOVE_BIT_SEL2_READ_ACCESS 1u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_REMOVE_BIT_SEL2_WRITE_ACCESS 1u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_REMOVE_BIT_SEL2_FIELD_MASK 0x000000000003f000ull
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_REMOVE_BIT_SEL2_GET(x) \
   (((x) & 0x000000000003f000ull) >> 12)
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_REMOVE_BIT_SEL2_SET(x) \
   (((x) << 12) & 0x000000000003f000ull)
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_REMOVE_BIT_SEL2_MODIFY(r, x) \
   ((((x) << 12) & 0x000000000003f000ull) | ((r) & 0xfffffffffffc0fffull))
/* Field member: etsoc_mem_shire_esr::ms_mem_ctl.esr_ms_addr_remove_bit_sel1 */
/* Source filename: etsoc_mem_shire_esr.csr, line: 44                      */
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_REMOVE_BIT_SEL1_MSB 11u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_REMOVE_BIT_SEL1_LSB 6u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_REMOVE_BIT_SEL1_WIDTH 6u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_REMOVE_BIT_SEL1_READ_ACCESS 1u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_REMOVE_BIT_SEL1_WRITE_ACCESS 1u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_REMOVE_BIT_SEL1_FIELD_MASK 0x0000000000000fc0ull
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_REMOVE_BIT_SEL1_GET(x) \
   (((x) & 0x0000000000000fc0ull) >> 6)
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_REMOVE_BIT_SEL1_SET(x) \
   (((x) << 6) & 0x0000000000000fc0ull)
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_REMOVE_BIT_SEL1_MODIFY(r, x) \
   ((((x) << 6) & 0x0000000000000fc0ull) | ((r) & 0xfffffffffffff03full))
/* Field member: etsoc_mem_shire_esr::ms_mem_ctl.esr_ms_addr_remove_bit_sel0 */
/* Source filename: etsoc_mem_shire_esr.csr, line: 33                      */
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_REMOVE_BIT_SEL0_MSB 5u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_REMOVE_BIT_SEL0_LSB 0u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_REMOVE_BIT_SEL0_WIDTH 6u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_REMOVE_BIT_SEL0_READ_ACCESS 1u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_REMOVE_BIT_SEL0_WRITE_ACCESS 1u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_REMOVE_BIT_SEL0_FIELD_MASK 0x000000000000003full
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_REMOVE_BIT_SEL0_GET(x) \
   ((x) & 0x000000000000003full)
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_REMOVE_BIT_SEL0_SET(x) \
   ((x) & 0x000000000000003full)
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_CTL_ESR_MS_ADDR_REMOVE_BIT_SEL0_MODIFY(r, x) \
   (((x) & 0x000000000000003full) | ((r) & 0xffffffffffffffc0ull))

/* Register type: etsoc_mem_shire_esr::ms_atomic_sm_ctl                    */
/* Register template: etsoc_mem_shire_esr::ms_atomic_sm_ctl                */
/* Source filename: etsoc_mem_shire_esr.csr, line: 121                     */
/* Field member: etsoc_mem_shire_esr::ms_atomic_sm_ctl.esr_ms_atomic_state */
/* Source filename: etsoc_mem_shire_esr.csr, line: 139                     */
#define ETSOC_MEM_SHIRE_ESR_MS_ATOMIC_SM_CTL_ESR_MS_ATOMIC_STATE_MSB 7u
#define ETSOC_MEM_SHIRE_ESR_MS_ATOMIC_SM_CTL_ESR_MS_ATOMIC_STATE_LSB 4u
#define ETSOC_MEM_SHIRE_ESR_MS_ATOMIC_SM_CTL_ESR_MS_ATOMIC_STATE_WIDTH 4u
#define ETSOC_MEM_SHIRE_ESR_MS_ATOMIC_SM_CTL_ESR_MS_ATOMIC_STATE_READ_ACCESS 1u
#define ETSOC_MEM_SHIRE_ESR_MS_ATOMIC_SM_CTL_ESR_MS_ATOMIC_STATE_WRITE_ACCESS 1u
#define ETSOC_MEM_SHIRE_ESR_MS_ATOMIC_SM_CTL_ESR_MS_ATOMIC_STATE_FIELD_MASK 0x00000000000000f0ull
#define ETSOC_MEM_SHIRE_ESR_MS_ATOMIC_SM_CTL_ESR_MS_ATOMIC_STATE_GET(x) \
   (((x) & 0x00000000000000f0ull) >> 4)
#define ETSOC_MEM_SHIRE_ESR_MS_ATOMIC_SM_CTL_ESR_MS_ATOMIC_STATE_SET(x) \
   (((x) << 4) & 0x00000000000000f0ull)
#define ETSOC_MEM_SHIRE_ESR_MS_ATOMIC_SM_CTL_ESR_MS_ATOMIC_STATE_MODIFY(r, x) \
   ((((x) << 4) & 0x00000000000000f0ull) | ((r) & 0xffffffffffffff0full))
/* Field member: etsoc_mem_shire_esr::ms_atomic_sm_ctl.esr_ms_atomic_evict_start */
/* Source filename: etsoc_mem_shire_esr.csr, line: 126                     */
#define ETSOC_MEM_SHIRE_ESR_MS_ATOMIC_SM_CTL_ESR_MS_ATOMIC_EVICT_START_MSB 0u
#define ETSOC_MEM_SHIRE_ESR_MS_ATOMIC_SM_CTL_ESR_MS_ATOMIC_EVICT_START_LSB 0u
#define ETSOC_MEM_SHIRE_ESR_MS_ATOMIC_SM_CTL_ESR_MS_ATOMIC_EVICT_START_WIDTH 1u
#define ETSOC_MEM_SHIRE_ESR_MS_ATOMIC_SM_CTL_ESR_MS_ATOMIC_EVICT_START_READ_ACCESS 1u
#define ETSOC_MEM_SHIRE_ESR_MS_ATOMIC_SM_CTL_ESR_MS_ATOMIC_EVICT_START_WRITE_ACCESS 1u
#define ETSOC_MEM_SHIRE_ESR_MS_ATOMIC_SM_CTL_ESR_MS_ATOMIC_EVICT_START_FIELD_MASK 0x0000000000000001ull
#define ETSOC_MEM_SHIRE_ESR_MS_ATOMIC_SM_CTL_ESR_MS_ATOMIC_EVICT_START_GET(x) \
   ((x) & 0x0000000000000001ull)
#define ETSOC_MEM_SHIRE_ESR_MS_ATOMIC_SM_CTL_ESR_MS_ATOMIC_EVICT_START_SET(x) \
   ((x) & 0x0000000000000001ull)
#define ETSOC_MEM_SHIRE_ESR_MS_ATOMIC_SM_CTL_ESR_MS_ATOMIC_EVICT_START_MODIFY(r, x) \
   (((x) & 0x0000000000000001ull) | ((r) & 0xfffffffffffffffeull))

/* Register type: etsoc_mem_shire_esr::ms_mem_revision_id                  */
/* Register template: etsoc_mem_shire_esr::ms_mem_revision_id              */
/* Source filename: etsoc_mem_shire_esr.csr, line: 148                     */
/* Field member: etsoc_mem_shire_esr::ms_mem_revision_id.memshire_id       */
/* Source filename: etsoc_mem_shire_esr.csr, line: 190                     */
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_MEMSHIRE_ID_MSB 47u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_MEMSHIRE_ID_LSB 40u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_MEMSHIRE_ID_WIDTH 8u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_MEMSHIRE_ID_READ_ACCESS 1u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_MEMSHIRE_ID_WRITE_ACCESS 0u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_MEMSHIRE_ID_FIELD_MASK 0x0000ff0000000000ull
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_MEMSHIRE_ID_GET(x) \
   (((x) & 0x0000ff0000000000ull) >> 40)
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_MEMSHIRE_ID_SET(x) \
   (((x) << 40) & 0x0000ff0000000000ull)
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_MEMSHIRE_ID_MODIFY(r, x) \
   ((((x) << 40) & 0x0000ff0000000000ull) | ((r) & 0xffff00ffffffffffull))
/* Field member: etsoc_mem_shire_esr::ms_mem_revision_id.memshire_revision_b3 */
/* Source filename: etsoc_mem_shire_esr.csr, line: 181                     */
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_MEMSHIRE_REVISION_B3_MSB 31u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_MEMSHIRE_REVISION_B3_LSB 24u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_MEMSHIRE_REVISION_B3_WIDTH 8u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_MEMSHIRE_REVISION_B3_READ_ACCESS 1u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_MEMSHIRE_REVISION_B3_WRITE_ACCESS 0u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_MEMSHIRE_REVISION_B3_FIELD_MASK 0x00000000ff000000ull
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_MEMSHIRE_REVISION_B3_GET(x) \
   (((x) & 0x00000000ff000000ull) >> 24)
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_MEMSHIRE_REVISION_B3_SET(x) \
   (((x) << 24) & 0x00000000ff000000ull)
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_MEMSHIRE_REVISION_B3_MODIFY(r, x) \
   ((((x) << 24) & 0x00000000ff000000ull) | ((r) & 0xffffffff00ffffffull))
/* Field member: etsoc_mem_shire_esr::ms_mem_revision_id.memshire_revision_b2 */
/* Source filename: etsoc_mem_shire_esr.csr, line: 172                     */
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_MEMSHIRE_REVISION_B2_MSB 23u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_MEMSHIRE_REVISION_B2_LSB 16u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_MEMSHIRE_REVISION_B2_WIDTH 8u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_MEMSHIRE_REVISION_B2_READ_ACCESS 1u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_MEMSHIRE_REVISION_B2_WRITE_ACCESS 0u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_MEMSHIRE_REVISION_B2_FIELD_MASK 0x0000000000ff0000ull
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_MEMSHIRE_REVISION_B2_GET(x) \
   (((x) & 0x0000000000ff0000ull) >> 16)
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_MEMSHIRE_REVISION_B2_SET(x) \
   (((x) << 16) & 0x0000000000ff0000ull)
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_MEMSHIRE_REVISION_B2_MODIFY(r, x) \
   ((((x) << 16) & 0x0000000000ff0000ull) | ((r) & 0xffffffffff00ffffull))
/* Field member: etsoc_mem_shire_esr::ms_mem_revision_id.memshire_revision_b1 */
/* Source filename: etsoc_mem_shire_esr.csr, line: 163                     */
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_MEMSHIRE_REVISION_B1_MSB 15u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_MEMSHIRE_REVISION_B1_LSB 8u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_MEMSHIRE_REVISION_B1_WIDTH 8u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_MEMSHIRE_REVISION_B1_READ_ACCESS 1u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_MEMSHIRE_REVISION_B1_WRITE_ACCESS 0u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_MEMSHIRE_REVISION_B1_FIELD_MASK 0x000000000000ff00ull
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_MEMSHIRE_REVISION_B1_GET(x) \
   (((x) & 0x000000000000ff00ull) >> 8)
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_MEMSHIRE_REVISION_B1_SET(x) \
   (((x) << 8) & 0x000000000000ff00ull)
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_MEMSHIRE_REVISION_B1_MODIFY(r, x) \
   ((((x) << 8) & 0x000000000000ff00ull) | ((r) & 0xffffffffffff00ffull))
/* Field member: etsoc_mem_shire_esr::ms_mem_revision_id.memshire_revision_b0 */
/* Source filename: etsoc_mem_shire_esr.csr, line: 154                     */
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_MEMSHIRE_REVISION_B0_MSB 7u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_MEMSHIRE_REVISION_B0_LSB 0u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_MEMSHIRE_REVISION_B0_WIDTH 8u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_MEMSHIRE_REVISION_B0_READ_ACCESS 1u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_MEMSHIRE_REVISION_B0_WRITE_ACCESS 0u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_MEMSHIRE_REVISION_B0_FIELD_MASK 0x00000000000000ffull
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_MEMSHIRE_REVISION_B0_GET(x) \
   ((x) & 0x00000000000000ffull)
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_MEMSHIRE_REVISION_B0_SET(x) \
   ((x) & 0x00000000000000ffull)
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_REVISION_ID_MEMSHIRE_REVISION_B0_MODIFY(r, x) \
   (((x) & 0x00000000000000ffull) | ((r) & 0xffffffffffffff00ull))

/* Register type: etsoc_mem_shire_esr::ms_clk_gate_ctl                     */
/* Register template: etsoc_mem_shire_esr::ms_clk_gate_ctl                 */
/* Source filename: etsoc_mem_shire_esr.csr, line: 200                     */
/* Field member: etsoc_mem_shire_esr::ms_clk_gate_ctl.debug_clock_disable  */
/* Source filename: etsoc_mem_shire_esr.csr, line: 205                     */
#define ETSOC_MEM_SHIRE_ESR_MS_CLK_GATE_CTL_DEBUG_CLOCK_DISABLE_MSB 0u
#define ETSOC_MEM_SHIRE_ESR_MS_CLK_GATE_CTL_DEBUG_CLOCK_DISABLE_LSB 0u
#define ETSOC_MEM_SHIRE_ESR_MS_CLK_GATE_CTL_DEBUG_CLOCK_DISABLE_WIDTH 1u
#define ETSOC_MEM_SHIRE_ESR_MS_CLK_GATE_CTL_DEBUG_CLOCK_DISABLE_READ_ACCESS 1u
#define ETSOC_MEM_SHIRE_ESR_MS_CLK_GATE_CTL_DEBUG_CLOCK_DISABLE_WRITE_ACCESS 1u
#define ETSOC_MEM_SHIRE_ESR_MS_CLK_GATE_CTL_DEBUG_CLOCK_DISABLE_FIELD_MASK 0x0000000000000001ull
#define ETSOC_MEM_SHIRE_ESR_MS_CLK_GATE_CTL_DEBUG_CLOCK_DISABLE_GET(x) \
   ((x) & 0x0000000000000001ull)
#define ETSOC_MEM_SHIRE_ESR_MS_CLK_GATE_CTL_DEBUG_CLOCK_DISABLE_SET(x) \
   ((x) & 0x0000000000000001ull)
#define ETSOC_MEM_SHIRE_ESR_MS_CLK_GATE_CTL_DEBUG_CLOCK_DISABLE_MODIFY(r, x) \
   (((x) & 0x0000000000000001ull) | ((r) & 0xfffffffffffffffeull))

/* Register type: etsoc_mem_shire_esr::ms_mem_status                       */
/* Register template: etsoc_mem_shire_esr::ms_mem_status                   */
/* Source filename: etsoc_mem_shire_esr.csr, line: 214                     */
/* Field member: etsoc_mem_shire_esr::ms_mem_status.pll_lock_lost          */
/* Source filename: etsoc_mem_shire_esr.csr, line: 232                     */
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_STATUS_PLL_LOCK_LOST_MSB 1u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_STATUS_PLL_LOCK_LOST_LSB 1u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_STATUS_PLL_LOCK_LOST_WIDTH 1u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_STATUS_PLL_LOCK_LOST_READ_ACCESS 1u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_STATUS_PLL_LOCK_LOST_WRITE_ACCESS 0u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_STATUS_PLL_LOCK_LOST_FIELD_MASK 0x0000000000000002ull
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_STATUS_PLL_LOCK_LOST_GET(x) \
   (((x) & 0x0000000000000002ull) >> 1)
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_STATUS_PLL_LOCK_LOST_SET(x) \
   (((x) << 1) & 0x0000000000000002ull)
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_STATUS_PLL_LOCK_LOST_MODIFY(r, x) \
   ((((x) << 1) & 0x0000000000000002ull) | ((r) & 0xfffffffffffffffdull))
/* Field member: etsoc_mem_shire_esr::ms_mem_status.pll_lock_detect        */
/* Source filename: etsoc_mem_shire_esr.csr, line: 220                     */
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_STATUS_PLL_LOCK_DETECT_MSB 0u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_STATUS_PLL_LOCK_DETECT_LSB 0u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_STATUS_PLL_LOCK_DETECT_WIDTH 1u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_STATUS_PLL_LOCK_DETECT_READ_ACCESS 1u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_STATUS_PLL_LOCK_DETECT_WRITE_ACCESS 0u
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_STATUS_PLL_LOCK_DETECT_FIELD_MASK 0x0000000000000001ull
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_STATUS_PLL_LOCK_DETECT_GET(x) \
   ((x) & 0x0000000000000001ull)
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_STATUS_PLL_LOCK_DETECT_SET(x) \
   ((x) & 0x0000000000000001ull)
#define ETSOC_MEM_SHIRE_ESR_MS_MEM_STATUS_PLL_LOCK_DETECT_MODIFY(r, x) \
   (((x) & 0x0000000000000001ull) | ((r) & 0xfffffffffffffffeull))

/* ####################################################################### */
/*        TYPE DEFINITIONS                                                 */
/* ####################################################################### */

/* Typedef for Addressmap: etsoc_mem_shire_esr                             */
/* Source filename: etsoc_mem_shire_esr.csr, line: 246                     */
typedef struct {
   volatile uint64_t ms_mem_ctl; /**< Offset 0x0 (R/W) */
   volatile uint64_t ms_atomic_sm_ctl; /**< Offset 0x8 (R/W) */
   volatile uint64_t ms_mem_revision_id; /**< Offset 0x10 (R) */
   volatile uint64_t ms_clk_gate_ctl; /**< Offset 0x18 (R/W) */
   volatile uint64_t ms_mem_status; /**< Offset 0x20 (R) */
   uint8_t _pad0[0x18];
} Etsoc_mem_shire_esr, *PTR_Etsoc_mem_shire_esr;

#endif
