/*                                                                         */
/*                                                                         */
/* Generated by Semifore, Inc. csrCompile                                  */
/*    C Header output                                                      */

#ifndef _MAX_SRAM_CONFIG_UNIT_H_
#define _MAX_SRAM_CONFIG_UNIT_H_



/* ####################################################################### */
/*        ADDRESS MACROS                                                   */
/* ####################################################################### */

/* Address Space for Addressmap: scu                                       */
/* Source filename: max_sram_config_unit.csr, line: 68                     */
/* Register: scu.sacrls_config                                             */
#define SCU_SACRLS_CONFIG_ADDRESS 0x0u
#define SCU_SACRLS_CONFIG_BYTE_ADDRESS 0x0u
/* Register: scu.sadcls_config                                             */
#define SCU_SADCLS_CONFIG_ADDRESS 0x8u
#define SCU_SADCLS_CONFIG_BYTE_ADDRESS 0x8u
/* Register: scu.saduls_config                                             */
#define SCU_SADULS_CONFIG_ADDRESS 0x10u
#define SCU_SADULS_CONFIG_BYTE_ADDRESS 0x10u
/* Register: scu.sadrls_config                                             */
#define SCU_SADRLS_CONFIG_ADDRESS 0x18u
#define SCU_SADRLS_CONFIG_BYTE_ADDRESS 0x18u


/* ####################################################################### */
/*        TEMPLATE MACROS                                                  */
/* ####################################################################### */

/* Addressmap type: scu                                                    */
/* Addressmap template: scu                                                */
/* Source filename: max_sram_config_unit.csr, line: 6                      */
#define SCU_SIZE 0x20u
#define SCU_BYTE_SIZE 0x20u
/* Register member: scu.sacrls_config                                      */
/* Register type referenced: scu::sacrls_config                            */
/* Register template referenced: scu::sacrls_config                        */
#define SCU_SACRLS_CONFIG_OFFSET 0x0u
#define SCU_SACRLS_CONFIG_BYTE_OFFSET 0x0u
#define SCU_SACRLS_CONFIG_READ_ACCESS 1u
#define SCU_SACRLS_CONFIG_WRITE_ACCESS 1u
#define SCU_SACRLS_CONFIG_READ_MASK 0xffffffffffffffffull
#define SCU_SACRLS_CONFIG_WRITE_MASK 0xffffffffffffffffull
/* Register member: scu.sadcls_config                                      */
/* Register type referenced: scu::sadcls_config                            */
/* Register template referenced: scu::sadcls_config                        */
#define SCU_SADCLS_CONFIG_OFFSET 0x8u
#define SCU_SADCLS_CONFIG_BYTE_OFFSET 0x8u
#define SCU_SADCLS_CONFIG_READ_ACCESS 1u
#define SCU_SADCLS_CONFIG_WRITE_ACCESS 1u
#define SCU_SADCLS_CONFIG_READ_MASK 0xffffffffffffffffull
#define SCU_SADCLS_CONFIG_WRITE_MASK 0xffffffffffffffffull
/* Register member: scu.saduls_config                                      */
/* Register type referenced: scu::saduls_config                            */
/* Register template referenced: scu::saduls_config                        */
#define SCU_SADULS_CONFIG_OFFSET 0x10u
#define SCU_SADULS_CONFIG_BYTE_OFFSET 0x10u
#define SCU_SADULS_CONFIG_READ_ACCESS 1u
#define SCU_SADULS_CONFIG_WRITE_ACCESS 1u
#define SCU_SADULS_CONFIG_READ_MASK 0xffffffffffffffffull
#define SCU_SADULS_CONFIG_WRITE_MASK 0xffffffffffffffffull
/* Register member: scu.sadrls_config                                      */
/* Register type referenced: scu::sadrls_config                            */
/* Register template referenced: scu::sadrls_config                        */
#define SCU_SADRLS_CONFIG_OFFSET 0x18u
#define SCU_SADRLS_CONFIG_BYTE_OFFSET 0x18u
#define SCU_SADRLS_CONFIG_READ_ACCESS 1u
#define SCU_SADRLS_CONFIG_WRITE_ACCESS 1u
#define SCU_SADRLS_CONFIG_READ_MASK 0xffffffffffffffffull
#define SCU_SADRLS_CONFIG_WRITE_MASK 0xffffffffffffffffull

/* Register type: scu::sacrls_config                                       */
/* Register template: scu::sacrls_config                                   */
/* Source filename: max_sram_config_unit.csr, line: 8                      */
/* Field member: scu::sacrls_config.sacrls_config                          */
/* Source filename: max_sram_config_unit.csr, line: 11                     */
#define SCU_SACRLS_CONFIG_SACRLS_CONFIG_MSB 63u
#define SCU_SACRLS_CONFIG_SACRLS_CONFIG_LSB 0u
#define SCU_SACRLS_CONFIG_SACRLS_CONFIG_WIDTH 64u
#define SCU_SACRLS_CONFIG_SACRLS_CONFIG_READ_ACCESS 1u
#define SCU_SACRLS_CONFIG_SACRLS_CONFIG_WRITE_ACCESS 1u
#define SCU_SACRLS_CONFIG_SACRLS_CONFIG_FIELD_MASK 0xffffffffffffffffull
#define SCU_SACRLS_CONFIG_SACRLS_CONFIG_GET(x) ((x) & 0xffffffffffffffffull)
#define SCU_SACRLS_CONFIG_SACRLS_CONFIG_SET(x) ((x) & 0xffffffffffffffffull)
#define SCU_SACRLS_CONFIG_SACRLS_CONFIG_MODIFY(r, x) \
   ((x) & 0xffffffffffffffffull)

/* Register type: scu::sadcls_config                                       */
/* Register template: scu::sadcls_config                                   */
/* Source filename: max_sram_config_unit.csr, line: 23                     */
/* Field member: scu::sadcls_config.sadcls_config                          */
/* Source filename: max_sram_config_unit.csr, line: 26                     */
#define SCU_SADCLS_CONFIG_SADCLS_CONFIG_MSB 63u
#define SCU_SADCLS_CONFIG_SADCLS_CONFIG_LSB 0u
#define SCU_SADCLS_CONFIG_SADCLS_CONFIG_WIDTH 64u
#define SCU_SADCLS_CONFIG_SADCLS_CONFIG_READ_ACCESS 1u
#define SCU_SADCLS_CONFIG_SADCLS_CONFIG_WRITE_ACCESS 1u
#define SCU_SADCLS_CONFIG_SADCLS_CONFIG_FIELD_MASK 0xffffffffffffffffull
#define SCU_SADCLS_CONFIG_SADCLS_CONFIG_GET(x) ((x) & 0xffffffffffffffffull)
#define SCU_SADCLS_CONFIG_SADCLS_CONFIG_SET(x) ((x) & 0xffffffffffffffffull)
#define SCU_SADCLS_CONFIG_SADCLS_CONFIG_MODIFY(r, x) \
   ((x) & 0xffffffffffffffffull)

/* Register type: scu::saduls_config                                       */
/* Register template: scu::saduls_config                                   */
/* Source filename: max_sram_config_unit.csr, line: 38                     */
/* Field member: scu::saduls_config.saduls_config                          */
/* Source filename: max_sram_config_unit.csr, line: 41                     */
#define SCU_SADULS_CONFIG_SADULS_CONFIG_MSB 63u
#define SCU_SADULS_CONFIG_SADULS_CONFIG_LSB 0u
#define SCU_SADULS_CONFIG_SADULS_CONFIG_WIDTH 64u
#define SCU_SADULS_CONFIG_SADULS_CONFIG_READ_ACCESS 1u
#define SCU_SADULS_CONFIG_SADULS_CONFIG_WRITE_ACCESS 1u
#define SCU_SADULS_CONFIG_SADULS_CONFIG_FIELD_MASK 0xffffffffffffffffull
#define SCU_SADULS_CONFIG_SADULS_CONFIG_GET(x) ((x) & 0xffffffffffffffffull)
#define SCU_SADULS_CONFIG_SADULS_CONFIG_SET(x) ((x) & 0xffffffffffffffffull)
#define SCU_SADULS_CONFIG_SADULS_CONFIG_MODIFY(r, x) \
   ((x) & 0xffffffffffffffffull)

/* Register type: scu::sadrls_config                                       */
/* Register template: scu::sadrls_config                                   */
/* Source filename: max_sram_config_unit.csr, line: 53                     */
/* Field member: scu::sadrls_config.sadrls_config                          */
/* Source filename: max_sram_config_unit.csr, line: 56                     */
#define SCU_SADRLS_CONFIG_SADRLS_CONFIG_MSB 63u
#define SCU_SADRLS_CONFIG_SADRLS_CONFIG_LSB 0u
#define SCU_SADRLS_CONFIG_SADRLS_CONFIG_WIDTH 64u
#define SCU_SADRLS_CONFIG_SADRLS_CONFIG_READ_ACCESS 1u
#define SCU_SADRLS_CONFIG_SADRLS_CONFIG_WRITE_ACCESS 1u
#define SCU_SADRLS_CONFIG_SADRLS_CONFIG_FIELD_MASK 0xffffffffffffffffull
#define SCU_SADRLS_CONFIG_SADRLS_CONFIG_GET(x) ((x) & 0xffffffffffffffffull)
#define SCU_SADRLS_CONFIG_SADRLS_CONFIG_SET(x) ((x) & 0xffffffffffffffffull)
#define SCU_SADRLS_CONFIG_SADRLS_CONFIG_MODIFY(r, x) \
   ((x) & 0xffffffffffffffffull)

/* ####################################################################### */
/*        TYPE DEFINITIONS                                                 */
/* ####################################################################### */

/* Typedef for Addressmap: scu                                             */
/* Source filename: max_sram_config_unit.csr, line: 68                     */
typedef struct {
   volatile uint64_t sacrls_config; /**< Offset 0x0 (R/W) */
   volatile uint64_t sadcls_config; /**< Offset 0x8 (R/W) */
   volatile uint64_t saduls_config; /**< Offset 0x10 (R/W) */
   volatile uint64_t sadrls_config; /**< Offset 0x18 (R/W) */
} Scu, *PTR_Scu;

#endif
