/*------------------------------------------------------------------------- 
* Copyright (C) 2018, Esperanto Technologies Inc. 
* The copyright to the computer program(s) herein is the 
* property of Esperanto Technologies.
* The program(s) may be used and/or copied only with
* the written permission of Esperanto Technologies or 
* in accordance with the terms and conditions stipulated in the 
* agreement/contract under which the program(s) have been supplied. 
*------------------------------------------------------------------------- 
*/

/**
* @file pShire_subsystem_regTest.h 
* @version $Release$ 
* @date $Date$
* @author 
*
* @brief 
*
* Setup SoC to enable TC run 
*/ 
/** 
 *  @Component      HAL
 *
 *  @Filename       pShire_subsystem_regTest.h
 *
 *  @Description    IPs register table 
 *
 *//*======================================================================== */

#include "DWC_pcie_subsystem_custom.h"


REGTEST_t pShire_subsystemRegs[] =

{

/* regAddress                                        regSize                       resetValue                                        bitMask                                           regName                            */   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_GEN_CTRL_1_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_GEN_CTRL_1_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_GEN_CTRL_1_WRITE_MASK,"PE0_GEN_CTRL_1",                  },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_GEN_CTRL_2_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_GEN_CTRL_2_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_GEN_CTRL_2_WRITE_MASK,"PE0_GEN_CTRL_2",                  },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_GEN_CTRL_3_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_GEN_CTRL_3_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_GEN_CTRL_3_WRITE_MASK,"PE0_GEN_CTRL_3",                  },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_GEN_CTRL_4_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_GEN_CTRL_4_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_GEN_CTRL_4_WRITE_MASK,"PE0_GEN_CTRL_4",                  },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_PM_CTRL_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_PM_CTRL_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_PM_CTRL_WRITE_MASK,"PE0_PM_CTRL",                     },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_PM_STS_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_PM_STS_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_PM_STS_WRITE_MASK,"PE0_PM_STS",                      },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_TX_MSG_HDR_1_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_TX_MSG_HDR_1_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_TX_MSG_HDR_1_WRITE_MASK,"PE0_TX_MSG_HDR_1",                },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_TX_MSG_HDR_2_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_TX_MSG_HDR_2_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_TX_MSG_HDR_2_WRITE_MASK,"PE0_TX_MSG_HDR_2",                },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_TX_MSG_HDR_3_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_TX_MSG_HDR_3_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_TX_MSG_HDR_3_WRITE_MASK,"PE0_TX_MSG_HDR_3",                },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_TX_MSG_HDR_4_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_TX_MSG_HDR_4_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_TX_MSG_HDR_4_WRITE_MASK,"PE0_TX_MSG_HDR_4",                },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_TX_MSG_REQ_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_TX_MSG_REQ_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_TX_MSG_REQ_WRITE_MASK,"PE0_TX_MSG_REQ",                  },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_RX_MSG_DATA_1_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_RX_MSG_DATA_1_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_RX_MSG_DATA_1_WRITE_MASK,"PE0_RX_MSG_DATA_1",               },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_RX_MSG_DATA_2_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_RX_MSG_DATA_2_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_RX_MSG_DATA_2_WRITE_MASK,"PE0_RX_MSG_DATA_2",               },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_RX_MSG_HDR_1_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_RX_MSG_HDR_1_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_RX_MSG_HDR_1_WRITE_MASK,"PE0_RX_MSG_HDR_1",                },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_RX_MSG_HDR_2_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_RX_MSG_HDR_2_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_RX_MSG_HDR_2_WRITE_MASK,"PE0_RX_MSG_HDR_2",                },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_RX_MSG_HDR_3_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_RX_MSG_HDR_3_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_RX_MSG_HDR_3_WRITE_MASK,"PE0_RX_MSG_HDR_3",                },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_RX_MSG_HDR_4_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_RX_MSG_HDR_4_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_RX_MSG_HDR_4_WRITE_MASK,"PE0_RX_MSG_HDR_4",                },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_RX_MSG_STS_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_RX_MSG_STS_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_RX_MSG_STS_WRITE_MASK,"PE0_RX_MSG_STS",                  },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_RX_MSG_CAP_CTRL_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_RX_MSG_CAP_CTRL_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_RX_MSG_CAP_CTRL_WRITE_MASK,"PE0_RX_MSG_CAP_CTRL",             },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_RX_MSG_INT_CTRL_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_RX_MSG_INT_CTRL_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_RX_MSG_INT_CTRL_WRITE_MASK,"PE0_RX_MSG_INT_CTRL",             },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_LINK_DBG_1_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_LINK_DBG_1_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_LINK_DBG_1_WRITE_MASK,"PE0_LINK_DBG_1",                  },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_LINK_DBG_2_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_LINK_DBG_2_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_LINK_DBG_2_WRITE_MASK,"PE0_LINK_DBG_2",                  },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_ERR_STS_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_ERR_STS_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_ERR_STS_WRITE_MASK,"PE0_ERR_STS",                     },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_ERR_INT_CTRL_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_ERR_INT_CTRL_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_ERR_INT_CTRL_WRITE_MASK,"PE0_ERR_INT_CTRL",                },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_INT_STS_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_INT_STS_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_INT_STS_WRITE_MASK,"PE0_INT_STS",                     },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_MSI_GEN_CTRL_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_MSI_GEN_CTRL_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_MSI_GEN_CTRL_WRITE_MASK,"PE0_MSI_GEN_CTRL",                },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_FSM_TRACK_1_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_FSM_TRACK_1_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_FSM_TRACK_1_WRITE_MASK,"PE0_FSM_TRACK_1",                 },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_FSM_TRACK_2_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_FSM_TRACK_2_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_FSM_TRACK_2_WRITE_MASK,"PE0_FSM_TRACK_2",                 },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_FSM_TRACK_3_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_FSM_TRACK_3_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE0_FSM_TRACK_3_WRITE_MASK,"PE0_FSM_TRACK_3",                 },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_GEN_CTRL_1_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_GEN_CTRL_1_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_GEN_CTRL_1_WRITE_MASK,"PE1_GEN_CTRL_1",                  },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_GEN_CTRL_2_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_GEN_CTRL_2_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_GEN_CTRL_2_WRITE_MASK,"PE1_GEN_CTRL_2",                  },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_GEN_CTRL_3_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_GEN_CTRL_3_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_GEN_CTRL_3_WRITE_MASK,"PE1_GEN_CTRL_3",                  },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_GEN_CTRL_4_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_GEN_CTRL_4_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_GEN_CTRL_4_WRITE_MASK,"PE1_GEN_CTRL_4",                  },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_PM_CTRL_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_PM_CTRL_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_PM_CTRL_WRITE_MASK,"PE1_PM_CTRL",                     },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_PM_STS_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_PM_STS_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_PM_STS_WRITE_MASK,"PE1_PM_STS",                      },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_TX_MSG_HDR_1_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_TX_MSG_HDR_1_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_TX_MSG_HDR_1_WRITE_MASK,"PE1_TX_MSG_HDR_1",                },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_TX_MSG_HDR_2_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_TX_MSG_HDR_2_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_TX_MSG_HDR_2_WRITE_MASK,"PE1_TX_MSG_HDR_2",                },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_TX_MSG_HDR_3_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_TX_MSG_HDR_3_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_TX_MSG_HDR_3_WRITE_MASK,"PE1_TX_MSG_HDR_3",                },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_TX_MSG_HDR_4_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_TX_MSG_HDR_4_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_TX_MSG_HDR_4_WRITE_MASK,"PE1_TX_MSG_HDR_4",                },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_TX_MSG_REQ_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_TX_MSG_REQ_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_TX_MSG_REQ_WRITE_MASK,"PE1_TX_MSG_REQ",                  },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_RX_MSG_DATA_1_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_RX_MSG_DATA_1_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_RX_MSG_DATA_1_WRITE_MASK,"PE1_RX_MSG_DATA_1",               },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_RX_MSG_DATA_2_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_RX_MSG_DATA_2_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_RX_MSG_DATA_2_WRITE_MASK,"PE1_RX_MSG_DATA_2",               },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_RX_MSG_HDR_1_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_RX_MSG_HDR_1_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_RX_MSG_HDR_1_WRITE_MASK,"PE1_RX_MSG_HDR_1",                },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_RX_MSG_HDR_2_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_RX_MSG_HDR_2_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_RX_MSG_HDR_2_WRITE_MASK,"PE1_RX_MSG_HDR_2",                },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_RX_MSG_HDR_3_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_RX_MSG_HDR_3_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_RX_MSG_HDR_3_WRITE_MASK,"PE1_RX_MSG_HDR_3",                },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_RX_MSG_HDR_4_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_RX_MSG_HDR_4_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_RX_MSG_HDR_4_WRITE_MASK,"PE1_RX_MSG_HDR_4",                },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_RX_MSG_STS_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_RX_MSG_STS_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_RX_MSG_STS_WRITE_MASK,"PE1_RX_MSG_STS",                  },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_RX_MSG_CAP_CTRL_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_RX_MSG_CAP_CTRL_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_RX_MSG_CAP_CTRL_WRITE_MASK,"PE1_RX_MSG_CAP_CTRL",             },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_RX_MSG_INT_CTRL_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_RX_MSG_INT_CTRL_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_RX_MSG_INT_CTRL_WRITE_MASK,"PE1_RX_MSG_INT_CTRL",             },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_LINK_DBG_1_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_LINK_DBG_1_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_LINK_DBG_1_WRITE_MASK,"PE1_LINK_DBG_1",                  },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_LINK_DBG_2_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_LINK_DBG_2_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_LINK_DBG_2_WRITE_MASK,"PE1_LINK_DBG_2",                  },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_ERR_STS_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_ERR_STS_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_ERR_STS_WRITE_MASK,"PE1_ERR_STS",                     },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_ERR_INT_CTRL_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_ERR_INT_CTRL_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_ERR_INT_CTRL_WRITE_MASK,"PE1_ERR_INT_CTRL",                },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_INT_STS_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_INT_STS_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_INT_STS_WRITE_MASK,"PE1_INT_STS",                     },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_MSI_GEN_CTRL_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_MSI_GEN_CTRL_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_MSI_GEN_CTRL_WRITE_MASK,"PE1_MSI_GEN_CTRL",                },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_FSM_TRACK_1_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_FSM_TRACK_1_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_FSM_TRACK_1_WRITE_MASK,"PE1_FSM_TRACK_1",                 },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_FSM_TRACK_2_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_FSM_TRACK_2_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_FSM_TRACK_2_WRITE_MASK,"PE1_FSM_TRACK_2",                 },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_FSM_TRACK_3_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_FSM_TRACK_3_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PE1_FSM_TRACK_3_WRITE_MASK,"PE1_FSM_TRACK_3",                 },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_SUBSYSTEM_VERSION_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_SUBSYSTEM_VERSION_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_SUBSYSTEM_VERSION_WRITE_MASK,"PCIE_SUBSYSTEM_VERSION",          },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_APB_CLKFREQ_TIMEOUT_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_APB_CLKFREQ_TIMEOUT_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_APB_CLKFREQ_TIMEOUT_WRITE_MASK,"APB_CLKFREQ_TIMEOUT",             },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_SS_RST_CTRL_1_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_SS_RST_CTRL_1_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_SS_RST_CTRL_1_WRITE_MASK,"SS_RST_CTRL_1",                   },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_COMMON_CTRL_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_COMMON_CTRL_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_COMMON_CTRL_WRITE_MASK,"PCIE_PHY_COMMON_CTRL",            },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY0_GEN_CTRL_1_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY0_GEN_CTRL_1_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY0_GEN_CTRL_1_WRITE_MASK,"PCIE_PHY0_GEN_CTRL_1",            },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY0_GEN_CTRL_2_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY0_GEN_CTRL_2_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY0_GEN_CTRL_2_WRITE_MASK,"PCIE_PHY0_GEN_CTRL_2",            },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY0_MPLLA_CTRL_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY0_MPLLA_CTRL_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY0_MPLLA_CTRL_WRITE_MASK,"PCIE_PHY0_MPLLA_CTRL",            },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY0_MPLLB_CTRL_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY0_MPLLB_CTRL_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY0_MPLLB_CTRL_WRITE_MASK,"PCIE_PHY0_MPLLB_CTRL",            },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY1_GEN_CTRL_1_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY1_GEN_CTRL_1_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY1_GEN_CTRL_1_WRITE_MASK,"PCIE_PHY1_GEN_CTRL_1",            },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY1_GEN_CTRL_2_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY1_GEN_CTRL_2_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY1_GEN_CTRL_2_WRITE_MASK,"PCIE_PHY1_GEN_CTRL_2",            },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY1_MPLLA_CTRL_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY1_MPLLA_CTRL_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY1_MPLLA_CTRL_WRITE_MASK,"PCIE_PHY1_MPLLA_CTRL",            },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY1_MPLLB_CTRL_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY1_MPLLB_CTRL_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY1_MPLLB_CTRL_WRITE_MASK,"PCIE_PHY1_MPLLB_CTRL",            },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_MPLLA_CTRL_1_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_MPLLA_CTRL_1_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_MPLLA_CTRL_1_WRITE_MASK,"PCIE_PHY_MPLLA_CTRL_1",           },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_MPLLA_CTRL_2_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_MPLLA_CTRL_2_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_MPLLA_CTRL_2_WRITE_MASK,"PCIE_PHY_MPLLA_CTRL_2",           },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_MPLLA_CTRL_3_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_MPLLA_CTRL_3_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_MPLLA_CTRL_3_WRITE_MASK,"PCIE_PHY_MPLLA_CTRL_3",           },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_MPLLA_CTRL_4_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_MPLLA_CTRL_4_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_MPLLA_CTRL_4_WRITE_MASK,"PCIE_PHY_MPLLA_CTRL_4",           },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_MPLLA_CTRL_5_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_MPLLA_CTRL_5_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_MPLLA_CTRL_5_WRITE_MASK,"PCIE_PHY_MPLLA_CTRL_5",           },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_MPLLA_CTRL_6_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_MPLLA_CTRL_6_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_MPLLA_CTRL_6_WRITE_MASK,"PCIE_PHY_MPLLA_CTRL_6",           },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_MPLLA_CTRL_7_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_MPLLA_CTRL_7_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_MPLLA_CTRL_7_WRITE_MASK,"PCIE_PHY_MPLLA_CTRL_7",           },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_MPLLB_CTRL_1_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_MPLLB_CTRL_1_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_MPLLB_CTRL_1_WRITE_MASK,"PCIE_PHY_MPLLB_CTRL_1",           },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_MPLLB_CTRL_2_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_MPLLB_CTRL_2_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_MPLLB_CTRL_2_WRITE_MASK,"PCIE_PHY_MPLLB_CTRL_2",           },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_MPLLB_CTRL_3_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_MPLLB_CTRL_3_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_MPLLB_CTRL_3_WRITE_MASK,"PCIE_PHY_MPLLB_CTRL_3",           },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_MPLLB_CTRL_4_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_MPLLB_CTRL_4_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_MPLLB_CTRL_4_WRITE_MASK,"PCIE_PHY_MPLLB_CTRL_4",           },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_MPLLB_CTRL_5_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_MPLLB_CTRL_5_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_MPLLB_CTRL_5_WRITE_MASK,"PCIE_PHY_MPLLB_CTRL_5",           },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_MPLLB_CTRL_6_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_MPLLB_CTRL_6_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_MPLLB_CTRL_6_WRITE_MASK,"PCIE_PHY_MPLLB_CTRL_6",           },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_MPLLB_CTRL_7_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_MPLLB_CTRL_7_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_MPLLB_CTRL_7_WRITE_MASK,"PCIE_PHY_MPLLB_CTRL_7",           },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_GEN_CTRL_1_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_GEN_CTRL_1_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_GEN_CTRL_1_WRITE_MASK,"PCIE_PHY_EXT_GEN_CTRL_1",         },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_GEN_CTRL_2_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_GEN_CTRL_2_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_GEN_CTRL_2_WRITE_MASK,"PCIE_PHY_EXT_GEN_CTRL_2",         },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN1_1_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN1_1_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN1_1_WRITE_MASK,"PCIE_PHY_EXT_RX_CTRL_GEN1_1",     },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN1_2_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN1_2_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN1_2_WRITE_MASK,"PCIE_PHY_EXT_RX_CTRL_GEN1_2",     },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN1_4_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN1_4_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN1_4_WRITE_MASK,"PCIE_PHY_EXT_RX_CTRL_GEN1_4",     },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN2_1_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN2_1_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN2_1_WRITE_MASK,"PCIE_PHY_EXT_RX_CTRL_GEN2_1",     },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN2_2_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN2_2_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN2_2_WRITE_MASK,"PCIE_PHY_EXT_RX_CTRL_GEN2_2",     },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN2_3_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN2_3_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN2_3_WRITE_MASK,"PCIE_PHY_EXT_RX_CTRL_GEN2_3",     },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN2_4_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN2_4_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN2_4_WRITE_MASK,"PCIE_PHY_EXT_RX_CTRL_GEN2_4",     },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN3_1_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN3_1_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN3_1_WRITE_MASK,"PCIE_PHY_EXT_RX_CTRL_GEN3_1",     },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN3_2_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN3_2_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN3_2_WRITE_MASK,"PCIE_PHY_EXT_RX_CTRL_GEN3_2",     },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN3_3_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN3_3_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN3_3_WRITE_MASK,"PCIE_PHY_EXT_RX_CTRL_GEN3_3",     },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN3_4_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN3_4_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN3_4_WRITE_MASK,"PCIE_PHY_EXT_RX_CTRL_GEN3_4",     },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN4_1_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN4_1_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN4_1_WRITE_MASK,"PCIE_PHY_EXT_RX_CTRL_GEN4_1",     },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN4_2_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN4_2_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN4_2_WRITE_MASK,"PCIE_PHY_EXT_RX_CTRL_GEN4_2",     },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN4_3_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN4_3_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN4_3_WRITE_MASK,"PCIE_PHY_EXT_RX_CTRL_GEN4_3",     },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN4_4_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN4_4_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN4_4_WRITE_MASK,"PCIE_PHY_EXT_RX_CTRL_GEN4_4",     },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN1_5_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN1_5_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN1_5_WRITE_MASK,"PCIE_PHY_EXT_RX_CTRL_GEN1_5",     },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN2_5_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN2_5_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN2_5_WRITE_MASK,"PCIE_PHY_EXT_RX_CTRL_GEN2_5",     },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN3_5_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN3_5_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN3_5_WRITE_MASK,"PCIE_PHY_EXT_RX_CTRL_GEN3_5",     },   

{  DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN4_5_OFFSET,REGTEST_SIZE_32_BIT,          DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN4_5_RESET_VALUE,DWC_PCIE_SUBSYSTEM_CUSTOM_APB_SLAVE_SUBSYSTEM_PCIE_PHY_EXT_RX_CTRL_GEN4_5_WRITE_MASK,"PCIE_PHY_EXT_RX_CTRL_GEN4_5",     },   

   /* End List Delimiter */

{  REGTEST_END_OF_LIST,                              0,                            0,                                                0,                                                0,                                 }    

};  

