/*                                                                         */
/*                                                                         */
/* Generated by Semifore, Inc. csrCompile                                  */
/*    C Header output                                                      */

#ifndef _PU_GPIO_H_
#define _PU_GPIO_H_


/* ####################################################################### */
/*        ENUMERATION MACROS                                               */
/* ####################################################################### */

/* Enumeration: pu_gpio::GPIO_CONFIG_REG1::ADD_ENCODED_PARAMS::ADD_ENCODED_PARAMS */
/* Source filename: pu_gpio.csr, line: 727                                 */
#define PU_GPIO_GPIO_CONFIG_REG1_ADD_ENCODED_PARAMS_ADD_ENCODED_PARAMS_DISABLED 0x0u
#define PU_GPIO_GPIO_CONFIG_REG1_ADD_ENCODED_PARAMS_ADD_ENCODED_PARAMS_ENABLED 0x1u

/* Enumeration: pu_gpio::GPIO_CONFIG_REG1::APB_DATA_WIDTH::APB_DATA_WIDTH  */
/* Source filename: pu_gpio.csr, line: 478                                 */
#define PU_GPIO_GPIO_CONFIG_REG1_APB_DATA_WIDTH_APB_DATA_WIDTH_APB_16BITS 0x1u
#define PU_GPIO_GPIO_CONFIG_REG1_APB_DATA_WIDTH_APB_DATA_WIDTH_APB_32BITS 0x2u
#define PU_GPIO_GPIO_CONFIG_REG1_APB_DATA_WIDTH_APB_DATA_WIDTH_APB_8BITS 0x0u

/* Enumeration: pu_gpio::GPIO_CONFIG_REG1::DEBOUNCE::DEBOUNCE              */
/* Source filename: pu_gpio.csr, line: 708                                 */
#define PU_GPIO_GPIO_CONFIG_REG1_DEBOUNCE_DEBOUNCE_DISABLED 0x0u
#define PU_GPIO_GPIO_CONFIG_REG1_DEBOUNCE_DEBOUNCE_ENABLED 0x1u

/* Enumeration: pu_gpio::GPIO_CONFIG_REG1::GPIO_ID::GPIO_ID                */
/* Source filename: pu_gpio.csr, line: 746                                 */
#define PU_GPIO_GPIO_CONFIG_REG1_GPIO_ID_GPIO_ID_DISABLED 0x0u
#define PU_GPIO_GPIO_CONFIG_REG1_GPIO_ID_GPIO_ID_ENABLED 0x1u

/* Enumeration: pu_gpio::GPIO_CONFIG_REG1::HW_PORTA::HW_PORTA              */
/* Source filename: pu_gpio.csr, line: 604                                 */
#define PU_GPIO_GPIO_CONFIG_REG1_HW_PORTA_HW_PORTA_DISABLED 0x0u
#define PU_GPIO_GPIO_CONFIG_REG1_HW_PORTA_HW_PORTA_ENABLED 0x1u

/* Enumeration: pu_gpio::GPIO_CONFIG_REG1::HW_PORTB::HW_PORTB              */
/* Source filename: pu_gpio.csr, line: 625                                 */
#define PU_GPIO_GPIO_CONFIG_REG1_HW_PORTB_HW_PORTB_DISABLED 0x0u
#define PU_GPIO_GPIO_CONFIG_REG1_HW_PORTB_HW_PORTB_ENABLED 0x1u

/* Enumeration: pu_gpio::GPIO_CONFIG_REG1::HW_PORTC::HW_PORTC              */
/* Source filename: pu_gpio.csr, line: 646                                 */
#define PU_GPIO_GPIO_CONFIG_REG1_HW_PORTC_HW_PORTC_DISABLED 0x0u
#define PU_GPIO_GPIO_CONFIG_REG1_HW_PORTC_HW_PORTC_ENABLED 0x1u

/* Enumeration: pu_gpio::GPIO_CONFIG_REG1::HW_PORTD::HW_PORTD              */
/* Source filename: pu_gpio.csr, line: 667                                 */
#define PU_GPIO_GPIO_CONFIG_REG1_HW_PORTD_HW_PORTD_DISABLED 0x0u
#define PU_GPIO_GPIO_CONFIG_REG1_HW_PORTD_HW_PORTD_ENABLED 0x1u

/* Enumeration: pu_gpio::GPIO_CONFIG_REG1::INTERRUPT_BOTH_EDGE_TYPE::INTERRUPT_BOTH_EDGE_TYPE */
/* Source filename: pu_gpio.csr, line: 773                                 */
#define PU_GPIO_GPIO_CONFIG_REG1_INTERRUPT_BOTH_EDGE_TYPE_INTERRUPT_BOTH_EDGE_TYPE_DISABLED 0x0u
#define PU_GPIO_GPIO_CONFIG_REG1_INTERRUPT_BOTH_EDGE_TYPE_INTERRUPT_BOTH_EDGE_TYPE_ENABLED 0x1u

/* Enumeration: pu_gpio::GPIO_CONFIG_REG1::NUM_PORTS::NUM_PORTS            */
/* Source filename: pu_gpio.csr, line: 501                                 */
#define PU_GPIO_GPIO_CONFIG_REG1_NUM_PORTS_NUM_PORTS_NUM_PORTS_1 0x0u
#define PU_GPIO_GPIO_CONFIG_REG1_NUM_PORTS_NUM_PORTS_NUM_PORTS_2 0x1u
#define PU_GPIO_GPIO_CONFIG_REG1_NUM_PORTS_NUM_PORTS_NUM_PORTS_3 0x2u
#define PU_GPIO_GPIO_CONFIG_REG1_NUM_PORTS_NUM_PORTS_NUM_PORTS_4 0x3u

/* Enumeration: pu_gpio::GPIO_CONFIG_REG1::PORTA_INTR::PORTA_INTR          */
/* Source filename: pu_gpio.csr, line: 688                                 */
#define PU_GPIO_GPIO_CONFIG_REG1_PORTA_INTR_PORTA_INTR_DISABLED 0x0u
#define PU_GPIO_GPIO_CONFIG_REG1_PORTA_INTR_PORTA_INTR_ENABLED 0x1u

/* Enumeration: pu_gpio::GPIO_CONFIG_REG1::PORTA_SINGLE_CTL::PORTA_SINGLE_CTL */
/* Source filename: pu_gpio.csr, line: 528                                 */
#define PU_GPIO_GPIO_CONFIG_REG1_PORTA_SINGLE_CTL_PORTA_SINGLE_CTL_DISABLED 0x0u
#define PU_GPIO_GPIO_CONFIG_REG1_PORTA_SINGLE_CTL_PORTA_SINGLE_CTL_ENABLED 0x1u

/* Enumeration: pu_gpio::GPIO_CONFIG_REG1::PORTB_SINGLE_CTL::PORTB_SINGLE_CTL */
/* Source filename: pu_gpio.csr, line: 547                                 */
#define PU_GPIO_GPIO_CONFIG_REG1_PORTB_SINGLE_CTL_PORTB_SINGLE_CTL_DISABLED 0x0u
#define PU_GPIO_GPIO_CONFIG_REG1_PORTB_SINGLE_CTL_PORTB_SINGLE_CTL_ENABLED 0x1u

/* Enumeration: pu_gpio::GPIO_CONFIG_REG1::PORTC_SINGLE_CTL::PORTC_SINGLE_CTL */
/* Source filename: pu_gpio.csr, line: 566                                 */
#define PU_GPIO_GPIO_CONFIG_REG1_PORTC_SINGLE_CTL_PORTC_SINGLE_CTL_DISABLED 0x0u
#define PU_GPIO_GPIO_CONFIG_REG1_PORTC_SINGLE_CTL_PORTC_SINGLE_CTL_ENABLED 0x1u

/* Enumeration: pu_gpio::GPIO_CONFIG_REG1::PORTD_SINGLE_CTL::PORTD_SINGLE_CTL */
/* Source filename: pu_gpio.csr, line: 585                                 */
#define PU_GPIO_GPIO_CONFIG_REG1_PORTD_SINGLE_CTL_PORTD_SINGLE_CTL_DISABLED 0x0u
#define PU_GPIO_GPIO_CONFIG_REG1_PORTD_SINGLE_CTL_PORTD_SINGLE_CTL_ENABLED 0x1u

/* Enumeration: pu_gpio::GPIO_DEBOUNCE::GPIO_DEBOUNCE::GPIO_DEBOUNCE       */
/* Source filename: pu_gpio.csr, line: 286                                 */
#define PU_GPIO_GPIO_DEBOUNCE_GPIO_DEBOUNCE_GPIO_DEBOUNCE_DISABLED 0x0ul
#define PU_GPIO_GPIO_DEBOUNCE_GPIO_DEBOUNCE_GPIO_DEBOUNCE_ENABLED 0x1ul

/* Enumeration: pu_gpio::GPIO_INTEN::GPIO_INTEN::GPIO_INTEN                */
/* Source filename: pu_gpio.csr, line: 98                                  */
#define PU_GPIO_GPIO_INTEN_GPIO_INTEN_GPIO_INTEN_DISABLED 0x0ul
#define PU_GPIO_GPIO_INTEN_GPIO_INTEN_GPIO_INTEN_ENABLED 0x1ul

/* Enumeration: pu_gpio::GPIO_INTMASK::GPIO_INTMASK::GPIO_INTMASK          */
/* Source filename: pu_gpio.csr, line: 133                                 */
#define PU_GPIO_GPIO_INTMASK_GPIO_INTMASK_GPIO_INTMASK_DISABLED 0x0ul
#define PU_GPIO_GPIO_INTMASK_GPIO_INTMASK_GPIO_INTMASK_ENABLED 0x1ul

/* Enumeration: pu_gpio::GPIO_INTSTATUS::GPIO_INTSTATUS::GPIO_INTSTATUS    */
/* Source filename: pu_gpio.csr, line: 226                                 */
#define PU_GPIO_GPIO_INTSTATUS_GPIO_INTSTATUS_GPIO_INTSTATUS_ACTIVE 0x1ul
#define PU_GPIO_GPIO_INTSTATUS_GPIO_INTSTATUS_GPIO_INTSTATUS_INACTIVE 0x0ul

/* Enumeration: pu_gpio::GPIO_INTTYPE_LEVEL::GPIO_INTTYPE_LEVEL::GPIO_INTTYPE_LEVEL */
/* Source filename: pu_gpio.csr, line: 164                                 */
#define PU_GPIO_GPIO_INTTYPE_LEVEL_GPIO_INTTYPE_LEVEL_GPIO_INTTYPE_LEVEL_EDGE_SENSITIVE 0x1ul
#define PU_GPIO_GPIO_INTTYPE_LEVEL_GPIO_INTTYPE_LEVEL_GPIO_INTTYPE_LEVEL_LEVEL_SENSITIVE 0x0ul

/* Enumeration: pu_gpio::GPIO_INT_POLARITY::GPIO_INT_POLARITY::GPIO_INT_POLARITY */
/* Source filename: pu_gpio.csr, line: 197                                 */
#define PU_GPIO_GPIO_INT_POLARITY_GPIO_INT_POLARITY_GPIO_INT_POLARITY_ACTIVE_HIGH 0x1ul
#define PU_GPIO_GPIO_INT_POLARITY_GPIO_INT_POLARITY_GPIO_INT_POLARITY_ACTIVE_LOW 0x0ul

/* Enumeration: pu_gpio::GPIO_LS_SYNC::GPIO_LS_SYNC::GPIO_LS_SYNC          */
/* Source filename: pu_gpio.csr, line: 360                                 */
#define PU_GPIO_GPIO_LS_SYNC_GPIO_LS_SYNC_GPIO_LS_SYNC_DISABLED 0x0u
#define PU_GPIO_GPIO_LS_SYNC_GPIO_LS_SYNC_GPIO_LS_SYNC_ENABLED 0x1u

/* Enumeration: pu_gpio::GPIO_PORTA_EOI::GPIO_PORTA_EOI::GPIO_PORTA_EOI    */
/* Source filename: pu_gpio.csr, line: 319                                 */
#define PU_GPIO_GPIO_PORTA_EOI_GPIO_PORTA_EOI_GPIO_PORTA_EOI_DISABLED 0x0ul
#define PU_GPIO_GPIO_PORTA_EOI_GPIO_PORTA_EOI_GPIO_PORTA_EOI_ENABLED 0x1ul

/* Enumeration: pu_gpio::GPIO_RAW_INTSTATUS::GPIO_RAW_INTSTATUS::GPIO_RAW_INTSTATUS */
/* Source filename: pu_gpio.csr, line: 254                                 */
#define PU_GPIO_GPIO_RAW_INTSTATUS_GPIO_RAW_INTSTATUS_GPIO_RAW_INTSTATUS_ACTIVE 0x1ul
#define PU_GPIO_GPIO_RAW_INTSTATUS_GPIO_RAW_INTSTATUS_GPIO_RAW_INTSTATUS_INACTIVE 0x0ul

/* Enumeration: pu_gpio::GPIO_SWPORTA_DDR::GPIO_SWPORTA_DDR::GPIO_SWPORTA_DDR */
/* Source filename: pu_gpio.csr, line: 61                                  */
#define PU_GPIO_GPIO_SWPORTA_DDR_GPIO_SWPORTA_DDR_GPIO_SWPORTA_DDR_IN 0x0ul
#define PU_GPIO_GPIO_SWPORTA_DDR_GPIO_SWPORTA_DDR_GPIO_SWPORTA_DDR_OUT 0x1ul


/* ####################################################################### */
/*        ADDRESS MACROS                                                   */
/* ####################################################################### */

/* Address Space for Addressmap: pu_gpio                                   */
/* Source filename: pu_gpio.csr, line: 793                                 */
/* Register: pu_gpio.GPIO_SWPORTA_DR                                       */
#define PU_GPIO_GPIO_SWPORTA_DR_ADDRESS 0x0u
#define PU_GPIO_GPIO_SWPORTA_DR_BYTE_ADDRESS 0x0u
/* Register: pu_gpio.GPIO_SWPORTA_DDR                                      */
#define PU_GPIO_GPIO_SWPORTA_DDR_ADDRESS 0x4u
#define PU_GPIO_GPIO_SWPORTA_DDR_BYTE_ADDRESS 0x4u
/* Register: pu_gpio.GPIO_INTEN                                            */
#define PU_GPIO_GPIO_INTEN_ADDRESS 0x30u
#define PU_GPIO_GPIO_INTEN_BYTE_ADDRESS 0x30u
/* Register: pu_gpio.GPIO_INTMASK                                          */
#define PU_GPIO_GPIO_INTMASK_ADDRESS 0x34u
#define PU_GPIO_GPIO_INTMASK_BYTE_ADDRESS 0x34u
/* Register: pu_gpio.GPIO_INTTYPE_LEVEL                                    */
#define PU_GPIO_GPIO_INTTYPE_LEVEL_ADDRESS 0x38u
#define PU_GPIO_GPIO_INTTYPE_LEVEL_BYTE_ADDRESS 0x38u
/* Register: pu_gpio.GPIO_INT_POLARITY                                     */
#define PU_GPIO_GPIO_INT_POLARITY_ADDRESS 0x3cu
#define PU_GPIO_GPIO_INT_POLARITY_BYTE_ADDRESS 0x3cu
/* Register: pu_gpio.GPIO_INTSTATUS                                        */
#define PU_GPIO_GPIO_INTSTATUS_ADDRESS 0x40u
#define PU_GPIO_GPIO_INTSTATUS_BYTE_ADDRESS 0x40u
/* Register: pu_gpio.GPIO_RAW_INTSTATUS                                    */
#define PU_GPIO_GPIO_RAW_INTSTATUS_ADDRESS 0x44u
#define PU_GPIO_GPIO_RAW_INTSTATUS_BYTE_ADDRESS 0x44u
/* Register: pu_gpio.GPIO_DEBOUNCE                                         */
#define PU_GPIO_GPIO_DEBOUNCE_ADDRESS 0x48u
#define PU_GPIO_GPIO_DEBOUNCE_BYTE_ADDRESS 0x48u
/* Register: pu_gpio.GPIO_PORTA_EOI                                        */
#define PU_GPIO_GPIO_PORTA_EOI_ADDRESS 0x4cu
#define PU_GPIO_GPIO_PORTA_EOI_BYTE_ADDRESS 0x4cu
/* Register: pu_gpio.GPIO_EXT_PORTA                                        */
#define PU_GPIO_GPIO_EXT_PORTA_ADDRESS 0x50u
#define PU_GPIO_GPIO_EXT_PORTA_BYTE_ADDRESS 0x50u
/* Register: pu_gpio.GPIO_LS_SYNC                                          */
#define PU_GPIO_GPIO_LS_SYNC_ADDRESS 0x60u
#define PU_GPIO_GPIO_LS_SYNC_BYTE_ADDRESS 0x60u
/* Register: pu_gpio.GPIO_ID_CODE                                          */
#define PU_GPIO_GPIO_ID_CODE_ADDRESS 0x64u
#define PU_GPIO_GPIO_ID_CODE_BYTE_ADDRESS 0x64u
/* Register: pu_gpio.GPIO_VER_ID_CODE                                      */
#define PU_GPIO_GPIO_VER_ID_CODE_ADDRESS 0x6cu
#define PU_GPIO_GPIO_VER_ID_CODE_BYTE_ADDRESS 0x6cu
/* Register: pu_gpio.GPIO_CONFIG_REG2                                      */
#define PU_GPIO_GPIO_CONFIG_REG2_ADDRESS 0x70u
#define PU_GPIO_GPIO_CONFIG_REG2_BYTE_ADDRESS 0x70u
/* Register: pu_gpio.GPIO_CONFIG_REG1                                      */
#define PU_GPIO_GPIO_CONFIG_REG1_ADDRESS 0x74u
#define PU_GPIO_GPIO_CONFIG_REG1_BYTE_ADDRESS 0x74u


/* ####################################################################### */
/*        TEMPLATE MACROS                                                  */
/* ####################################################################### */

/* Addressmap type: pu_gpio                                                */
/* Addressmap template: pu_gpio                                            */
/* Source filename: pu_gpio.csr, line: 22                                  */
#define PU_GPIO_SIZE 0x78u
#define PU_GPIO_BYTE_SIZE 0x78u
/* Register member: pu_gpio.GPIO_SWPORTA_DR                                */
/* Register type referenced: pu_gpio::GPIO_SWPORTA_DR                      */
/* Register template referenced: pu_gpio::GPIO_SWPORTA_DR                  */
#define PU_GPIO_GPIO_SWPORTA_DR_OFFSET 0x0u
#define PU_GPIO_GPIO_SWPORTA_DR_BYTE_OFFSET 0x0u
#define PU_GPIO_GPIO_SWPORTA_DR_READ_ACCESS 1u
#define PU_GPIO_GPIO_SWPORTA_DR_WRITE_ACCESS 1u
#define PU_GPIO_GPIO_SWPORTA_DR_RESET_VALUE 0x00000000ul
#define PU_GPIO_GPIO_SWPORTA_DR_RESET_MASK 0xfffffffful
#define PU_GPIO_GPIO_SWPORTA_DR_READ_MASK 0xfffffffful
#define PU_GPIO_GPIO_SWPORTA_DR_WRITE_MASK 0xfffffffful
/* Register member: pu_gpio.GPIO_SWPORTA_DDR                               */
/* Register type referenced: pu_gpio::GPIO_SWPORTA_DDR                     */
/* Register template referenced: pu_gpio::GPIO_SWPORTA_DDR                 */
#define PU_GPIO_GPIO_SWPORTA_DDR_OFFSET 0x4u
#define PU_GPIO_GPIO_SWPORTA_DDR_BYTE_OFFSET 0x4u
#define PU_GPIO_GPIO_SWPORTA_DDR_READ_ACCESS 1u
#define PU_GPIO_GPIO_SWPORTA_DDR_WRITE_ACCESS 1u
#define PU_GPIO_GPIO_SWPORTA_DDR_RESET_VALUE 0x00000000ul
#define PU_GPIO_GPIO_SWPORTA_DDR_RESET_MASK 0xfffffffful
#define PU_GPIO_GPIO_SWPORTA_DDR_READ_MASK 0xfffffffful
#define PU_GPIO_GPIO_SWPORTA_DDR_WRITE_MASK 0xfffffffful
/* Register member: pu_gpio.GPIO_INTEN                                     */
/* Register type referenced: pu_gpio::GPIO_INTEN                           */
/* Register template referenced: pu_gpio::GPIO_INTEN                       */
#define PU_GPIO_GPIO_INTEN_OFFSET 0x30u
#define PU_GPIO_GPIO_INTEN_BYTE_OFFSET 0x30u
#define PU_GPIO_GPIO_INTEN_READ_ACCESS 1u
#define PU_GPIO_GPIO_INTEN_WRITE_ACCESS 1u
#define PU_GPIO_GPIO_INTEN_RESET_VALUE 0x00000000ul
#define PU_GPIO_GPIO_INTEN_RESET_MASK 0xfffffffful
#define PU_GPIO_GPIO_INTEN_READ_MASK 0xfffffffful
#define PU_GPIO_GPIO_INTEN_WRITE_MASK 0xfffffffful
/* Register member: pu_gpio.GPIO_INTMASK                                   */
/* Register type referenced: pu_gpio::GPIO_INTMASK                         */
/* Register template referenced: pu_gpio::GPIO_INTMASK                     */
#define PU_GPIO_GPIO_INTMASK_OFFSET 0x34u
#define PU_GPIO_GPIO_INTMASK_BYTE_OFFSET 0x34u
#define PU_GPIO_GPIO_INTMASK_READ_ACCESS 1u
#define PU_GPIO_GPIO_INTMASK_WRITE_ACCESS 1u
#define PU_GPIO_GPIO_INTMASK_RESET_VALUE 0x00000000ul
#define PU_GPIO_GPIO_INTMASK_RESET_MASK 0xfffffffful
#define PU_GPIO_GPIO_INTMASK_READ_MASK 0xfffffffful
#define PU_GPIO_GPIO_INTMASK_WRITE_MASK 0xfffffffful
/* Register member: pu_gpio.GPIO_INTTYPE_LEVEL                             */
/* Register type referenced: pu_gpio::GPIO_INTTYPE_LEVEL                   */
/* Register template referenced: pu_gpio::GPIO_INTTYPE_LEVEL               */
#define PU_GPIO_GPIO_INTTYPE_LEVEL_OFFSET 0x38u
#define PU_GPIO_GPIO_INTTYPE_LEVEL_BYTE_OFFSET 0x38u
#define PU_GPIO_GPIO_INTTYPE_LEVEL_READ_ACCESS 1u
#define PU_GPIO_GPIO_INTTYPE_LEVEL_WRITE_ACCESS 1u
#define PU_GPIO_GPIO_INTTYPE_LEVEL_RESET_VALUE 0x00000000ul
#define PU_GPIO_GPIO_INTTYPE_LEVEL_RESET_MASK 0xfffffffful
#define PU_GPIO_GPIO_INTTYPE_LEVEL_READ_MASK 0xfffffffful
#define PU_GPIO_GPIO_INTTYPE_LEVEL_WRITE_MASK 0xfffffffful
/* Register member: pu_gpio.GPIO_INT_POLARITY                              */
/* Register type referenced: pu_gpio::GPIO_INT_POLARITY                    */
/* Register template referenced: pu_gpio::GPIO_INT_POLARITY                */
#define PU_GPIO_GPIO_INT_POLARITY_OFFSET 0x3cu
#define PU_GPIO_GPIO_INT_POLARITY_BYTE_OFFSET 0x3cu
#define PU_GPIO_GPIO_INT_POLARITY_READ_ACCESS 1u
#define PU_GPIO_GPIO_INT_POLARITY_WRITE_ACCESS 1u
#define PU_GPIO_GPIO_INT_POLARITY_RESET_VALUE 0x00000000ul
#define PU_GPIO_GPIO_INT_POLARITY_RESET_MASK 0xfffffffful
#define PU_GPIO_GPIO_INT_POLARITY_READ_MASK 0xfffffffful
#define PU_GPIO_GPIO_INT_POLARITY_WRITE_MASK 0xfffffffful
/* Register member: pu_gpio.GPIO_INTSTATUS                                 */
/* Register type referenced: pu_gpio::GPIO_INTSTATUS                       */
/* Register template referenced: pu_gpio::GPIO_INTSTATUS                   */
#define PU_GPIO_GPIO_INTSTATUS_OFFSET 0x40u
#define PU_GPIO_GPIO_INTSTATUS_BYTE_OFFSET 0x40u
#define PU_GPIO_GPIO_INTSTATUS_READ_ACCESS 1u
#define PU_GPIO_GPIO_INTSTATUS_WRITE_ACCESS 0u
#define PU_GPIO_GPIO_INTSTATUS_RESET_VALUE 0x00000000ul
#define PU_GPIO_GPIO_INTSTATUS_RESET_MASK 0xfffffffful
#define PU_GPIO_GPIO_INTSTATUS_READ_MASK 0xfffffffful
#define PU_GPIO_GPIO_INTSTATUS_WRITE_MASK 0x00000000ul
/* Register member: pu_gpio.GPIO_RAW_INTSTATUS                             */
/* Register type referenced: pu_gpio::GPIO_RAW_INTSTATUS                   */
/* Register template referenced: pu_gpio::GPIO_RAW_INTSTATUS               */
#define PU_GPIO_GPIO_RAW_INTSTATUS_OFFSET 0x44u
#define PU_GPIO_GPIO_RAW_INTSTATUS_BYTE_OFFSET 0x44u
#define PU_GPIO_GPIO_RAW_INTSTATUS_READ_ACCESS 1u
#define PU_GPIO_GPIO_RAW_INTSTATUS_WRITE_ACCESS 0u
#define PU_GPIO_GPIO_RAW_INTSTATUS_RESET_VALUE 0x00000000ul
#define PU_GPIO_GPIO_RAW_INTSTATUS_RESET_MASK 0xfffffffful
#define PU_GPIO_GPIO_RAW_INTSTATUS_READ_MASK 0xfffffffful
#define PU_GPIO_GPIO_RAW_INTSTATUS_WRITE_MASK 0x00000000ul
/* Register member: pu_gpio.GPIO_DEBOUNCE                                  */
/* Register type referenced: pu_gpio::GPIO_DEBOUNCE                        */
/* Register template referenced: pu_gpio::GPIO_DEBOUNCE                    */
#define PU_GPIO_GPIO_DEBOUNCE_OFFSET 0x48u
#define PU_GPIO_GPIO_DEBOUNCE_BYTE_OFFSET 0x48u
#define PU_GPIO_GPIO_DEBOUNCE_READ_ACCESS 1u
#define PU_GPIO_GPIO_DEBOUNCE_WRITE_ACCESS 1u
#define PU_GPIO_GPIO_DEBOUNCE_RESET_VALUE 0x00000000ul
#define PU_GPIO_GPIO_DEBOUNCE_RESET_MASK 0xfffffffful
#define PU_GPIO_GPIO_DEBOUNCE_READ_MASK 0xfffffffful
#define PU_GPIO_GPIO_DEBOUNCE_WRITE_MASK 0xfffffffful
/* Register member: pu_gpio.GPIO_PORTA_EOI                                 */
/* Register type referenced: pu_gpio::GPIO_PORTA_EOI                       */
/* Register template referenced: pu_gpio::GPIO_PORTA_EOI                   */
#define PU_GPIO_GPIO_PORTA_EOI_OFFSET 0x4cu
#define PU_GPIO_GPIO_PORTA_EOI_BYTE_OFFSET 0x4cu
#define PU_GPIO_GPIO_PORTA_EOI_READ_ACCESS 0u
#define PU_GPIO_GPIO_PORTA_EOI_WRITE_ACCESS 1u
#define PU_GPIO_GPIO_PORTA_EOI_RESET_VALUE 0x00000000ul
#define PU_GPIO_GPIO_PORTA_EOI_RESET_MASK 0xfffffffful
#define PU_GPIO_GPIO_PORTA_EOI_READ_MASK 0x00000000ul
#define PU_GPIO_GPIO_PORTA_EOI_WRITE_MASK 0xfffffffful
/* Register member: pu_gpio.GPIO_EXT_PORTA                                 */
/* Register type referenced: pu_gpio::GPIO_EXT_PORTA                       */
/* Register template referenced: pu_gpio::GPIO_EXT_PORTA                   */
#define PU_GPIO_GPIO_EXT_PORTA_OFFSET 0x50u
#define PU_GPIO_GPIO_EXT_PORTA_BYTE_OFFSET 0x50u
#define PU_GPIO_GPIO_EXT_PORTA_READ_ACCESS 1u
#define PU_GPIO_GPIO_EXT_PORTA_WRITE_ACCESS 0u
#define PU_GPIO_GPIO_EXT_PORTA_RESET_VALUE 0x00000000ul
#define PU_GPIO_GPIO_EXT_PORTA_RESET_MASK 0xfffffffful
#define PU_GPIO_GPIO_EXT_PORTA_READ_MASK 0xfffffffful
#define PU_GPIO_GPIO_EXT_PORTA_WRITE_MASK 0x00000000ul
/* Register member: pu_gpio.GPIO_LS_SYNC                                   */
/* Register type referenced: pu_gpio::GPIO_LS_SYNC                         */
/* Register template referenced: pu_gpio::GPIO_LS_SYNC                     */
#define PU_GPIO_GPIO_LS_SYNC_OFFSET 0x60u
#define PU_GPIO_GPIO_LS_SYNC_BYTE_OFFSET 0x60u
#define PU_GPIO_GPIO_LS_SYNC_READ_ACCESS 1u
#define PU_GPIO_GPIO_LS_SYNC_WRITE_ACCESS 1u
#define PU_GPIO_GPIO_LS_SYNC_RESET_VALUE 0x00000000ul
#define PU_GPIO_GPIO_LS_SYNC_RESET_MASK 0xfffffffful
#define PU_GPIO_GPIO_LS_SYNC_READ_MASK 0xfffffffful
#define PU_GPIO_GPIO_LS_SYNC_WRITE_MASK 0x00000001ul
/* Register member: pu_gpio.GPIO_ID_CODE                                   */
/* Register type referenced: pu_gpio::GPIO_ID_CODE                         */
/* Register template referenced: pu_gpio::GPIO_ID_CODE                     */
#define PU_GPIO_GPIO_ID_CODE_OFFSET 0x64u
#define PU_GPIO_GPIO_ID_CODE_BYTE_OFFSET 0x64u
#define PU_GPIO_GPIO_ID_CODE_READ_ACCESS 1u
#define PU_GPIO_GPIO_ID_CODE_WRITE_ACCESS 0u
#define PU_GPIO_GPIO_ID_CODE_RESET_VALUE 0x00000001ul
#define PU_GPIO_GPIO_ID_CODE_RESET_MASK 0xfffffffful
#define PU_GPIO_GPIO_ID_CODE_READ_MASK 0xfffffffful
#define PU_GPIO_GPIO_ID_CODE_WRITE_MASK 0x00000000ul
/* Register member: pu_gpio.GPIO_VER_ID_CODE                               */
/* Register type referenced: pu_gpio::GPIO_VER_ID_CODE                     */
/* Register template referenced: pu_gpio::GPIO_VER_ID_CODE                 */
#define PU_GPIO_GPIO_VER_ID_CODE_OFFSET 0x6cu
#define PU_GPIO_GPIO_VER_ID_CODE_BYTE_OFFSET 0x6cu
#define PU_GPIO_GPIO_VER_ID_CODE_READ_ACCESS 1u
#define PU_GPIO_GPIO_VER_ID_CODE_WRITE_ACCESS 0u
#define PU_GPIO_GPIO_VER_ID_CODE_RESET_VALUE 0x3231332aul
#define PU_GPIO_GPIO_VER_ID_CODE_RESET_MASK 0xfffffffful
#define PU_GPIO_GPIO_VER_ID_CODE_READ_MASK 0xfffffffful
#define PU_GPIO_GPIO_VER_ID_CODE_WRITE_MASK 0x00000000ul
/* Register member: pu_gpio.GPIO_CONFIG_REG2                               */
/* Register type referenced: pu_gpio::GPIO_CONFIG_REG2                     */
/* Register template referenced: pu_gpio::GPIO_CONFIG_REG2                 */
#define PU_GPIO_GPIO_CONFIG_REG2_OFFSET 0x70u
#define PU_GPIO_GPIO_CONFIG_REG2_BYTE_OFFSET 0x70u
#define PU_GPIO_GPIO_CONFIG_REG2_READ_ACCESS 1u
#define PU_GPIO_GPIO_CONFIG_REG2_WRITE_ACCESS 0u
#define PU_GPIO_GPIO_CONFIG_REG2_RESET_VALUE 0x00039ce7ul
#define PU_GPIO_GPIO_CONFIG_REG2_RESET_MASK 0xfffffffful
#define PU_GPIO_GPIO_CONFIG_REG2_READ_MASK 0xfffffffful
#define PU_GPIO_GPIO_CONFIG_REG2_WRITE_MASK 0x00000000ul
/* Register member: pu_gpio.GPIO_CONFIG_REG1                               */
/* Register type referenced: pu_gpio::GPIO_CONFIG_REG1                     */
/* Register template referenced: pu_gpio::GPIO_CONFIG_REG1                 */
#define PU_GPIO_GPIO_CONFIG_REG1_OFFSET 0x74u
#define PU_GPIO_GPIO_CONFIG_REG1_BYTE_OFFSET 0x74u
#define PU_GPIO_GPIO_CONFIG_REG1_READ_ACCESS 1u
#define PU_GPIO_GPIO_CONFIG_REG1_WRITE_ACCESS 0u
#define PU_GPIO_GPIO_CONFIG_REG1_RESET_VALUE 0x001ff0f2ul
#define PU_GPIO_GPIO_CONFIG_REG1_RESET_MASK 0xfffffffful
#define PU_GPIO_GPIO_CONFIG_REG1_READ_MASK 0xfffffffful
#define PU_GPIO_GPIO_CONFIG_REG1_WRITE_MASK 0x00000000ul

/* Register type: pu_gpio::GPIO_SWPORTA_DR                                 */
/* Register template: pu_gpio::GPIO_SWPORTA_DR                             */
/* Source filename: pu_gpio.csr, line: 26                                  */
/* Field member: pu_gpio::GPIO_SWPORTA_DR.GPIO_SWPORTA_DR                  */
/* Source filename: pu_gpio.csr, line: 31                                  */
#define PU_GPIO_GPIO_SWPORTA_DR_GPIO_SWPORTA_DR_MSB 31u
#define PU_GPIO_GPIO_SWPORTA_DR_GPIO_SWPORTA_DR_LSB 0u
#define PU_GPIO_GPIO_SWPORTA_DR_GPIO_SWPORTA_DR_WIDTH 32u
#define PU_GPIO_GPIO_SWPORTA_DR_GPIO_SWPORTA_DR_READ_ACCESS 1u
#define PU_GPIO_GPIO_SWPORTA_DR_GPIO_SWPORTA_DR_WRITE_ACCESS 1u
#define PU_GPIO_GPIO_SWPORTA_DR_GPIO_SWPORTA_DR_RESET 0x00000000ul
#define PU_GPIO_GPIO_SWPORTA_DR_GPIO_SWPORTA_DR_FIELD_MASK 0xfffffffful
#define PU_GPIO_GPIO_SWPORTA_DR_GPIO_SWPORTA_DR_GET(x) ((x) & 0xfffffffful)
#define PU_GPIO_GPIO_SWPORTA_DR_GPIO_SWPORTA_DR_SET(x) ((x) & 0xfffffffful)
#define PU_GPIO_GPIO_SWPORTA_DR_GPIO_SWPORTA_DR_MODIFY(r, x) \
   ((x) & 0xfffffffful)

/* Register type: pu_gpio::GPIO_SWPORTA_DDR                                */
/* Register template: pu_gpio::GPIO_SWPORTA_DDR                            */
/* Source filename: pu_gpio.csr, line: 47                                  */
/* Field member: pu_gpio::GPIO_SWPORTA_DDR.GPIO_SWPORTA_DDR                */
/* Source filename: pu_gpio.csr, line: 52                                  */
#define PU_GPIO_GPIO_SWPORTA_DDR_GPIO_SWPORTA_DDR_MSB 31u
#define PU_GPIO_GPIO_SWPORTA_DDR_GPIO_SWPORTA_DDR_LSB 0u
#define PU_GPIO_GPIO_SWPORTA_DDR_GPIO_SWPORTA_DDR_WIDTH 32u
#define PU_GPIO_GPIO_SWPORTA_DDR_GPIO_SWPORTA_DDR_READ_ACCESS 1u
#define PU_GPIO_GPIO_SWPORTA_DDR_GPIO_SWPORTA_DDR_WRITE_ACCESS 1u
#define PU_GPIO_GPIO_SWPORTA_DDR_GPIO_SWPORTA_DDR_RESET 0x00000000ul
#define PU_GPIO_GPIO_SWPORTA_DDR_GPIO_SWPORTA_DDR_FIELD_MASK 0xfffffffful
#define PU_GPIO_GPIO_SWPORTA_DDR_GPIO_SWPORTA_DDR_GET(x) ((x) & 0xfffffffful)
#define PU_GPIO_GPIO_SWPORTA_DDR_GPIO_SWPORTA_DDR_SET(x) ((x) & 0xfffffffful)
#define PU_GPIO_GPIO_SWPORTA_DDR_GPIO_SWPORTA_DDR_MODIFY(r, x) \
   ((x) & 0xfffffffful)

/* Register type: pu_gpio::GPIO_INTEN                                      */
/* Register template: pu_gpio::GPIO_INTEN                                  */
/* Source filename: pu_gpio.csr, line: 75                                  */
/* Field member: pu_gpio::GPIO_INTEN.GPIO_INTEN                            */
/* Source filename: pu_gpio.csr, line: 83                                  */
#define PU_GPIO_GPIO_INTEN_GPIO_INTEN_MSB 31u
#define PU_GPIO_GPIO_INTEN_GPIO_INTEN_LSB 0u
#define PU_GPIO_GPIO_INTEN_GPIO_INTEN_WIDTH 32u
#define PU_GPIO_GPIO_INTEN_GPIO_INTEN_READ_ACCESS 1u
#define PU_GPIO_GPIO_INTEN_GPIO_INTEN_WRITE_ACCESS 1u
#define PU_GPIO_GPIO_INTEN_GPIO_INTEN_RESET 0x00000000ul
#define PU_GPIO_GPIO_INTEN_GPIO_INTEN_FIELD_MASK 0xfffffffful
#define PU_GPIO_GPIO_INTEN_GPIO_INTEN_GET(x) ((x) & 0xfffffffful)
#define PU_GPIO_GPIO_INTEN_GPIO_INTEN_SET(x) ((x) & 0xfffffffful)
#define PU_GPIO_GPIO_INTEN_GPIO_INTEN_MODIFY(r, x) ((x) & 0xfffffffful)

/* Register type: pu_gpio::GPIO_INTMASK                                    */
/* Register template: pu_gpio::GPIO_INTMASK                                */
/* Source filename: pu_gpio.csr, line: 112                                 */
/* Field member: pu_gpio::GPIO_INTMASK.GPIO_INTMASK                        */
/* Source filename: pu_gpio.csr, line: 120                                 */
#define PU_GPIO_GPIO_INTMASK_GPIO_INTMASK_MSB 31u
#define PU_GPIO_GPIO_INTMASK_GPIO_INTMASK_LSB 0u
#define PU_GPIO_GPIO_INTMASK_GPIO_INTMASK_WIDTH 32u
#define PU_GPIO_GPIO_INTMASK_GPIO_INTMASK_READ_ACCESS 1u
#define PU_GPIO_GPIO_INTMASK_GPIO_INTMASK_WRITE_ACCESS 1u
#define PU_GPIO_GPIO_INTMASK_GPIO_INTMASK_RESET 0x00000000ul
#define PU_GPIO_GPIO_INTMASK_GPIO_INTMASK_FIELD_MASK 0xfffffffful
#define PU_GPIO_GPIO_INTMASK_GPIO_INTMASK_GET(x) ((x) & 0xfffffffful)
#define PU_GPIO_GPIO_INTMASK_GPIO_INTMASK_SET(x) ((x) & 0xfffffffful)
#define PU_GPIO_GPIO_INTMASK_GPIO_INTMASK_MODIFY(r, x) ((x) & 0xfffffffful)

/* Register type: pu_gpio::GPIO_INTTYPE_LEVEL                              */
/* Register template: pu_gpio::GPIO_INTTYPE_LEVEL                          */
/* Source filename: pu_gpio.csr, line: 147                                 */
/* Field member: pu_gpio::GPIO_INTTYPE_LEVEL.GPIO_INTTYPE_LEVEL            */
/* Source filename: pu_gpio.csr, line: 155                                 */
#define PU_GPIO_GPIO_INTTYPE_LEVEL_GPIO_INTTYPE_LEVEL_MSB 31u
#define PU_GPIO_GPIO_INTTYPE_LEVEL_GPIO_INTTYPE_LEVEL_LSB 0u
#define PU_GPIO_GPIO_INTTYPE_LEVEL_GPIO_INTTYPE_LEVEL_WIDTH 32u
#define PU_GPIO_GPIO_INTTYPE_LEVEL_GPIO_INTTYPE_LEVEL_READ_ACCESS 1u
#define PU_GPIO_GPIO_INTTYPE_LEVEL_GPIO_INTTYPE_LEVEL_WRITE_ACCESS 1u
#define PU_GPIO_GPIO_INTTYPE_LEVEL_GPIO_INTTYPE_LEVEL_RESET 0x00000000ul
#define PU_GPIO_GPIO_INTTYPE_LEVEL_GPIO_INTTYPE_LEVEL_FIELD_MASK 0xfffffffful
#define PU_GPIO_GPIO_INTTYPE_LEVEL_GPIO_INTTYPE_LEVEL_GET(x) \
   ((x) & 0xfffffffful)
#define PU_GPIO_GPIO_INTTYPE_LEVEL_GPIO_INTTYPE_LEVEL_SET(x) \
   ((x) & 0xfffffffful)
#define PU_GPIO_GPIO_INTTYPE_LEVEL_GPIO_INTTYPE_LEVEL_MODIFY(r, x) \
   ((x) & 0xfffffffful)

/* Register type: pu_gpio::GPIO_INT_POLARITY                               */
/* Register template: pu_gpio::GPIO_INT_POLARITY                           */
/* Source filename: pu_gpio.csr, line: 178                                 */
/* Field member: pu_gpio::GPIO_INT_POLARITY.GPIO_INT_POLARITY              */
/* Source filename: pu_gpio.csr, line: 186                                 */
#define PU_GPIO_GPIO_INT_POLARITY_GPIO_INT_POLARITY_MSB 31u
#define PU_GPIO_GPIO_INT_POLARITY_GPIO_INT_POLARITY_LSB 0u
#define PU_GPIO_GPIO_INT_POLARITY_GPIO_INT_POLARITY_WIDTH 32u
#define PU_GPIO_GPIO_INT_POLARITY_GPIO_INT_POLARITY_READ_ACCESS 1u
#define PU_GPIO_GPIO_INT_POLARITY_GPIO_INT_POLARITY_WRITE_ACCESS 1u
#define PU_GPIO_GPIO_INT_POLARITY_GPIO_INT_POLARITY_RESET 0x00000000ul
#define PU_GPIO_GPIO_INT_POLARITY_GPIO_INT_POLARITY_FIELD_MASK 0xfffffffful
#define PU_GPIO_GPIO_INT_POLARITY_GPIO_INT_POLARITY_GET(x) \
   ((x) & 0xfffffffful)
#define PU_GPIO_GPIO_INT_POLARITY_GPIO_INT_POLARITY_SET(x) \
   ((x) & 0xfffffffful)
#define PU_GPIO_GPIO_INT_POLARITY_GPIO_INT_POLARITY_MODIFY(r, x) \
   ((x) & 0xfffffffful)

/* Register type: pu_gpio::GPIO_INTSTATUS                                  */
/* Register template: pu_gpio::GPIO_INTSTATUS                              */
/* Source filename: pu_gpio.csr, line: 211                                 */
/* Field member: pu_gpio::GPIO_INTSTATUS.GPIO_INTSTATUS                    */
/* Source filename: pu_gpio.csr, line: 220                                 */
#define PU_GPIO_GPIO_INTSTATUS_GPIO_INTSTATUS_MSB 31u
#define PU_GPIO_GPIO_INTSTATUS_GPIO_INTSTATUS_LSB 0u
#define PU_GPIO_GPIO_INTSTATUS_GPIO_INTSTATUS_WIDTH 32u
#define PU_GPIO_GPIO_INTSTATUS_GPIO_INTSTATUS_READ_ACCESS 1u
#define PU_GPIO_GPIO_INTSTATUS_GPIO_INTSTATUS_WRITE_ACCESS 0u
#define PU_GPIO_GPIO_INTSTATUS_GPIO_INTSTATUS_RESET 0x00000000ul
#define PU_GPIO_GPIO_INTSTATUS_GPIO_INTSTATUS_FIELD_MASK 0xfffffffful
#define PU_GPIO_GPIO_INTSTATUS_GPIO_INTSTATUS_GET(x) ((x) & 0xfffffffful)
#define PU_GPIO_GPIO_INTSTATUS_GPIO_INTSTATUS_SET(x) ((x) & 0xfffffffful)
#define PU_GPIO_GPIO_INTSTATUS_GPIO_INTSTATUS_MODIFY(r, x) \
   ((x) & 0xfffffffful)

/* Register type: pu_gpio::GPIO_RAW_INTSTATUS                              */
/* Register template: pu_gpio::GPIO_RAW_INTSTATUS                          */
/* Source filename: pu_gpio.csr, line: 239                                 */
/* Field member: pu_gpio::GPIO_RAW_INTSTATUS.GPIO_RAW_INTSTATUS            */
/* Source filename: pu_gpio.csr, line: 248                                 */
#define PU_GPIO_GPIO_RAW_INTSTATUS_GPIO_RAW_INTSTATUS_MSB 31u
#define PU_GPIO_GPIO_RAW_INTSTATUS_GPIO_RAW_INTSTATUS_LSB 0u
#define PU_GPIO_GPIO_RAW_INTSTATUS_GPIO_RAW_INTSTATUS_WIDTH 32u
#define PU_GPIO_GPIO_RAW_INTSTATUS_GPIO_RAW_INTSTATUS_READ_ACCESS 1u
#define PU_GPIO_GPIO_RAW_INTSTATUS_GPIO_RAW_INTSTATUS_WRITE_ACCESS 0u
#define PU_GPIO_GPIO_RAW_INTSTATUS_GPIO_RAW_INTSTATUS_RESET 0x00000000ul
#define PU_GPIO_GPIO_RAW_INTSTATUS_GPIO_RAW_INTSTATUS_FIELD_MASK 0xfffffffful
#define PU_GPIO_GPIO_RAW_INTSTATUS_GPIO_RAW_INTSTATUS_GET(x) \
   ((x) & 0xfffffffful)
#define PU_GPIO_GPIO_RAW_INTSTATUS_GPIO_RAW_INTSTATUS_SET(x) \
   ((x) & 0xfffffffful)
#define PU_GPIO_GPIO_RAW_INTSTATUS_GPIO_RAW_INTSTATUS_MODIFY(r, x) \
   ((x) & 0xfffffffful)

/* Register type: pu_gpio::GPIO_DEBOUNCE                                   */
/* Register template: pu_gpio::GPIO_DEBOUNCE                               */
/* Source filename: pu_gpio.csr, line: 267                                 */
/* Field member: pu_gpio::GPIO_DEBOUNCE.GPIO_DEBOUNCE                      */
/* Source filename: pu_gpio.csr, line: 276                                 */
#define PU_GPIO_GPIO_DEBOUNCE_GPIO_DEBOUNCE_MSB 31u
#define PU_GPIO_GPIO_DEBOUNCE_GPIO_DEBOUNCE_LSB 0u
#define PU_GPIO_GPIO_DEBOUNCE_GPIO_DEBOUNCE_WIDTH 32u
#define PU_GPIO_GPIO_DEBOUNCE_GPIO_DEBOUNCE_READ_ACCESS 1u
#define PU_GPIO_GPIO_DEBOUNCE_GPIO_DEBOUNCE_WRITE_ACCESS 1u
#define PU_GPIO_GPIO_DEBOUNCE_GPIO_DEBOUNCE_RESET 0x00000000ul
#define PU_GPIO_GPIO_DEBOUNCE_GPIO_DEBOUNCE_FIELD_MASK 0xfffffffful
#define PU_GPIO_GPIO_DEBOUNCE_GPIO_DEBOUNCE_GET(x) ((x) & 0xfffffffful)
#define PU_GPIO_GPIO_DEBOUNCE_GPIO_DEBOUNCE_SET(x) ((x) & 0xfffffffful)
#define PU_GPIO_GPIO_DEBOUNCE_GPIO_DEBOUNCE_MODIFY(r, x) ((x) & 0xfffffffful)

/* Register type: pu_gpio::GPIO_PORTA_EOI                                  */
/* Register template: pu_gpio::GPIO_PORTA_EOI                              */
/* Source filename: pu_gpio.csr, line: 300                                 */
/* Field member: pu_gpio::GPIO_PORTA_EOI.GPIO_PORTA_EOI                    */
/* Source filename: pu_gpio.csr, line: 310                                 */
#define PU_GPIO_GPIO_PORTA_EOI_GPIO_PORTA_EOI_MSB 31u
#define PU_GPIO_GPIO_PORTA_EOI_GPIO_PORTA_EOI_LSB 0u
#define PU_GPIO_GPIO_PORTA_EOI_GPIO_PORTA_EOI_WIDTH 32u
#define PU_GPIO_GPIO_PORTA_EOI_GPIO_PORTA_EOI_READ_ACCESS 0u
#define PU_GPIO_GPIO_PORTA_EOI_GPIO_PORTA_EOI_WRITE_ACCESS 1u
#define PU_GPIO_GPIO_PORTA_EOI_GPIO_PORTA_EOI_RESET 0x00000000ul
#define PU_GPIO_GPIO_PORTA_EOI_GPIO_PORTA_EOI_FIELD_MASK 0xfffffffful
#define PU_GPIO_GPIO_PORTA_EOI_GPIO_PORTA_EOI_GET(x) ((x) & 0xfffffffful)
#define PU_GPIO_GPIO_PORTA_EOI_GPIO_PORTA_EOI_SET(x) ((x) & 0xfffffffful)
#define PU_GPIO_GPIO_PORTA_EOI_GPIO_PORTA_EOI_MODIFY(r, x) \
   ((x) & 0xfffffffful)

/* Register type: pu_gpio::GPIO_EXT_PORTA                                  */
/* Register template: pu_gpio::GPIO_EXT_PORTA                              */
/* Source filename: pu_gpio.csr, line: 333                                 */
/* Field member: pu_gpio::GPIO_EXT_PORTA.GPIO_EXT_PORTA                    */
/* Source filename: pu_gpio.csr, line: 339                                 */
#define PU_GPIO_GPIO_EXT_PORTA_GPIO_EXT_PORTA_MSB 31u
#define PU_GPIO_GPIO_EXT_PORTA_GPIO_EXT_PORTA_LSB 0u
#define PU_GPIO_GPIO_EXT_PORTA_GPIO_EXT_PORTA_WIDTH 32u
#define PU_GPIO_GPIO_EXT_PORTA_GPIO_EXT_PORTA_READ_ACCESS 1u
#define PU_GPIO_GPIO_EXT_PORTA_GPIO_EXT_PORTA_WRITE_ACCESS 0u
#define PU_GPIO_GPIO_EXT_PORTA_GPIO_EXT_PORTA_RESET 0x00000000ul
#define PU_GPIO_GPIO_EXT_PORTA_GPIO_EXT_PORTA_FIELD_MASK 0xfffffffful
#define PU_GPIO_GPIO_EXT_PORTA_GPIO_EXT_PORTA_GET(x) ((x) & 0xfffffffful)
#define PU_GPIO_GPIO_EXT_PORTA_GPIO_EXT_PORTA_SET(x) ((x) & 0xfffffffful)
#define PU_GPIO_GPIO_EXT_PORTA_GPIO_EXT_PORTA_MODIFY(r, x) \
   ((x) & 0xfffffffful)

/* Register type: pu_gpio::GPIO_LS_SYNC                                    */
/* Register template: pu_gpio::GPIO_LS_SYNC                                */
/* Source filename: pu_gpio.csr, line: 348                                 */
/* Field member: pu_gpio::GPIO_LS_SYNC.RSVD_GPIO_LS_SYNC                   */
/* Source filename: pu_gpio.csr, line: 373                                 */
#define PU_GPIO_GPIO_LS_SYNC_RSVD_GPIO_LS_SYNC_MSB 31u
#define PU_GPIO_GPIO_LS_SYNC_RSVD_GPIO_LS_SYNC_LSB 1u
#define PU_GPIO_GPIO_LS_SYNC_RSVD_GPIO_LS_SYNC_WIDTH 31u
#define PU_GPIO_GPIO_LS_SYNC_RSVD_GPIO_LS_SYNC_READ_ACCESS 1u
#define PU_GPIO_GPIO_LS_SYNC_RSVD_GPIO_LS_SYNC_WRITE_ACCESS 0u
#define PU_GPIO_GPIO_LS_SYNC_RSVD_GPIO_LS_SYNC_RESET 0x00000000ul
#define PU_GPIO_GPIO_LS_SYNC_RSVD_GPIO_LS_SYNC_FIELD_MASK 0xfffffffeul
#define PU_GPIO_GPIO_LS_SYNC_RSVD_GPIO_LS_SYNC_GET(x) \
   (((x) & 0xfffffffeul) >> 1)
#define PU_GPIO_GPIO_LS_SYNC_RSVD_GPIO_LS_SYNC_SET(x) \
   (((x) << 1) & 0xfffffffeul)
#define PU_GPIO_GPIO_LS_SYNC_RSVD_GPIO_LS_SYNC_MODIFY(r, x) \
   ((((x) << 1) & 0xfffffffeul) | ((r) & 0x00000001ul))
/* Field member: pu_gpio::GPIO_LS_SYNC.GPIO_LS_SYNC                        */
/* Source filename: pu_gpio.csr, line: 353                                 */
#define PU_GPIO_GPIO_LS_SYNC_GPIO_LS_SYNC_MSB 0u
#define PU_GPIO_GPIO_LS_SYNC_GPIO_LS_SYNC_LSB 0u
#define PU_GPIO_GPIO_LS_SYNC_GPIO_LS_SYNC_WIDTH 1u
#define PU_GPIO_GPIO_LS_SYNC_GPIO_LS_SYNC_READ_ACCESS 1u
#define PU_GPIO_GPIO_LS_SYNC_GPIO_LS_SYNC_WRITE_ACCESS 1u
#define PU_GPIO_GPIO_LS_SYNC_GPIO_LS_SYNC_RESET 0x0u
#define PU_GPIO_GPIO_LS_SYNC_GPIO_LS_SYNC_FIELD_MASK 0x00000001ul
#define PU_GPIO_GPIO_LS_SYNC_GPIO_LS_SYNC_GET(x) ((x) & 0x00000001ul)
#define PU_GPIO_GPIO_LS_SYNC_GPIO_LS_SYNC_SET(x) ((x) & 0x00000001ul)
#define PU_GPIO_GPIO_LS_SYNC_GPIO_LS_SYNC_MODIFY(r, x) \
   (((x) & 0x00000001ul) | ((r) & 0xfffffffeul))

/* Register type: pu_gpio::GPIO_ID_CODE                                    */
/* Register template: pu_gpio::GPIO_ID_CODE                                */
/* Source filename: pu_gpio.csr, line: 382                                 */
/* Field member: pu_gpio::GPIO_ID_CODE.GPIO_ID_CODE                        */
/* Source filename: pu_gpio.csr, line: 388                                 */
#define PU_GPIO_GPIO_ID_CODE_GPIO_ID_CODE_MSB 31u
#define PU_GPIO_GPIO_ID_CODE_GPIO_ID_CODE_LSB 0u
#define PU_GPIO_GPIO_ID_CODE_GPIO_ID_CODE_WIDTH 32u
#define PU_GPIO_GPIO_ID_CODE_GPIO_ID_CODE_READ_ACCESS 1u
#define PU_GPIO_GPIO_ID_CODE_GPIO_ID_CODE_WRITE_ACCESS 0u
#define PU_GPIO_GPIO_ID_CODE_GPIO_ID_CODE_RESET 0x00000001ul
#define PU_GPIO_GPIO_ID_CODE_GPIO_ID_CODE_FIELD_MASK 0xfffffffful
#define PU_GPIO_GPIO_ID_CODE_GPIO_ID_CODE_GET(x) ((x) & 0xfffffffful)
#define PU_GPIO_GPIO_ID_CODE_GPIO_ID_CODE_SET(x) ((x) & 0xfffffffful)
#define PU_GPIO_GPIO_ID_CODE_GPIO_ID_CODE_MODIFY(r, x) ((x) & 0xfffffffful)

/* Register type: pu_gpio::GPIO_VER_ID_CODE                                */
/* Register template: pu_gpio::GPIO_VER_ID_CODE                            */
/* Source filename: pu_gpio.csr, line: 398                                 */
/* Field member: pu_gpio::GPIO_VER_ID_CODE.GPIO_VER_ID_CODE                */
/* Source filename: pu_gpio.csr, line: 404                                 */
#define PU_GPIO_GPIO_VER_ID_CODE_GPIO_VER_ID_CODE_MSB 31u
#define PU_GPIO_GPIO_VER_ID_CODE_GPIO_VER_ID_CODE_LSB 0u
#define PU_GPIO_GPIO_VER_ID_CODE_GPIO_VER_ID_CODE_WIDTH 32u
#define PU_GPIO_GPIO_VER_ID_CODE_GPIO_VER_ID_CODE_READ_ACCESS 1u
#define PU_GPIO_GPIO_VER_ID_CODE_GPIO_VER_ID_CODE_WRITE_ACCESS 0u
#define PU_GPIO_GPIO_VER_ID_CODE_GPIO_VER_ID_CODE_RESET 0x3231332aul
#define PU_GPIO_GPIO_VER_ID_CODE_GPIO_VER_ID_CODE_FIELD_MASK 0xfffffffful
#define PU_GPIO_GPIO_VER_ID_CODE_GPIO_VER_ID_CODE_GET(x) ((x) & 0xfffffffful)
#define PU_GPIO_GPIO_VER_ID_CODE_GPIO_VER_ID_CODE_SET(x) ((x) & 0xfffffffful)
#define PU_GPIO_GPIO_VER_ID_CODE_GPIO_VER_ID_CODE_MODIFY(r, x) \
   ((x) & 0xfffffffful)

/* Register type: pu_gpio::GPIO_CONFIG_REG2                                */
/* Register template: pu_gpio::GPIO_CONFIG_REG2                            */
/* Source filename: pu_gpio.csr, line: 414                                 */
/* Field member: pu_gpio::GPIO_CONFIG_REG2.RSVD_GPIO_CONFIG_REG2           */
/* Source filename: pu_gpio.csr, line: 452                                 */
#define PU_GPIO_GPIO_CONFIG_REG2_RSVD_GPIO_CONFIG_REG2_MSB 31u
#define PU_GPIO_GPIO_CONFIG_REG2_RSVD_GPIO_CONFIG_REG2_LSB 20u
#define PU_GPIO_GPIO_CONFIG_REG2_RSVD_GPIO_CONFIG_REG2_WIDTH 12u
#define PU_GPIO_GPIO_CONFIG_REG2_RSVD_GPIO_CONFIG_REG2_READ_ACCESS 1u
#define PU_GPIO_GPIO_CONFIG_REG2_RSVD_GPIO_CONFIG_REG2_WRITE_ACCESS 0u
#define PU_GPIO_GPIO_CONFIG_REG2_RSVD_GPIO_CONFIG_REG2_RESET 0x000u
#define PU_GPIO_GPIO_CONFIG_REG2_RSVD_GPIO_CONFIG_REG2_FIELD_MASK 0xfff00000ul
#define PU_GPIO_GPIO_CONFIG_REG2_RSVD_GPIO_CONFIG_REG2_GET(x) \
   (((x) & 0xfff00000ul) >> 20)
#define PU_GPIO_GPIO_CONFIG_REG2_RSVD_GPIO_CONFIG_REG2_SET(x) \
   (((x) << 20) & 0xfff00000ul)
#define PU_GPIO_GPIO_CONFIG_REG2_RSVD_GPIO_CONFIG_REG2_MODIFY(r, x) \
   ((((x) << 20) & 0xfff00000ul) | ((r) & 0x000ffffful))
/* Field member: pu_gpio::GPIO_CONFIG_REG2.ENCODED_ID_PWIDTH_D             */
/* Source filename: pu_gpio.csr, line: 445                                 */
#define PU_GPIO_GPIO_CONFIG_REG2_ENCODED_ID_PWIDTH_D_MSB 19u
#define PU_GPIO_GPIO_CONFIG_REG2_ENCODED_ID_PWIDTH_D_LSB 15u
#define PU_GPIO_GPIO_CONFIG_REG2_ENCODED_ID_PWIDTH_D_WIDTH 5u
#define PU_GPIO_GPIO_CONFIG_REG2_ENCODED_ID_PWIDTH_D_READ_ACCESS 1u
#define PU_GPIO_GPIO_CONFIG_REG2_ENCODED_ID_PWIDTH_D_WRITE_ACCESS 0u
#define PU_GPIO_GPIO_CONFIG_REG2_ENCODED_ID_PWIDTH_D_RESET 0x07u
#define PU_GPIO_GPIO_CONFIG_REG2_ENCODED_ID_PWIDTH_D_FIELD_MASK 0x000f8000ul
#define PU_GPIO_GPIO_CONFIG_REG2_ENCODED_ID_PWIDTH_D_GET(x) \
   (((x) & 0x000f8000ul) >> 15)
#define PU_GPIO_GPIO_CONFIG_REG2_ENCODED_ID_PWIDTH_D_SET(x) \
   (((x) << 15) & 0x000f8000ul)
#define PU_GPIO_GPIO_CONFIG_REG2_ENCODED_ID_PWIDTH_D_MODIFY(r, x) \
   ((((x) << 15) & 0x000f8000ul) | ((r) & 0xfff07ffful))
/* Field member: pu_gpio::GPIO_CONFIG_REG2.ENCODED_ID_PWIDTH_C             */
/* Source filename: pu_gpio.csr, line: 438                                 */
#define PU_GPIO_GPIO_CONFIG_REG2_ENCODED_ID_PWIDTH_C_MSB 14u
#define PU_GPIO_GPIO_CONFIG_REG2_ENCODED_ID_PWIDTH_C_LSB 10u
#define PU_GPIO_GPIO_CONFIG_REG2_ENCODED_ID_PWIDTH_C_WIDTH 5u
#define PU_GPIO_GPIO_CONFIG_REG2_ENCODED_ID_PWIDTH_C_READ_ACCESS 1u
#define PU_GPIO_GPIO_CONFIG_REG2_ENCODED_ID_PWIDTH_C_WRITE_ACCESS 0u
#define PU_GPIO_GPIO_CONFIG_REG2_ENCODED_ID_PWIDTH_C_RESET 0x07u
#define PU_GPIO_GPIO_CONFIG_REG2_ENCODED_ID_PWIDTH_C_FIELD_MASK 0x00007c00ul
#define PU_GPIO_GPIO_CONFIG_REG2_ENCODED_ID_PWIDTH_C_GET(x) \
   (((x) & 0x00007c00ul) >> 10)
#define PU_GPIO_GPIO_CONFIG_REG2_ENCODED_ID_PWIDTH_C_SET(x) \
   (((x) << 10) & 0x00007c00ul)
#define PU_GPIO_GPIO_CONFIG_REG2_ENCODED_ID_PWIDTH_C_MODIFY(r, x) \
   ((((x) << 10) & 0x00007c00ul) | ((r) & 0xffff83fful))
/* Field member: pu_gpio::GPIO_CONFIG_REG2.ENCODED_ID_PWIDTH_B             */
/* Source filename: pu_gpio.csr, line: 431                                 */
#define PU_GPIO_GPIO_CONFIG_REG2_ENCODED_ID_PWIDTH_B_MSB 9u
#define PU_GPIO_GPIO_CONFIG_REG2_ENCODED_ID_PWIDTH_B_LSB 5u
#define PU_GPIO_GPIO_CONFIG_REG2_ENCODED_ID_PWIDTH_B_WIDTH 5u
#define PU_GPIO_GPIO_CONFIG_REG2_ENCODED_ID_PWIDTH_B_READ_ACCESS 1u
#define PU_GPIO_GPIO_CONFIG_REG2_ENCODED_ID_PWIDTH_B_WRITE_ACCESS 0u
#define PU_GPIO_GPIO_CONFIG_REG2_ENCODED_ID_PWIDTH_B_RESET 0x07u
#define PU_GPIO_GPIO_CONFIG_REG2_ENCODED_ID_PWIDTH_B_FIELD_MASK 0x000003e0ul
#define PU_GPIO_GPIO_CONFIG_REG2_ENCODED_ID_PWIDTH_B_GET(x) \
   (((x) & 0x000003e0ul) >> 5)
#define PU_GPIO_GPIO_CONFIG_REG2_ENCODED_ID_PWIDTH_B_SET(x) \
   (((x) << 5) & 0x000003e0ul)
#define PU_GPIO_GPIO_CONFIG_REG2_ENCODED_ID_PWIDTH_B_MODIFY(r, x) \
   ((((x) << 5) & 0x000003e0ul) | ((r) & 0xfffffc1ful))
/* Field member: pu_gpio::GPIO_CONFIG_REG2.ENCODED_ID_PWIDTH_A             */
/* Source filename: pu_gpio.csr, line: 424                                 */
#define PU_GPIO_GPIO_CONFIG_REG2_ENCODED_ID_PWIDTH_A_MSB 4u
#define PU_GPIO_GPIO_CONFIG_REG2_ENCODED_ID_PWIDTH_A_LSB 0u
#define PU_GPIO_GPIO_CONFIG_REG2_ENCODED_ID_PWIDTH_A_WIDTH 5u
#define PU_GPIO_GPIO_CONFIG_REG2_ENCODED_ID_PWIDTH_A_READ_ACCESS 1u
#define PU_GPIO_GPIO_CONFIG_REG2_ENCODED_ID_PWIDTH_A_WRITE_ACCESS 0u
#define PU_GPIO_GPIO_CONFIG_REG2_ENCODED_ID_PWIDTH_A_RESET 0x07u
#define PU_GPIO_GPIO_CONFIG_REG2_ENCODED_ID_PWIDTH_A_FIELD_MASK 0x0000001ful
#define PU_GPIO_GPIO_CONFIG_REG2_ENCODED_ID_PWIDTH_A_GET(x) \
   ((x) & 0x0000001ful)
#define PU_GPIO_GPIO_CONFIG_REG2_ENCODED_ID_PWIDTH_A_SET(x) \
   ((x) & 0x0000001ful)
#define PU_GPIO_GPIO_CONFIG_REG2_ENCODED_ID_PWIDTH_A_MODIFY(r, x) \
   (((x) & 0x0000001ful) | ((r) & 0xffffffe0ul))

/* Register type: pu_gpio::GPIO_CONFIG_REG1                                */
/* Register template: pu_gpio::GPIO_CONFIG_REG1                            */
/* Source filename: pu_gpio.csr, line: 460                                 */
/* Field member: pu_gpio::GPIO_CONFIG_REG1.RSVD_GPIO_CONFIG_REG1           */
/* Source filename: pu_gpio.csr, line: 785                                 */
#define PU_GPIO_GPIO_CONFIG_REG1_RSVD_GPIO_CONFIG_REG1_MSB 31u
#define PU_GPIO_GPIO_CONFIG_REG1_RSVD_GPIO_CONFIG_REG1_LSB 22u
#define PU_GPIO_GPIO_CONFIG_REG1_RSVD_GPIO_CONFIG_REG1_WIDTH 10u
#define PU_GPIO_GPIO_CONFIG_REG1_RSVD_GPIO_CONFIG_REG1_READ_ACCESS 1u
#define PU_GPIO_GPIO_CONFIG_REG1_RSVD_GPIO_CONFIG_REG1_WRITE_ACCESS 0u
#define PU_GPIO_GPIO_CONFIG_REG1_RSVD_GPIO_CONFIG_REG1_RESET 0x000u
#define PU_GPIO_GPIO_CONFIG_REG1_RSVD_GPIO_CONFIG_REG1_FIELD_MASK 0xffc00000ul
#define PU_GPIO_GPIO_CONFIG_REG1_RSVD_GPIO_CONFIG_REG1_GET(x) \
   (((x) & 0xffc00000ul) >> 22)
#define PU_GPIO_GPIO_CONFIG_REG1_RSVD_GPIO_CONFIG_REG1_SET(x) \
   (((x) << 22) & 0xffc00000ul)
#define PU_GPIO_GPIO_CONFIG_REG1_RSVD_GPIO_CONFIG_REG1_MODIFY(r, x) \
   ((((x) << 22) & 0xffc00000ul) | ((r) & 0x003ffffful))
/* Field member: pu_gpio::GPIO_CONFIG_REG1.INTERRUPT_BOTH_EDGE_TYPE        */
/* Source filename: pu_gpio.csr, line: 766                                 */
#define PU_GPIO_GPIO_CONFIG_REG1_INTERRUPT_BOTH_EDGE_TYPE_MSB 21u
#define PU_GPIO_GPIO_CONFIG_REG1_INTERRUPT_BOTH_EDGE_TYPE_LSB 21u
#define PU_GPIO_GPIO_CONFIG_REG1_INTERRUPT_BOTH_EDGE_TYPE_WIDTH 1u
#define PU_GPIO_GPIO_CONFIG_REG1_INTERRUPT_BOTH_EDGE_TYPE_READ_ACCESS 1u
#define PU_GPIO_GPIO_CONFIG_REG1_INTERRUPT_BOTH_EDGE_TYPE_WRITE_ACCESS 0u
#define PU_GPIO_GPIO_CONFIG_REG1_INTERRUPT_BOTH_EDGE_TYPE_RESET 0x0u
#define PU_GPIO_GPIO_CONFIG_REG1_INTERRUPT_BOTH_EDGE_TYPE_FIELD_MASK 0x00200000ul
#define PU_GPIO_GPIO_CONFIG_REG1_INTERRUPT_BOTH_EDGE_TYPE_GET(x) \
   (((x) & 0x00200000ul) >> 21)
#define PU_GPIO_GPIO_CONFIG_REG1_INTERRUPT_BOTH_EDGE_TYPE_SET(x) \
   (((x) << 21) & 0x00200000ul)
#define PU_GPIO_GPIO_CONFIG_REG1_INTERRUPT_BOTH_EDGE_TYPE_MODIFY(r, x) \
   ((((x) << 21) & 0x00200000ul) | ((r) & 0xffdffffful))
/* Field member: pu_gpio::GPIO_CONFIG_REG1.ENCODED_ID_WIDTH                */
/* Source filename: pu_gpio.csr, line: 758                                 */
#define PU_GPIO_GPIO_CONFIG_REG1_ENCODED_ID_WIDTH_MSB 20u
#define PU_GPIO_GPIO_CONFIG_REG1_ENCODED_ID_WIDTH_LSB 16u
#define PU_GPIO_GPIO_CONFIG_REG1_ENCODED_ID_WIDTH_WIDTH 5u
#define PU_GPIO_GPIO_CONFIG_REG1_ENCODED_ID_WIDTH_READ_ACCESS 1u
#define PU_GPIO_GPIO_CONFIG_REG1_ENCODED_ID_WIDTH_WRITE_ACCESS 0u
#define PU_GPIO_GPIO_CONFIG_REG1_ENCODED_ID_WIDTH_RESET 0x1fu
#define PU_GPIO_GPIO_CONFIG_REG1_ENCODED_ID_WIDTH_FIELD_MASK 0x001f0000ul
#define PU_GPIO_GPIO_CONFIG_REG1_ENCODED_ID_WIDTH_GET(x) \
   (((x) & 0x001f0000ul) >> 16)
#define PU_GPIO_GPIO_CONFIG_REG1_ENCODED_ID_WIDTH_SET(x) \
   (((x) << 16) & 0x001f0000ul)
#define PU_GPIO_GPIO_CONFIG_REG1_ENCODED_ID_WIDTH_MODIFY(r, x) \
   ((((x) << 16) & 0x001f0000ul) | ((r) & 0xffe0fffful))
/* Field member: pu_gpio::GPIO_CONFIG_REG1.GPIO_ID                         */
/* Source filename: pu_gpio.csr, line: 739                                 */
#define PU_GPIO_GPIO_CONFIG_REG1_GPIO_ID_MSB 15u
#define PU_GPIO_GPIO_CONFIG_REG1_GPIO_ID_LSB 15u
#define PU_GPIO_GPIO_CONFIG_REG1_GPIO_ID_WIDTH 1u
#define PU_GPIO_GPIO_CONFIG_REG1_GPIO_ID_READ_ACCESS 1u
#define PU_GPIO_GPIO_CONFIG_REG1_GPIO_ID_WRITE_ACCESS 0u
#define PU_GPIO_GPIO_CONFIG_REG1_GPIO_ID_RESET 0x1u
#define PU_GPIO_GPIO_CONFIG_REG1_GPIO_ID_FIELD_MASK 0x00008000ul
#define PU_GPIO_GPIO_CONFIG_REG1_GPIO_ID_GET(x) (((x) & 0x00008000ul) >> 15)
#define PU_GPIO_GPIO_CONFIG_REG1_GPIO_ID_SET(x) \
   (((x) << 15) & 0x00008000ul)
#define PU_GPIO_GPIO_CONFIG_REG1_GPIO_ID_MODIFY(r, x) \
   ((((x) << 15) & 0x00008000ul) | ((r) & 0xffff7ffful))
/* Field member: pu_gpio::GPIO_CONFIG_REG1.ADD_ENCODED_PARAMS              */
/* Source filename: pu_gpio.csr, line: 720                                 */
#define PU_GPIO_GPIO_CONFIG_REG1_ADD_ENCODED_PARAMS_MSB 14u
#define PU_GPIO_GPIO_CONFIG_REG1_ADD_ENCODED_PARAMS_LSB 14u
#define PU_GPIO_GPIO_CONFIG_REG1_ADD_ENCODED_PARAMS_WIDTH 1u
#define PU_GPIO_GPIO_CONFIG_REG1_ADD_ENCODED_PARAMS_READ_ACCESS 1u
#define PU_GPIO_GPIO_CONFIG_REG1_ADD_ENCODED_PARAMS_WRITE_ACCESS 0u
#define PU_GPIO_GPIO_CONFIG_REG1_ADD_ENCODED_PARAMS_RESET 0x1u
#define PU_GPIO_GPIO_CONFIG_REG1_ADD_ENCODED_PARAMS_FIELD_MASK 0x00004000ul
#define PU_GPIO_GPIO_CONFIG_REG1_ADD_ENCODED_PARAMS_GET(x) \
   (((x) & 0x00004000ul) >> 14)
#define PU_GPIO_GPIO_CONFIG_REG1_ADD_ENCODED_PARAMS_SET(x) \
   (((x) << 14) & 0x00004000ul)
#define PU_GPIO_GPIO_CONFIG_REG1_ADD_ENCODED_PARAMS_MODIFY(r, x) \
   ((((x) << 14) & 0x00004000ul) | ((r) & 0xffffbffful))
/* Field member: pu_gpio::GPIO_CONFIG_REG1.DEBOUNCE                        */
/* Source filename: pu_gpio.csr, line: 701                                 */
#define PU_GPIO_GPIO_CONFIG_REG1_DEBOUNCE_MSB 13u
#define PU_GPIO_GPIO_CONFIG_REG1_DEBOUNCE_LSB 13u
#define PU_GPIO_GPIO_CONFIG_REG1_DEBOUNCE_WIDTH 1u
#define PU_GPIO_GPIO_CONFIG_REG1_DEBOUNCE_READ_ACCESS 1u
#define PU_GPIO_GPIO_CONFIG_REG1_DEBOUNCE_WRITE_ACCESS 0u
#define PU_GPIO_GPIO_CONFIG_REG1_DEBOUNCE_RESET 0x1u
#define PU_GPIO_GPIO_CONFIG_REG1_DEBOUNCE_FIELD_MASK 0x00002000ul
#define PU_GPIO_GPIO_CONFIG_REG1_DEBOUNCE_GET(x) (((x) & 0x00002000ul) >> 13)
#define PU_GPIO_GPIO_CONFIG_REG1_DEBOUNCE_SET(x) \
   (((x) << 13) & 0x00002000ul)
#define PU_GPIO_GPIO_CONFIG_REG1_DEBOUNCE_MODIFY(r, x) \
   ((((x) << 13) & 0x00002000ul) | ((r) & 0xffffdffful))
/* Field member: pu_gpio::GPIO_CONFIG_REG1.PORTA_INTR                      */
/* Source filename: pu_gpio.csr, line: 681                                 */
#define PU_GPIO_GPIO_CONFIG_REG1_PORTA_INTR_MSB 12u
#define PU_GPIO_GPIO_CONFIG_REG1_PORTA_INTR_LSB 12u
#define PU_GPIO_GPIO_CONFIG_REG1_PORTA_INTR_WIDTH 1u
#define PU_GPIO_GPIO_CONFIG_REG1_PORTA_INTR_READ_ACCESS 1u
#define PU_GPIO_GPIO_CONFIG_REG1_PORTA_INTR_WRITE_ACCESS 0u
#define PU_GPIO_GPIO_CONFIG_REG1_PORTA_INTR_RESET 0x1u
#define PU_GPIO_GPIO_CONFIG_REG1_PORTA_INTR_FIELD_MASK 0x00001000ul
#define PU_GPIO_GPIO_CONFIG_REG1_PORTA_INTR_GET(x) \
   (((x) & 0x00001000ul) >> 12)
#define PU_GPIO_GPIO_CONFIG_REG1_PORTA_INTR_SET(x) \
   (((x) << 12) & 0x00001000ul)
#define PU_GPIO_GPIO_CONFIG_REG1_PORTA_INTR_MODIFY(r, x) \
   ((((x) << 12) & 0x00001000ul) | ((r) & 0xffffeffful))
/* Field member: pu_gpio::GPIO_CONFIG_REG1.HW_PORTD                        */
/* Source filename: pu_gpio.csr, line: 660                                 */
#define PU_GPIO_GPIO_CONFIG_REG1_HW_PORTD_MSB 11u
#define PU_GPIO_GPIO_CONFIG_REG1_HW_PORTD_LSB 11u
#define PU_GPIO_GPIO_CONFIG_REG1_HW_PORTD_WIDTH 1u
#define PU_GPIO_GPIO_CONFIG_REG1_HW_PORTD_READ_ACCESS 1u
#define PU_GPIO_GPIO_CONFIG_REG1_HW_PORTD_WRITE_ACCESS 0u
#define PU_GPIO_GPIO_CONFIG_REG1_HW_PORTD_RESET 0x0u
#define PU_GPIO_GPIO_CONFIG_REG1_HW_PORTD_FIELD_MASK 0x00000800ul
#define PU_GPIO_GPIO_CONFIG_REG1_HW_PORTD_GET(x) (((x) & 0x00000800ul) >> 11)
#define PU_GPIO_GPIO_CONFIG_REG1_HW_PORTD_SET(x) \
   (((x) << 11) & 0x00000800ul)
#define PU_GPIO_GPIO_CONFIG_REG1_HW_PORTD_MODIFY(r, x) \
   ((((x) << 11) & 0x00000800ul) | ((r) & 0xfffff7fful))
/* Field member: pu_gpio::GPIO_CONFIG_REG1.HW_PORTC                        */
/* Source filename: pu_gpio.csr, line: 639                                 */
#define PU_GPIO_GPIO_CONFIG_REG1_HW_PORTC_MSB 10u
#define PU_GPIO_GPIO_CONFIG_REG1_HW_PORTC_LSB 10u
#define PU_GPIO_GPIO_CONFIG_REG1_HW_PORTC_WIDTH 1u
#define PU_GPIO_GPIO_CONFIG_REG1_HW_PORTC_READ_ACCESS 1u
#define PU_GPIO_GPIO_CONFIG_REG1_HW_PORTC_WRITE_ACCESS 0u
#define PU_GPIO_GPIO_CONFIG_REG1_HW_PORTC_RESET 0x0u
#define PU_GPIO_GPIO_CONFIG_REG1_HW_PORTC_FIELD_MASK 0x00000400ul
#define PU_GPIO_GPIO_CONFIG_REG1_HW_PORTC_GET(x) (((x) & 0x00000400ul) >> 10)
#define PU_GPIO_GPIO_CONFIG_REG1_HW_PORTC_SET(x) \
   (((x) << 10) & 0x00000400ul)
#define PU_GPIO_GPIO_CONFIG_REG1_HW_PORTC_MODIFY(r, x) \
   ((((x) << 10) & 0x00000400ul) | ((r) & 0xfffffbfful))
/* Field member: pu_gpio::GPIO_CONFIG_REG1.HW_PORTB                        */
/* Source filename: pu_gpio.csr, line: 618                                 */
#define PU_GPIO_GPIO_CONFIG_REG1_HW_PORTB_MSB 9u
#define PU_GPIO_GPIO_CONFIG_REG1_HW_PORTB_LSB 9u
#define PU_GPIO_GPIO_CONFIG_REG1_HW_PORTB_WIDTH 1u
#define PU_GPIO_GPIO_CONFIG_REG1_HW_PORTB_READ_ACCESS 1u
#define PU_GPIO_GPIO_CONFIG_REG1_HW_PORTB_WRITE_ACCESS 0u
#define PU_GPIO_GPIO_CONFIG_REG1_HW_PORTB_RESET 0x0u
#define PU_GPIO_GPIO_CONFIG_REG1_HW_PORTB_FIELD_MASK 0x00000200ul
#define PU_GPIO_GPIO_CONFIG_REG1_HW_PORTB_GET(x) (((x) & 0x00000200ul) >> 9)
#define PU_GPIO_GPIO_CONFIG_REG1_HW_PORTB_SET(x) (((x) << 9) & 0x00000200ul)
#define PU_GPIO_GPIO_CONFIG_REG1_HW_PORTB_MODIFY(r, x) \
   ((((x) << 9) & 0x00000200ul) | ((r) & 0xfffffdfful))
/* Field member: pu_gpio::GPIO_CONFIG_REG1.HW_PORTA                        */
/* Source filename: pu_gpio.csr, line: 597                                 */
#define PU_GPIO_GPIO_CONFIG_REG1_HW_PORTA_MSB 8u
#define PU_GPIO_GPIO_CONFIG_REG1_HW_PORTA_LSB 8u
#define PU_GPIO_GPIO_CONFIG_REG1_HW_PORTA_WIDTH 1u
#define PU_GPIO_GPIO_CONFIG_REG1_HW_PORTA_READ_ACCESS 1u
#define PU_GPIO_GPIO_CONFIG_REG1_HW_PORTA_WRITE_ACCESS 0u
#define PU_GPIO_GPIO_CONFIG_REG1_HW_PORTA_RESET 0x0u
#define PU_GPIO_GPIO_CONFIG_REG1_HW_PORTA_FIELD_MASK 0x00000100ul
#define PU_GPIO_GPIO_CONFIG_REG1_HW_PORTA_GET(x) (((x) & 0x00000100ul) >> 8)
#define PU_GPIO_GPIO_CONFIG_REG1_HW_PORTA_SET(x) (((x) << 8) & 0x00000100ul)
#define PU_GPIO_GPIO_CONFIG_REG1_HW_PORTA_MODIFY(r, x) \
   ((((x) << 8) & 0x00000100ul) | ((r) & 0xfffffefful))
/* Field member: pu_gpio::GPIO_CONFIG_REG1.PORTD_SINGLE_CTL                */
/* Source filename: pu_gpio.csr, line: 578                                 */
#define PU_GPIO_GPIO_CONFIG_REG1_PORTD_SINGLE_CTL_MSB 7u
#define PU_GPIO_GPIO_CONFIG_REG1_PORTD_SINGLE_CTL_LSB 7u
#define PU_GPIO_GPIO_CONFIG_REG1_PORTD_SINGLE_CTL_WIDTH 1u
#define PU_GPIO_GPIO_CONFIG_REG1_PORTD_SINGLE_CTL_READ_ACCESS 1u
#define PU_GPIO_GPIO_CONFIG_REG1_PORTD_SINGLE_CTL_WRITE_ACCESS 0u
#define PU_GPIO_GPIO_CONFIG_REG1_PORTD_SINGLE_CTL_RESET 0x1u
#define PU_GPIO_GPIO_CONFIG_REG1_PORTD_SINGLE_CTL_FIELD_MASK 0x00000080ul
#define PU_GPIO_GPIO_CONFIG_REG1_PORTD_SINGLE_CTL_GET(x) \
   (((x) & 0x00000080ul) >> 7)
#define PU_GPIO_GPIO_CONFIG_REG1_PORTD_SINGLE_CTL_SET(x) \
   (((x) << 7) & 0x00000080ul)
#define PU_GPIO_GPIO_CONFIG_REG1_PORTD_SINGLE_CTL_MODIFY(r, x) \
   ((((x) << 7) & 0x00000080ul) | ((r) & 0xffffff7ful))
/* Field member: pu_gpio::GPIO_CONFIG_REG1.PORTC_SINGLE_CTL                */
/* Source filename: pu_gpio.csr, line: 559                                 */
#define PU_GPIO_GPIO_CONFIG_REG1_PORTC_SINGLE_CTL_MSB 6u
#define PU_GPIO_GPIO_CONFIG_REG1_PORTC_SINGLE_CTL_LSB 6u
#define PU_GPIO_GPIO_CONFIG_REG1_PORTC_SINGLE_CTL_WIDTH 1u
#define PU_GPIO_GPIO_CONFIG_REG1_PORTC_SINGLE_CTL_READ_ACCESS 1u
#define PU_GPIO_GPIO_CONFIG_REG1_PORTC_SINGLE_CTL_WRITE_ACCESS 0u
#define PU_GPIO_GPIO_CONFIG_REG1_PORTC_SINGLE_CTL_RESET 0x1u
#define PU_GPIO_GPIO_CONFIG_REG1_PORTC_SINGLE_CTL_FIELD_MASK 0x00000040ul
#define PU_GPIO_GPIO_CONFIG_REG1_PORTC_SINGLE_CTL_GET(x) \
   (((x) & 0x00000040ul) >> 6)
#define PU_GPIO_GPIO_CONFIG_REG1_PORTC_SINGLE_CTL_SET(x) \
   (((x) << 6) & 0x00000040ul)
#define PU_GPIO_GPIO_CONFIG_REG1_PORTC_SINGLE_CTL_MODIFY(r, x) \
   ((((x) << 6) & 0x00000040ul) | ((r) & 0xffffffbful))
/* Field member: pu_gpio::GPIO_CONFIG_REG1.PORTB_SINGLE_CTL                */
/* Source filename: pu_gpio.csr, line: 540                                 */
#define PU_GPIO_GPIO_CONFIG_REG1_PORTB_SINGLE_CTL_MSB 5u
#define PU_GPIO_GPIO_CONFIG_REG1_PORTB_SINGLE_CTL_LSB 5u
#define PU_GPIO_GPIO_CONFIG_REG1_PORTB_SINGLE_CTL_WIDTH 1u
#define PU_GPIO_GPIO_CONFIG_REG1_PORTB_SINGLE_CTL_READ_ACCESS 1u
#define PU_GPIO_GPIO_CONFIG_REG1_PORTB_SINGLE_CTL_WRITE_ACCESS 0u
#define PU_GPIO_GPIO_CONFIG_REG1_PORTB_SINGLE_CTL_RESET 0x1u
#define PU_GPIO_GPIO_CONFIG_REG1_PORTB_SINGLE_CTL_FIELD_MASK 0x00000020ul
#define PU_GPIO_GPIO_CONFIG_REG1_PORTB_SINGLE_CTL_GET(x) \
   (((x) & 0x00000020ul) >> 5)
#define PU_GPIO_GPIO_CONFIG_REG1_PORTB_SINGLE_CTL_SET(x) \
   (((x) << 5) & 0x00000020ul)
#define PU_GPIO_GPIO_CONFIG_REG1_PORTB_SINGLE_CTL_MODIFY(r, x) \
   ((((x) << 5) & 0x00000020ul) | ((r) & 0xffffffdful))
/* Field member: pu_gpio::GPIO_CONFIG_REG1.PORTA_SINGLE_CTL                */
/* Source filename: pu_gpio.csr, line: 521                                 */
#define PU_GPIO_GPIO_CONFIG_REG1_PORTA_SINGLE_CTL_MSB 4u
#define PU_GPIO_GPIO_CONFIG_REG1_PORTA_SINGLE_CTL_LSB 4u
#define PU_GPIO_GPIO_CONFIG_REG1_PORTA_SINGLE_CTL_WIDTH 1u
#define PU_GPIO_GPIO_CONFIG_REG1_PORTA_SINGLE_CTL_READ_ACCESS 1u
#define PU_GPIO_GPIO_CONFIG_REG1_PORTA_SINGLE_CTL_WRITE_ACCESS 0u
#define PU_GPIO_GPIO_CONFIG_REG1_PORTA_SINGLE_CTL_RESET 0x1u
#define PU_GPIO_GPIO_CONFIG_REG1_PORTA_SINGLE_CTL_FIELD_MASK 0x00000010ul
#define PU_GPIO_GPIO_CONFIG_REG1_PORTA_SINGLE_CTL_GET(x) \
   (((x) & 0x00000010ul) >> 4)
#define PU_GPIO_GPIO_CONFIG_REG1_PORTA_SINGLE_CTL_SET(x) \
   (((x) << 4) & 0x00000010ul)
#define PU_GPIO_GPIO_CONFIG_REG1_PORTA_SINGLE_CTL_MODIFY(r, x) \
   ((((x) << 4) & 0x00000010ul) | ((r) & 0xffffffeful))
/* Field member: pu_gpio::GPIO_CONFIG_REG1.NUM_PORTS                       */
/* Source filename: pu_gpio.csr, line: 494                                 */
#define PU_GPIO_GPIO_CONFIG_REG1_NUM_PORTS_MSB 3u
#define PU_GPIO_GPIO_CONFIG_REG1_NUM_PORTS_LSB 2u
#define PU_GPIO_GPIO_CONFIG_REG1_NUM_PORTS_WIDTH 2u
#define PU_GPIO_GPIO_CONFIG_REG1_NUM_PORTS_READ_ACCESS 1u
#define PU_GPIO_GPIO_CONFIG_REG1_NUM_PORTS_WRITE_ACCESS 0u
#define PU_GPIO_GPIO_CONFIG_REG1_NUM_PORTS_RESET 0x0u
#define PU_GPIO_GPIO_CONFIG_REG1_NUM_PORTS_FIELD_MASK 0x0000000cul
#define PU_GPIO_GPIO_CONFIG_REG1_NUM_PORTS_GET(x) (((x) & 0x0000000cul) >> 2)
#define PU_GPIO_GPIO_CONFIG_REG1_NUM_PORTS_SET(x) \
   (((x) << 2) & 0x0000000cul)
#define PU_GPIO_GPIO_CONFIG_REG1_NUM_PORTS_MODIFY(r, x) \
   ((((x) << 2) & 0x0000000cul) | ((r) & 0xfffffff3ul))
/* Field member: pu_gpio::GPIO_CONFIG_REG1.APB_DATA_WIDTH                  */
/* Source filename: pu_gpio.csr, line: 469                                 */
#define PU_GPIO_GPIO_CONFIG_REG1_APB_DATA_WIDTH_MSB 1u
#define PU_GPIO_GPIO_CONFIG_REG1_APB_DATA_WIDTH_LSB 0u
#define PU_GPIO_GPIO_CONFIG_REG1_APB_DATA_WIDTH_WIDTH 2u
#define PU_GPIO_GPIO_CONFIG_REG1_APB_DATA_WIDTH_READ_ACCESS 1u
#define PU_GPIO_GPIO_CONFIG_REG1_APB_DATA_WIDTH_WRITE_ACCESS 0u
#define PU_GPIO_GPIO_CONFIG_REG1_APB_DATA_WIDTH_RESET 0x2u
#define PU_GPIO_GPIO_CONFIG_REG1_APB_DATA_WIDTH_FIELD_MASK 0x00000003ul
#define PU_GPIO_GPIO_CONFIG_REG1_APB_DATA_WIDTH_GET(x) ((x) & 0x00000003ul)
#define PU_GPIO_GPIO_CONFIG_REG1_APB_DATA_WIDTH_SET(x) ((x) & 0x00000003ul)
#define PU_GPIO_GPIO_CONFIG_REG1_APB_DATA_WIDTH_MODIFY(r, x) \
   (((x) & 0x00000003ul) | ((r) & 0xfffffffcul))

/* ####################################################################### */
/*        TYPE DEFINITIONS                                                 */
/* ####################################################################### */

/* Typedef for Addressmap: pu_gpio                                         */
/* Source filename: pu_gpio.csr, line: 793                                 */
typedef struct {
   volatile uint32_t GPIO_SWPORTA_DR; /**< Offset 0x0 (R/W) */
   volatile uint32_t GPIO_SWPORTA_DDR; /**< Offset 0x4 (R/W) */
   uint8_t _pad0[0x28];
   volatile uint32_t GPIO_INTEN; /**< Offset 0x30 (R/W) */
   volatile uint32_t GPIO_INTMASK; /**< Offset 0x34 (R/W) */
   volatile uint32_t GPIO_INTTYPE_LEVEL; /**< Offset 0x38 (R/W) */
   volatile uint32_t GPIO_INT_POLARITY; /**< Offset 0x3c (R/W) */
   uint32_t GPIO_INTSTATUS; /**< Offset 0x40 (R) */
   uint32_t GPIO_RAW_INTSTATUS; /**< Offset 0x44 (R) */
   volatile uint32_t GPIO_DEBOUNCE; /**< Offset 0x48 (R/W) */
   volatile uint32_t GPIO_PORTA_EOI; /**< Offset 0x4c (W) */
   uint32_t GPIO_EXT_PORTA; /**< Offset 0x50 (R) */
   uint8_t _pad1[0xc];
   volatile uint32_t GPIO_LS_SYNC; /**< Offset 0x60 (R/W) */
   uint32_t GPIO_ID_CODE; /**< Offset 0x64 (R) */
   uint8_t _pad2[0x4];
   uint32_t GPIO_VER_ID_CODE; /**< Offset 0x6c (R) */
   uint32_t GPIO_CONFIG_REG2; /**< Offset 0x70 (R) */
   uint32_t GPIO_CONFIG_REG1; /**< Offset 0x74 (R) */
} Pu_gpio, *PTR_Pu_gpio;

#endif
