/*------------------------------------------------------------------------- 
* Copyright (c) 2025 Ainekko, Co.
* SPDX-License-Identifier: Apache-2.0
*------------------------------------------------------------------------- 
*/

/**
* @file pu_timers_regTest.h.py 
* @version $Release$ 
* @date $Date$
* @author 
*
* @brief 
*
* Setup SoC to enable TC run 
*/ 
/** 
 *  @Component      HAL
 *
 *  @Filename       pu_timers_regTest.h
 *
 *  @Description    IPs register table 
 *
 *//*======================================================================== */

#include "pu_timers.h"


REGTEST_t pu_timersRegs[] =

{

/* regAddress                                        regSize                       resetValue                                        bitMask                                           regName                            */   

{  PU_DW_APB_TIMERS_TIMER1LOADCOUNT_OFFSET,          REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMER1LOADCOUNT_RESET_VALUE,     PU_DW_APB_TIMERS_TIMER1LOADCOUNT_WRITE_MASK,      "TIMER1LOADCOUNT",                 },   

//{  PU_DW_APB_TIMERS_TIMER1CURRENTVAL_OFFSET,         REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMER1CURRENTVAL_RESET_VALUE,    PU_DW_APB_TIMERS_TIMER1CURRENTVAL_WRITE_MASK,     "TIMER1CURRENTVAL",                },   

{  PU_DW_APB_TIMERS_TIMER1CONTROLREG_OFFSET,         REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMER1CONTROLREG_RESET_VALUE,    PU_DW_APB_TIMERS_TIMER1CONTROLREG_WRITE_MASK,     "TIMER1CONTROLREG",                },   

{  PU_DW_APB_TIMERS_TIMER1EOI_OFFSET,                REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMER1EOI_RESET_VALUE,           PU_DW_APB_TIMERS_TIMER1EOI_WRITE_MASK,            "TIMER1EOI",                       },   

{  PU_DW_APB_TIMERS_TIMER1INTSTAT_OFFSET,            REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMER1INTSTAT_RESET_VALUE,       PU_DW_APB_TIMERS_TIMER1INTSTAT_WRITE_MASK,        "TIMER1INTSTAT",                   },   

{  PU_DW_APB_TIMERS_TIMER2LOADCOUNT_OFFSET,          REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMER2LOADCOUNT_RESET_VALUE,     PU_DW_APB_TIMERS_TIMER2LOADCOUNT_WRITE_MASK,      "TIMER2LOADCOUNT",                 },   

//{  PU_DW_APB_TIMERS_TIMER2CURRENTVAL_OFFSET,         REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMER2CURRENTVAL_RESET_VALUE,    PU_DW_APB_TIMERS_TIMER2CURRENTVAL_WRITE_MASK,     "TIMER2CURRENTVAL",                },   

{  PU_DW_APB_TIMERS_TIMER2CONTROLREG_OFFSET,         REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMER2CONTROLREG_RESET_VALUE,    PU_DW_APB_TIMERS_TIMER2CONTROLREG_WRITE_MASK,     "TIMER2CONTROLREG",                },   

{  PU_DW_APB_TIMERS_TIMER2EOI_OFFSET,                REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMER2EOI_RESET_VALUE,           PU_DW_APB_TIMERS_TIMER2EOI_WRITE_MASK,            "TIMER2EOI",                       },   

{  PU_DW_APB_TIMERS_TIMER2INTSTAT_OFFSET,            REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMER2INTSTAT_RESET_VALUE,       PU_DW_APB_TIMERS_TIMER2INTSTAT_WRITE_MASK,        "TIMER2INTSTAT",                   },   

{  PU_DW_APB_TIMERS_TIMER3LOADCOUNT_OFFSET,          REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMER3LOADCOUNT_RESET_VALUE,     PU_DW_APB_TIMERS_TIMER3LOADCOUNT_WRITE_MASK,      "TIMER3LOADCOUNT",                 },   

//{  PU_DW_APB_TIMERS_TIMER3CURRENTVAL_OFFSET,         REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMER3CURRENTVAL_RESET_VALUE,    PU_DW_APB_TIMERS_TIMER3CURRENTVAL_WRITE_MASK,     "TIMER3CURRENTVAL",                },   

{  PU_DW_APB_TIMERS_TIMER3CONTROLREG_OFFSET,         REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMER3CONTROLREG_RESET_VALUE,    PU_DW_APB_TIMERS_TIMER3CONTROLREG_WRITE_MASK,     "TIMER3CONTROLREG",                },   

{  PU_DW_APB_TIMERS_TIMER3EOI_OFFSET,                REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMER3EOI_RESET_VALUE,           PU_DW_APB_TIMERS_TIMER3EOI_WRITE_MASK,            "TIMER3EOI",                       },   

{  PU_DW_APB_TIMERS_TIMER3INTSTAT_OFFSET,            REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMER3INTSTAT_RESET_VALUE,       PU_DW_APB_TIMERS_TIMER3INTSTAT_WRITE_MASK,        "TIMER3INTSTAT",                   },   

{  PU_DW_APB_TIMERS_TIMER4LOADCOUNT_OFFSET,          REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMER4LOADCOUNT_RESET_VALUE,     PU_DW_APB_TIMERS_TIMER4LOADCOUNT_WRITE_MASK,      "TIMER4LOADCOUNT",                 },   

//{  PU_DW_APB_TIMERS_TIMER4CURRENTVAL_OFFSET,         REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMER4CURRENTVAL_RESET_VALUE,    PU_DW_APB_TIMERS_TIMER4CURRENTVAL_WRITE_MASK,     "TIMER4CURRENTVAL",                },   

{  PU_DW_APB_TIMERS_TIMER4CONTROLREG_OFFSET,         REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMER4CONTROLREG_RESET_VALUE,    PU_DW_APB_TIMERS_TIMER4CONTROLREG_WRITE_MASK,     "TIMER4CONTROLREG",                },   

{  PU_DW_APB_TIMERS_TIMER4EOI_OFFSET,                REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMER4EOI_RESET_VALUE,           PU_DW_APB_TIMERS_TIMER4EOI_WRITE_MASK,            "TIMER4EOI",                       },   

{  PU_DW_APB_TIMERS_TIMER4INTSTAT_OFFSET,            REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMER4INTSTAT_RESET_VALUE,       PU_DW_APB_TIMERS_TIMER4INTSTAT_WRITE_MASK,        "TIMER4INTSTAT",                   },   

{  PU_DW_APB_TIMERS_TIMER5LOADCOUNT_OFFSET,          REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMER5LOADCOUNT_RESET_VALUE,     PU_DW_APB_TIMERS_TIMER5LOADCOUNT_WRITE_MASK,      "TIMER5LOADCOUNT",                 },   

//{  PU_DW_APB_TIMERS_TIMER5CURRENTVAL_OFFSET,         REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMER5CURRENTVAL_RESET_VALUE,    PU_DW_APB_TIMERS_TIMER5CURRENTVAL_WRITE_MASK,     "TIMER5CURRENTVAL",                },   

{  PU_DW_APB_TIMERS_TIMER5CONTROLREG_OFFSET,         REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMER5CONTROLREG_RESET_VALUE,    PU_DW_APB_TIMERS_TIMER5CONTROLREG_WRITE_MASK,     "TIMER5CONTROLREG",                },   

{  PU_DW_APB_TIMERS_TIMER5EOI_OFFSET,                REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMER5EOI_RESET_VALUE,           PU_DW_APB_TIMERS_TIMER5EOI_WRITE_MASK,            "TIMER5EOI",                       },   

{  PU_DW_APB_TIMERS_TIMER5INTSTAT_OFFSET,            REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMER5INTSTAT_RESET_VALUE,       PU_DW_APB_TIMERS_TIMER5INTSTAT_WRITE_MASK,        "TIMER5INTSTAT",                   },   

{  PU_DW_APB_TIMERS_TIMER6LOADCOUNT_OFFSET,          REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMER6LOADCOUNT_RESET_VALUE,     PU_DW_APB_TIMERS_TIMER6LOADCOUNT_WRITE_MASK,      "TIMER6LOADCOUNT",                 },   

//{  PU_DW_APB_TIMERS_TIMER6CURRENTVAL_OFFSET,         REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMER6CURRENTVAL_RESET_VALUE,    PU_DW_APB_TIMERS_TIMER6CURRENTVAL_WRITE_MASK,     "TIMER6CURRENTVAL",                },   

{  PU_DW_APB_TIMERS_TIMER6CONTROLREG_OFFSET,         REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMER6CONTROLREG_RESET_VALUE,    PU_DW_APB_TIMERS_TIMER6CONTROLREG_WRITE_MASK,     "TIMER6CONTROLREG",                },   

{  PU_DW_APB_TIMERS_TIMER6EOI_OFFSET,                REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMER6EOI_RESET_VALUE,           PU_DW_APB_TIMERS_TIMER6EOI_WRITE_MASK,            "TIMER6EOI",                       },   

{  PU_DW_APB_TIMERS_TIMER6INTSTAT_OFFSET,            REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMER6INTSTAT_RESET_VALUE,       PU_DW_APB_TIMERS_TIMER6INTSTAT_WRITE_MASK,        "TIMER6INTSTAT",                   },   

{  PU_DW_APB_TIMERS_TIMER7LOADCOUNT_OFFSET,          REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMER7LOADCOUNT_RESET_VALUE,     PU_DW_APB_TIMERS_TIMER7LOADCOUNT_WRITE_MASK,      "TIMER7LOADCOUNT",                 },   

//{  PU_DW_APB_TIMERS_TIMER7CURRENTVAL_OFFSET,         REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMER7CURRENTVAL_RESET_VALUE,    PU_DW_APB_TIMERS_TIMER7CURRENTVAL_WRITE_MASK,     "TIMER7CURRENTVAL",                },   

{  PU_DW_APB_TIMERS_TIMER7CONTROLREG_OFFSET,         REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMER7CONTROLREG_RESET_VALUE,    PU_DW_APB_TIMERS_TIMER7CONTROLREG_WRITE_MASK,     "TIMER7CONTROLREG",                },   

{  PU_DW_APB_TIMERS_TIMER7EOI_OFFSET,                REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMER7EOI_RESET_VALUE,           PU_DW_APB_TIMERS_TIMER7EOI_WRITE_MASK,            "TIMER7EOI",                       },   

{  PU_DW_APB_TIMERS_TIMER7INTSTAT_OFFSET,            REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMER7INTSTAT_RESET_VALUE,       PU_DW_APB_TIMERS_TIMER7INTSTAT_WRITE_MASK,        "TIMER7INTSTAT",                   },   

{  PU_DW_APB_TIMERS_TIMER8LOADCOUNT_OFFSET,          REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMER8LOADCOUNT_RESET_VALUE,     PU_DW_APB_TIMERS_TIMER8LOADCOUNT_WRITE_MASK,      "TIMER8LOADCOUNT",                 },   

//{  PU_DW_APB_TIMERS_TIMER8CURRENTVAL_OFFSET,         REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMER8CURRENTVAL_RESET_VALUE,    PU_DW_APB_TIMERS_TIMER8CURRENTVAL_WRITE_MASK,     "TIMER8CURRENTVAL",                },   

{  PU_DW_APB_TIMERS_TIMER8CONTROLREG_OFFSET,         REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMER8CONTROLREG_RESET_VALUE,    PU_DW_APB_TIMERS_TIMER8CONTROLREG_WRITE_MASK,     "TIMER8CONTROLREG",                },   

{  PU_DW_APB_TIMERS_TIMER8EOI_OFFSET,                REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMER8EOI_RESET_VALUE,           PU_DW_APB_TIMERS_TIMER8EOI_WRITE_MASK,            "TIMER8EOI",                       },   

{  PU_DW_APB_TIMERS_TIMER8INTSTAT_OFFSET,            REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMER8INTSTAT_RESET_VALUE,       PU_DW_APB_TIMERS_TIMER8INTSTAT_WRITE_MASK,        "TIMER8INTSTAT",                   },   

{  PU_DW_APB_TIMERS_TIMERSINTSTATUS_OFFSET,          REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMERSINTSTATUS_RESET_VALUE,     PU_DW_APB_TIMERS_TIMERSINTSTATUS_WRITE_MASK,      "TimersIntStatus",                 },   

{  PU_DW_APB_TIMERS_TIMERSEOI_OFFSET,                REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMERSEOI_RESET_VALUE,           PU_DW_APB_TIMERS_TIMERSEOI_WRITE_MASK,            "TimersEOI",                       },   

{  PU_DW_APB_TIMERS_TIMERSRAWINTSTATUS_OFFSET,       REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMERSRAWINTSTATUS_RESET_VALUE,  PU_DW_APB_TIMERS_TIMERSRAWINTSTATUS_WRITE_MASK,   "TimersRawIntStatus",              },   

{  PU_DW_APB_TIMERS_TIMERS_COMP_VERSION_OFFSET,      REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMERS_COMP_VERSION_RESET_VALUE, PU_DW_APB_TIMERS_TIMERS_COMP_VERSION_WRITE_MASK,  "TIMERS_COMP_VERSION",             },   

{  PU_DW_APB_TIMERS_TIMER1LOADCOUNT2_OFFSET,         REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMER1LOADCOUNT2_RESET_VALUE,    PU_DW_APB_TIMERS_TIMER1LOADCOUNT2_WRITE_MASK,     "TIMER1LOADCOUNT2",                },   

{  PU_DW_APB_TIMERS_TIMER2LOADCOUNT2_OFFSET,         REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMER2LOADCOUNT2_RESET_VALUE,    PU_DW_APB_TIMERS_TIMER2LOADCOUNT2_WRITE_MASK,     "TIMER2LOADCOUNT2",                },   

{  PU_DW_APB_TIMERS_TIMER3LOADCOUNT2_OFFSET,         REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMER3LOADCOUNT2_RESET_VALUE,    PU_DW_APB_TIMERS_TIMER3LOADCOUNT2_WRITE_MASK,     "TIMER3LOADCOUNT2",                },   

{  PU_DW_APB_TIMERS_TIMER4LOADCOUNT2_OFFSET,         REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMER4LOADCOUNT2_RESET_VALUE,    PU_DW_APB_TIMERS_TIMER4LOADCOUNT2_WRITE_MASK,     "TIMER4LOADCOUNT2",                },   

{  PU_DW_APB_TIMERS_TIMER5LOADCOUNT2_OFFSET,         REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMER5LOADCOUNT2_RESET_VALUE,    PU_DW_APB_TIMERS_TIMER5LOADCOUNT2_WRITE_MASK,     "TIMER5LOADCOUNT2",                },   

{  PU_DW_APB_TIMERS_TIMER6LOADCOUNT2_OFFSET,         REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMER6LOADCOUNT2_RESET_VALUE,    PU_DW_APB_TIMERS_TIMER6LOADCOUNT2_WRITE_MASK,     "TIMER6LOADCOUNT2",                },   

{  PU_DW_APB_TIMERS_TIMER7LOADCOUNT2_OFFSET,         REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMER7LOADCOUNT2_RESET_VALUE,    PU_DW_APB_TIMERS_TIMER7LOADCOUNT2_WRITE_MASK,     "TIMER7LOADCOUNT2",                },   

{  PU_DW_APB_TIMERS_TIMER8LOADCOUNT2_OFFSET,         REGTEST_SIZE_32_BIT,          PU_DW_APB_TIMERS_TIMER8LOADCOUNT2_RESET_VALUE,    PU_DW_APB_TIMERS_TIMER8LOADCOUNT2_WRITE_MASK,     "TIMER8LOADCOUNT2",                },   

   /* End List Delimiter */

{  REGTEST_END_OF_LIST,                              0,                            0,                                                0,                                                0,                                 }    

};  

