/*                                                                         */
/*                                                                         */
/* Generated by Semifore, Inc. csrCompile                                  */
/*    C Header output                                                      */

#ifndef _PU_WDT_H_
#define _PU_WDT_H_


/* ####################################################################### */
/*        ENUMERATION MACROS                                               */
/* ####################################################################### */

/* Enumeration: pu_DW_apb_wdt::WDT_COMP_PARAM_1::APB_DATA_WIDTH::APB_DATA_WIDTH */
/* Source filename: pu_wdt.csr, line: 724                                  */
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_APB_DATA_WIDTH_APB_DATA_WIDTH_APB_16BITS 0x1u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_APB_DATA_WIDTH_APB_DATA_WIDTH_APB_32BITS 0x2u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_APB_DATA_WIDTH_APB_DATA_WIDTH_APB_8BITS 0x0u

/* Enumeration: pu_DW_apb_wdt::WDT_COMP_PARAM_1::WDT_ALWAYS_EN::WDT_ALWAYS_EN */
/* Source filename: pu_wdt.csr, line: 566                                  */
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_ALWAYS_EN_WDT_ALWAYS_EN_DISABLED 0x0u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_ALWAYS_EN_WDT_ALWAYS_EN_ENABLED 0x1u

/* Enumeration: pu_DW_apb_wdt::WDT_COMP_PARAM_1::WDT_DFLT_RMOD::WDT_DFLT_RMOD */
/* Source filename: pu_wdt.csr, line: 589                                  */
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DFLT_RMOD_WDT_DFLT_RMOD_DISABLED 0x0u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DFLT_RMOD_WDT_DFLT_RMOD_ENABLED 0x1u

/* Enumeration: pu_DW_apb_wdt::WDT_COMP_PARAM_1::WDT_DUAL_TOP::WDT_DUAL_TOP */
/* Source filename: pu_wdt.csr, line: 608                                  */
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DUAL_TOP_WDT_DUAL_TOP_DISABLED 0x0u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DUAL_TOP_WDT_DUAL_TOP_ENABLED 0x1u

/* Enumeration: pu_DW_apb_wdt::WDT_COMP_PARAM_1::WDT_HC_RMOD::WDT_HC_RMOD  */
/* Source filename: pu_wdt.csr, line: 626                                  */
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_HC_RMOD_WDT_HC_RMOD_HARDCODED 0x1u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_HC_RMOD_WDT_HC_RMOD_PROGRAMMABLE 0x0u

/* Enumeration: pu_DW_apb_wdt::WDT_COMP_PARAM_1::WDT_HC_RPL::WDT_HC_RPL    */
/* Source filename: pu_wdt.csr, line: 644                                  */
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_HC_RPL_WDT_HC_RPL_HARDCODED 0x1u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_HC_RPL_WDT_HC_RPL_PROGRAMMABLE 0x0u

/* Enumeration: pu_DW_apb_wdt::WDT_COMP_PARAM_1::WDT_HC_TOP::WDT_HC_TOP    */
/* Source filename: pu_wdt.csr, line: 663                                  */
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_HC_TOP_WDT_HC_TOP_HARDCODED 0x1u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_HC_TOP_WDT_HC_TOP_PROGRAMMABLE 0x0u

/* Enumeration: pu_DW_apb_wdt::WDT_COMP_PARAM_1::WDT_PAUSE::WDT_PAUSE      */
/* Source filename: pu_wdt.csr, line: 705                                  */
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_PAUSE_WDT_PAUSE_DISABLED 0x0u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_PAUSE_WDT_PAUSE_ENABLED 0x1u

/* Enumeration: pu_DW_apb_wdt::WDT_COMP_PARAM_1::WDT_USE_FIX_TOP::WDT_USE_FIX_TOP */
/* Source filename: pu_wdt.csr, line: 685                                  */
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_USE_FIX_TOP_WDT_USE_FIX_TOP_PREDEFINED 0x1u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_USE_FIX_TOP_WDT_USE_FIX_TOP_USERDEFINED 0x0u

/* Enumeration: pu_DW_apb_wdt::WDT_CR::RMOD::RMOD                          */
/* Source filename: pu_wdt.csr, line: 61                                   */
#define PU_DW_APB_WDT_WDT_CR_RMOD_RMOD_INTERRUPT 0x1u
#define PU_DW_APB_WDT_WDT_CR_RMOD_RMOD_RESET 0x0u

/* Enumeration: pu_DW_apb_wdt::WDT_CR::RPL::RPL                            */
/* Source filename: pu_wdt.csr, line: 92                                   */
#define PU_DW_APB_WDT_WDT_CR_RPL_RPL_PCLK_CYCLES_128 0x6u
#define PU_DW_APB_WDT_WDT_CR_RPL_RPL_PCLK_CYCLES_16 0x3u
#define PU_DW_APB_WDT_WDT_CR_RPL_RPL_PCLK_CYCLES_2 0x0u
#define PU_DW_APB_WDT_WDT_CR_RPL_RPL_PCLK_CYCLES_256 0x7u
#define PU_DW_APB_WDT_WDT_CR_RPL_RPL_PCLK_CYCLES_32 0x4u
#define PU_DW_APB_WDT_WDT_CR_RPL_RPL_PCLK_CYCLES_4 0x1u
#define PU_DW_APB_WDT_WDT_CR_RPL_RPL_PCLK_CYCLES_64 0x5u
#define PU_DW_APB_WDT_WDT_CR_RPL_RPL_PCLK_CYCLES_8 0x2u

/* Enumeration: pu_DW_apb_wdt::WDT_CR::WDT_EN::WDT_EN                      */
/* Source filename: pu_wdt.csr, line: 40                                   */
#define PU_DW_APB_WDT_WDT_CR_WDT_EN_WDT_EN_DISABLED 0x0u
#define PU_DW_APB_WDT_WDT_CR_WDT_EN_WDT_EN_ENABLED 0x1u

/* Enumeration: pu_DW_apb_wdt::WDT_CRR::WDT_CRR::WDT_CRR                   */
/* Source filename: pu_wdt.csr, line: 400                                  */
#define PU_DW_APB_WDT_WDT_CRR_WDT_CRR_WDT_CRR_RESTART 0x76u

/* Enumeration: pu_DW_apb_wdt::WDT_STAT::WDT_STAT::WDT_STAT                */
/* Source filename: pu_wdt.csr, line: 430                                  */
#define PU_DW_APB_WDT_WDT_STAT_WDT_STAT_WDT_STAT_ACTIVE 0x1u
#define PU_DW_APB_WDT_WDT_STAT_WDT_STAT_WDT_STAT_INACTIVE 0x0u

/* Enumeration: pu_DW_apb_wdt::WDT_TORR::TOP::TOP                          */
/* Source filename: pu_wdt.csr, line: 182                                  */
#define PU_DW_APB_WDT_WDT_TORR_TOP_TOP_USER0_OR_64K 0x0u
#define PU_DW_APB_WDT_WDT_TORR_TOP_TOP_USER10_OR_64M 0xau
#define PU_DW_APB_WDT_WDT_TORR_TOP_TOP_USER11_OR_128M 0xbu
#define PU_DW_APB_WDT_WDT_TORR_TOP_TOP_USER12_OR_256M 0xcu
#define PU_DW_APB_WDT_WDT_TORR_TOP_TOP_USER13_OR_512M 0xdu
#define PU_DW_APB_WDT_WDT_TORR_TOP_TOP_USER14_OR_1G 0xeu
#define PU_DW_APB_WDT_WDT_TORR_TOP_TOP_USER15_OR_2G 0xfu
#define PU_DW_APB_WDT_WDT_TORR_TOP_TOP_USER1_OR_128K 0x1u
#define PU_DW_APB_WDT_WDT_TORR_TOP_TOP_USER2_OR_256K 0x2u
#define PU_DW_APB_WDT_WDT_TORR_TOP_TOP_USER3_OR_512K 0x3u
#define PU_DW_APB_WDT_WDT_TORR_TOP_TOP_USER4_OR_1M 0x4u
#define PU_DW_APB_WDT_WDT_TORR_TOP_TOP_USER5_OR_2M 0x5u
#define PU_DW_APB_WDT_WDT_TORR_TOP_TOP_USER6_OR_4M 0x6u
#define PU_DW_APB_WDT_WDT_TORR_TOP_TOP_USER7_OR_8M 0x7u
#define PU_DW_APB_WDT_WDT_TORR_TOP_TOP_USER8_OR_16M 0x8u
#define PU_DW_APB_WDT_WDT_TORR_TOP_TOP_USER9_OR_32M 0x9u

/* Enumeration: pu_DW_apb_wdt::WDT_TORR::TOP_INIT::TOP_INIT                */
/* Source filename: pu_wdt.csr, line: 289                                  */
#define PU_DW_APB_WDT_WDT_TORR_TOP_INIT_TOP_INIT_USER0_OR_64K 0x0u
#define PU_DW_APB_WDT_WDT_TORR_TOP_INIT_TOP_INIT_USER10_OR_64M 0xau
#define PU_DW_APB_WDT_WDT_TORR_TOP_INIT_TOP_INIT_USER11_OR_128M 0xbu
#define PU_DW_APB_WDT_WDT_TORR_TOP_INIT_TOP_INIT_USER12_OR_256M 0xcu
#define PU_DW_APB_WDT_WDT_TORR_TOP_INIT_TOP_INIT_USER13_OR_512M 0xdu
#define PU_DW_APB_WDT_WDT_TORR_TOP_INIT_TOP_INIT_USER14_OR_1G 0xeu
#define PU_DW_APB_WDT_WDT_TORR_TOP_INIT_TOP_INIT_USER15_OR_2G 0xfu
#define PU_DW_APB_WDT_WDT_TORR_TOP_INIT_TOP_INIT_USER1_OR_128K 0x1u
#define PU_DW_APB_WDT_WDT_TORR_TOP_INIT_TOP_INIT_USER2_OR_256K 0x2u
#define PU_DW_APB_WDT_WDT_TORR_TOP_INIT_TOP_INIT_USER3_OR_512K 0x3u
#define PU_DW_APB_WDT_WDT_TORR_TOP_INIT_TOP_INIT_USER4_OR_1M 0x4u
#define PU_DW_APB_WDT_WDT_TORR_TOP_INIT_TOP_INIT_USER5_OR_2M 0x5u
#define PU_DW_APB_WDT_WDT_TORR_TOP_INIT_TOP_INIT_USER6_OR_4M 0x6u
#define PU_DW_APB_WDT_WDT_TORR_TOP_INIT_TOP_INIT_USER7_OR_8M 0x7u
#define PU_DW_APB_WDT_WDT_TORR_TOP_INIT_TOP_INIT_USER8_OR_16M 0x8u
#define PU_DW_APB_WDT_WDT_TORR_TOP_INIT_TOP_INIT_USER9_OR_32M 0x9u


/* ####################################################################### */
/*        ADDRESS MACROS                                                   */
/* ####################################################################### */

/* Address Space for Addressmap: pu_DW_apb_wdt                             */
/* Source filename: pu_wdt.csr, line: 824                                  */
/* Register: pu_DW_apb_wdt.WDT_CR                                          */
#define PU_DW_APB_WDT_WDT_CR_ADDRESS 0x0u
#define PU_DW_APB_WDT_WDT_CR_BYTE_ADDRESS 0x0u
/* Register: pu_DW_apb_wdt.WDT_TORR                                        */
#define PU_DW_APB_WDT_WDT_TORR_ADDRESS 0x4u
#define PU_DW_APB_WDT_WDT_TORR_BYTE_ADDRESS 0x4u
/* Register: pu_DW_apb_wdt.WDT_CCVR                                        */
#define PU_DW_APB_WDT_WDT_CCVR_ADDRESS 0x8u
#define PU_DW_APB_WDT_WDT_CCVR_BYTE_ADDRESS 0x8u
/* Register: pu_DW_apb_wdt.WDT_CRR                                         */
#define PU_DW_APB_WDT_WDT_CRR_ADDRESS 0xcu
#define PU_DW_APB_WDT_WDT_CRR_BYTE_ADDRESS 0xcu
/* Register: pu_DW_apb_wdt.WDT_STAT                                        */
#define PU_DW_APB_WDT_WDT_STAT_ADDRESS 0x10u
#define PU_DW_APB_WDT_WDT_STAT_BYTE_ADDRESS 0x10u
/* Register: pu_DW_apb_wdt.WDT_EOI                                         */
#define PU_DW_APB_WDT_WDT_EOI_ADDRESS 0x14u
#define PU_DW_APB_WDT_WDT_EOI_BYTE_ADDRESS 0x14u
/* Register: pu_DW_apb_wdt.WDT_COMP_PARAM_5                                */
#define PU_DW_APB_WDT_WDT_COMP_PARAM_5_ADDRESS 0xe4u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_5_BYTE_ADDRESS 0xe4u
/* Register: pu_DW_apb_wdt.WDT_COMP_PARAM_4                                */
#define PU_DW_APB_WDT_WDT_COMP_PARAM_4_ADDRESS 0xe8u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_4_BYTE_ADDRESS 0xe8u
/* Register: pu_DW_apb_wdt.WDT_COMP_PARAM_3                                */
#define PU_DW_APB_WDT_WDT_COMP_PARAM_3_ADDRESS 0xecu
#define PU_DW_APB_WDT_WDT_COMP_PARAM_3_BYTE_ADDRESS 0xecu
/* Register: pu_DW_apb_wdt.WDT_COMP_PARAM_2                                */
#define PU_DW_APB_WDT_WDT_COMP_PARAM_2_ADDRESS 0xf0u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_2_BYTE_ADDRESS 0xf0u
/* Register: pu_DW_apb_wdt.WDT_COMP_PARAM_1                                */
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_ADDRESS 0xf4u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_BYTE_ADDRESS 0xf4u
/* Register: pu_DW_apb_wdt.WDT_COMP_VERSION                                */
#define PU_DW_APB_WDT_WDT_COMP_VERSION_ADDRESS 0xf8u
#define PU_DW_APB_WDT_WDT_COMP_VERSION_BYTE_ADDRESS 0xf8u
/* Register: pu_DW_apb_wdt.WDT_COMP_TYPE                                   */
#define PU_DW_APB_WDT_WDT_COMP_TYPE_ADDRESS 0xfcu
#define PU_DW_APB_WDT_WDT_COMP_TYPE_BYTE_ADDRESS 0xfcu


/* ####################################################################### */
/*        TEMPLATE MACROS                                                  */
/* ####################################################################### */

/* Addressmap type: pu_DW_apb_wdt                                          */
/* Addressmap template: pu_DW_apb_wdt                                      */
/* Source filename: pu_wdt.csr, line: 19                                   */
#define PU_DW_APB_WDT_SIZE 0x100u
#define PU_DW_APB_WDT_BYTE_SIZE 0x100u
/* Register member: pu_DW_apb_wdt.WDT_CR                                   */
/* Register type referenced: pu_DW_apb_wdt::WDT_CR                         */
/* Register template referenced: pu_DW_apb_wdt::WDT_CR                     */
#define PU_DW_APB_WDT_WDT_CR_OFFSET 0x0u
#define PU_DW_APB_WDT_WDT_CR_BYTE_OFFSET 0x0u
#define PU_DW_APB_WDT_WDT_CR_READ_ACCESS 1u
#define PU_DW_APB_WDT_WDT_CR_WRITE_ACCESS 1u
#define PU_DW_APB_WDT_WDT_CR_RESET_VALUE 0x0000000aul
#define PU_DW_APB_WDT_WDT_CR_RESET_MASK 0xfffffffful
#define PU_DW_APB_WDT_WDT_CR_READ_MASK 0xfffffffful
#define PU_DW_APB_WDT_WDT_CR_WRITE_MASK 0x0000003ful
/* Register member: pu_DW_apb_wdt.WDT_TORR                                 */
/* Register type referenced: pu_DW_apb_wdt::WDT_TORR                       */
/* Register template referenced: pu_DW_apb_wdt::WDT_TORR                   */
#define PU_DW_APB_WDT_WDT_TORR_OFFSET 0x4u
#define PU_DW_APB_WDT_WDT_TORR_BYTE_OFFSET 0x4u
#define PU_DW_APB_WDT_WDT_TORR_READ_ACCESS 1u
#define PU_DW_APB_WDT_WDT_TORR_WRITE_ACCESS 1u
#define PU_DW_APB_WDT_WDT_TORR_RESET_VALUE 0x00000000ul
#define PU_DW_APB_WDT_WDT_TORR_RESET_MASK 0xfffffffful
#define PU_DW_APB_WDT_WDT_TORR_READ_MASK 0xfffffffful
#define PU_DW_APB_WDT_WDT_TORR_WRITE_MASK 0x000000fful
/* Register member: pu_DW_apb_wdt.WDT_CCVR                                 */
/* Register type referenced: pu_DW_apb_wdt::WDT_CCVR                       */
/* Register template referenced: pu_DW_apb_wdt::WDT_CCVR                   */
#define PU_DW_APB_WDT_WDT_CCVR_OFFSET 0x8u
#define PU_DW_APB_WDT_WDT_CCVR_BYTE_OFFSET 0x8u
#define PU_DW_APB_WDT_WDT_CCVR_READ_ACCESS 1u
#define PU_DW_APB_WDT_WDT_CCVR_WRITE_ACCESS 0u
#define PU_DW_APB_WDT_WDT_CCVR_RESET_VALUE 0x0000fffful
#define PU_DW_APB_WDT_WDT_CCVR_RESET_MASK 0xfffffffful
#define PU_DW_APB_WDT_WDT_CCVR_READ_MASK 0xfffffffful
#define PU_DW_APB_WDT_WDT_CCVR_WRITE_MASK 0x00000000ul
/* Register member: pu_DW_apb_wdt.WDT_CRR                                  */
/* Register type referenced: pu_DW_apb_wdt::WDT_CRR                        */
/* Register template referenced: pu_DW_apb_wdt::WDT_CRR                    */
#define PU_DW_APB_WDT_WDT_CRR_OFFSET 0xcu
#define PU_DW_APB_WDT_WDT_CRR_BYTE_OFFSET 0xcu
#define PU_DW_APB_WDT_WDT_CRR_READ_ACCESS 0u
#define PU_DW_APB_WDT_WDT_CRR_WRITE_ACCESS 1u
#define PU_DW_APB_WDT_WDT_CRR_RESET_VALUE 0x00000000ul
#define PU_DW_APB_WDT_WDT_CRR_RESET_MASK 0xfffffffful
#define PU_DW_APB_WDT_WDT_CRR_READ_MASK 0x00000000ul
#define PU_DW_APB_WDT_WDT_CRR_WRITE_MASK 0xfffffffful
/* Register member: pu_DW_apb_wdt.WDT_STAT                                 */
/* Register type referenced: pu_DW_apb_wdt::WDT_STAT                       */
/* Register template referenced: pu_DW_apb_wdt::WDT_STAT                   */
#define PU_DW_APB_WDT_WDT_STAT_OFFSET 0x10u
#define PU_DW_APB_WDT_WDT_STAT_BYTE_OFFSET 0x10u
#define PU_DW_APB_WDT_WDT_STAT_READ_ACCESS 1u
#define PU_DW_APB_WDT_WDT_STAT_WRITE_ACCESS 0u
#define PU_DW_APB_WDT_WDT_STAT_RESET_VALUE 0x00000000ul
#define PU_DW_APB_WDT_WDT_STAT_RESET_MASK 0xfffffffful
#define PU_DW_APB_WDT_WDT_STAT_READ_MASK 0xfffffffful
#define PU_DW_APB_WDT_WDT_STAT_WRITE_MASK 0x00000000ul
/* Register member: pu_DW_apb_wdt.WDT_EOI                                  */
/* Register type referenced: pu_DW_apb_wdt::WDT_EOI                        */
/* Register template referenced: pu_DW_apb_wdt::WDT_EOI                    */
#define PU_DW_APB_WDT_WDT_EOI_OFFSET 0x14u
#define PU_DW_APB_WDT_WDT_EOI_BYTE_OFFSET 0x14u
#define PU_DW_APB_WDT_WDT_EOI_READ_ACCESS 1u
#define PU_DW_APB_WDT_WDT_EOI_WRITE_ACCESS 0u
#define PU_DW_APB_WDT_WDT_EOI_RESET_VALUE 0x00000000ul
#define PU_DW_APB_WDT_WDT_EOI_RESET_MASK 0xfffffffful
#define PU_DW_APB_WDT_WDT_EOI_READ_MASK 0xfffffffful
#define PU_DW_APB_WDT_WDT_EOI_WRITE_MASK 0x00000000ul
/* Register member: pu_DW_apb_wdt.WDT_COMP_PARAM_5                         */
/* Register type referenced: pu_DW_apb_wdt::WDT_COMP_PARAM_5               */
/* Register template referenced: pu_DW_apb_wdt::WDT_COMP_PARAM_5           */
#define PU_DW_APB_WDT_WDT_COMP_PARAM_5_OFFSET 0xe4u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_5_BYTE_OFFSET 0xe4u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_5_READ_ACCESS 1u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_5_WRITE_ACCESS 0u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_5_RESET_VALUE 0x7ffffffful
#define PU_DW_APB_WDT_WDT_COMP_PARAM_5_RESET_MASK 0xfffffffful
#define PU_DW_APB_WDT_WDT_COMP_PARAM_5_READ_MASK 0xfffffffful
#define PU_DW_APB_WDT_WDT_COMP_PARAM_5_WRITE_MASK 0x00000000ul
/* Register member: pu_DW_apb_wdt.WDT_COMP_PARAM_4                         */
/* Register type referenced: pu_DW_apb_wdt::WDT_COMP_PARAM_4               */
/* Register template referenced: pu_DW_apb_wdt::WDT_COMP_PARAM_4           */
#define PU_DW_APB_WDT_WDT_COMP_PARAM_4_OFFSET 0xe8u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_4_BYTE_OFFSET 0xe8u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_4_READ_ACCESS 1u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_4_WRITE_ACCESS 0u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_4_RESET_VALUE 0x7ffffffful
#define PU_DW_APB_WDT_WDT_COMP_PARAM_4_RESET_MASK 0xfffffffful
#define PU_DW_APB_WDT_WDT_COMP_PARAM_4_READ_MASK 0xfffffffful
#define PU_DW_APB_WDT_WDT_COMP_PARAM_4_WRITE_MASK 0x00000000ul
/* Register member: pu_DW_apb_wdt.WDT_COMP_PARAM_3                         */
/* Register type referenced: pu_DW_apb_wdt::WDT_COMP_PARAM_3               */
/* Register template referenced: pu_DW_apb_wdt::WDT_COMP_PARAM_3           */
#define PU_DW_APB_WDT_WDT_COMP_PARAM_3_OFFSET 0xecu
#define PU_DW_APB_WDT_WDT_COMP_PARAM_3_BYTE_OFFSET 0xecu
#define PU_DW_APB_WDT_WDT_COMP_PARAM_3_READ_ACCESS 1u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_3_WRITE_ACCESS 0u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_3_RESET_VALUE 0x00000000ul
#define PU_DW_APB_WDT_WDT_COMP_PARAM_3_RESET_MASK 0xfffffffful
#define PU_DW_APB_WDT_WDT_COMP_PARAM_3_READ_MASK 0xfffffffful
#define PU_DW_APB_WDT_WDT_COMP_PARAM_3_WRITE_MASK 0x00000000ul
/* Register member: pu_DW_apb_wdt.WDT_COMP_PARAM_2                         */
/* Register type referenced: pu_DW_apb_wdt::WDT_COMP_PARAM_2               */
/* Register template referenced: pu_DW_apb_wdt::WDT_COMP_PARAM_2           */
#define PU_DW_APB_WDT_WDT_COMP_PARAM_2_OFFSET 0xf0u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_2_BYTE_OFFSET 0xf0u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_2_READ_ACCESS 1u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_2_WRITE_ACCESS 0u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_2_RESET_VALUE 0x0000fffful
#define PU_DW_APB_WDT_WDT_COMP_PARAM_2_RESET_MASK 0xfffffffful
#define PU_DW_APB_WDT_WDT_COMP_PARAM_2_READ_MASK 0xfffffffful
#define PU_DW_APB_WDT_WDT_COMP_PARAM_2_WRITE_MASK 0x00000000ul
/* Register member: pu_DW_apb_wdt.WDT_COMP_PARAM_1                         */
/* Register type referenced: pu_DW_apb_wdt::WDT_COMP_PARAM_1               */
/* Register template referenced: pu_DW_apb_wdt::WDT_COMP_PARAM_1           */
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_OFFSET 0xf4u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_BYTE_OFFSET 0xf4u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_READ_ACCESS 1u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WRITE_ACCESS 0u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_RESET_VALUE 0x10000a06ul
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_RESET_MASK 0xfffffffful
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_READ_MASK 0xfffffffful
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WRITE_MASK 0x00000000ul
/* Register member: pu_DW_apb_wdt.WDT_COMP_VERSION                         */
/* Register type referenced: pu_DW_apb_wdt::WDT_COMP_VERSION               */
/* Register template referenced: pu_DW_apb_wdt::WDT_COMP_VERSION           */
#define PU_DW_APB_WDT_WDT_COMP_VERSION_OFFSET 0xf8u
#define PU_DW_APB_WDT_WDT_COMP_VERSION_BYTE_OFFSET 0xf8u
#define PU_DW_APB_WDT_WDT_COMP_VERSION_READ_ACCESS 1u
#define PU_DW_APB_WDT_WDT_COMP_VERSION_WRITE_ACCESS 0u
#define PU_DW_APB_WDT_WDT_COMP_VERSION_RESET_VALUE 0x3131312aul
#define PU_DW_APB_WDT_WDT_COMP_VERSION_RESET_MASK 0xfffffffful
#define PU_DW_APB_WDT_WDT_COMP_VERSION_READ_MASK 0xfffffffful
#define PU_DW_APB_WDT_WDT_COMP_VERSION_WRITE_MASK 0x00000000ul
/* Register member: pu_DW_apb_wdt.WDT_COMP_TYPE                            */
/* Register type referenced: pu_DW_apb_wdt::WDT_COMP_TYPE                  */
/* Register template referenced: pu_DW_apb_wdt::WDT_COMP_TYPE              */
#define PU_DW_APB_WDT_WDT_COMP_TYPE_OFFSET 0xfcu
#define PU_DW_APB_WDT_WDT_COMP_TYPE_BYTE_OFFSET 0xfcu
#define PU_DW_APB_WDT_WDT_COMP_TYPE_READ_ACCESS 1u
#define PU_DW_APB_WDT_WDT_COMP_TYPE_WRITE_ACCESS 0u
#define PU_DW_APB_WDT_WDT_COMP_TYPE_RESET_VALUE 0x44570120ul
#define PU_DW_APB_WDT_WDT_COMP_TYPE_RESET_MASK 0xfffffffful
#define PU_DW_APB_WDT_WDT_COMP_TYPE_READ_MASK 0xfffffffful
#define PU_DW_APB_WDT_WDT_COMP_TYPE_WRITE_MASK 0x00000000ul

/* Register type: pu_DW_apb_wdt::WDT_CR                                    */
/* Register template: pu_DW_apb_wdt::WDT_CR                                */
/* Source filename: pu_wdt.csr, line: 21                                   */
/* Field member: pu_DW_apb_wdt::WDT_CR.RSVD_WDT_CR                         */
/* Source filename: pu_wdt.csr, line: 138                                  */
#define PU_DW_APB_WDT_WDT_CR_RSVD_WDT_CR_MSB 31u
#define PU_DW_APB_WDT_WDT_CR_RSVD_WDT_CR_LSB 6u
#define PU_DW_APB_WDT_WDT_CR_RSVD_WDT_CR_WIDTH 26u
#define PU_DW_APB_WDT_WDT_CR_RSVD_WDT_CR_READ_ACCESS 1u
#define PU_DW_APB_WDT_WDT_CR_RSVD_WDT_CR_WRITE_ACCESS 0u
#define PU_DW_APB_WDT_WDT_CR_RSVD_WDT_CR_RESET 0x0000000ul
#define PU_DW_APB_WDT_WDT_CR_RSVD_WDT_CR_FIELD_MASK 0xffffffc0ul
#define PU_DW_APB_WDT_WDT_CR_RSVD_WDT_CR_GET(x) (((x) & 0xffffffc0ul) >> 6)
#define PU_DW_APB_WDT_WDT_CR_RSVD_WDT_CR_SET(x) (((x) << 6) & 0xffffffc0ul)
#define PU_DW_APB_WDT_WDT_CR_RSVD_WDT_CR_MODIFY(r, x) \
   ((((x) << 6) & 0xffffffc0ul) | ((r) & 0x0000003ful))
/* Field member: pu_DW_apb_wdt::WDT_CR.NO_NAME                             */
/* Source filename: pu_wdt.csr, line: 129                                  */
#define PU_DW_APB_WDT_WDT_CR_NO_NAME_MSB 5u
#define PU_DW_APB_WDT_WDT_CR_NO_NAME_LSB 5u
#define PU_DW_APB_WDT_WDT_CR_NO_NAME_WIDTH 1u
#define PU_DW_APB_WDT_WDT_CR_NO_NAME_READ_ACCESS 1u
#define PU_DW_APB_WDT_WDT_CR_NO_NAME_WRITE_ACCESS 1u
#define PU_DW_APB_WDT_WDT_CR_NO_NAME_RESET 0x0u
#define PU_DW_APB_WDT_WDT_CR_NO_NAME_FIELD_MASK 0x00000020ul
#define PU_DW_APB_WDT_WDT_CR_NO_NAME_GET(x) (((x) & 0x00000020ul) >> 5)
#define PU_DW_APB_WDT_WDT_CR_NO_NAME_SET(x) (((x) << 5) & 0x00000020ul)
#define PU_DW_APB_WDT_WDT_CR_NO_NAME_MODIFY(r, x) \
   ((((x) << 5) & 0x00000020ul) | ((r) & 0xffffffdful))
/* Field member: pu_DW_apb_wdt::WDT_CR.RPL                                 */
/* Source filename: pu_wdt.csr, line: 76                                   */
#define PU_DW_APB_WDT_WDT_CR_RPL_MSB 4u
#define PU_DW_APB_WDT_WDT_CR_RPL_LSB 2u
#define PU_DW_APB_WDT_WDT_CR_RPL_WIDTH 3u
#define PU_DW_APB_WDT_WDT_CR_RPL_READ_ACCESS 1u
#define PU_DW_APB_WDT_WDT_CR_RPL_WRITE_ACCESS 1u
#define PU_DW_APB_WDT_WDT_CR_RPL_RESET 0x2u
#define PU_DW_APB_WDT_WDT_CR_RPL_FIELD_MASK 0x0000001cul
#define PU_DW_APB_WDT_WDT_CR_RPL_GET(x) (((x) & 0x0000001cul) >> 2)
#define PU_DW_APB_WDT_WDT_CR_RPL_SET(x) (((x) << 2) & 0x0000001cul)
#define PU_DW_APB_WDT_WDT_CR_RPL_MODIFY(r, x) \
   ((((x) << 2) & 0x0000001cul) | ((r) & 0xffffffe3ul))
/* Field member: pu_DW_apb_wdt::WDT_CR.RMOD                                */
/* Source filename: pu_wdt.csr, line: 53                                   */
#define PU_DW_APB_WDT_WDT_CR_RMOD_MSB 1u
#define PU_DW_APB_WDT_WDT_CR_RMOD_LSB 1u
#define PU_DW_APB_WDT_WDT_CR_RMOD_WIDTH 1u
#define PU_DW_APB_WDT_WDT_CR_RMOD_READ_ACCESS 1u
#define PU_DW_APB_WDT_WDT_CR_RMOD_WRITE_ACCESS 1u
#define PU_DW_APB_WDT_WDT_CR_RMOD_RESET 0x1u
#define PU_DW_APB_WDT_WDT_CR_RMOD_FIELD_MASK 0x00000002ul
#define PU_DW_APB_WDT_WDT_CR_RMOD_GET(x) (((x) & 0x00000002ul) >> 1)
#define PU_DW_APB_WDT_WDT_CR_RMOD_SET(x) (((x) << 1) & 0x00000002ul)
#define PU_DW_APB_WDT_WDT_CR_RMOD_MODIFY(r, x) \
   ((((x) << 1) & 0x00000002ul) | ((r) & 0xfffffffdul))
/* Field member: pu_DW_apb_wdt::WDT_CR.WDT_EN                              */
/* Source filename: pu_wdt.csr, line: 26                                   */
#define PU_DW_APB_WDT_WDT_CR_WDT_EN_MSB 0u
#define PU_DW_APB_WDT_WDT_CR_WDT_EN_LSB 0u
#define PU_DW_APB_WDT_WDT_CR_WDT_EN_WIDTH 1u
#define PU_DW_APB_WDT_WDT_CR_WDT_EN_READ_ACCESS 1u
#define PU_DW_APB_WDT_WDT_CR_WDT_EN_WRITE_ACCESS 1u
#define PU_DW_APB_WDT_WDT_CR_WDT_EN_RESET 0x0u
#define PU_DW_APB_WDT_WDT_CR_WDT_EN_FIELD_MASK 0x00000001ul
#define PU_DW_APB_WDT_WDT_CR_WDT_EN_GET(x) ((x) & 0x00000001ul)
#define PU_DW_APB_WDT_WDT_CR_WDT_EN_SET(x) ((x) & 0x00000001ul)
#define PU_DW_APB_WDT_WDT_CR_WDT_EN_MODIFY(r, x) \
   (((x) & 0x00000001ul) | ((r) & 0xfffffffeul))

/* Register type: pu_DW_apb_wdt::WDT_TORR                                  */
/* Register template: pu_DW_apb_wdt::WDT_TORR                              */
/* Source filename: pu_wdt.csr, line: 147                                  */
/* Field member: pu_DW_apb_wdt::WDT_TORR.RSVD_WDT_TORR                     */
/* Source filename: pu_wdt.csr, line: 358                                  */
#define PU_DW_APB_WDT_WDT_TORR_RSVD_WDT_TORR_MSB 31u
#define PU_DW_APB_WDT_WDT_TORR_RSVD_WDT_TORR_LSB 8u
#define PU_DW_APB_WDT_WDT_TORR_RSVD_WDT_TORR_WIDTH 24u
#define PU_DW_APB_WDT_WDT_TORR_RSVD_WDT_TORR_READ_ACCESS 1u
#define PU_DW_APB_WDT_WDT_TORR_RSVD_WDT_TORR_WRITE_ACCESS 0u
#define PU_DW_APB_WDT_WDT_TORR_RSVD_WDT_TORR_RESET 0x000000ul
#define PU_DW_APB_WDT_WDT_TORR_RSVD_WDT_TORR_FIELD_MASK 0xffffff00ul
#define PU_DW_APB_WDT_WDT_TORR_RSVD_WDT_TORR_GET(x) \
   (((x) & 0xffffff00ul) >> 8)
#define PU_DW_APB_WDT_WDT_TORR_RSVD_WDT_TORR_SET(x) \
   (((x) << 8) & 0xffffff00ul)
#define PU_DW_APB_WDT_WDT_TORR_RSVD_WDT_TORR_MODIFY(r, x) \
   ((((x) << 8) & 0xffffff00ul) | ((r) & 0x000000fful))
/* Field member: pu_DW_apb_wdt::WDT_TORR.TOP_INIT                          */
/* Source filename: pu_wdt.csr, line: 251                                  */
#define PU_DW_APB_WDT_WDT_TORR_TOP_INIT_MSB 7u
#define PU_DW_APB_WDT_WDT_TORR_TOP_INIT_LSB 4u
#define PU_DW_APB_WDT_WDT_TORR_TOP_INIT_WIDTH 4u
#define PU_DW_APB_WDT_WDT_TORR_TOP_INIT_READ_ACCESS 1u
#define PU_DW_APB_WDT_WDT_TORR_TOP_INIT_WRITE_ACCESS 1u
#define PU_DW_APB_WDT_WDT_TORR_TOP_INIT_RESET 0x0u
#define PU_DW_APB_WDT_WDT_TORR_TOP_INIT_FIELD_MASK 0x000000f0ul
#define PU_DW_APB_WDT_WDT_TORR_TOP_INIT_GET(x) (((x) & 0x000000f0ul) >> 4)
#define PU_DW_APB_WDT_WDT_TORR_TOP_INIT_SET(x) (((x) << 4) & 0x000000f0ul)
#define PU_DW_APB_WDT_WDT_TORR_TOP_INIT_MODIFY(r, x) \
   ((((x) << 4) & 0x000000f0ul) | ((r) & 0xffffff0ful))
/* Field member: pu_DW_apb_wdt::WDT_TORR.TOP                               */
/* Source filename: pu_wdt.csr, line: 152                                  */
#define PU_DW_APB_WDT_WDT_TORR_TOP_MSB 3u
#define PU_DW_APB_WDT_WDT_TORR_TOP_LSB 0u
#define PU_DW_APB_WDT_WDT_TORR_TOP_WIDTH 4u
#define PU_DW_APB_WDT_WDT_TORR_TOP_READ_ACCESS 1u
#define PU_DW_APB_WDT_WDT_TORR_TOP_WRITE_ACCESS 1u
#define PU_DW_APB_WDT_WDT_TORR_TOP_RESET 0x0u
#define PU_DW_APB_WDT_WDT_TORR_TOP_FIELD_MASK 0x0000000ful
#define PU_DW_APB_WDT_WDT_TORR_TOP_GET(x) ((x) & 0x0000000ful)
#define PU_DW_APB_WDT_WDT_TORR_TOP_SET(x) ((x) & 0x0000000ful)
#define PU_DW_APB_WDT_WDT_TORR_TOP_MODIFY(r, x) \
   (((x) & 0x0000000ful) | ((r) & 0xfffffff0ul))

/* Register type: pu_DW_apb_wdt::WDT_CCVR                                  */
/* Register template: pu_DW_apb_wdt::WDT_CCVR                              */
/* Source filename: pu_wdt.csr, line: 367                                  */
/* Field member: pu_DW_apb_wdt::WDT_CCVR.WDT_CCVR                          */
/* Source filename: pu_wdt.csr, line: 373                                  */
#define PU_DW_APB_WDT_WDT_CCVR_WDT_CCVR_MSB 31u
#define PU_DW_APB_WDT_WDT_CCVR_WDT_CCVR_LSB 0u
#define PU_DW_APB_WDT_WDT_CCVR_WDT_CCVR_WIDTH 32u
#define PU_DW_APB_WDT_WDT_CCVR_WDT_CCVR_READ_ACCESS 1u
#define PU_DW_APB_WDT_WDT_CCVR_WDT_CCVR_WRITE_ACCESS 0u
#define PU_DW_APB_WDT_WDT_CCVR_WDT_CCVR_RESET 0x0000fffful
#define PU_DW_APB_WDT_WDT_CCVR_WDT_CCVR_FIELD_MASK 0xfffffffful
#define PU_DW_APB_WDT_WDT_CCVR_WDT_CCVR_GET(x) ((x) & 0xfffffffful)
#define PU_DW_APB_WDT_WDT_CCVR_WDT_CCVR_SET(x) ((x) & 0xfffffffful)
#define PU_DW_APB_WDT_WDT_CCVR_WDT_CCVR_MODIFY(r, x) ((x) & 0xfffffffful)

/* Register type: pu_DW_apb_wdt::WDT_CRR                                   */
/* Register template: pu_DW_apb_wdt::WDT_CRR                               */
/* Source filename: pu_wdt.csr, line: 385                                  */
/* Field member: pu_DW_apb_wdt::WDT_CRR.RSVD_WDT_CRR                       */
/* Source filename: pu_wdt.csr, line: 409                                  */
#define PU_DW_APB_WDT_WDT_CRR_RSVD_WDT_CRR_MSB 31u
#define PU_DW_APB_WDT_WDT_CRR_RSVD_WDT_CRR_LSB 8u
#define PU_DW_APB_WDT_WDT_CRR_RSVD_WDT_CRR_WIDTH 24u
#define PU_DW_APB_WDT_WDT_CRR_RSVD_WDT_CRR_READ_ACCESS 0u
#define PU_DW_APB_WDT_WDT_CRR_RSVD_WDT_CRR_WRITE_ACCESS 1u
#define PU_DW_APB_WDT_WDT_CRR_RSVD_WDT_CRR_RESET 0x000000ul
#define PU_DW_APB_WDT_WDT_CRR_RSVD_WDT_CRR_FIELD_MASK 0xffffff00ul
#define PU_DW_APB_WDT_WDT_CRR_RSVD_WDT_CRR_GET(x) (((x) & 0xffffff00ul) >> 8)
#define PU_DW_APB_WDT_WDT_CRR_RSVD_WDT_CRR_SET(x) \
   (((x) << 8) & 0xffffff00ul)
#define PU_DW_APB_WDT_WDT_CRR_RSVD_WDT_CRR_MODIFY(r, x) \
   ((((x) << 8) & 0xffffff00ul) | ((r) & 0x000000fful))
/* Field member: pu_DW_apb_wdt::WDT_CRR.WDT_CRR                            */
/* Source filename: pu_wdt.csr, line: 391                                  */
#define PU_DW_APB_WDT_WDT_CRR_WDT_CRR_MSB 7u
#define PU_DW_APB_WDT_WDT_CRR_WDT_CRR_LSB 0u
#define PU_DW_APB_WDT_WDT_CRR_WDT_CRR_WIDTH 8u
#define PU_DW_APB_WDT_WDT_CRR_WDT_CRR_READ_ACCESS 0u
#define PU_DW_APB_WDT_WDT_CRR_WDT_CRR_WRITE_ACCESS 1u
#define PU_DW_APB_WDT_WDT_CRR_WDT_CRR_RESET 0x00u
#define PU_DW_APB_WDT_WDT_CRR_WDT_CRR_FIELD_MASK 0x000000fful
#define PU_DW_APB_WDT_WDT_CRR_WDT_CRR_GET(x) ((x) & 0x000000fful)
#define PU_DW_APB_WDT_WDT_CRR_WDT_CRR_SET(x) ((x) & 0x000000fful)
#define PU_DW_APB_WDT_WDT_CRR_WDT_CRR_MODIFY(r, x) \
   (((x) & 0x000000fful) | ((r) & 0xffffff00ul))

/* Register type: pu_DW_apb_wdt::WDT_STAT                                  */
/* Register template: pu_DW_apb_wdt::WDT_STAT                              */
/* Source filename: pu_wdt.csr, line: 417                                  */
/* Field member: pu_DW_apb_wdt::WDT_STAT.RSVD_WDT_STAT                     */
/* Source filename: pu_wdt.csr, line: 442                                  */
#define PU_DW_APB_WDT_WDT_STAT_RSVD_WDT_STAT_MSB 31u
#define PU_DW_APB_WDT_WDT_STAT_RSVD_WDT_STAT_LSB 1u
#define PU_DW_APB_WDT_WDT_STAT_RSVD_WDT_STAT_WIDTH 31u
#define PU_DW_APB_WDT_WDT_STAT_RSVD_WDT_STAT_READ_ACCESS 1u
#define PU_DW_APB_WDT_WDT_STAT_RSVD_WDT_STAT_WRITE_ACCESS 0u
#define PU_DW_APB_WDT_WDT_STAT_RSVD_WDT_STAT_RESET 0x00000000ul
#define PU_DW_APB_WDT_WDT_STAT_RSVD_WDT_STAT_FIELD_MASK 0xfffffffeul
#define PU_DW_APB_WDT_WDT_STAT_RSVD_WDT_STAT_GET(x) \
   (((x) & 0xfffffffeul) >> 1)
#define PU_DW_APB_WDT_WDT_STAT_RSVD_WDT_STAT_SET(x) \
   (((x) << 1) & 0xfffffffeul)
#define PU_DW_APB_WDT_WDT_STAT_RSVD_WDT_STAT_MODIFY(r, x) \
   ((((x) << 1) & 0xfffffffeul) | ((r) & 0x00000001ul))
/* Field member: pu_DW_apb_wdt::WDT_STAT.WDT_STAT                          */
/* Source filename: pu_wdt.csr, line: 423                                  */
#define PU_DW_APB_WDT_WDT_STAT_WDT_STAT_MSB 0u
#define PU_DW_APB_WDT_WDT_STAT_WDT_STAT_LSB 0u
#define PU_DW_APB_WDT_WDT_STAT_WDT_STAT_WIDTH 1u
#define PU_DW_APB_WDT_WDT_STAT_WDT_STAT_READ_ACCESS 1u
#define PU_DW_APB_WDT_WDT_STAT_WDT_STAT_WRITE_ACCESS 0u
#define PU_DW_APB_WDT_WDT_STAT_WDT_STAT_RESET 0x0u
#define PU_DW_APB_WDT_WDT_STAT_WDT_STAT_FIELD_MASK 0x00000001ul
#define PU_DW_APB_WDT_WDT_STAT_WDT_STAT_GET(x) ((x) & 0x00000001ul)
#define PU_DW_APB_WDT_WDT_STAT_WDT_STAT_SET(x) ((x) & 0x00000001ul)
#define PU_DW_APB_WDT_WDT_STAT_WDT_STAT_MODIFY(r, x) \
   (((x) & 0x00000001ul) | ((r) & 0xfffffffeul))

/* Register type: pu_DW_apb_wdt::WDT_EOI                                   */
/* Register template: pu_DW_apb_wdt::WDT_EOI                               */
/* Source filename: pu_wdt.csr, line: 450                                  */
/* Field member: pu_DW_apb_wdt::WDT_EOI.RSVD_WDT_EOI                       */
/* Source filename: pu_wdt.csr, line: 465                                  */
#define PU_DW_APB_WDT_WDT_EOI_RSVD_WDT_EOI_MSB 31u
#define PU_DW_APB_WDT_WDT_EOI_RSVD_WDT_EOI_LSB 1u
#define PU_DW_APB_WDT_WDT_EOI_RSVD_WDT_EOI_WIDTH 31u
#define PU_DW_APB_WDT_WDT_EOI_RSVD_WDT_EOI_READ_ACCESS 1u
#define PU_DW_APB_WDT_WDT_EOI_RSVD_WDT_EOI_WRITE_ACCESS 0u
#define PU_DW_APB_WDT_WDT_EOI_RSVD_WDT_EOI_RESET 0x00000000ul
#define PU_DW_APB_WDT_WDT_EOI_RSVD_WDT_EOI_FIELD_MASK 0xfffffffeul
#define PU_DW_APB_WDT_WDT_EOI_RSVD_WDT_EOI_GET(x) (((x) & 0xfffffffeul) >> 1)
#define PU_DW_APB_WDT_WDT_EOI_RSVD_WDT_EOI_SET(x) \
   (((x) << 1) & 0xfffffffeul)
#define PU_DW_APB_WDT_WDT_EOI_RSVD_WDT_EOI_MODIFY(r, x) \
   ((((x) << 1) & 0xfffffffeul) | ((r) & 0x00000001ul))
/* Field member: pu_DW_apb_wdt::WDT_EOI.WDT_EOI                            */
/* Source filename: pu_wdt.csr, line: 456                                  */
#define PU_DW_APB_WDT_WDT_EOI_WDT_EOI_MSB 0u
#define PU_DW_APB_WDT_WDT_EOI_WDT_EOI_LSB 0u
#define PU_DW_APB_WDT_WDT_EOI_WDT_EOI_WIDTH 1u
#define PU_DW_APB_WDT_WDT_EOI_WDT_EOI_READ_ACCESS 1u
#define PU_DW_APB_WDT_WDT_EOI_WDT_EOI_WRITE_ACCESS 0u
#define PU_DW_APB_WDT_WDT_EOI_WDT_EOI_RESET 0x0u
#define PU_DW_APB_WDT_WDT_EOI_WDT_EOI_FIELD_MASK 0x00000001ul
#define PU_DW_APB_WDT_WDT_EOI_WDT_EOI_GET(x) ((x) & 0x00000001ul)
#define PU_DW_APB_WDT_WDT_EOI_WDT_EOI_SET(x) ((x) & 0x00000001ul)
#define PU_DW_APB_WDT_WDT_EOI_WDT_EOI_MODIFY(r, x) \
   (((x) & 0x00000001ul) | ((r) & 0xfffffffeul))

/* Register type: pu_DW_apb_wdt::WDT_COMP_PARAM_5                          */
/* Register template: pu_DW_apb_wdt::WDT_COMP_PARAM_5                      */
/* Source filename: pu_wdt.csr, line: 473                                  */
/* Field member: pu_DW_apb_wdt::WDT_COMP_PARAM_5.CP_WDT_USER_TOP_MAX       */
/* Source filename: pu_wdt.csr, line: 482                                  */
#define PU_DW_APB_WDT_WDT_COMP_PARAM_5_CP_WDT_USER_TOP_MAX_MSB 31u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_5_CP_WDT_USER_TOP_MAX_LSB 0u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_5_CP_WDT_USER_TOP_MAX_WIDTH 32u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_5_CP_WDT_USER_TOP_MAX_READ_ACCESS 1u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_5_CP_WDT_USER_TOP_MAX_WRITE_ACCESS 0u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_5_CP_WDT_USER_TOP_MAX_RESET 0x7ffffffful
#define PU_DW_APB_WDT_WDT_COMP_PARAM_5_CP_WDT_USER_TOP_MAX_FIELD_MASK 0xfffffffful
#define PU_DW_APB_WDT_WDT_COMP_PARAM_5_CP_WDT_USER_TOP_MAX_GET(x) \
   ((x) & 0xfffffffful)
#define PU_DW_APB_WDT_WDT_COMP_PARAM_5_CP_WDT_USER_TOP_MAX_SET(x) \
   ((x) & 0xfffffffful)
#define PU_DW_APB_WDT_WDT_COMP_PARAM_5_CP_WDT_USER_TOP_MAX_MODIFY(r, x) \
   ((x) & 0xfffffffful)

/* Register type: pu_DW_apb_wdt::WDT_COMP_PARAM_4                          */
/* Register template: pu_DW_apb_wdt::WDT_COMP_PARAM_4                      */
/* Source filename: pu_wdt.csr, line: 492                                  */
/* Field member: pu_DW_apb_wdt::WDT_COMP_PARAM_4.CP_WDT_USER_TOP_INIT_MAX  */
/* Source filename: pu_wdt.csr, line: 501                                  */
#define PU_DW_APB_WDT_WDT_COMP_PARAM_4_CP_WDT_USER_TOP_INIT_MAX_MSB 31u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_4_CP_WDT_USER_TOP_INIT_MAX_LSB 0u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_4_CP_WDT_USER_TOP_INIT_MAX_WIDTH 32u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_4_CP_WDT_USER_TOP_INIT_MAX_READ_ACCESS 1u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_4_CP_WDT_USER_TOP_INIT_MAX_WRITE_ACCESS 0u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_4_CP_WDT_USER_TOP_INIT_MAX_RESET 0x7ffffffful
#define PU_DW_APB_WDT_WDT_COMP_PARAM_4_CP_WDT_USER_TOP_INIT_MAX_FIELD_MASK 0xfffffffful
#define PU_DW_APB_WDT_WDT_COMP_PARAM_4_CP_WDT_USER_TOP_INIT_MAX_GET(x) \
   ((x) & 0xfffffffful)
#define PU_DW_APB_WDT_WDT_COMP_PARAM_4_CP_WDT_USER_TOP_INIT_MAX_SET(x) \
   ((x) & 0xfffffffful)
#define PU_DW_APB_WDT_WDT_COMP_PARAM_4_CP_WDT_USER_TOP_INIT_MAX_MODIFY(r, x) \
   ((x) & 0xfffffffful)

/* Register type: pu_DW_apb_wdt::WDT_COMP_PARAM_3                          */
/* Register template: pu_DW_apb_wdt::WDT_COMP_PARAM_3                      */
/* Source filename: pu_wdt.csr, line: 511                                  */
/* Field member: pu_DW_apb_wdt::WDT_COMP_PARAM_3.CD_WDT_TOP_RST            */
/* Source filename: pu_wdt.csr, line: 520                                  */
#define PU_DW_APB_WDT_WDT_COMP_PARAM_3_CD_WDT_TOP_RST_MSB 31u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_3_CD_WDT_TOP_RST_LSB 0u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_3_CD_WDT_TOP_RST_WIDTH 32u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_3_CD_WDT_TOP_RST_READ_ACCESS 1u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_3_CD_WDT_TOP_RST_WRITE_ACCESS 0u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_3_CD_WDT_TOP_RST_RESET 0x00000000ul
#define PU_DW_APB_WDT_WDT_COMP_PARAM_3_CD_WDT_TOP_RST_FIELD_MASK 0xfffffffful
#define PU_DW_APB_WDT_WDT_COMP_PARAM_3_CD_WDT_TOP_RST_GET(x) \
   ((x) & 0xfffffffful)
#define PU_DW_APB_WDT_WDT_COMP_PARAM_3_CD_WDT_TOP_RST_SET(x) \
   ((x) & 0xfffffffful)
#define PU_DW_APB_WDT_WDT_COMP_PARAM_3_CD_WDT_TOP_RST_MODIFY(r, x) \
   ((x) & 0xfffffffful)

/* Register type: pu_DW_apb_wdt::WDT_COMP_PARAM_2                          */
/* Register template: pu_DW_apb_wdt::WDT_COMP_PARAM_2                      */
/* Source filename: pu_wdt.csr, line: 529                                  */
/* Field member: pu_DW_apb_wdt::WDT_COMP_PARAM_2.CP_WDT_CNT_RST            */
/* Source filename: pu_wdt.csr, line: 538                                  */
#define PU_DW_APB_WDT_WDT_COMP_PARAM_2_CP_WDT_CNT_RST_MSB 31u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_2_CP_WDT_CNT_RST_LSB 0u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_2_CP_WDT_CNT_RST_WIDTH 32u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_2_CP_WDT_CNT_RST_READ_ACCESS 1u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_2_CP_WDT_CNT_RST_WRITE_ACCESS 0u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_2_CP_WDT_CNT_RST_RESET 0x0000fffful
#define PU_DW_APB_WDT_WDT_COMP_PARAM_2_CP_WDT_CNT_RST_FIELD_MASK 0xfffffffful
#define PU_DW_APB_WDT_WDT_COMP_PARAM_2_CP_WDT_CNT_RST_GET(x) \
   ((x) & 0xfffffffful)
#define PU_DW_APB_WDT_WDT_COMP_PARAM_2_CP_WDT_CNT_RST_SET(x) \
   ((x) & 0xfffffffful)
#define PU_DW_APB_WDT_WDT_COMP_PARAM_2_CP_WDT_CNT_RST_MODIFY(r, x) \
   ((x) & 0xfffffffful)

/* Register type: pu_DW_apb_wdt::WDT_COMP_PARAM_1                          */
/* Register template: pu_DW_apb_wdt::WDT_COMP_PARAM_1                      */
/* Source filename: pu_wdt.csr, line: 547                                  */
/* Field member: pu_DW_apb_wdt::WDT_COMP_PARAM_1.RSVD_31_29                */
/* Source filename: pu_wdt.csr, line: 784                                  */
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_RSVD_31_29_MSB 31u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_RSVD_31_29_LSB 29u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_RSVD_31_29_WIDTH 3u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_RSVD_31_29_READ_ACCESS 1u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_RSVD_31_29_WRITE_ACCESS 0u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_RSVD_31_29_RESET 0x0u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_RSVD_31_29_FIELD_MASK 0xe0000000ul
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_RSVD_31_29_GET(x) \
   (((x) & 0xe0000000ul) >> 29)
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_RSVD_31_29_SET(x) \
   (((x) << 29) & 0xe0000000ul)
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_RSVD_31_29_MODIFY(r, x) \
   ((((x) << 29) & 0xe0000000ul) | ((r) & 0x1ffffffful))
/* Field member: pu_DW_apb_wdt::WDT_COMP_PARAM_1.WDT_CNT_WIDTH             */
/* Source filename: pu_wdt.csr, line: 777                                  */
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_CNT_WIDTH_MSB 28u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_CNT_WIDTH_LSB 24u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_CNT_WIDTH_WIDTH 5u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_CNT_WIDTH_READ_ACCESS 1u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_CNT_WIDTH_WRITE_ACCESS 0u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_CNT_WIDTH_RESET 0x10u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_CNT_WIDTH_FIELD_MASK 0x1f000000ul
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_CNT_WIDTH_GET(x) \
   (((x) & 0x1f000000ul) >> 24)
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_CNT_WIDTH_SET(x) \
   (((x) << 24) & 0x1f000000ul)
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_CNT_WIDTH_MODIFY(r, x) \
   ((((x) << 24) & 0x1f000000ul) | ((r) & 0xe0fffffful))
/* Field member: pu_DW_apb_wdt::WDT_COMP_PARAM_1.WDT_DFLT_TOP_INIT         */
/* Source filename: pu_wdt.csr, line: 767                                  */
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DFLT_TOP_INIT_MSB 23u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DFLT_TOP_INIT_LSB 20u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DFLT_TOP_INIT_WIDTH 4u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DFLT_TOP_INIT_READ_ACCESS 1u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DFLT_TOP_INIT_WRITE_ACCESS 0u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DFLT_TOP_INIT_RESET 0x0u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DFLT_TOP_INIT_FIELD_MASK 0x00f00000ul
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DFLT_TOP_INIT_GET(x) \
   (((x) & 0x00f00000ul) >> 20)
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DFLT_TOP_INIT_SET(x) \
   (((x) << 20) & 0x00f00000ul)
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DFLT_TOP_INIT_MODIFY(r, x) \
   ((((x) << 20) & 0x00f00000ul) | ((r) & 0xff0ffffful))
/* Field member: pu_DW_apb_wdt::WDT_COMP_PARAM_1.WDT_DFLT_TOP              */
/* Source filename: pu_wdt.csr, line: 756                                  */
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DFLT_TOP_MSB 19u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DFLT_TOP_LSB 16u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DFLT_TOP_WIDTH 4u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DFLT_TOP_READ_ACCESS 1u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DFLT_TOP_WRITE_ACCESS 0u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DFLT_TOP_RESET 0x0u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DFLT_TOP_FIELD_MASK 0x000f0000ul
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DFLT_TOP_GET(x) \
   (((x) & 0x000f0000ul) >> 16)
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DFLT_TOP_SET(x) \
   (((x) << 16) & 0x000f0000ul)
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DFLT_TOP_MODIFY(r, x) \
   ((((x) << 16) & 0x000f0000ul) | ((r) & 0xfff0fffful))
/* Field member: pu_DW_apb_wdt::WDT_COMP_PARAM_1.RSVD_15_13                */
/* Source filename: pu_wdt.csr, line: 748                                  */
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_RSVD_15_13_MSB 15u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_RSVD_15_13_LSB 13u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_RSVD_15_13_WIDTH 3u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_RSVD_15_13_READ_ACCESS 1u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_RSVD_15_13_WRITE_ACCESS 0u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_RSVD_15_13_RESET 0x0u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_RSVD_15_13_FIELD_MASK 0x0000e000ul
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_RSVD_15_13_GET(x) \
   (((x) & 0x0000e000ul) >> 13)
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_RSVD_15_13_SET(x) \
   (((x) << 13) & 0x0000e000ul)
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_RSVD_15_13_MODIFY(r, x) \
   ((((x) << 13) & 0x0000e000ul) | ((r) & 0xffff1ffful))
/* Field member: pu_DW_apb_wdt::WDT_COMP_PARAM_1.WDT_DFLT_RPL              */
/* Source filename: pu_wdt.csr, line: 740                                  */
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DFLT_RPL_MSB 12u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DFLT_RPL_LSB 10u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DFLT_RPL_WIDTH 3u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DFLT_RPL_READ_ACCESS 1u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DFLT_RPL_WRITE_ACCESS 0u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DFLT_RPL_RESET 0x2u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DFLT_RPL_FIELD_MASK 0x00001c00ul
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DFLT_RPL_GET(x) \
   (((x) & 0x00001c00ul) >> 10)
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DFLT_RPL_SET(x) \
   (((x) << 10) & 0x00001c00ul)
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DFLT_RPL_MODIFY(r, x) \
   ((((x) << 10) & 0x00001c00ul) | ((r) & 0xffffe3fful))
/* Field member: pu_DW_apb_wdt::WDT_COMP_PARAM_1.APB_DATA_WIDTH            */
/* Source filename: pu_wdt.csr, line: 717                                  */
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_APB_DATA_WIDTH_MSB 9u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_APB_DATA_WIDTH_LSB 8u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_APB_DATA_WIDTH_WIDTH 2u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_APB_DATA_WIDTH_READ_ACCESS 1u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_APB_DATA_WIDTH_WRITE_ACCESS 0u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_APB_DATA_WIDTH_RESET 0x2u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_APB_DATA_WIDTH_FIELD_MASK 0x00000300ul
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_APB_DATA_WIDTH_GET(x) \
   (((x) & 0x00000300ul) >> 8)
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_APB_DATA_WIDTH_SET(x) \
   (((x) << 8) & 0x00000300ul)
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_APB_DATA_WIDTH_MODIFY(r, x) \
   ((((x) << 8) & 0x00000300ul) | ((r) & 0xfffffcfful))
/* Field member: pu_DW_apb_wdt::WDT_COMP_PARAM_1.WDT_PAUSE                 */
/* Source filename: pu_wdt.csr, line: 697                                  */
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_PAUSE_MSB 7u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_PAUSE_LSB 7u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_PAUSE_WIDTH 1u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_PAUSE_READ_ACCESS 1u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_PAUSE_WRITE_ACCESS 0u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_PAUSE_RESET 0x0u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_PAUSE_FIELD_MASK 0x00000080ul
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_PAUSE_GET(x) \
   (((x) & 0x00000080ul) >> 7)
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_PAUSE_SET(x) \
   (((x) << 7) & 0x00000080ul)
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_PAUSE_MODIFY(r, x) \
   ((((x) << 7) & 0x00000080ul) | ((r) & 0xffffff7ful))
/* Field member: pu_DW_apb_wdt::WDT_COMP_PARAM_1.WDT_USE_FIX_TOP           */
/* Source filename: pu_wdt.csr, line: 675                                  */
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_USE_FIX_TOP_MSB 6u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_USE_FIX_TOP_LSB 6u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_USE_FIX_TOP_WIDTH 1u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_USE_FIX_TOP_READ_ACCESS 1u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_USE_FIX_TOP_WRITE_ACCESS 0u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_USE_FIX_TOP_RESET 0x0u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_USE_FIX_TOP_FIELD_MASK 0x00000040ul
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_USE_FIX_TOP_GET(x) \
   (((x) & 0x00000040ul) >> 6)
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_USE_FIX_TOP_SET(x) \
   (((x) << 6) & 0x00000040ul)
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_USE_FIX_TOP_MODIFY(r, x) \
   ((((x) << 6) & 0x00000040ul) | ((r) & 0xffffffbful))
/* Field member: pu_DW_apb_wdt::WDT_COMP_PARAM_1.WDT_HC_TOP                */
/* Source filename: pu_wdt.csr, line: 656                                  */
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_HC_TOP_MSB 5u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_HC_TOP_LSB 5u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_HC_TOP_WIDTH 1u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_HC_TOP_READ_ACCESS 1u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_HC_TOP_WRITE_ACCESS 0u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_HC_TOP_RESET 0x0u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_HC_TOP_FIELD_MASK 0x00000020ul
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_HC_TOP_GET(x) \
   (((x) & 0x00000020ul) >> 5)
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_HC_TOP_SET(x) \
   (((x) << 5) & 0x00000020ul)
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_HC_TOP_MODIFY(r, x) \
   ((((x) << 5) & 0x00000020ul) | ((r) & 0xffffffdful))
/* Field member: pu_DW_apb_wdt::WDT_COMP_PARAM_1.WDT_HC_RPL                */
/* Source filename: pu_wdt.csr, line: 638                                  */
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_HC_RPL_MSB 4u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_HC_RPL_LSB 4u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_HC_RPL_WIDTH 1u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_HC_RPL_READ_ACCESS 1u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_HC_RPL_WRITE_ACCESS 0u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_HC_RPL_RESET 0x0u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_HC_RPL_FIELD_MASK 0x00000010ul
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_HC_RPL_GET(x) \
   (((x) & 0x00000010ul) >> 4)
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_HC_RPL_SET(x) \
   (((x) << 4) & 0x00000010ul)
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_HC_RPL_MODIFY(r, x) \
   ((((x) << 4) & 0x00000010ul) | ((r) & 0xffffffeful))
/* Field member: pu_DW_apb_wdt::WDT_COMP_PARAM_1.WDT_HC_RMOD               */
/* Source filename: pu_wdt.csr, line: 620                                  */
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_HC_RMOD_MSB 3u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_HC_RMOD_LSB 3u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_HC_RMOD_WIDTH 1u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_HC_RMOD_READ_ACCESS 1u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_HC_RMOD_WRITE_ACCESS 0u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_HC_RMOD_RESET 0x0u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_HC_RMOD_FIELD_MASK 0x00000008ul
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_HC_RMOD_GET(x) \
   (((x) & 0x00000008ul) >> 3)
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_HC_RMOD_SET(x) \
   (((x) << 3) & 0x00000008ul)
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_HC_RMOD_MODIFY(r, x) \
   ((((x) << 3) & 0x00000008ul) | ((r) & 0xfffffff7ul))
/* Field member: pu_DW_apb_wdt::WDT_COMP_PARAM_1.WDT_DUAL_TOP              */
/* Source filename: pu_wdt.csr, line: 601                                  */
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DUAL_TOP_MSB 2u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DUAL_TOP_LSB 2u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DUAL_TOP_WIDTH 1u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DUAL_TOP_READ_ACCESS 1u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DUAL_TOP_WRITE_ACCESS 0u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DUAL_TOP_RESET 0x1u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DUAL_TOP_FIELD_MASK 0x00000004ul
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DUAL_TOP_GET(x) \
   (((x) & 0x00000004ul) >> 2)
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DUAL_TOP_SET(x) \
   (((x) << 2) & 0x00000004ul)
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DUAL_TOP_MODIFY(r, x) \
   ((((x) << 2) & 0x00000004ul) | ((r) & 0xfffffffbul))
/* Field member: pu_DW_apb_wdt::WDT_COMP_PARAM_1.WDT_DFLT_RMOD             */
/* Source filename: pu_wdt.csr, line: 578                                  */
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DFLT_RMOD_MSB 1u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DFLT_RMOD_LSB 1u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DFLT_RMOD_WIDTH 1u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DFLT_RMOD_READ_ACCESS 1u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DFLT_RMOD_WRITE_ACCESS 0u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DFLT_RMOD_RESET 0x1u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DFLT_RMOD_FIELD_MASK 0x00000002ul
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DFLT_RMOD_GET(x) \
   (((x) & 0x00000002ul) >> 1)
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DFLT_RMOD_SET(x) \
   (((x) << 1) & 0x00000002ul)
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_DFLT_RMOD_MODIFY(r, x) \
   ((((x) << 1) & 0x00000002ul) | ((r) & 0xfffffffdul))
/* Field member: pu_DW_apb_wdt::WDT_COMP_PARAM_1.WDT_ALWAYS_EN             */
/* Source filename: pu_wdt.csr, line: 557                                  */
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_ALWAYS_EN_MSB 0u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_ALWAYS_EN_LSB 0u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_ALWAYS_EN_WIDTH 1u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_ALWAYS_EN_READ_ACCESS 1u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_ALWAYS_EN_WRITE_ACCESS 0u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_ALWAYS_EN_RESET 0x0u
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_ALWAYS_EN_FIELD_MASK 0x00000001ul
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_ALWAYS_EN_GET(x) \
   ((x) & 0x00000001ul)
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_ALWAYS_EN_SET(x) \
   ((x) & 0x00000001ul)
#define PU_DW_APB_WDT_WDT_COMP_PARAM_1_WDT_ALWAYS_EN_MODIFY(r, x) \
   (((x) & 0x00000001ul) | ((r) & 0xfffffffeul))

/* Register type: pu_DW_apb_wdt::WDT_COMP_VERSION                          */
/* Register template: pu_DW_apb_wdt::WDT_COMP_VERSION                      */
/* Source filename: pu_wdt.csr, line: 792                                  */
/* Field member: pu_DW_apb_wdt::WDT_COMP_VERSION.WDT_COMP_VERSION          */
/* Source filename: pu_wdt.csr, line: 798                                  */
#define PU_DW_APB_WDT_WDT_COMP_VERSION_WDT_COMP_VERSION_MSB 31u
#define PU_DW_APB_WDT_WDT_COMP_VERSION_WDT_COMP_VERSION_LSB 0u
#define PU_DW_APB_WDT_WDT_COMP_VERSION_WDT_COMP_VERSION_WIDTH 32u
#define PU_DW_APB_WDT_WDT_COMP_VERSION_WDT_COMP_VERSION_READ_ACCESS 1u
#define PU_DW_APB_WDT_WDT_COMP_VERSION_WDT_COMP_VERSION_WRITE_ACCESS 0u
#define PU_DW_APB_WDT_WDT_COMP_VERSION_WDT_COMP_VERSION_RESET 0x3131312aul
#define PU_DW_APB_WDT_WDT_COMP_VERSION_WDT_COMP_VERSION_FIELD_MASK 0xfffffffful
#define PU_DW_APB_WDT_WDT_COMP_VERSION_WDT_COMP_VERSION_GET(x) \
   ((x) & 0xfffffffful)
#define PU_DW_APB_WDT_WDT_COMP_VERSION_WDT_COMP_VERSION_SET(x) \
   ((x) & 0xfffffffful)
#define PU_DW_APB_WDT_WDT_COMP_VERSION_WDT_COMP_VERSION_MODIFY(r, x) \
   ((x) & 0xfffffffful)

/* Register type: pu_DW_apb_wdt::WDT_COMP_TYPE                             */
/* Register template: pu_DW_apb_wdt::WDT_COMP_TYPE                         */
/* Source filename: pu_wdt.csr, line: 807                                  */
/* Field member: pu_DW_apb_wdt::WDT_COMP_TYPE.WDT_COMP_TYPE                */
/* Source filename: pu_wdt.csr, line: 813                                  */
#define PU_DW_APB_WDT_WDT_COMP_TYPE_WDT_COMP_TYPE_MSB 31u
#define PU_DW_APB_WDT_WDT_COMP_TYPE_WDT_COMP_TYPE_LSB 0u
#define PU_DW_APB_WDT_WDT_COMP_TYPE_WDT_COMP_TYPE_WIDTH 32u
#define PU_DW_APB_WDT_WDT_COMP_TYPE_WDT_COMP_TYPE_READ_ACCESS 1u
#define PU_DW_APB_WDT_WDT_COMP_TYPE_WDT_COMP_TYPE_WRITE_ACCESS 0u
#define PU_DW_APB_WDT_WDT_COMP_TYPE_WDT_COMP_TYPE_RESET 0x44570120ul
#define PU_DW_APB_WDT_WDT_COMP_TYPE_WDT_COMP_TYPE_FIELD_MASK 0xfffffffful
#define PU_DW_APB_WDT_WDT_COMP_TYPE_WDT_COMP_TYPE_GET(x) ((x) & 0xfffffffful)
#define PU_DW_APB_WDT_WDT_COMP_TYPE_WDT_COMP_TYPE_SET(x) ((x) & 0xfffffffful)
#define PU_DW_APB_WDT_WDT_COMP_TYPE_WDT_COMP_TYPE_MODIFY(r, x) \
   ((x) & 0xfffffffful)

/* ####################################################################### */
/*        TYPE DEFINITIONS                                                 */
/* ####################################################################### */

/* Typedef for Addressmap: pu_DW_apb_wdt                                   */
/* Source filename: pu_wdt.csr, line: 824                                  */
typedef struct {
   volatile uint32_t WDT_CR; /**< Offset 0x0 (R/W) */
   volatile uint32_t WDT_TORR; /**< Offset 0x4 (R/W) */
   uint32_t WDT_CCVR; /**< Offset 0x8 (R) */
   volatile uint32_t WDT_CRR; /**< Offset 0xc (W) */
   uint32_t WDT_STAT; /**< Offset 0x10 (R) */
   uint32_t WDT_EOI; /**< Offset 0x14 (R) */
   uint8_t _pad0[0xcc];
   uint32_t WDT_COMP_PARAM_5; /**< Offset 0xe4 (R) */
   uint32_t WDT_COMP_PARAM_4; /**< Offset 0xe8 (R) */
   uint32_t WDT_COMP_PARAM_3; /**< Offset 0xec (R) */
   uint32_t WDT_COMP_PARAM_2; /**< Offset 0xf0 (R) */
   uint32_t WDT_COMP_PARAM_1; /**< Offset 0xf4 (R) */
   uint32_t WDT_COMP_VERSION; /**< Offset 0xf8 (R) */
   uint32_t WDT_COMP_TYPE; /**< Offset 0xfc (R) */
} Pu_DW_apb_wdt, *PTR_Pu_DW_apb_wdt;

#endif
