/*                                                                         */
/*                                                                         */
/* Generated by Semifore, Inc. csrCompile                                  */
/*    C Header output                                                      */

#ifndef _PVTC_H_
#define _PVTC_H_



/* ####################################################################### */
/*        ADDRESS MACROS                                                   */
/* ####################################################################### */

/* Address Space for Addressmap: common_ip                                 */
/* Source filename: pvtc.csr, line: 306                                    */
/* Register: common_ip.clk_synth                                           */
#define COMMON_IP_CLK_SYNTH_ADDRESS 0x0u
#define COMMON_IP_CLK_SYNTH_BYTE_ADDRESS 0x0u
/* Register: common_ip.sdif_disable                                        */
#define COMMON_IP_SDIF_DISABLE_ADDRESS 0x4u
#define COMMON_IP_SDIF_DISABLE_BYTE_ADDRESS 0x4u
/* Register: common_ip.sdif_status                                         */
#define COMMON_IP_SDIF_STATUS_ADDRESS 0x8u
#define COMMON_IP_SDIF_STATUS_BYTE_ADDRESS 0x8u
/* Register: common_ip.sdif                                                */
#define COMMON_IP_SDIF_ADDRESS 0xcu
#define COMMON_IP_SDIF_BYTE_ADDRESS 0xcu
/* Register: common_ip.sdif_halt                                           */
#define COMMON_IP_SDIF_HALT_ADDRESS 0x10u
#define COMMON_IP_SDIF_HALT_BYTE_ADDRESS 0x10u
/* Register: common_ip.sdif_ctrl                                           */
#define COMMON_IP_SDIF_CTRL_ADDRESS 0x14u
#define COMMON_IP_SDIF_CTRL_BYTE_ADDRESS 0x14u
/* Register: common_ip.smpl_ctrl                                           */
#define COMMON_IP_SMPL_CTRL_ADDRESS 0x20u
#define COMMON_IP_SMPL_CTRL_BYTE_ADDRESS 0x20u
/* Register: common_ip.smpl_halt                                           */
#define COMMON_IP_SMPL_HALT_ADDRESS 0x24u
#define COMMON_IP_SMPL_HALT_BYTE_ADDRESS 0x24u
/* Register: common_ip.smpl_cnt                                            */
#define COMMON_IP_SMPL_CNT_ADDRESS 0x28u
#define COMMON_IP_SMPL_CNT_BYTE_ADDRESS 0x28u

/* Address Space for Addressmap: ptvc                                      */
/* Source filename: pvtc.csr, line: 317                                    */
/* Addressmap: ptvc.common                                                 */
#define PTVC_COMMON_ADDRESS 0x0u
#define PTVC_COMMON_BYTE_ADDRESS 0x0u
/* Register: ptvc.common.pvt_comp_id                                       */
#define PTVC_COMMON_PVT_COMP_ID_ADDRESS 0x0u
#define PTVC_COMMON_PVT_COMP_ID_BYTE_ADDRESS 0x0u
/* Register: ptvc.common.pvt_ip_cfg                                        */
#define PTVC_COMMON_PVT_IP_CFG_ADDRESS 0x4u
#define PTVC_COMMON_PVT_IP_CFG_BYTE_ADDRESS 0x4u
/* Register: ptvc.common.pvt_ip_num                                        */
#define PTVC_COMMON_PVT_IP_NUM_ADDRESS 0x8u
#define PTVC_COMMON_PVT_IP_NUM_BYTE_ADDRESS 0x8u
/* Register: ptvc.common.pvt_tm_scratch                                    */
#define PTVC_COMMON_PVT_TM_SCRATCH_ADDRESS 0xcu
#define PTVC_COMMON_PVT_TM_SCRATCH_BYTE_ADDRESS 0xcu
/* Register: ptvc.common.pvt_reg_lock                                      */
#define PTVC_COMMON_PVT_REG_LOCK_ADDRESS 0x10u
#define PTVC_COMMON_PVT_REG_LOCK_BYTE_ADDRESS 0x10u
/* Register: ptvc.common.pvt_reg_lock_status                               */
#define PTVC_COMMON_PVT_REG_LOCK_STATUS_ADDRESS 0x14u
#define PTVC_COMMON_PVT_REG_LOCK_STATUS_BYTE_ADDRESS 0x14u
/* Register: ptvc.common.pvt_tam_status                                    */
#define PTVC_COMMON_PVT_TAM_STATUS_ADDRESS 0x18u
#define PTVC_COMMON_PVT_TAM_STATUS_BYTE_ADDRESS 0x18u
/* Register: ptvc.common.pvt_tam_clear                                     */
#define PTVC_COMMON_PVT_TAM_CLEAR_ADDRESS 0x1cu
#define PTVC_COMMON_PVT_TAM_CLEAR_BYTE_ADDRESS 0x1cu
/* Register: ptvc.common.pvt_tmr_ctrl                                      */
#define PTVC_COMMON_PVT_TMR_CTRL_ADDRESS 0x20u
#define PTVC_COMMON_PVT_TMR_CTRL_BYTE_ADDRESS 0x20u
/* Register: ptvc.common.pvt_tmr_status                                    */
#define PTVC_COMMON_PVT_TMR_STATUS_ADDRESS 0x24u
#define PTVC_COMMON_PVT_TMR_STATUS_BYTE_ADDRESS 0x24u
/* Register: ptvc.common.pvt_tmr_irq_clear                                 */
#define PTVC_COMMON_PVT_TMR_IRQ_CLEAR_ADDRESS 0x28u
#define PTVC_COMMON_PVT_TMR_IRQ_CLEAR_BYTE_ADDRESS 0x28u
/* Register: ptvc.common.pvt_tmr_irq_test                                  */
#define PTVC_COMMON_PVT_TMR_IRQ_TEST_ADDRESS 0x2cu
#define PTVC_COMMON_PVT_TMR_IRQ_TEST_BYTE_ADDRESS 0x2cu
/* Addressmap: ptvc.irq                                                    */
#define PTVC_IRQ_ADDRESS 0x40u
#define PTVC_IRQ_BYTE_ADDRESS 0x40u
/* Register: ptvc.irq.irq_en                                               */
#define PTVC_IRQ_IRQ_EN_ADDRESS 0x40u
#define PTVC_IRQ_IRQ_EN_BYTE_ADDRESS 0x40u
/* Register: ptvc.irq.irq_tr_mask                                          */
#define PTVC_IRQ_IRQ_TR_MASK_ADDRESS 0x50u
#define PTVC_IRQ_IRQ_TR_MASK_BYTE_ADDRESS 0x50u
/* Register: ptvc.irq.irq_ts_mask                                          */
#define PTVC_IRQ_IRQ_TS_MASK_ADDRESS 0x54u
#define PTVC_IRQ_IRQ_TS_MASK_BYTE_ADDRESS 0x54u
/* Register: ptvc.irq.irq_vm_mask                                          */
#define PTVC_IRQ_IRQ_VM_MASK_ADDRESS 0x58u
#define PTVC_IRQ_IRQ_VM_MASK_BYTE_ADDRESS 0x58u
/* Register: ptvc.irq.irq_pd_mask                                          */
#define PTVC_IRQ_IRQ_PD_MASK_ADDRESS 0x5cu
#define PTVC_IRQ_IRQ_PD_MASK_BYTE_ADDRESS 0x5cu
/* Register: ptvc.irq.irq_tr_status                                        */
#define PTVC_IRQ_IRQ_TR_STATUS_ADDRESS 0x60u
#define PTVC_IRQ_IRQ_TR_STATUS_BYTE_ADDRESS 0x60u
/* Register: ptvc.irq.irq_ts_status                                        */
#define PTVC_IRQ_IRQ_TS_STATUS_ADDRESS 0x64u
#define PTVC_IRQ_IRQ_TS_STATUS_BYTE_ADDRESS 0x64u
/* Register: ptvc.irq.irq_vm_status                                        */
#define PTVC_IRQ_IRQ_VM_STATUS_ADDRESS 0x68u
#define PTVC_IRQ_IRQ_VM_STATUS_BYTE_ADDRESS 0x68u
/* Register: ptvc.irq.irq_pd_status                                        */
#define PTVC_IRQ_IRQ_PD_STATUS_ADDRESS 0x6cu
#define PTVC_IRQ_IRQ_PD_STATUS_BYTE_ADDRESS 0x6cu
/* Register: ptvc.irq.irq_tr_raw_status                                    */
#define PTVC_IRQ_IRQ_TR_RAW_STATUS_ADDRESS 0x70u
#define PTVC_IRQ_IRQ_TR_RAW_STATUS_BYTE_ADDRESS 0x70u
/* Register: ptvc.irq.irq_ts_raw_status                                    */
#define PTVC_IRQ_IRQ_TS_RAW_STATUS_ADDRESS 0x74u
#define PTVC_IRQ_IRQ_TS_RAW_STATUS_BYTE_ADDRESS 0x74u
/* Register: ptvc.irq.irq_vm_raw_status                                    */
#define PTVC_IRQ_IRQ_VM_RAW_STATUS_ADDRESS 0x78u
#define PTVC_IRQ_IRQ_VM_RAW_STATUS_BYTE_ADDRESS 0x78u
/* Register: ptvc.irq.irq_pd_raw_status                                    */
#define PTVC_IRQ_IRQ_PD_RAW_STATUS_ADDRESS 0x7cu
#define PTVC_IRQ_IRQ_PD_RAW_STATUS_BYTE_ADDRESS 0x7cu


/* ####################################################################### */
/*        TEMPLATE MACROS                                                  */
/* ####################################################################### */

/* Addressmap type: common_ip                                              */
/* Addressmap template: common_ip                                          */
/* Source filename: pvtc.csr, line: 278                                    */
#define COMMON_IP_SIZE 0x2cu
#define COMMON_IP_BYTE_SIZE 0x2cu
/* Register member: common_ip.clk_synth                                    */
/* Register type referenced: common_ip::clk_synth                          */
/* Register template referenced: common_ip::clk_synth                      */
#define COMMON_IP_CLK_SYNTH_OFFSET 0x0u
#define COMMON_IP_CLK_SYNTH_BYTE_OFFSET 0x0u
#define COMMON_IP_CLK_SYNTH_READ_ACCESS 1u
#define COMMON_IP_CLK_SYNTH_WRITE_ACCESS 1u
#define COMMON_IP_CLK_SYNTH_READ_MASK 0xfffffffful
#define COMMON_IP_CLK_SYNTH_WRITE_MASK 0xfffffffful
/* Register member: common_ip.sdif_disable                                 */
/* Register type referenced: common_ip::sdif_disable                       */
/* Register template referenced: common_ip::sdif_disable                   */
#define COMMON_IP_SDIF_DISABLE_OFFSET 0x4u
#define COMMON_IP_SDIF_DISABLE_BYTE_OFFSET 0x4u
#define COMMON_IP_SDIF_DISABLE_READ_ACCESS 1u
#define COMMON_IP_SDIF_DISABLE_WRITE_ACCESS 1u
#define COMMON_IP_SDIF_DISABLE_READ_MASK 0xfffffffful
#define COMMON_IP_SDIF_DISABLE_WRITE_MASK 0xfffffffful
/* Register member: common_ip.sdif_status                                  */
/* Register type referenced: common_ip::sdif_status                        */
/* Register template referenced: common_ip::sdif_status                    */
#define COMMON_IP_SDIF_STATUS_OFFSET 0x8u
#define COMMON_IP_SDIF_STATUS_BYTE_OFFSET 0x8u
#define COMMON_IP_SDIF_STATUS_READ_ACCESS 1u
#define COMMON_IP_SDIF_STATUS_WRITE_ACCESS 1u
#define COMMON_IP_SDIF_STATUS_READ_MASK 0xfffffffful
#define COMMON_IP_SDIF_STATUS_WRITE_MASK 0xfffffffful
/* Register member: common_ip.sdif                                         */
/* Register type referenced: common_ip::sdif                               */
/* Register template referenced: common_ip::sdif                           */
#define COMMON_IP_SDIF_OFFSET 0xcu
#define COMMON_IP_SDIF_BYTE_OFFSET 0xcu
#define COMMON_IP_SDIF_READ_ACCESS 1u
#define COMMON_IP_SDIF_WRITE_ACCESS 1u
#define COMMON_IP_SDIF_READ_MASK 0xfffffffful
#define COMMON_IP_SDIF_WRITE_MASK 0xfffffffful
/* Register member: common_ip.sdif_halt                                    */
/* Register type referenced: common_ip::sdif_halt                          */
/* Register template referenced: common_ip::sdif_halt                      */
#define COMMON_IP_SDIF_HALT_OFFSET 0x10u
#define COMMON_IP_SDIF_HALT_BYTE_OFFSET 0x10u
#define COMMON_IP_SDIF_HALT_READ_ACCESS 1u
#define COMMON_IP_SDIF_HALT_WRITE_ACCESS 1u
#define COMMON_IP_SDIF_HALT_READ_MASK 0xfffffffful
#define COMMON_IP_SDIF_HALT_WRITE_MASK 0xfffffffful
/* Register member: common_ip.sdif_ctrl                                    */
/* Register type referenced: common_ip::sdif_ctrl                          */
/* Register template referenced: common_ip::sdif_ctrl                      */
#define COMMON_IP_SDIF_CTRL_OFFSET 0x14u
#define COMMON_IP_SDIF_CTRL_BYTE_OFFSET 0x14u
#define COMMON_IP_SDIF_CTRL_READ_ACCESS 1u
#define COMMON_IP_SDIF_CTRL_WRITE_ACCESS 1u
#define COMMON_IP_SDIF_CTRL_READ_MASK 0xfffffffful
#define COMMON_IP_SDIF_CTRL_WRITE_MASK 0xfffffffful
/* Register member: common_ip.smpl_ctrl                                    */
/* Register type referenced: common_ip::smpl_ctrl                          */
/* Register template referenced: common_ip::smpl_ctrl                      */
#define COMMON_IP_SMPL_CTRL_OFFSET 0x20u
#define COMMON_IP_SMPL_CTRL_BYTE_OFFSET 0x20u
#define COMMON_IP_SMPL_CTRL_READ_ACCESS 1u
#define COMMON_IP_SMPL_CTRL_WRITE_ACCESS 1u
#define COMMON_IP_SMPL_CTRL_READ_MASK 0xfffffffful
#define COMMON_IP_SMPL_CTRL_WRITE_MASK 0xfffffffful
/* Register member: common_ip.smpl_halt                                    */
/* Register type referenced: common_ip::smpl_halt                          */
/* Register template referenced: common_ip::smpl_halt                      */
#define COMMON_IP_SMPL_HALT_OFFSET 0x24u
#define COMMON_IP_SMPL_HALT_BYTE_OFFSET 0x24u
#define COMMON_IP_SMPL_HALT_READ_ACCESS 1u
#define COMMON_IP_SMPL_HALT_WRITE_ACCESS 1u
#define COMMON_IP_SMPL_HALT_READ_MASK 0xfffffffful
#define COMMON_IP_SMPL_HALT_WRITE_MASK 0xfffffffful
/* Register member: common_ip.smpl_cnt                                     */
/* Register type referenced: common_ip::smpl_cnt                           */
/* Register template referenced: common_ip::smpl_cnt                       */
#define COMMON_IP_SMPL_CNT_OFFSET 0x28u
#define COMMON_IP_SMPL_CNT_BYTE_OFFSET 0x28u
#define COMMON_IP_SMPL_CNT_READ_ACCESS 1u
#define COMMON_IP_SMPL_CNT_WRITE_ACCESS 1u
#define COMMON_IP_SMPL_CNT_READ_MASK 0xfffffffful
#define COMMON_IP_SMPL_CNT_WRITE_MASK 0xfffffffful

/* Register type: common_ip::clk_synth                                     */
/* Register template: common_ip::clk_synth                                 */
/* Source filename: pvtc.csr, line: 279                                    */
/* Field member: common_ip::clk_synth.clk_synth                            */
/* Source filename: pvtc.csr, line: 279                                    */
#define COMMON_IP_CLK_SYNTH_CLK_SYNTH_MSB 31u
#define COMMON_IP_CLK_SYNTH_CLK_SYNTH_LSB 0u
#define COMMON_IP_CLK_SYNTH_CLK_SYNTH_WIDTH 32u
#define COMMON_IP_CLK_SYNTH_CLK_SYNTH_READ_ACCESS 1u
#define COMMON_IP_CLK_SYNTH_CLK_SYNTH_WRITE_ACCESS 1u
#define COMMON_IP_CLK_SYNTH_CLK_SYNTH_FIELD_MASK 0xfffffffful
#define COMMON_IP_CLK_SYNTH_CLK_SYNTH_GET(x) ((x) & 0xfffffffful)
#define COMMON_IP_CLK_SYNTH_CLK_SYNTH_SET(x) ((x) & 0xfffffffful)
#define COMMON_IP_CLK_SYNTH_CLK_SYNTH_MODIFY(r, x) ((x) & 0xfffffffful)

/* Register type: common_ip::sdif_disable                                  */
/* Register template: common_ip::sdif_disable                              */
/* Source filename: pvtc.csr, line: 282                                    */
/* Field member: common_ip::sdif_disable.sdif_disable                      */
/* Source filename: pvtc.csr, line: 282                                    */
#define COMMON_IP_SDIF_DISABLE_SDIF_DISABLE_MSB 31u
#define COMMON_IP_SDIF_DISABLE_SDIF_DISABLE_LSB 0u
#define COMMON_IP_SDIF_DISABLE_SDIF_DISABLE_WIDTH 32u
#define COMMON_IP_SDIF_DISABLE_SDIF_DISABLE_READ_ACCESS 1u
#define COMMON_IP_SDIF_DISABLE_SDIF_DISABLE_WRITE_ACCESS 1u
#define COMMON_IP_SDIF_DISABLE_SDIF_DISABLE_FIELD_MASK 0xfffffffful
#define COMMON_IP_SDIF_DISABLE_SDIF_DISABLE_GET(x) ((x) & 0xfffffffful)
#define COMMON_IP_SDIF_DISABLE_SDIF_DISABLE_SET(x) ((x) & 0xfffffffful)
#define COMMON_IP_SDIF_DISABLE_SDIF_DISABLE_MODIFY(r, x) ((x) & 0xfffffffful)

/* Register type: common_ip::sdif_status                                   */
/* Register template: common_ip::sdif_status                               */
/* Source filename: pvtc.csr, line: 285                                    */
/* Field member: common_ip::sdif_status.sdif_status                        */
/* Source filename: pvtc.csr, line: 285                                    */
#define COMMON_IP_SDIF_STATUS_SDIF_STATUS_MSB 31u
#define COMMON_IP_SDIF_STATUS_SDIF_STATUS_LSB 0u
#define COMMON_IP_SDIF_STATUS_SDIF_STATUS_WIDTH 32u
#define COMMON_IP_SDIF_STATUS_SDIF_STATUS_READ_ACCESS 1u
#define COMMON_IP_SDIF_STATUS_SDIF_STATUS_WRITE_ACCESS 1u
#define COMMON_IP_SDIF_STATUS_SDIF_STATUS_FIELD_MASK 0xfffffffful
#define COMMON_IP_SDIF_STATUS_SDIF_STATUS_GET(x) ((x) & 0xfffffffful)
#define COMMON_IP_SDIF_STATUS_SDIF_STATUS_SET(x) ((x) & 0xfffffffful)
#define COMMON_IP_SDIF_STATUS_SDIF_STATUS_MODIFY(r, x) ((x) & 0xfffffffful)

/* Register type: common_ip::sdif                                          */
/* Register template: common_ip::sdif                                      */
/* Source filename: pvtc.csr, line: 288                                    */
/* Field member: common_ip::sdif.sdif                                      */
/* Source filename: pvtc.csr, line: 288                                    */
#define COMMON_IP_SDIF_SDIF_MSB 31u
#define COMMON_IP_SDIF_SDIF_LSB 0u
#define COMMON_IP_SDIF_SDIF_WIDTH 32u
#define COMMON_IP_SDIF_SDIF_READ_ACCESS 1u
#define COMMON_IP_SDIF_SDIF_WRITE_ACCESS 1u
#define COMMON_IP_SDIF_SDIF_FIELD_MASK 0xfffffffful
#define COMMON_IP_SDIF_SDIF_GET(x) ((x) & 0xfffffffful)
#define COMMON_IP_SDIF_SDIF_SET(x) ((x) & 0xfffffffful)
#define COMMON_IP_SDIF_SDIF_MODIFY(r, x) ((x) & 0xfffffffful)

/* Register type: common_ip::sdif_halt                                     */
/* Register template: common_ip::sdif_halt                                 */
/* Source filename: pvtc.csr, line: 291                                    */
/* Field member: common_ip::sdif_halt.sdif_halt                            */
/* Source filename: pvtc.csr, line: 291                                    */
#define COMMON_IP_SDIF_HALT_SDIF_HALT_MSB 31u
#define COMMON_IP_SDIF_HALT_SDIF_HALT_LSB 0u
#define COMMON_IP_SDIF_HALT_SDIF_HALT_WIDTH 32u
#define COMMON_IP_SDIF_HALT_SDIF_HALT_READ_ACCESS 1u
#define COMMON_IP_SDIF_HALT_SDIF_HALT_WRITE_ACCESS 1u
#define COMMON_IP_SDIF_HALT_SDIF_HALT_FIELD_MASK 0xfffffffful
#define COMMON_IP_SDIF_HALT_SDIF_HALT_GET(x) ((x) & 0xfffffffful)
#define COMMON_IP_SDIF_HALT_SDIF_HALT_SET(x) ((x) & 0xfffffffful)
#define COMMON_IP_SDIF_HALT_SDIF_HALT_MODIFY(r, x) ((x) & 0xfffffffful)

/* Register type: common_ip::sdif_ctrl                                     */
/* Register template: common_ip::sdif_ctrl                                 */
/* Source filename: pvtc.csr, line: 294                                    */
/* Field member: common_ip::sdif_ctrl.sdif_ctrl                            */
/* Source filename: pvtc.csr, line: 294                                    */
#define COMMON_IP_SDIF_CTRL_SDIF_CTRL_MSB 31u
#define COMMON_IP_SDIF_CTRL_SDIF_CTRL_LSB 0u
#define COMMON_IP_SDIF_CTRL_SDIF_CTRL_WIDTH 32u
#define COMMON_IP_SDIF_CTRL_SDIF_CTRL_READ_ACCESS 1u
#define COMMON_IP_SDIF_CTRL_SDIF_CTRL_WRITE_ACCESS 1u
#define COMMON_IP_SDIF_CTRL_SDIF_CTRL_FIELD_MASK 0xfffffffful
#define COMMON_IP_SDIF_CTRL_SDIF_CTRL_GET(x) ((x) & 0xfffffffful)
#define COMMON_IP_SDIF_CTRL_SDIF_CTRL_SET(x) ((x) & 0xfffffffful)
#define COMMON_IP_SDIF_CTRL_SDIF_CTRL_MODIFY(r, x) ((x) & 0xfffffffful)

/* Register type: common_ip::smpl_ctrl                                     */
/* Register template: common_ip::smpl_ctrl                                 */
/* Source filename: pvtc.csr, line: 297                                    */
/* Field member: common_ip::smpl_ctrl.smpl_ctrl                            */
/* Source filename: pvtc.csr, line: 297                                    */
#define COMMON_IP_SMPL_CTRL_SMPL_CTRL_MSB 31u
#define COMMON_IP_SMPL_CTRL_SMPL_CTRL_LSB 0u
#define COMMON_IP_SMPL_CTRL_SMPL_CTRL_WIDTH 32u
#define COMMON_IP_SMPL_CTRL_SMPL_CTRL_READ_ACCESS 1u
#define COMMON_IP_SMPL_CTRL_SMPL_CTRL_WRITE_ACCESS 1u
#define COMMON_IP_SMPL_CTRL_SMPL_CTRL_FIELD_MASK 0xfffffffful
#define COMMON_IP_SMPL_CTRL_SMPL_CTRL_GET(x) ((x) & 0xfffffffful)
#define COMMON_IP_SMPL_CTRL_SMPL_CTRL_SET(x) ((x) & 0xfffffffful)
#define COMMON_IP_SMPL_CTRL_SMPL_CTRL_MODIFY(r, x) ((x) & 0xfffffffful)

/* Register type: common_ip::smpl_halt                                     */
/* Register template: common_ip::smpl_halt                                 */
/* Source filename: pvtc.csr, line: 300                                    */
/* Field member: common_ip::smpl_halt.smpl_halt                            */
/* Source filename: pvtc.csr, line: 300                                    */
#define COMMON_IP_SMPL_HALT_SMPL_HALT_MSB 31u
#define COMMON_IP_SMPL_HALT_SMPL_HALT_LSB 0u
#define COMMON_IP_SMPL_HALT_SMPL_HALT_WIDTH 32u
#define COMMON_IP_SMPL_HALT_SMPL_HALT_READ_ACCESS 1u
#define COMMON_IP_SMPL_HALT_SMPL_HALT_WRITE_ACCESS 1u
#define COMMON_IP_SMPL_HALT_SMPL_HALT_FIELD_MASK 0xfffffffful
#define COMMON_IP_SMPL_HALT_SMPL_HALT_GET(x) ((x) & 0xfffffffful)
#define COMMON_IP_SMPL_HALT_SMPL_HALT_SET(x) ((x) & 0xfffffffful)
#define COMMON_IP_SMPL_HALT_SMPL_HALT_MODIFY(r, x) ((x) & 0xfffffffful)

/* Register type: common_ip::smpl_cnt                                      */
/* Register template: common_ip::smpl_cnt                                  */
/* Source filename: pvtc.csr, line: 303                                    */
/* Field member: common_ip::smpl_cnt.smpl_cnt                              */
/* Source filename: pvtc.csr, line: 303                                    */
#define COMMON_IP_SMPL_CNT_SMPL_CNT_MSB 31u
#define COMMON_IP_SMPL_CNT_SMPL_CNT_LSB 0u
#define COMMON_IP_SMPL_CNT_SMPL_CNT_WIDTH 32u
#define COMMON_IP_SMPL_CNT_SMPL_CNT_READ_ACCESS 1u
#define COMMON_IP_SMPL_CNT_SMPL_CNT_WRITE_ACCESS 1u
#define COMMON_IP_SMPL_CNT_SMPL_CNT_FIELD_MASK 0xfffffffful
#define COMMON_IP_SMPL_CNT_SMPL_CNT_GET(x) ((x) & 0xfffffffful)
#define COMMON_IP_SMPL_CNT_SMPL_CNT_SET(x) ((x) & 0xfffffffful)
#define COMMON_IP_SMPL_CNT_SMPL_CNT_MODIFY(r, x) ((x) & 0xfffffffful)

/* Addressmap type: ptvc                                                   */
/* Addressmap template: ptvc                                               */
/* Source filename: pvtc.csr, line: 311                                    */
#define PTVC_SIZE 0x80u
#define PTVC_BYTE_SIZE 0x80u
/* Addressmap member: ptvc.common                                          */
/* Addressmap type referenced: common                                      */
/* Addressmap template referenced: common                                  */
#define PTVC_COMMON_OFFSET 0x0u
#define PTVC_COMMON_BYTE_OFFSET 0x0u
#define PTVC_COMMON_READ_ACCESS 1u
#define PTVC_COMMON_WRITE_ACCESS 1u
/* Addressmap member: ptvc.irq                                             */
/* Addressmap type referenced: irq                                         */
/* Addressmap template referenced: irq                                     */
#define PTVC_IRQ_OFFSET 0x40u
#define PTVC_IRQ_BYTE_OFFSET 0x40u
#define PTVC_IRQ_READ_ACCESS 1u
#define PTVC_IRQ_WRITE_ACCESS 1u

/* Addressmap type: common                                                 */
/* Addressmap template: common                                             */
/* Source filename: pvtc.csr, line: 15                                     */
#define COMMON_SIZE 0x30u
#define COMMON_BYTE_SIZE 0x30u
/* Register member: common.pvt_comp_id                                     */
/* Register type referenced: common::pvt_comp_id                           */
/* Register template referenced: common::pvt_comp_id                       */
#define COMMON_PVT_COMP_ID_OFFSET 0x0u
#define COMMON_PVT_COMP_ID_BYTE_OFFSET 0x0u
#define COMMON_PVT_COMP_ID_READ_ACCESS 1u
#define COMMON_PVT_COMP_ID_WRITE_ACCESS 0u
#define COMMON_PVT_COMP_ID_RESET_VALUE 0x9b487062ul
#define COMMON_PVT_COMP_ID_RESET_MASK 0xfffffffful
#define COMMON_PVT_COMP_ID_READ_MASK 0xfffffffful
#define COMMON_PVT_COMP_ID_WRITE_MASK 0x00000000ul
/* Register member: common.pvt_ip_cfg                                      */
/* Register type referenced: common::pvt_ip_cfg                            */
/* Register template referenced: common::pvt_ip_cfg                        */
#define COMMON_PVT_IP_CFG_OFFSET 0x4u
#define COMMON_PVT_IP_CFG_BYTE_OFFSET 0x4u
#define COMMON_PVT_IP_CFG_READ_ACCESS 1u
#define COMMON_PVT_IP_CFG_WRITE_ACCESS 0u
#define COMMON_PVT_IP_CFG_RESET_VALUE 0x10020808ul
#define COMMON_PVT_IP_CFG_RESET_MASK 0xfffffffful
#define COMMON_PVT_IP_CFG_READ_MASK 0xfffffffful
#define COMMON_PVT_IP_CFG_WRITE_MASK 0x00000000ul
/* Register member: common.pvt_ip_num                                      */
/* Register type referenced: common::pvt_ip_num                            */
/* Register template referenced: common::pvt_ip_num                        */
#define COMMON_PVT_IP_NUM_OFFSET 0x8u
#define COMMON_PVT_IP_NUM_BYTE_OFFSET 0x8u
#define COMMON_PVT_IP_NUM_READ_ACCESS 1u
#define COMMON_PVT_IP_NUM_WRITE_ACCESS 1u
#define COMMON_PVT_IP_NUM_RESET_VALUE 0x00000000ul
#define COMMON_PVT_IP_NUM_RESET_MASK 0xfffffffful
#define COMMON_PVT_IP_NUM_READ_MASK 0xfffffffful
#define COMMON_PVT_IP_NUM_WRITE_MASK 0xfffffffful
/* Register member: common.pvt_tm_scratch                                  */
/* Register type referenced: common::pvt_tm_scratch                        */
/* Register template referenced: common::pvt_tm_scratch                    */
#define COMMON_PVT_TM_SCRATCH_OFFSET 0xcu
#define COMMON_PVT_TM_SCRATCH_BYTE_OFFSET 0xcu
#define COMMON_PVT_TM_SCRATCH_READ_ACCESS 1u
#define COMMON_PVT_TM_SCRATCH_WRITE_ACCESS 1u
#define COMMON_PVT_TM_SCRATCH_RESET_VALUE 0x00000000ul
#define COMMON_PVT_TM_SCRATCH_RESET_MASK 0xfffffffful
#define COMMON_PVT_TM_SCRATCH_READ_MASK 0xfffffffful
#define COMMON_PVT_TM_SCRATCH_WRITE_MASK 0xfffffffful
/* Register member: common.pvt_reg_lock                                    */
/* Register type referenced: common::pvt_reg_lock                          */
/* Register template referenced: common::pvt_reg_lock                      */
#define COMMON_PVT_REG_LOCK_OFFSET 0x10u
#define COMMON_PVT_REG_LOCK_BYTE_OFFSET 0x10u
#define COMMON_PVT_REG_LOCK_READ_ACCESS 1u
#define COMMON_PVT_REG_LOCK_WRITE_ACCESS 1u
#define COMMON_PVT_REG_LOCK_RESET_VALUE 0x00000000ul
#define COMMON_PVT_REG_LOCK_RESET_MASK 0xfffffffful
#define COMMON_PVT_REG_LOCK_READ_MASK 0xfffffffful
#define COMMON_PVT_REG_LOCK_WRITE_MASK 0xfffffffful
/* Register member: common.pvt_reg_lock_status                             */
/* Register type referenced: common::pvt_reg_lock_status                   */
/* Register template referenced: common::pvt_reg_lock_status               */
#define COMMON_PVT_REG_LOCK_STATUS_OFFSET 0x14u
#define COMMON_PVT_REG_LOCK_STATUS_BYTE_OFFSET 0x14u
#define COMMON_PVT_REG_LOCK_STATUS_READ_ACCESS 1u
#define COMMON_PVT_REG_LOCK_STATUS_WRITE_ACCESS 0u
#define COMMON_PVT_REG_LOCK_STATUS_RESET_VALUE 0x00000000ul
#define COMMON_PVT_REG_LOCK_STATUS_RESET_MASK 0xfffffffful
#define COMMON_PVT_REG_LOCK_STATUS_READ_MASK 0xfffffffful
#define COMMON_PVT_REG_LOCK_STATUS_WRITE_MASK 0x00000000ul
/* Register member: common.pvt_tam_status                                  */
/* Register type referenced: common::pvt_tam_status                        */
/* Register template referenced: common::pvt_tam_status                    */
#define COMMON_PVT_TAM_STATUS_OFFSET 0x18u
#define COMMON_PVT_TAM_STATUS_BYTE_OFFSET 0x18u
#define COMMON_PVT_TAM_STATUS_READ_ACCESS 1u
#define COMMON_PVT_TAM_STATUS_WRITE_ACCESS 0u
#define COMMON_PVT_TAM_STATUS_RESET_VALUE 0x00000000ul
#define COMMON_PVT_TAM_STATUS_RESET_MASK 0xfffffffful
#define COMMON_PVT_TAM_STATUS_READ_MASK 0xfffffffful
#define COMMON_PVT_TAM_STATUS_WRITE_MASK 0x00000000ul
/* Register member: common.pvt_tam_clear                                   */
/* Register type referenced: common::pvt_tam_clear                         */
/* Register template referenced: common::pvt_tam_clear                     */
#define COMMON_PVT_TAM_CLEAR_OFFSET 0x1cu
#define COMMON_PVT_TAM_CLEAR_BYTE_OFFSET 0x1cu
#define COMMON_PVT_TAM_CLEAR_READ_ACCESS 0u
#define COMMON_PVT_TAM_CLEAR_WRITE_ACCESS 1u
#define COMMON_PVT_TAM_CLEAR_RESET_VALUE 0x00000000ul
#define COMMON_PVT_TAM_CLEAR_RESET_MASK 0xfffffffful
#define COMMON_PVT_TAM_CLEAR_READ_MASK 0x00000000ul
#define COMMON_PVT_TAM_CLEAR_WRITE_MASK 0x00000001ul
/* Register member: common.pvt_tmr_ctrl                                    */
/* Register type referenced: common::pvt_tmr_ctrl                          */
/* Register template referenced: common::pvt_tmr_ctrl                      */
#define COMMON_PVT_TMR_CTRL_OFFSET 0x20u
#define COMMON_PVT_TMR_CTRL_BYTE_OFFSET 0x20u
#define COMMON_PVT_TMR_CTRL_READ_ACCESS 1u
#define COMMON_PVT_TMR_CTRL_WRITE_ACCESS 1u
#define COMMON_PVT_TMR_CTRL_RESET_VALUE 0x00000000ul
#define COMMON_PVT_TMR_CTRL_RESET_MASK 0xfffffffful
#define COMMON_PVT_TMR_CTRL_READ_MASK 0xfffffffful
#define COMMON_PVT_TMR_CTRL_WRITE_MASK 0x0001fffful
/* Register member: common.pvt_tmr_status                                  */
/* Register type referenced: common::pvt_tmr_status                        */
/* Register template referenced: common::pvt_tmr_status                    */
#define COMMON_PVT_TMR_STATUS_OFFSET 0x24u
#define COMMON_PVT_TMR_STATUS_BYTE_OFFSET 0x24u
#define COMMON_PVT_TMR_STATUS_READ_ACCESS 1u
#define COMMON_PVT_TMR_STATUS_WRITE_ACCESS 1u
#define COMMON_PVT_TMR_STATUS_RESET_VALUE 0x00000000ul
#define COMMON_PVT_TMR_STATUS_RESET_MASK 0xfffffffful
#define COMMON_PVT_TMR_STATUS_READ_MASK 0xfffffffful
#define COMMON_PVT_TMR_STATUS_WRITE_MASK 0x00000003ul
/* Register member: common.pvt_tmr_irq_clear                               */
/* Register type referenced: common::pvt_tmr_irq_clear                     */
/* Register template referenced: common::pvt_tmr_irq_clear                 */
#define COMMON_PVT_TMR_IRQ_CLEAR_OFFSET 0x28u
#define COMMON_PVT_TMR_IRQ_CLEAR_BYTE_OFFSET 0x28u
#define COMMON_PVT_TMR_IRQ_CLEAR_READ_ACCESS 0u
#define COMMON_PVT_TMR_IRQ_CLEAR_WRITE_ACCESS 1u
#define COMMON_PVT_TMR_IRQ_CLEAR_RESET_VALUE 0x00000000ul
#define COMMON_PVT_TMR_IRQ_CLEAR_RESET_MASK 0xfffffffful
#define COMMON_PVT_TMR_IRQ_CLEAR_READ_MASK 0x00000000ul
#define COMMON_PVT_TMR_IRQ_CLEAR_WRITE_MASK 0x00000001ul
/* Register member: common.pvt_tmr_irq_test                                */
/* Register type referenced: common::pvt_tmr_irq_test                      */
/* Register template referenced: common::pvt_tmr_irq_test                  */
#define COMMON_PVT_TMR_IRQ_TEST_OFFSET 0x2cu
#define COMMON_PVT_TMR_IRQ_TEST_BYTE_OFFSET 0x2cu
#define COMMON_PVT_TMR_IRQ_TEST_READ_ACCESS 1u
#define COMMON_PVT_TMR_IRQ_TEST_WRITE_ACCESS 1u
#define COMMON_PVT_TMR_IRQ_TEST_RESET_VALUE 0x00000000ul
#define COMMON_PVT_TMR_IRQ_TEST_RESET_MASK 0xfffffffful
#define COMMON_PVT_TMR_IRQ_TEST_READ_MASK 0xfffffffful
#define COMMON_PVT_TMR_IRQ_TEST_WRITE_MASK 0x00000001ul

/* Register type: common::pvt_comp_id                                      */
/* Register template: common::pvt_comp_id                                  */
/* Source filename: pvtc.csr, line: 20                                     */
/* Field member: common::pvt_comp_id.moortec_id                            */
/* Source filename: pvtc.csr, line: 21                                     */
#define COMMON_PVT_COMP_ID_MOORTEC_ID_MSB 31u
#define COMMON_PVT_COMP_ID_MOORTEC_ID_LSB 18u
#define COMMON_PVT_COMP_ID_MOORTEC_ID_WIDTH 14u
#define COMMON_PVT_COMP_ID_MOORTEC_ID_READ_ACCESS 1u
#define COMMON_PVT_COMP_ID_MOORTEC_ID_WRITE_ACCESS 0u
#define COMMON_PVT_COMP_ID_MOORTEC_ID_RESET 0x26d2u
#define COMMON_PVT_COMP_ID_MOORTEC_ID_FIELD_MASK 0xfffc0000ul
#define COMMON_PVT_COMP_ID_MOORTEC_ID_GET(x) (((x) & 0xfffc0000ul) >> 18)
#define COMMON_PVT_COMP_ID_MOORTEC_ID_SET(x) (((x) << 18) & 0xfffc0000ul)
#define COMMON_PVT_COMP_ID_MOORTEC_ID_MODIFY(r, x) \
   ((((x) << 18) & 0xfffc0000ul) | ((r) & 0x0003fffful))
/* Field member: common::pvt_comp_id.component_id                          */
/* Source filename: pvtc.csr, line: 26                                     */
#define COMMON_PVT_COMP_ID_COMPONENT_ID_MSB 17u
#define COMMON_PVT_COMP_ID_COMPONENT_ID_LSB 12u
#define COMMON_PVT_COMP_ID_COMPONENT_ID_WIDTH 6u
#define COMMON_PVT_COMP_ID_COMPONENT_ID_READ_ACCESS 1u
#define COMMON_PVT_COMP_ID_COMPONENT_ID_WRITE_ACCESS 0u
#define COMMON_PVT_COMP_ID_COMPONENT_ID_RESET 0x07u
#define COMMON_PVT_COMP_ID_COMPONENT_ID_FIELD_MASK 0x0003f000ul
#define COMMON_PVT_COMP_ID_COMPONENT_ID_GET(x) (((x) & 0x0003f000ul) >> 12)
#define COMMON_PVT_COMP_ID_COMPONENT_ID_SET(x) (((x) << 12) & 0x0003f000ul)
#define COMMON_PVT_COMP_ID_COMPONENT_ID_MODIFY(r, x) \
   ((((x) << 12) & 0x0003f000ul) | ((r) & 0xfffc0ffful))
/* Field member: common::pvt_comp_id.rev_major                             */
/* Source filename: pvtc.csr, line: 31                                     */
#define COMMON_PVT_COMP_ID_REV_MAJOR_MSB 9u
#define COMMON_PVT_COMP_ID_REV_MAJOR_LSB 5u
#define COMMON_PVT_COMP_ID_REV_MAJOR_WIDTH 5u
#define COMMON_PVT_COMP_ID_REV_MAJOR_READ_ACCESS 1u
#define COMMON_PVT_COMP_ID_REV_MAJOR_WRITE_ACCESS 0u
#define COMMON_PVT_COMP_ID_REV_MAJOR_RESET 0x03u
#define COMMON_PVT_COMP_ID_REV_MAJOR_FIELD_MASK 0x000003e0ul
#define COMMON_PVT_COMP_ID_REV_MAJOR_GET(x) (((x) & 0x000003e0ul) >> 5)
#define COMMON_PVT_COMP_ID_REV_MAJOR_SET(x) (((x) << 5) & 0x000003e0ul)
#define COMMON_PVT_COMP_ID_REV_MAJOR_MODIFY(r, x) \
   ((((x) << 5) & 0x000003e0ul) | ((r) & 0xfffffc1ful))
/* Field member: common::pvt_comp_id.rev_minor                             */
/* Source filename: pvtc.csr, line: 36                                     */
#define COMMON_PVT_COMP_ID_REV_MINOR_MSB 4u
#define COMMON_PVT_COMP_ID_REV_MINOR_LSB 0u
#define COMMON_PVT_COMP_ID_REV_MINOR_WIDTH 5u
#define COMMON_PVT_COMP_ID_REV_MINOR_READ_ACCESS 1u
#define COMMON_PVT_COMP_ID_REV_MINOR_WRITE_ACCESS 0u
#define COMMON_PVT_COMP_ID_REV_MINOR_RESET 0x02u
#define COMMON_PVT_COMP_ID_REV_MINOR_FIELD_MASK 0x0000001ful
#define COMMON_PVT_COMP_ID_REV_MINOR_GET(x) ((x) & 0x0000001ful)
#define COMMON_PVT_COMP_ID_REV_MINOR_SET(x) ((x) & 0x0000001ful)
#define COMMON_PVT_COMP_ID_REV_MINOR_MODIFY(r, x) \
   (((x) & 0x0000001ful) | ((r) & 0xffffffe0ul))

/* Register type: common::pvt_ip_cfg                                       */
/* Register template: common::pvt_ip_cfg                                   */
/* Source filename: pvtc.csr, line: 44                                     */
/* Field member: common::pvt_ip_cfg.ch_num                                 */
/* Source filename: pvtc.csr, line: 45                                     */
#define COMMON_PVT_IP_CFG_CH_NUM_MSB 31u
#define COMMON_PVT_IP_CFG_CH_NUM_LSB 24u
#define COMMON_PVT_IP_CFG_CH_NUM_WIDTH 8u
#define COMMON_PVT_IP_CFG_CH_NUM_READ_ACCESS 1u
#define COMMON_PVT_IP_CFG_CH_NUM_WRITE_ACCESS 0u
#define COMMON_PVT_IP_CFG_CH_NUM_RESET 0x10u
#define COMMON_PVT_IP_CFG_CH_NUM_FIELD_MASK 0xff000000ul
#define COMMON_PVT_IP_CFG_CH_NUM_GET(x) (((x) & 0xff000000ul) >> 24)
#define COMMON_PVT_IP_CFG_CH_NUM_SET(x) (((x) << 24) & 0xff000000ul)
#define COMMON_PVT_IP_CFG_CH_NUM_MODIFY(r, x) \
   ((((x) << 24) & 0xff000000ul) | ((r) & 0x00fffffful))
/* Field member: common::pvt_ip_cfg.vm_num                                 */
/* Source filename: pvtc.csr, line: 50                                     */
#define COMMON_PVT_IP_CFG_VM_NUM_MSB 23u
#define COMMON_PVT_IP_CFG_VM_NUM_LSB 16u
#define COMMON_PVT_IP_CFG_VM_NUM_WIDTH 8u
#define COMMON_PVT_IP_CFG_VM_NUM_READ_ACCESS 1u
#define COMMON_PVT_IP_CFG_VM_NUM_WRITE_ACCESS 0u
#define COMMON_PVT_IP_CFG_VM_NUM_RESET 0x02u
#define COMMON_PVT_IP_CFG_VM_NUM_FIELD_MASK 0x00ff0000ul
#define COMMON_PVT_IP_CFG_VM_NUM_GET(x) (((x) & 0x00ff0000ul) >> 16)
#define COMMON_PVT_IP_CFG_VM_NUM_SET(x) (((x) << 16) & 0x00ff0000ul)
#define COMMON_PVT_IP_CFG_VM_NUM_MODIFY(r, x) \
   ((((x) << 16) & 0x00ff0000ul) | ((r) & 0xff00fffful))
/* Field member: common::pvt_ip_cfg.pd_num                                 */
/* Source filename: pvtc.csr, line: 55                                     */
#define COMMON_PVT_IP_CFG_PD_NUM_MSB 15u
#define COMMON_PVT_IP_CFG_PD_NUM_LSB 8u
#define COMMON_PVT_IP_CFG_PD_NUM_WIDTH 8u
#define COMMON_PVT_IP_CFG_PD_NUM_READ_ACCESS 1u
#define COMMON_PVT_IP_CFG_PD_NUM_WRITE_ACCESS 0u
#define COMMON_PVT_IP_CFG_PD_NUM_RESET 0x08u
#define COMMON_PVT_IP_CFG_PD_NUM_FIELD_MASK 0x0000ff00ul
#define COMMON_PVT_IP_CFG_PD_NUM_GET(x) (((x) & 0x0000ff00ul) >> 8)
#define COMMON_PVT_IP_CFG_PD_NUM_SET(x) (((x) << 8) & 0x0000ff00ul)
#define COMMON_PVT_IP_CFG_PD_NUM_MODIFY(r, x) \
   ((((x) << 8) & 0x0000ff00ul) | ((r) & 0xffff00fful))
/* Field member: common::pvt_ip_cfg.ts_num                                 */
/* Source filename: pvtc.csr, line: 60                                     */
#define COMMON_PVT_IP_CFG_TS_NUM_MSB 7u
#define COMMON_PVT_IP_CFG_TS_NUM_LSB 0u
#define COMMON_PVT_IP_CFG_TS_NUM_WIDTH 8u
#define COMMON_PVT_IP_CFG_TS_NUM_READ_ACCESS 1u
#define COMMON_PVT_IP_CFG_TS_NUM_WRITE_ACCESS 0u
#define COMMON_PVT_IP_CFG_TS_NUM_RESET 0x08u
#define COMMON_PVT_IP_CFG_TS_NUM_FIELD_MASK 0x000000fful
#define COMMON_PVT_IP_CFG_TS_NUM_GET(x) ((x) & 0x000000fful)
#define COMMON_PVT_IP_CFG_TS_NUM_SET(x) ((x) & 0x000000fful)
#define COMMON_PVT_IP_CFG_TS_NUM_MODIFY(r, x) \
   (((x) & 0x000000fful) | ((r) & 0xffffff00ul))

/* Register type: common::pvt_ip_num                                       */
/* Register template: common::pvt_ip_num                                   */
/* Source filename: pvtc.csr, line: 67                                     */
/* Field member: common::pvt_ip_num.custom_id                              */
/* Source filename: pvtc.csr, line: 68                                     */
#define COMMON_PVT_IP_NUM_CUSTOM_ID_MSB 31u
#define COMMON_PVT_IP_NUM_CUSTOM_ID_LSB 0u
#define COMMON_PVT_IP_NUM_CUSTOM_ID_WIDTH 32u
#define COMMON_PVT_IP_NUM_CUSTOM_ID_READ_ACCESS 1u
#define COMMON_PVT_IP_NUM_CUSTOM_ID_WRITE_ACCESS 1u
#define COMMON_PVT_IP_NUM_CUSTOM_ID_RESET 0x00000000ul
#define COMMON_PVT_IP_NUM_CUSTOM_ID_FIELD_MASK 0xfffffffful
#define COMMON_PVT_IP_NUM_CUSTOM_ID_GET(x) ((x) & 0xfffffffful)
#define COMMON_PVT_IP_NUM_CUSTOM_ID_SET(x) ((x) & 0xfffffffful)
#define COMMON_PVT_IP_NUM_CUSTOM_ID_MODIFY(r, x) ((x) & 0xfffffffful)

/* Register type: common::pvt_tm_scratch                                   */
/* Register template: common::pvt_tm_scratch                               */
/* Source filename: pvtc.csr, line: 74                                     */
/* Field member: common::pvt_tm_scratch.scratch                            */
/* Source filename: pvtc.csr, line: 75                                     */
#define COMMON_PVT_TM_SCRATCH_SCRATCH_MSB 31u
#define COMMON_PVT_TM_SCRATCH_SCRATCH_LSB 0u
#define COMMON_PVT_TM_SCRATCH_SCRATCH_WIDTH 32u
#define COMMON_PVT_TM_SCRATCH_SCRATCH_READ_ACCESS 1u
#define COMMON_PVT_TM_SCRATCH_SCRATCH_WRITE_ACCESS 1u
#define COMMON_PVT_TM_SCRATCH_SCRATCH_RESET 0x00000000ul
#define COMMON_PVT_TM_SCRATCH_SCRATCH_FIELD_MASK 0xfffffffful
#define COMMON_PVT_TM_SCRATCH_SCRATCH_GET(x) ((x) & 0xfffffffful)
#define COMMON_PVT_TM_SCRATCH_SCRATCH_SET(x) ((x) & 0xfffffffful)
#define COMMON_PVT_TM_SCRATCH_SCRATCH_MODIFY(r, x) ((x) & 0xfffffffful)

/* Register type: common::pvt_reg_lock                                     */
/* Register template: common::pvt_reg_lock                                 */
/* Source filename: pvtc.csr, line: 81                                     */
/* Field member: common::pvt_reg_lock.lock                                 */
/* Source filename: pvtc.csr, line: 82                                     */
#define COMMON_PVT_REG_LOCK_LOCK_MSB 31u
#define COMMON_PVT_REG_LOCK_LOCK_LSB 0u
#define COMMON_PVT_REG_LOCK_LOCK_WIDTH 32u
#define COMMON_PVT_REG_LOCK_LOCK_READ_ACCESS 1u
#define COMMON_PVT_REG_LOCK_LOCK_WRITE_ACCESS 1u
#define COMMON_PVT_REG_LOCK_LOCK_RESET 0x00000000ul
#define COMMON_PVT_REG_LOCK_LOCK_FIELD_MASK 0xfffffffful
#define COMMON_PVT_REG_LOCK_LOCK_GET(x) ((x) & 0xfffffffful)
#define COMMON_PVT_REG_LOCK_LOCK_SET(x) ((x) & 0xfffffffful)
#define COMMON_PVT_REG_LOCK_LOCK_MODIFY(r, x) ((x) & 0xfffffffful)

/* Register type: common::pvt_reg_lock_status                              */
/* Register template: common::pvt_reg_lock_status                          */
/* Source filename: pvtc.csr, line: 88                                     */
/* Field member: common::pvt_reg_lock_status.hw_lock_status                */
/* Source filename: pvtc.csr, line: 89                                     */
#define COMMON_PVT_REG_LOCK_STATUS_HW_LOCK_STATUS_MSB 1u
#define COMMON_PVT_REG_LOCK_STATUS_HW_LOCK_STATUS_LSB 1u
#define COMMON_PVT_REG_LOCK_STATUS_HW_LOCK_STATUS_WIDTH 1u
#define COMMON_PVT_REG_LOCK_STATUS_HW_LOCK_STATUS_READ_ACCESS 1u
#define COMMON_PVT_REG_LOCK_STATUS_HW_LOCK_STATUS_WRITE_ACCESS 0u
#define COMMON_PVT_REG_LOCK_STATUS_HW_LOCK_STATUS_RESET 0x0u
#define COMMON_PVT_REG_LOCK_STATUS_HW_LOCK_STATUS_FIELD_MASK 0x00000002ul
#define COMMON_PVT_REG_LOCK_STATUS_HW_LOCK_STATUS_GET(x) \
   (((x) & 0x00000002ul) >> 1)
#define COMMON_PVT_REG_LOCK_STATUS_HW_LOCK_STATUS_SET(x) \
   (((x) << 1) & 0x00000002ul)
#define COMMON_PVT_REG_LOCK_STATUS_HW_LOCK_STATUS_MODIFY(r, x) \
   ((((x) << 1) & 0x00000002ul) | ((r) & 0xfffffffdul))
/* Field member: common::pvt_reg_lock_status.sw_lock_status                */
/* Source filename: pvtc.csr, line: 95                                     */
#define COMMON_PVT_REG_LOCK_STATUS_SW_LOCK_STATUS_MSB 0u
#define COMMON_PVT_REG_LOCK_STATUS_SW_LOCK_STATUS_LSB 0u
#define COMMON_PVT_REG_LOCK_STATUS_SW_LOCK_STATUS_WIDTH 1u
#define COMMON_PVT_REG_LOCK_STATUS_SW_LOCK_STATUS_READ_ACCESS 1u
#define COMMON_PVT_REG_LOCK_STATUS_SW_LOCK_STATUS_WRITE_ACCESS 0u
#define COMMON_PVT_REG_LOCK_STATUS_SW_LOCK_STATUS_RESET 0x0u
#define COMMON_PVT_REG_LOCK_STATUS_SW_LOCK_STATUS_FIELD_MASK 0x00000001ul
#define COMMON_PVT_REG_LOCK_STATUS_SW_LOCK_STATUS_GET(x) ((x) & 0x00000001ul)
#define COMMON_PVT_REG_LOCK_STATUS_SW_LOCK_STATUS_SET(x) ((x) & 0x00000001ul)
#define COMMON_PVT_REG_LOCK_STATUS_SW_LOCK_STATUS_MODIFY(r, x) \
   (((x) & 0x00000001ul) | ((r) & 0xfffffffeul))

/* Register type: common::pvt_tam_status                                   */
/* Register template: common::pvt_tam_status                               */
/* Source filename: pvtc.csr, line: 103                                    */
/* Field member: common::pvt_tam_status.tam_status                         */
/* Source filename: pvtc.csr, line: 104                                    */
#define COMMON_PVT_TAM_STATUS_TAM_STATUS_MSB 0u
#define COMMON_PVT_TAM_STATUS_TAM_STATUS_LSB 0u
#define COMMON_PVT_TAM_STATUS_TAM_STATUS_WIDTH 1u
#define COMMON_PVT_TAM_STATUS_TAM_STATUS_READ_ACCESS 1u
#define COMMON_PVT_TAM_STATUS_TAM_STATUS_WRITE_ACCESS 0u
#define COMMON_PVT_TAM_STATUS_TAM_STATUS_RESET 0x0u
#define COMMON_PVT_TAM_STATUS_TAM_STATUS_FIELD_MASK 0x00000001ul
#define COMMON_PVT_TAM_STATUS_TAM_STATUS_GET(x) ((x) & 0x00000001ul)
#define COMMON_PVT_TAM_STATUS_TAM_STATUS_SET(x) ((x) & 0x00000001ul)
#define COMMON_PVT_TAM_STATUS_TAM_STATUS_MODIFY(r, x) \
   (((x) & 0x00000001ul) | ((r) & 0xfffffffeul))

/* Register type: common::pvt_tam_clear                                    */
/* Register template: common::pvt_tam_clear                                */
/* Source filename: pvtc.csr, line: 112                                    */
/* Field member: common::pvt_tam_clear.tam_status_clr                      */
/* Source filename: pvtc.csr, line: 113                                    */
#define COMMON_PVT_TAM_CLEAR_TAM_STATUS_CLR_MSB 0u
#define COMMON_PVT_TAM_CLEAR_TAM_STATUS_CLR_LSB 0u
#define COMMON_PVT_TAM_CLEAR_TAM_STATUS_CLR_WIDTH 1u
#define COMMON_PVT_TAM_CLEAR_TAM_STATUS_CLR_READ_ACCESS 0u
#define COMMON_PVT_TAM_CLEAR_TAM_STATUS_CLR_WRITE_ACCESS 1u
#define COMMON_PVT_TAM_CLEAR_TAM_STATUS_CLR_RESET 0x0u
#define COMMON_PVT_TAM_CLEAR_TAM_STATUS_CLR_FIELD_MASK 0x00000001ul
#define COMMON_PVT_TAM_CLEAR_TAM_STATUS_CLR_GET(x) ((x) & 0x00000001ul)
#define COMMON_PVT_TAM_CLEAR_TAM_STATUS_CLR_SET(x) ((x) & 0x00000001ul)
#define COMMON_PVT_TAM_CLEAR_TAM_STATUS_CLR_MODIFY(r, x) \
   (((x) & 0x00000001ul) | ((r) & 0xfffffffeul))

/* Register type: common::pvt_tmr_ctrl                                     */
/* Register template: common::pvt_tmr_ctrl                                 */
/* Source filename: pvtc.csr, line: 120                                    */
/* Field member: common::pvt_tmr_ctrl.tmr_run                              */
/* Source filename: pvtc.csr, line: 121                                    */
#define COMMON_PVT_TMR_CTRL_TMR_RUN_MSB 16u
#define COMMON_PVT_TMR_CTRL_TMR_RUN_LSB 16u
#define COMMON_PVT_TMR_CTRL_TMR_RUN_WIDTH 1u
#define COMMON_PVT_TMR_CTRL_TMR_RUN_READ_ACCESS 1u
#define COMMON_PVT_TMR_CTRL_TMR_RUN_WRITE_ACCESS 1u
#define COMMON_PVT_TMR_CTRL_TMR_RUN_RESET 0x0u
#define COMMON_PVT_TMR_CTRL_TMR_RUN_FIELD_MASK 0x00010000ul
#define COMMON_PVT_TMR_CTRL_TMR_RUN_GET(x) (((x) & 0x00010000ul) >> 16)
#define COMMON_PVT_TMR_CTRL_TMR_RUN_SET(x) (((x) << 16) & 0x00010000ul)
#define COMMON_PVT_TMR_CTRL_TMR_RUN_MODIFY(r, x) \
   ((((x) << 16) & 0x00010000ul) | ((r) & 0xfffefffful))
/* Field member: common::pvt_tmr_ctrl.tmr_delay                            */
/* Source filename: pvtc.csr, line: 125                                    */
#define COMMON_PVT_TMR_CTRL_TMR_DELAY_MSB 15u
#define COMMON_PVT_TMR_CTRL_TMR_DELAY_LSB 0u
#define COMMON_PVT_TMR_CTRL_TMR_DELAY_WIDTH 16u
#define COMMON_PVT_TMR_CTRL_TMR_DELAY_READ_ACCESS 1u
#define COMMON_PVT_TMR_CTRL_TMR_DELAY_WRITE_ACCESS 1u
#define COMMON_PVT_TMR_CTRL_TMR_DELAY_RESET 0x0000u
#define COMMON_PVT_TMR_CTRL_TMR_DELAY_FIELD_MASK 0x0000fffful
#define COMMON_PVT_TMR_CTRL_TMR_DELAY_GET(x) ((x) & 0x0000fffful)
#define COMMON_PVT_TMR_CTRL_TMR_DELAY_SET(x) ((x) & 0x0000fffful)
#define COMMON_PVT_TMR_CTRL_TMR_DELAY_MODIFY(r, x) \
   (((x) & 0x0000fffful) | ((r) & 0xffff0000ul))

/* Register type: common::pvt_tmr_status                                   */
/* Register template: common::pvt_tmr_status                               */
/* Source filename: pvtc.csr, line: 131                                    */
/* Field member: common::pvt_tmr_status.tmr_done                           */
/* Source filename: pvtc.csr, line: 132                                    */
#define COMMON_PVT_TMR_STATUS_TMR_DONE_MSB 1u
#define COMMON_PVT_TMR_STATUS_TMR_DONE_LSB 1u
#define COMMON_PVT_TMR_STATUS_TMR_DONE_WIDTH 1u
#define COMMON_PVT_TMR_STATUS_TMR_DONE_READ_ACCESS 1u
#define COMMON_PVT_TMR_STATUS_TMR_DONE_WRITE_ACCESS 1u
#define COMMON_PVT_TMR_STATUS_TMR_DONE_RESET 0x0u
#define COMMON_PVT_TMR_STATUS_TMR_DONE_FIELD_MASK 0x00000002ul
#define COMMON_PVT_TMR_STATUS_TMR_DONE_GET(x) (((x) & 0x00000002ul) >> 1)
#define COMMON_PVT_TMR_STATUS_TMR_DONE_SET(x) (((x) << 1) & 0x00000002ul)
#define COMMON_PVT_TMR_STATUS_TMR_DONE_MODIFY(r, x) \
   ((((x) << 1) & 0x00000002ul) | ((r) & 0xfffffffdul))
/* Field member: common::pvt_tmr_status.tmr_busy                           */
/* Source filename: pvtc.csr, line: 137                                    */
#define COMMON_PVT_TMR_STATUS_TMR_BUSY_MSB 0u
#define COMMON_PVT_TMR_STATUS_TMR_BUSY_LSB 0u
#define COMMON_PVT_TMR_STATUS_TMR_BUSY_WIDTH 1u
#define COMMON_PVT_TMR_STATUS_TMR_BUSY_READ_ACCESS 1u
#define COMMON_PVT_TMR_STATUS_TMR_BUSY_WRITE_ACCESS 1u
#define COMMON_PVT_TMR_STATUS_TMR_BUSY_RESET 0x0u
#define COMMON_PVT_TMR_STATUS_TMR_BUSY_FIELD_MASK 0x00000001ul
#define COMMON_PVT_TMR_STATUS_TMR_BUSY_GET(x) ((x) & 0x00000001ul)
#define COMMON_PVT_TMR_STATUS_TMR_BUSY_SET(x) ((x) & 0x00000001ul)
#define COMMON_PVT_TMR_STATUS_TMR_BUSY_MODIFY(r, x) \
   (((x) & 0x00000001ul) | ((r) & 0xfffffffeul))

/* Register type: common::pvt_tmr_irq_clear                                */
/* Register template: common::pvt_tmr_irq_clear                            */
/* Source filename: pvtc.csr, line: 144                                    */
/* Field member: common::pvt_tmr_irq_clear.tmr_irq_clr                     */
/* Source filename: pvtc.csr, line: 145                                    */
#define COMMON_PVT_TMR_IRQ_CLEAR_TMR_IRQ_CLR_MSB 0u
#define COMMON_PVT_TMR_IRQ_CLEAR_TMR_IRQ_CLR_LSB 0u
#define COMMON_PVT_TMR_IRQ_CLEAR_TMR_IRQ_CLR_WIDTH 1u
#define COMMON_PVT_TMR_IRQ_CLEAR_TMR_IRQ_CLR_READ_ACCESS 0u
#define COMMON_PVT_TMR_IRQ_CLEAR_TMR_IRQ_CLR_WRITE_ACCESS 1u
#define COMMON_PVT_TMR_IRQ_CLEAR_TMR_IRQ_CLR_RESET 0x0u
#define COMMON_PVT_TMR_IRQ_CLEAR_TMR_IRQ_CLR_FIELD_MASK 0x00000001ul
#define COMMON_PVT_TMR_IRQ_CLEAR_TMR_IRQ_CLR_GET(x) ((x) & 0x00000001ul)
#define COMMON_PVT_TMR_IRQ_CLEAR_TMR_IRQ_CLR_SET(x) ((x) & 0x00000001ul)
#define COMMON_PVT_TMR_IRQ_CLEAR_TMR_IRQ_CLR_MODIFY(r, x) \
   (((x) & 0x00000001ul) | ((r) & 0xfffffffeul))

/* Register type: common::pvt_tmr_irq_test                                 */
/* Register template: common::pvt_tmr_irq_test                             */
/* Source filename: pvtc.csr, line: 152                                    */
/* Field member: common::pvt_tmr_irq_test.tmr_irq_test                     */
/* Source filename: pvtc.csr, line: 153                                    */
#define COMMON_PVT_TMR_IRQ_TEST_TMR_IRQ_TEST_MSB 0u
#define COMMON_PVT_TMR_IRQ_TEST_TMR_IRQ_TEST_LSB 0u
#define COMMON_PVT_TMR_IRQ_TEST_TMR_IRQ_TEST_WIDTH 1u
#define COMMON_PVT_TMR_IRQ_TEST_TMR_IRQ_TEST_READ_ACCESS 1u
#define COMMON_PVT_TMR_IRQ_TEST_TMR_IRQ_TEST_WRITE_ACCESS 1u
#define COMMON_PVT_TMR_IRQ_TEST_TMR_IRQ_TEST_RESET 0x0u
#define COMMON_PVT_TMR_IRQ_TEST_TMR_IRQ_TEST_FIELD_MASK 0x00000001ul
#define COMMON_PVT_TMR_IRQ_TEST_TMR_IRQ_TEST_GET(x) ((x) & 0x00000001ul)
#define COMMON_PVT_TMR_IRQ_TEST_TMR_IRQ_TEST_SET(x) ((x) & 0x00000001ul)
#define COMMON_PVT_TMR_IRQ_TEST_TMR_IRQ_TEST_MODIFY(r, x) \
   (((x) & 0x00000001ul) | ((r) & 0xfffffffeul))

/* Addressmap type: irq                                                    */
/* Addressmap template: irq                                                */
/* Source filename: pvtc.csr, line: 160                                    */
#define IRQ_SIZE 0x40u
#define IRQ_BYTE_SIZE 0x40u
/* Register member: irq.irq_en                                             */
/* Register type referenced: irq::irq_en                                   */
/* Register template referenced: irq::irq_en                               */
#define IRQ_IRQ_EN_OFFSET 0x0u
#define IRQ_IRQ_EN_BYTE_OFFSET 0x0u
#define IRQ_IRQ_EN_READ_ACCESS 1u
#define IRQ_IRQ_EN_WRITE_ACCESS 1u
#define IRQ_IRQ_EN_RESET_VALUE 0x00000000ul
#define IRQ_IRQ_EN_RESET_MASK 0xfffffffful
#define IRQ_IRQ_EN_READ_MASK 0xfffffffful
#define IRQ_IRQ_EN_WRITE_MASK 0x0000000ful
/* Register member: irq.irq_tr_mask                                        */
/* Register type referenced: irq::irq_tr_mask                              */
/* Register template referenced: irq::irq_tr_mask                          */
#define IRQ_IRQ_TR_MASK_OFFSET 0x10u
#define IRQ_IRQ_TR_MASK_BYTE_OFFSET 0x10u
#define IRQ_IRQ_TR_MASK_READ_ACCESS 1u
#define IRQ_IRQ_TR_MASK_WRITE_ACCESS 1u
#define IRQ_IRQ_TR_MASK_RESET_VALUE 0x00000000ul
#define IRQ_IRQ_TR_MASK_RESET_MASK 0xfffffffful
#define IRQ_IRQ_TR_MASK_READ_MASK 0xfffffffful
#define IRQ_IRQ_TR_MASK_WRITE_MASK 0x00000001ul
/* Register member: irq.irq_ts_mask                                        */
/* Register type referenced: irq::irq_ts_mask                              */
/* Register template referenced: irq::irq_ts_mask                          */
#define IRQ_IRQ_TS_MASK_OFFSET 0x14u
#define IRQ_IRQ_TS_MASK_BYTE_OFFSET 0x14u
#define IRQ_IRQ_TS_MASK_READ_ACCESS 1u
#define IRQ_IRQ_TS_MASK_WRITE_ACCESS 1u
#define IRQ_IRQ_TS_MASK_RESET_VALUE 0x00000000ul
#define IRQ_IRQ_TS_MASK_RESET_MASK 0xfffffffful
#define IRQ_IRQ_TS_MASK_READ_MASK 0xfffffffful
#define IRQ_IRQ_TS_MASK_WRITE_MASK 0x000000fful
/* Register member: irq.irq_vm_mask                                        */
/* Register type referenced: irq::irq_vm_mask                              */
/* Register template referenced: irq::irq_vm_mask                          */
#define IRQ_IRQ_VM_MASK_OFFSET 0x18u
#define IRQ_IRQ_VM_MASK_BYTE_OFFSET 0x18u
#define IRQ_IRQ_VM_MASK_READ_ACCESS 1u
#define IRQ_IRQ_VM_MASK_WRITE_ACCESS 1u
#define IRQ_IRQ_VM_MASK_RESET_VALUE 0x00000000ul
#define IRQ_IRQ_VM_MASK_RESET_MASK 0xfffffffful
#define IRQ_IRQ_VM_MASK_READ_MASK 0xfffffffful
#define IRQ_IRQ_VM_MASK_WRITE_MASK 0x00000003ul
/* Register member: irq.irq_pd_mask                                        */
/* Register type referenced: irq::irq_pd_mask                              */
/* Register template referenced: irq::irq_pd_mask                          */
#define IRQ_IRQ_PD_MASK_OFFSET 0x1cu
#define IRQ_IRQ_PD_MASK_BYTE_OFFSET 0x1cu
#define IRQ_IRQ_PD_MASK_READ_ACCESS 1u
#define IRQ_IRQ_PD_MASK_WRITE_ACCESS 1u
#define IRQ_IRQ_PD_MASK_RESET_VALUE 0x00000000ul
#define IRQ_IRQ_PD_MASK_RESET_MASK 0xfffffffful
#define IRQ_IRQ_PD_MASK_READ_MASK 0xfffffffful
#define IRQ_IRQ_PD_MASK_WRITE_MASK 0x000000fful
/* Register member: irq.irq_tr_status                                      */
/* Register type referenced: irq::irq_tr_status                            */
/* Register template referenced: irq::irq_tr_status                        */
#define IRQ_IRQ_TR_STATUS_OFFSET 0x20u
#define IRQ_IRQ_TR_STATUS_BYTE_OFFSET 0x20u
#define IRQ_IRQ_TR_STATUS_READ_ACCESS 1u
#define IRQ_IRQ_TR_STATUS_WRITE_ACCESS 0u
#define IRQ_IRQ_TR_STATUS_RESET_VALUE 0x00000000ul
#define IRQ_IRQ_TR_STATUS_RESET_MASK 0xfffffffful
#define IRQ_IRQ_TR_STATUS_READ_MASK 0xfffffffful
#define IRQ_IRQ_TR_STATUS_WRITE_MASK 0x00000000ul
/* Register member: irq.irq_ts_status                                      */
/* Register type referenced: irq::irq_ts_status                            */
/* Register template referenced: irq::irq_ts_status                        */
#define IRQ_IRQ_TS_STATUS_OFFSET 0x24u
#define IRQ_IRQ_TS_STATUS_BYTE_OFFSET 0x24u
#define IRQ_IRQ_TS_STATUS_READ_ACCESS 1u
#define IRQ_IRQ_TS_STATUS_WRITE_ACCESS 0u
#define IRQ_IRQ_TS_STATUS_RESET_VALUE 0x00000000ul
#define IRQ_IRQ_TS_STATUS_RESET_MASK 0xfffffffful
#define IRQ_IRQ_TS_STATUS_READ_MASK 0xfffffffful
#define IRQ_IRQ_TS_STATUS_WRITE_MASK 0x00000000ul
/* Register member: irq.irq_vm_status                                      */
/* Register type referenced: irq::irq_vm_status                            */
/* Register template referenced: irq::irq_vm_status                        */
#define IRQ_IRQ_VM_STATUS_OFFSET 0x28u
#define IRQ_IRQ_VM_STATUS_BYTE_OFFSET 0x28u
#define IRQ_IRQ_VM_STATUS_READ_ACCESS 1u
#define IRQ_IRQ_VM_STATUS_WRITE_ACCESS 0u
#define IRQ_IRQ_VM_STATUS_RESET_VALUE 0x00000000ul
#define IRQ_IRQ_VM_STATUS_RESET_MASK 0xfffffffful
#define IRQ_IRQ_VM_STATUS_READ_MASK 0xfffffffful
#define IRQ_IRQ_VM_STATUS_WRITE_MASK 0x00000000ul
/* Register member: irq.irq_pd_status                                      */
/* Register type referenced: irq::irq_pd_status                            */
/* Register template referenced: irq::irq_pd_status                        */
#define IRQ_IRQ_PD_STATUS_OFFSET 0x2cu
#define IRQ_IRQ_PD_STATUS_BYTE_OFFSET 0x2cu
#define IRQ_IRQ_PD_STATUS_READ_ACCESS 1u
#define IRQ_IRQ_PD_STATUS_WRITE_ACCESS 0u
#define IRQ_IRQ_PD_STATUS_RESET_VALUE 0x00000000ul
#define IRQ_IRQ_PD_STATUS_RESET_MASK 0xfffffffful
#define IRQ_IRQ_PD_STATUS_READ_MASK 0xfffffffful
#define IRQ_IRQ_PD_STATUS_WRITE_MASK 0x00000000ul
/* Register member: irq.irq_tr_raw_status                                  */
/* Register type referenced: irq::irq_tr_raw_status                        */
/* Register template referenced: irq::irq_tr_raw_status                    */
#define IRQ_IRQ_TR_RAW_STATUS_OFFSET 0x30u
#define IRQ_IRQ_TR_RAW_STATUS_BYTE_OFFSET 0x30u
#define IRQ_IRQ_TR_RAW_STATUS_READ_ACCESS 1u
#define IRQ_IRQ_TR_RAW_STATUS_WRITE_ACCESS 0u
#define IRQ_IRQ_TR_RAW_STATUS_RESET_VALUE 0x00000000ul
#define IRQ_IRQ_TR_RAW_STATUS_RESET_MASK 0xfffffffful
#define IRQ_IRQ_TR_RAW_STATUS_READ_MASK 0xfffffffful
#define IRQ_IRQ_TR_RAW_STATUS_WRITE_MASK 0x00000000ul
/* Register member: irq.irq_ts_raw_status                                  */
/* Register type referenced: irq::irq_ts_raw_status                        */
/* Register template referenced: irq::irq_ts_raw_status                    */
#define IRQ_IRQ_TS_RAW_STATUS_OFFSET 0x34u
#define IRQ_IRQ_TS_RAW_STATUS_BYTE_OFFSET 0x34u
#define IRQ_IRQ_TS_RAW_STATUS_READ_ACCESS 1u
#define IRQ_IRQ_TS_RAW_STATUS_WRITE_ACCESS 0u
#define IRQ_IRQ_TS_RAW_STATUS_RESET_VALUE 0x00000000ul
#define IRQ_IRQ_TS_RAW_STATUS_RESET_MASK 0xfffffffful
#define IRQ_IRQ_TS_RAW_STATUS_READ_MASK 0xfffffffful
#define IRQ_IRQ_TS_RAW_STATUS_WRITE_MASK 0x00000000ul
/* Register member: irq.irq_vm_raw_status                                  */
/* Register type referenced: irq::irq_vm_raw_status                        */
/* Register template referenced: irq::irq_vm_raw_status                    */
#define IRQ_IRQ_VM_RAW_STATUS_OFFSET 0x38u
#define IRQ_IRQ_VM_RAW_STATUS_BYTE_OFFSET 0x38u
#define IRQ_IRQ_VM_RAW_STATUS_READ_ACCESS 1u
#define IRQ_IRQ_VM_RAW_STATUS_WRITE_ACCESS 0u
#define IRQ_IRQ_VM_RAW_STATUS_RESET_VALUE 0x00000000ul
#define IRQ_IRQ_VM_RAW_STATUS_RESET_MASK 0xfffffffful
#define IRQ_IRQ_VM_RAW_STATUS_READ_MASK 0xfffffffful
#define IRQ_IRQ_VM_RAW_STATUS_WRITE_MASK 0x00000000ul
/* Register member: irq.irq_pd_raw_status                                  */
/* Register type referenced: irq::irq_pd_raw_status                        */
/* Register template referenced: irq::irq_pd_raw_status                    */
#define IRQ_IRQ_PD_RAW_STATUS_OFFSET 0x3cu
#define IRQ_IRQ_PD_RAW_STATUS_BYTE_OFFSET 0x3cu
#define IRQ_IRQ_PD_RAW_STATUS_READ_ACCESS 1u
#define IRQ_IRQ_PD_RAW_STATUS_WRITE_ACCESS 0u
#define IRQ_IRQ_PD_RAW_STATUS_RESET_VALUE 0x00000000ul
#define IRQ_IRQ_PD_RAW_STATUS_RESET_MASK 0xfffffffful
#define IRQ_IRQ_PD_RAW_STATUS_READ_MASK 0xfffffffful
#define IRQ_IRQ_PD_RAW_STATUS_WRITE_MASK 0x00000000ul

/* Register type: irq::irq_en                                              */
/* Register template: irq::irq_en                                          */
/* Source filename: pvtc.csr, line: 165                                    */
/* Field member: irq::irq_en.pd_irq_enable                                 */
/* Source filename: pvtc.csr, line: 166                                    */
#define IRQ_IRQ_EN_PD_IRQ_ENABLE_MSB 3u
#define IRQ_IRQ_EN_PD_IRQ_ENABLE_LSB 3u
#define IRQ_IRQ_EN_PD_IRQ_ENABLE_WIDTH 1u
#define IRQ_IRQ_EN_PD_IRQ_ENABLE_READ_ACCESS 1u
#define IRQ_IRQ_EN_PD_IRQ_ENABLE_WRITE_ACCESS 1u
#define IRQ_IRQ_EN_PD_IRQ_ENABLE_RESET 0x0u
#define IRQ_IRQ_EN_PD_IRQ_ENABLE_FIELD_MASK 0x00000008ul
#define IRQ_IRQ_EN_PD_IRQ_ENABLE_GET(x) (((x) & 0x00000008ul) >> 3)
#define IRQ_IRQ_EN_PD_IRQ_ENABLE_SET(x) (((x) << 3) & 0x00000008ul)
#define IRQ_IRQ_EN_PD_IRQ_ENABLE_MODIFY(r, x) \
   ((((x) << 3) & 0x00000008ul) | ((r) & 0xfffffff7ul))
/* Field member: irq::irq_en.vm_irq_enbale                                 */
/* Source filename: pvtc.csr, line: 170                                    */
#define IRQ_IRQ_EN_VM_IRQ_ENBALE_MSB 2u
#define IRQ_IRQ_EN_VM_IRQ_ENBALE_LSB 2u
#define IRQ_IRQ_EN_VM_IRQ_ENBALE_WIDTH 1u
#define IRQ_IRQ_EN_VM_IRQ_ENBALE_READ_ACCESS 1u
#define IRQ_IRQ_EN_VM_IRQ_ENBALE_WRITE_ACCESS 1u
#define IRQ_IRQ_EN_VM_IRQ_ENBALE_RESET 0x0u
#define IRQ_IRQ_EN_VM_IRQ_ENBALE_FIELD_MASK 0x00000004ul
#define IRQ_IRQ_EN_VM_IRQ_ENBALE_GET(x) (((x) & 0x00000004ul) >> 2)
#define IRQ_IRQ_EN_VM_IRQ_ENBALE_SET(x) (((x) << 2) & 0x00000004ul)
#define IRQ_IRQ_EN_VM_IRQ_ENBALE_MODIFY(r, x) \
   ((((x) << 2) & 0x00000004ul) | ((r) & 0xfffffffbul))
/* Field member: irq::irq_en.ts_irq_enbale                                 */
/* Source filename: pvtc.csr, line: 174                                    */
#define IRQ_IRQ_EN_TS_IRQ_ENBALE_MSB 1u
#define IRQ_IRQ_EN_TS_IRQ_ENBALE_LSB 1u
#define IRQ_IRQ_EN_TS_IRQ_ENBALE_WIDTH 1u
#define IRQ_IRQ_EN_TS_IRQ_ENBALE_READ_ACCESS 1u
#define IRQ_IRQ_EN_TS_IRQ_ENBALE_WRITE_ACCESS 1u
#define IRQ_IRQ_EN_TS_IRQ_ENBALE_RESET 0x0u
#define IRQ_IRQ_EN_TS_IRQ_ENBALE_FIELD_MASK 0x00000002ul
#define IRQ_IRQ_EN_TS_IRQ_ENBALE_GET(x) (((x) & 0x00000002ul) >> 1)
#define IRQ_IRQ_EN_TS_IRQ_ENBALE_SET(x) (((x) << 1) & 0x00000002ul)
#define IRQ_IRQ_EN_TS_IRQ_ENBALE_MODIFY(r, x) \
   ((((x) << 1) & 0x00000002ul) | ((r) & 0xfffffffdul))
/* Field member: irq::irq_en.tmr_irq_enable                                */
/* Source filename: pvtc.csr, line: 178                                    */
#define IRQ_IRQ_EN_TMR_IRQ_ENABLE_MSB 0u
#define IRQ_IRQ_EN_TMR_IRQ_ENABLE_LSB 0u
#define IRQ_IRQ_EN_TMR_IRQ_ENABLE_WIDTH 1u
#define IRQ_IRQ_EN_TMR_IRQ_ENABLE_READ_ACCESS 1u
#define IRQ_IRQ_EN_TMR_IRQ_ENABLE_WRITE_ACCESS 1u
#define IRQ_IRQ_EN_TMR_IRQ_ENABLE_RESET 0x0u
#define IRQ_IRQ_EN_TMR_IRQ_ENABLE_FIELD_MASK 0x00000001ul
#define IRQ_IRQ_EN_TMR_IRQ_ENABLE_GET(x) ((x) & 0x00000001ul)
#define IRQ_IRQ_EN_TMR_IRQ_ENABLE_SET(x) ((x) & 0x00000001ul)
#define IRQ_IRQ_EN_TMR_IRQ_ENABLE_MODIFY(r, x) \
   (((x) & 0x00000001ul) | ((r) & 0xfffffffeul))

/* Register type: irq::irq_tr_mask                                         */
/* Register template: irq::irq_tr_mask                                     */
/* Source filename: pvtc.csr, line: 184                                    */
/* Field member: irq::irq_tr_mask.mask                                     */
/* Source filename: pvtc.csr, line: 185                                    */
#define IRQ_IRQ_TR_MASK_MASK_MSB 0u
#define IRQ_IRQ_TR_MASK_MASK_LSB 0u
#define IRQ_IRQ_TR_MASK_MASK_WIDTH 1u
#define IRQ_IRQ_TR_MASK_MASK_READ_ACCESS 1u
#define IRQ_IRQ_TR_MASK_MASK_WRITE_ACCESS 1u
#define IRQ_IRQ_TR_MASK_MASK_RESET 0x0u
#define IRQ_IRQ_TR_MASK_MASK_FIELD_MASK 0x00000001ul
#define IRQ_IRQ_TR_MASK_MASK_GET(x) ((x) & 0x00000001ul)
#define IRQ_IRQ_TR_MASK_MASK_SET(x) ((x) & 0x00000001ul)
#define IRQ_IRQ_TR_MASK_MASK_MODIFY(r, x) \
   (((x) & 0x00000001ul) | ((r) & 0xfffffffeul))

/* Register type: irq::irq_ts_mask                                         */
/* Register template: irq::irq_ts_mask                                     */
/* Source filename: pvtc.csr, line: 191                                    */
/* Field member: irq::irq_ts_mask.mask                                     */
/* Source filename: pvtc.csr, line: 192                                    */
#define IRQ_IRQ_TS_MASK_MASK_MSB 7u
#define IRQ_IRQ_TS_MASK_MASK_LSB 0u
#define IRQ_IRQ_TS_MASK_MASK_WIDTH 8u
#define IRQ_IRQ_TS_MASK_MASK_READ_ACCESS 1u
#define IRQ_IRQ_TS_MASK_MASK_WRITE_ACCESS 1u
#define IRQ_IRQ_TS_MASK_MASK_RESET 0x00u
#define IRQ_IRQ_TS_MASK_MASK_FIELD_MASK 0x000000fful
#define IRQ_IRQ_TS_MASK_MASK_GET(x) ((x) & 0x000000fful)
#define IRQ_IRQ_TS_MASK_MASK_SET(x) ((x) & 0x000000fful)
#define IRQ_IRQ_TS_MASK_MASK_MODIFY(r, x) \
   (((x) & 0x000000fful) | ((r) & 0xffffff00ul))

/* Register type: irq::irq_vm_mask                                         */
/* Register template: irq::irq_vm_mask                                     */
/* Source filename: pvtc.csr, line: 198                                    */
/* Field member: irq::irq_vm_mask.mask                                     */
/* Source filename: pvtc.csr, line: 199                                    */
#define IRQ_IRQ_VM_MASK_MASK_MSB 1u
#define IRQ_IRQ_VM_MASK_MASK_LSB 0u
#define IRQ_IRQ_VM_MASK_MASK_WIDTH 2u
#define IRQ_IRQ_VM_MASK_MASK_READ_ACCESS 1u
#define IRQ_IRQ_VM_MASK_MASK_WRITE_ACCESS 1u
#define IRQ_IRQ_VM_MASK_MASK_RESET 0x0u
#define IRQ_IRQ_VM_MASK_MASK_FIELD_MASK 0x00000003ul
#define IRQ_IRQ_VM_MASK_MASK_GET(x) ((x) & 0x00000003ul)
#define IRQ_IRQ_VM_MASK_MASK_SET(x) ((x) & 0x00000003ul)
#define IRQ_IRQ_VM_MASK_MASK_MODIFY(r, x) \
   (((x) & 0x00000003ul) | ((r) & 0xfffffffcul))

/* Register type: irq::irq_pd_mask                                         */
/* Register template: irq::irq_pd_mask                                     */
/* Source filename: pvtc.csr, line: 205                                    */
/* Field member: irq::irq_pd_mask.mask                                     */
/* Source filename: pvtc.csr, line: 206                                    */
#define IRQ_IRQ_PD_MASK_MASK_MSB 7u
#define IRQ_IRQ_PD_MASK_MASK_LSB 0u
#define IRQ_IRQ_PD_MASK_MASK_WIDTH 8u
#define IRQ_IRQ_PD_MASK_MASK_READ_ACCESS 1u
#define IRQ_IRQ_PD_MASK_MASK_WRITE_ACCESS 1u
#define IRQ_IRQ_PD_MASK_MASK_RESET 0x00u
#define IRQ_IRQ_PD_MASK_MASK_FIELD_MASK 0x000000fful
#define IRQ_IRQ_PD_MASK_MASK_GET(x) ((x) & 0x000000fful)
#define IRQ_IRQ_PD_MASK_MASK_SET(x) ((x) & 0x000000fful)
#define IRQ_IRQ_PD_MASK_MASK_MODIFY(r, x) \
   (((x) & 0x000000fful) | ((r) & 0xffffff00ul))

/* Register type: irq::irq_tr_status                                       */
/* Register template: irq::irq_tr_status                                   */
/* Source filename: pvtc.csr, line: 212                                    */
/* Field member: irq::irq_tr_status.status                                 */
/* Source filename: pvtc.csr, line: 213                                    */
#define IRQ_IRQ_TR_STATUS_STATUS_MSB 0u
#define IRQ_IRQ_TR_STATUS_STATUS_LSB 0u
#define IRQ_IRQ_TR_STATUS_STATUS_WIDTH 1u
#define IRQ_IRQ_TR_STATUS_STATUS_READ_ACCESS 1u
#define IRQ_IRQ_TR_STATUS_STATUS_WRITE_ACCESS 0u
#define IRQ_IRQ_TR_STATUS_STATUS_RESET 0x0u
#define IRQ_IRQ_TR_STATUS_STATUS_FIELD_MASK 0x00000001ul
#define IRQ_IRQ_TR_STATUS_STATUS_GET(x) ((x) & 0x00000001ul)
#define IRQ_IRQ_TR_STATUS_STATUS_SET(x) ((x) & 0x00000001ul)
#define IRQ_IRQ_TR_STATUS_STATUS_MODIFY(r, x) \
   (((x) & 0x00000001ul) | ((r) & 0xfffffffeul))

/* Register type: irq::irq_ts_status                                       */
/* Register template: irq::irq_ts_status                                   */
/* Source filename: pvtc.csr, line: 220                                    */
/* Field member: irq::irq_ts_status.status                                 */
/* Source filename: pvtc.csr, line: 221                                    */
#define IRQ_IRQ_TS_STATUS_STATUS_MSB 7u
#define IRQ_IRQ_TS_STATUS_STATUS_LSB 0u
#define IRQ_IRQ_TS_STATUS_STATUS_WIDTH 8u
#define IRQ_IRQ_TS_STATUS_STATUS_READ_ACCESS 1u
#define IRQ_IRQ_TS_STATUS_STATUS_WRITE_ACCESS 0u
#define IRQ_IRQ_TS_STATUS_STATUS_RESET 0x00u
#define IRQ_IRQ_TS_STATUS_STATUS_FIELD_MASK 0x000000fful
#define IRQ_IRQ_TS_STATUS_STATUS_GET(x) ((x) & 0x000000fful)
#define IRQ_IRQ_TS_STATUS_STATUS_SET(x) ((x) & 0x000000fful)
#define IRQ_IRQ_TS_STATUS_STATUS_MODIFY(r, x) \
   (((x) & 0x000000fful) | ((r) & 0xffffff00ul))

/* Register type: irq::irq_vm_status                                       */
/* Register template: irq::irq_vm_status                                   */
/* Source filename: pvtc.csr, line: 228                                    */
/* Field member: irq::irq_vm_status.status                                 */
/* Source filename: pvtc.csr, line: 229                                    */
#define IRQ_IRQ_VM_STATUS_STATUS_MSB 1u
#define IRQ_IRQ_VM_STATUS_STATUS_LSB 0u
#define IRQ_IRQ_VM_STATUS_STATUS_WIDTH 2u
#define IRQ_IRQ_VM_STATUS_STATUS_READ_ACCESS 1u
#define IRQ_IRQ_VM_STATUS_STATUS_WRITE_ACCESS 0u
#define IRQ_IRQ_VM_STATUS_STATUS_RESET 0x0u
#define IRQ_IRQ_VM_STATUS_STATUS_FIELD_MASK 0x00000003ul
#define IRQ_IRQ_VM_STATUS_STATUS_GET(x) ((x) & 0x00000003ul)
#define IRQ_IRQ_VM_STATUS_STATUS_SET(x) ((x) & 0x00000003ul)
#define IRQ_IRQ_VM_STATUS_STATUS_MODIFY(r, x) \
   (((x) & 0x00000003ul) | ((r) & 0xfffffffcul))

/* Register type: irq::irq_pd_status                                       */
/* Register template: irq::irq_pd_status                                   */
/* Source filename: pvtc.csr, line: 236                                    */
/* Field member: irq::irq_pd_status.status                                 */
/* Source filename: pvtc.csr, line: 237                                    */
#define IRQ_IRQ_PD_STATUS_STATUS_MSB 7u
#define IRQ_IRQ_PD_STATUS_STATUS_LSB 0u
#define IRQ_IRQ_PD_STATUS_STATUS_WIDTH 8u
#define IRQ_IRQ_PD_STATUS_STATUS_READ_ACCESS 1u
#define IRQ_IRQ_PD_STATUS_STATUS_WRITE_ACCESS 0u
#define IRQ_IRQ_PD_STATUS_STATUS_RESET 0x00u
#define IRQ_IRQ_PD_STATUS_STATUS_FIELD_MASK 0x000000fful
#define IRQ_IRQ_PD_STATUS_STATUS_GET(x) ((x) & 0x000000fful)
#define IRQ_IRQ_PD_STATUS_STATUS_SET(x) ((x) & 0x000000fful)
#define IRQ_IRQ_PD_STATUS_STATUS_MODIFY(r, x) \
   (((x) & 0x000000fful) | ((r) & 0xffffff00ul))

/* Register type: irq::irq_tr_raw_status                                   */
/* Register template: irq::irq_tr_raw_status                               */
/* Source filename: pvtc.csr, line: 244                                    */
/* Field member: irq::irq_tr_raw_status.status                             */
/* Source filename: pvtc.csr, line: 245                                    */
#define IRQ_IRQ_TR_RAW_STATUS_STATUS_MSB 0u
#define IRQ_IRQ_TR_RAW_STATUS_STATUS_LSB 0u
#define IRQ_IRQ_TR_RAW_STATUS_STATUS_WIDTH 1u
#define IRQ_IRQ_TR_RAW_STATUS_STATUS_READ_ACCESS 1u
#define IRQ_IRQ_TR_RAW_STATUS_STATUS_WRITE_ACCESS 0u
#define IRQ_IRQ_TR_RAW_STATUS_STATUS_RESET 0x0u
#define IRQ_IRQ_TR_RAW_STATUS_STATUS_FIELD_MASK 0x00000001ul
#define IRQ_IRQ_TR_RAW_STATUS_STATUS_GET(x) ((x) & 0x00000001ul)
#define IRQ_IRQ_TR_RAW_STATUS_STATUS_SET(x) ((x) & 0x00000001ul)
#define IRQ_IRQ_TR_RAW_STATUS_STATUS_MODIFY(r, x) \
   (((x) & 0x00000001ul) | ((r) & 0xfffffffeul))

/* Register type: irq::irq_ts_raw_status                                   */
/* Register template: irq::irq_ts_raw_status                               */
/* Source filename: pvtc.csr, line: 252                                    */
/* Field member: irq::irq_ts_raw_status.status                             */
/* Source filename: pvtc.csr, line: 253                                    */
#define IRQ_IRQ_TS_RAW_STATUS_STATUS_MSB 7u
#define IRQ_IRQ_TS_RAW_STATUS_STATUS_LSB 0u
#define IRQ_IRQ_TS_RAW_STATUS_STATUS_WIDTH 8u
#define IRQ_IRQ_TS_RAW_STATUS_STATUS_READ_ACCESS 1u
#define IRQ_IRQ_TS_RAW_STATUS_STATUS_WRITE_ACCESS 0u
#define IRQ_IRQ_TS_RAW_STATUS_STATUS_RESET 0x00u
#define IRQ_IRQ_TS_RAW_STATUS_STATUS_FIELD_MASK 0x000000fful
#define IRQ_IRQ_TS_RAW_STATUS_STATUS_GET(x) ((x) & 0x000000fful)
#define IRQ_IRQ_TS_RAW_STATUS_STATUS_SET(x) ((x) & 0x000000fful)
#define IRQ_IRQ_TS_RAW_STATUS_STATUS_MODIFY(r, x) \
   (((x) & 0x000000fful) | ((r) & 0xffffff00ul))

/* Register type: irq::irq_vm_raw_status                                   */
/* Register template: irq::irq_vm_raw_status                               */
/* Source filename: pvtc.csr, line: 260                                    */
/* Field member: irq::irq_vm_raw_status.status                             */
/* Source filename: pvtc.csr, line: 261                                    */
#define IRQ_IRQ_VM_RAW_STATUS_STATUS_MSB 1u
#define IRQ_IRQ_VM_RAW_STATUS_STATUS_LSB 0u
#define IRQ_IRQ_VM_RAW_STATUS_STATUS_WIDTH 2u
#define IRQ_IRQ_VM_RAW_STATUS_STATUS_READ_ACCESS 1u
#define IRQ_IRQ_VM_RAW_STATUS_STATUS_WRITE_ACCESS 0u
#define IRQ_IRQ_VM_RAW_STATUS_STATUS_RESET 0x0u
#define IRQ_IRQ_VM_RAW_STATUS_STATUS_FIELD_MASK 0x00000003ul
#define IRQ_IRQ_VM_RAW_STATUS_STATUS_GET(x) ((x) & 0x00000003ul)
#define IRQ_IRQ_VM_RAW_STATUS_STATUS_SET(x) ((x) & 0x00000003ul)
#define IRQ_IRQ_VM_RAW_STATUS_STATUS_MODIFY(r, x) \
   (((x) & 0x00000003ul) | ((r) & 0xfffffffcul))

/* Register type: irq::irq_pd_raw_status                                   */
/* Register template: irq::irq_pd_raw_status                               */
/* Source filename: pvtc.csr, line: 268                                    */
/* Field member: irq::irq_pd_raw_status.status                             */
/* Source filename: pvtc.csr, line: 269                                    */
#define IRQ_IRQ_PD_RAW_STATUS_STATUS_MSB 7u
#define IRQ_IRQ_PD_RAW_STATUS_STATUS_LSB 0u
#define IRQ_IRQ_PD_RAW_STATUS_STATUS_WIDTH 8u
#define IRQ_IRQ_PD_RAW_STATUS_STATUS_READ_ACCESS 1u
#define IRQ_IRQ_PD_RAW_STATUS_STATUS_WRITE_ACCESS 0u
#define IRQ_IRQ_PD_RAW_STATUS_STATUS_RESET 0x00u
#define IRQ_IRQ_PD_RAW_STATUS_STATUS_FIELD_MASK 0x000000fful
#define IRQ_IRQ_PD_RAW_STATUS_STATUS_GET(x) ((x) & 0x000000fful)
#define IRQ_IRQ_PD_RAW_STATUS_STATUS_SET(x) ((x) & 0x000000fful)
#define IRQ_IRQ_PD_RAW_STATUS_STATUS_MODIFY(r, x) \
   (((x) & 0x000000fful) | ((r) & 0xffffff00ul))

/* ####################################################################### */
/*        TYPE DEFINITIONS                                                 */
/* ####################################################################### */

/* Typedef for Addressmap: common_ip                                       */
/* Source filename: pvtc.csr, line: 306                                    */
typedef struct {
   volatile uint32_t clk_synth; /**< Offset 0x0 (R/W) */
   volatile uint32_t sdif_disable; /**< Offset 0x4 (R/W) */
   volatile uint32_t sdif_status; /**< Offset 0x8 (R/W) */
   volatile uint32_t sdif; /**< Offset 0xc (R/W) */
   volatile uint32_t sdif_halt; /**< Offset 0x10 (R/W) */
   volatile uint32_t sdif_ctrl; /**< Offset 0x14 (R/W) */
   uint8_t _pad0[0x8];
   volatile uint32_t smpl_ctrl; /**< Offset 0x20 (R/W) */
   volatile uint32_t smpl_halt; /**< Offset 0x24 (R/W) */
   volatile uint32_t smpl_cnt; /**< Offset 0x28 (R/W) */
} Common_ip, *PTR_Common_ip;

/* Typedef for Addressmap: common                                          */
/* Source filename: pvtc.csr, line: 158                                    */
typedef struct {
   volatile uint32_t pvt_comp_id; /**< Offset 0x0 (R) */
   volatile uint32_t pvt_ip_cfg; /**< Offset 0x4 (R) */
   volatile uint32_t pvt_ip_num; /**< Offset 0x8 (R/W) */
   volatile uint32_t pvt_tm_scratch; /**< Offset 0xc (R/W) */
   volatile uint32_t pvt_reg_lock; /**< Offset 0x10 (R/W) */
   volatile uint32_t pvt_reg_lock_status; /**< Offset 0x14 (R) */
   volatile uint32_t pvt_tam_status; /**< Offset 0x18 (R) */
   volatile uint32_t pvt_tam_clear; /**< Offset 0x1c (W) */
   volatile uint32_t pvt_tmr_ctrl; /**< Offset 0x20 (R/W) */
   volatile uint32_t pvt_tmr_status; /**< Offset 0x24 (R/W) */
   volatile uint32_t pvt_tmr_irq_clear; /**< Offset 0x28 (W) */
   volatile uint32_t pvt_tmr_irq_test; /**< Offset 0x2c (R/W) */
} Common, *PTR_Common;

/* Typedef for Addressmap: irq                                             */
/* Source filename: pvtc.csr, line: 276                                    */
typedef struct {
   volatile uint32_t irq_en; /**< Offset 0x0 (R/W) */
   uint8_t _pad0[0xc];
   volatile uint32_t irq_tr_mask; /**< Offset 0x10 (R/W) */
   volatile uint32_t irq_ts_mask; /**< Offset 0x14 (R/W) */
   volatile uint32_t irq_vm_mask; /**< Offset 0x18 (R/W) */
   volatile uint32_t irq_pd_mask; /**< Offset 0x1c (R/W) */
   volatile uint32_t irq_tr_status; /**< Offset 0x20 (R) */
   volatile uint32_t irq_ts_status; /**< Offset 0x24 (R) */
   volatile uint32_t irq_vm_status; /**< Offset 0x28 (R) */
   volatile uint32_t irq_pd_status; /**< Offset 0x2c (R) */
   volatile uint32_t irq_tr_raw_status; /**< Offset 0x30 (R) */
   volatile uint32_t irq_ts_raw_status; /**< Offset 0x34 (R) */
   volatile uint32_t irq_vm_raw_status; /**< Offset 0x38 (R) */
   volatile uint32_t irq_pd_raw_status; /**< Offset 0x3c (R) */
} Irq, *PTR_Irq;

/* Typedef for Addressmap: ptvc                                            */
/* Source filename: pvtc.csr, line: 317                                    */
typedef struct {
   Common common; /**< Offset 0x0 (R/W) */
   uint8_t _pad0[0x10];
   Irq irq; /**< Offset 0x40 (R/W) */
} Ptvc, *PTR_Ptvc;

#endif
