/**
 *  @Component      spio_plic
 *
 *  @Filename       $REPOROOT/dv/tests/ioshire/sw/inc/spio_plic_intr_device.h
 *
 *  @Description    Defines IDs for SPIO PLIC interrupt sources
 *
 *//*======================================================================== */



#ifndef __SPIO_PLIC_DEVICE_H
#define __SPIO_PLIC_DEVICE_H

#ifdef __cplusplus
extern "C"
{
#endif



#define SPIO_PLIC_NO_INTERRUPT_INTR_ID          0
#define SPIO_PLIC_MINSHIRE_ERR0_INTR_ID         1
#define SPIO_PLIC_MINSHIRE_ERR1_INTR_ID         2
#define SPIO_PLIC_MINSHIRE_ERR2_INTR_ID         3
#define SPIO_PLIC_MINSHIRE_ERR3_INTR_ID         4
#define SPIO_PLIC_MINSHIRE_ERR4_INTR_ID         5
#define SPIO_PLIC_MINSHIRE_ERR5_INTR_ID         6
#define SPIO_PLIC_MINSHIRE_ERR6_INTR_ID         7
#define SPIO_PLIC_MINSHIRE_ERR7_INTR_ID         8
#define SPIO_PLIC_MINSHIRE_ERR8_INTR_ID         9
#define SPIO_PLIC_MINSHIRE_ERR9_INTR_ID        10
#define SPIO_PLIC_MINSHIRE_ERR10_INTR_ID       11
#define SPIO_PLIC_MINSHIRE_ERR11_INTR_ID       12
#define SPIO_PLIC_MINSHIRE_ERR12_INTR_ID       13
#define SPIO_PLIC_MINSHIRE_ERR13_INTR_ID       14
#define SPIO_PLIC_MINSHIRE_ERR14_INTR_ID       15
#define SPIO_PLIC_MINSHIRE_ERR15_INTR_ID       16
#define SPIO_PLIC_MINSHIRE_ERR16_INTR_ID       17
#define SPIO_PLIC_MINSHIRE_ERR17_INTR_ID       18
#define SPIO_PLIC_MINSHIRE_ERR18_INTR_ID       19
#define SPIO_PLIC_MINSHIRE_ERR19_INTR_ID       20
#define SPIO_PLIC_MINSHIRE_ERR20_INTR_ID       21
#define SPIO_PLIC_MINSHIRE_ERR21_INTR_ID       22
#define SPIO_PLIC_MINSHIRE_ERR22_INTR_ID       23
#define SPIO_PLIC_MINSHIRE_ERR23_INTR_ID       24
#define SPIO_PLIC_MINSHIRE_ERR24_INTR_ID       25
#define SPIO_PLIC_MINSHIRE_ERR25_INTR_ID       26
#define SPIO_PLIC_MINSHIRE_ERR26_INTR_ID       27
#define SPIO_PLIC_MINSHIRE_ERR27_INTR_ID       28
#define SPIO_PLIC_MINSHIRE_ERR28_INTR_ID       29
#define SPIO_PLIC_MINSHIRE_ERR29_INTR_ID       30
#define SPIO_PLIC_MINSHIRE_ERR30_INTR_ID       31
#define SPIO_PLIC_MINSHIRE_ERR31_INTR_ID       32
#define SPIO_PLIC_MINSHIRE_ERR32_INTR_ID       33
#define SPIO_PLIC_MINSHIRE_ERR33_INTR_ID       34
#define SPIO_PLIC_MINSHIRE_NOC0_INTR_ID        35
#define SPIO_PLIC_MINSHIRE_NOC1_INTR_ID        36
#define SPIO_PLIC_MINSHIRE_NOC2_INTR_ID        37
#define SPIO_PLIC_MINSHIRE_NOC3_INTR_ID        38
#define SPIO_PLIC_MINSHIRE_NOC4_INTR_ID        39
#define SPIO_PLIC_MINSHIRE_NOC5_INTR_ID        40
#define SPIO_PLIC_MINSHIRE_NOC6_INTR_ID        41
#define SPIO_PLIC_MINSHIRE_NOC7_INTR_ID        42
#define SPIO_PLIC_MINSHIRE_NOC8_INTR_ID        43
#define SPIO_PLIC_MINSHIRE_NOC9_INTR_ID        44
#define SPIO_PLIC_MINSHIRE_NOC10_INTR_ID       45
#define SPIO_PLIC_MINSHIRE_NOC11_INTR_ID       46
#define SPIO_PLIC_MINSHIRE_NOC12_INTR_ID       47
#define SPIO_PLIC_MINSHIRE_NOC13_INTR_ID       48
#define SPIO_PLIC_MINSHIRE_NOC14_INTR_ID       49
#define SPIO_PLIC_MINSHIRE_NOC15_INTR_ID       50
#define SPIO_PLIC_MINSHIRE_NOC16_INTR_ID       51
#define SPIO_PLIC_MINSHIRE_NOC17_INTR_ID       52
#define SPIO_PLIC_MINSHIRE_NOC18_INTR_ID       53
#define SPIO_PLIC_MINSHIRE_NOC19_INTR_ID       54
#define SPIO_PLIC_MINSHIRE_NOC20_INTR_ID       55
#define SPIO_PLIC_MINSHIRE_NOC21_INTR_ID       56
#define SPIO_PLIC_MINSHIRE_NOC22_INTR_ID       57
#define SPIO_PLIC_MINSHIRE_NOC23_INTR_ID       58
#define SPIO_PLIC_MINSHIRE_NOC24_INTR_ID       59
#define SPIO_PLIC_MINSHIRE_NOC25_INTR_ID       60
#define SPIO_PLIC_MINSHIRE_NOC26_INTR_ID       61
#define SPIO_PLIC_MINSHIRE_NOC27_INTR_ID       62
#define SPIO_PLIC_MINSHIRE_NOC28_INTR_ID       63
#define SPIO_PLIC_MINSHIRE_NOC29_INTR_ID       64
#define SPIO_PLIC_MINSHIRE_NOC30_INTR_ID       65
#define SPIO_PLIC_MINSHIRE_NOC31_INTR_ID       66
#define SPIO_PLIC_MINSHIRE_NOC32_INTR_ID       67
#define SPIO_PLIC_MINSHIRE_NOC33_INTR_ID       68
#define SPIO_PLIC_MAXSHIRE_ERR_INTR_ID         69
#define SPIO_PLIC_MEMSHIRE_CRIT_E0_INTR_ID     70
#define SPIO_PLIC_MEMSHIRE_CRIT_E1_INTR_ID     71
#define SPIO_PLIC_MEMSHIRE_CRIT_E2_INTR_ID     72
#define SPIO_PLIC_MEMSHIRE_CRIT_E3_INTR_ID     73
#define SPIO_PLIC_MEMSHIRE_CRIT_W0_INTR_ID     74
#define SPIO_PLIC_MEMSHIRE_CRIT_W1_INTR_ID     75
#define SPIO_PLIC_MEMSHIRE_CRIT_W2_INTR_ID     76
#define SPIO_PLIC_MEMSHIRE_CRIT_W3_INTR_ID     77
#define SPIO_PLIC_MEMSHIRE_NOC_E0_INTR_ID      78
#define SPIO_PLIC_MEMSHIRE_NOC_E1_INTR_ID      79
#define SPIO_PLIC_MEMSHIRE_NOC_E2_INTR_ID      80
#define SPIO_PLIC_MEMSHIRE_NOC_E3_INTR_ID      81
#define SPIO_PLIC_MEMSHIRE_NOC_W0_INTR_ID      82
#define SPIO_PLIC_MEMSHIRE_NOC_W1_INTR_ID      83
#define SPIO_PLIC_MEMSHIRE_NOC_W2_INTR_ID      84
#define SPIO_PLIC_MEMSHIRE_NOC_W3_INTR_ID      85
#define SPIO_PLIC_MEMSHIRE_NORM_E0_INTR_ID     86
#define SPIO_PLIC_MEMSHIRE_NORM_E1_INTR_ID     87
#define SPIO_PLIC_MEMSHIRE_NORM_E2_INTR_ID     88
#define SPIO_PLIC_MEMSHIRE_NORM_E3_INTR_ID     89
#define SPIO_PLIC_MEMSHIRE_NORM_W0_INTR_ID     90
#define SPIO_PLIC_MEMSHIRE_NORM_W1_INTR_ID     91
#define SPIO_PLIC_MEMSHIRE_NORM_W2_INTR_ID     92
#define SPIO_PLIC_MEMSHIRE_NORM_W3_INTR_ID     93
#define SPIO_PLIC_PSHIRE_PCIE0_ERR_INTR_ID     94
#define SPIO_PLIC_PSHIRE_PCIE1_ERR_INTR_ID     95
#define SPIO_PLIC_PSHIRE_PCIE0_EDMA0_INTR_ID    96
#define SPIO_PLIC_PSHIRE_PCIE0_EDMA1_INTR_ID    97
#define SPIO_PLIC_PSHIRE_PCIE0_EDMA2_INTR_ID    98
#define SPIO_PLIC_PSHIRE_PCIE0_EDMA3_INTR_ID    99
#define SPIO_PLIC_PSHIRE_PCIE0_EDMA4_INTR_ID   100
#define SPIO_PLIC_PSHIRE_PCIE0_EDMA5_INTR_ID   101
#define SPIO_PLIC_PSHIRE_PCIE0_EDMA6_INTR_ID   102
#define SPIO_PLIC_PSHIRE_PCIE0_EDMA7_INTR_ID   103
#define SPIO_PLIC_PSHIRE_NOC_INTR_ID          104
#define SPIO_PLIC_SPIO_NOC_INTR_ID            105
#define SPIO_PLIC_PU_NOC_INTR_ID              106
#define SPIO_PLIC_IOSHIRE_MESH_INTR_ID        107
#define SPIO_PLIC_IOSHIRE_DBG_MESH_INTR_ID    108
#define SPIO_PLIC_PU_PLIC0_INTR_ID            109
#define SPIO_PLIC_PU_PLIC1_INTR_ID            110
#define SPIO_PLIC_SP_ICACHE_ECC_INTR_ID       111
#define SPIO_PLIC_DMA_INTR_ID                 112
#define SPIO_PLIC_MBOX_MXN_INTR_ID            113
#define SPIO_PLIC_MBOX_MMIN_INTR_ID           114
#define SPIO_PLIC_MBOX_HOST_INTR_ID           115
#define SPIO_PLIC_I2C0_INTR_ID                116
#define SPIO_PLIC_I2C1_INTR_ID                117
#define SPIO_PLIC_SPI0_INTR_ID                118
#define SPIO_PLIC_SPI1_INTR_ID                119
#define SPIO_PLIC_UART0_INTR_ID               120
#define SPIO_PLIC_UART1_INTR_ID               121
#define SPIO_PLIC_GPIO_INTR_ID                122
#define SPIO_PLIC_WDT_INTR_ID                 123
#define SPIO_PLIC_PU_WDT_INTR_ID              124
#define SPIO_PLIC_TIMER0_INTR_ID              125
#define SPIO_PLIC_TIMER1_INTR_ID              126
#define SPIO_PLIC_TIMER2_INTR_ID              127
#define SPIO_PLIC_TIMER3_INTR_ID              128
#define SPIO_PLIC_TIMER4_INTR_ID              129
#define SPIO_PLIC_TIMER5_INTR_ID              130
#define SPIO_PLIC_TIMER6_INTR_ID              131
#define SPIO_PLIC_TIMER7_INTR_ID              132
#define SPIO_PLIC_CRU_INTR_ID                 133
#define SPIO_PLIC_CRU_SW_INTR_ID              134
#define SPIO_PLIC_PVTC0_INTR_ID               135
#define SPIO_PLIC_PVTC1_INTR_ID               136
#define SPIO_PLIC_PVTC2_INTR_ID               137
#define SPIO_PLIC_PVTC3_INTR_ID               138
#define SPIO_PLIC_PVTC4_INTR_ID               139
#define SPIO_PLIC_VAULT_SECURE_INTR_ID        140
#define SPIO_PLIC_VAULT_INTR_ID               141
#define SPIO_PLIC_US_DBG_UPSTR_INTR_ID        142
#define SPIO_PLIC_US_DBG_DOWNSTR_INTR_ID      143
#define SPIO_PLIC_SMS_SFP_READY_INTR_ID       144
#define SPIO_PLIC_SMS_SFP_FAIL_INTR_ID        145
#define SPIO_PLIC_PERSTN_ASSERT_INTR_ID       146
#define SPIO_PLIC_PERSTN_DEASSERT_INTR_ID     147
#define SPIO_PLIC_RESERVED0_INTR_ID           148
#define SPIO_PLIC_RESERVED1_INTR_ID           149
#define SPIO_PLIC_RESERVED2_INTR_ID           150
#define SPIO_PLIC_RESERVED3_INTR_ID           151
#define SPIO_PLIC_RESERVED4_INTR_ID           152
#define SPIO_PLIC_RESERVED5_INTR_ID           153
#define SPIO_PLIC_RESERVED6_INTR_ID           154
#define SPIO_PLIC_RESERVED7_INTR_ID           155

#define SPIO_PLIC_INTR_SRC_CNT                156


#ifdef __cplusplus
}
#endif

#endif	/* __SPIO_PLIC_DEVICE_H*/



