/*------------------------------------------------------------------------- 
* Copyright (C) 2018, Esperanto Technologies Inc. 
* The copyright to the computer program(s) herein is the 
* property of Esperanto Technologies.
* The program(s) may be used and/or copied only with
* the written permission of Esperanto Technologies or 
* in accordance with the terms and conditions stipulated in the 
* agreement/contract under which the program(s) have been supplied. 
*------------------------------------------------------------------------- 
*/

/**
* @file spio_pll_regTest.h 
* @version $Release$ 
* @date $Date$
* @author 
*
* @brief 
*
* Setup SoC to enable TC run 
*/ 
/** 
 *  @Component      HAL
 *
 *  @Filename       spio_pll_regTest.h
 *
 *  @Description    IPs register table 
 *
 *//*======================================================================== */

#include "mvls_tn7_hpdpll.ipxact.h"


REGTEST_t spio_pllRegs[] =

{

/* regAddress                                        regSize                       resetValue                                        bitMask                                           regName                            */   

// {  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER0_OFFSET*4,       REGTEST_SIZE_32_BIT,          MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER0_RESET_VALUE,  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER0_WRITE_MASK,   "Register0",                       },   

//{  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER1_OFFSET*4,       REGTEST_SIZE_32_BIT,          MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER1_RESET_VALUE,  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER1_WRITE_MASK,   "Register1",                       },   

//{  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER2_OFFSET*4,       REGTEST_SIZE_32_BIT,          MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER2_RESET_VALUE,  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER2_WRITE_MASK,   "Register2",                       },   

// {  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER3_OFFSET*4,       REGTEST_SIZE_32_BIT,          MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER3_RESET_VALUE,  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER3_WRITE_MASK,   "Register3",                       },   

//{  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER4_OFFSET*4,       REGTEST_SIZE_32_BIT,          MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER4_RESET_VALUE,  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER4_WRITE_MASK,   "Register4",                       },   

{  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER5_OFFSET*4,       REGTEST_SIZE_32_BIT,          MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER5_RESET_VALUE,  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER5_WRITE_MASK,   "Register5",                       },   

{  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER6_OFFSET*4,       REGTEST_SIZE_32_BIT,          MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER6_RESET_VALUE,  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER6_WRITE_MASK,   "Register6",                       },   

//{  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER7_OFFSET*4,       REGTEST_SIZE_32_BIT,          MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER7_RESET_VALUE,  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER7_WRITE_MASK,   "Register7",                       },   

{  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER8_OFFSET*4,       REGTEST_SIZE_32_BIT,          MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER8_RESET_VALUE,  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER8_WRITE_MASK,   "Register8",                       },   

{  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER9_OFFSET*4,       REGTEST_SIZE_32_BIT,          MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER9_RESET_VALUE,  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER9_WRITE_MASK,   "Register9",                       },   

//{  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER10_OFFSET*4,      REGTEST_SIZE_32_BIT,          MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER10_RESET_VALUE, MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER10_WRITE_MASK,  "Register10",                      },   

// {  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER11_OFFSET*4,      REGTEST_SIZE_32_BIT,          MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER11_RESET_VALUE, MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER11_WRITE_MASK,  "Register11",                      },   

{  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER12_OFFSET*4,      REGTEST_SIZE_32_BIT,          MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER12_RESET_VALUE, MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER12_WRITE_MASK,  "Register12",                      },   

{  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER13_OFFSET*4,      REGTEST_SIZE_32_BIT,          MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER13_RESET_VALUE, MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER13_WRITE_MASK,  "Register13",                      },   

//{  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER14_OFFSET*4,      REGTEST_SIZE_32_BIT,          MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER14_RESET_VALUE, MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER14_WRITE_MASK,  "Register14",                      },   

//{  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER18_OFFSET*4,      REGTEST_SIZE_32_BIT,          MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER18_RESET_VALUE, MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER18_WRITE_MASK,  "Register18",                      },   

//{  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER22_OFFSET*4,      REGTEST_SIZE_32_BIT,          MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER22_RESET_VALUE, MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER22_WRITE_MASK,  "Register22",                      },   

//{  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER23_OFFSET*4,      REGTEST_SIZE_32_BIT,          MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER23_RESET_VALUE, MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER23_WRITE_MASK,  "Register23",                      },   

//{  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER24_OFFSET*4,      REGTEST_SIZE_32_BIT,          MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER24_RESET_VALUE, MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER24_WRITE_MASK,  "Register24",                      },   

//{  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER25_OFFSET*4,      REGTEST_SIZE_32_BIT,          MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER25_RESET_VALUE, MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER25_WRITE_MASK,  "Register25",                      },   

//{  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER26_OFFSET*4,      REGTEST_SIZE_32_BIT,          MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER26_RESET_VALUE, MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER26_WRITE_MASK,  "Register26",                      },   

//{  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER27_OFFSET*4,      REGTEST_SIZE_32_BIT,          MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER27_RESET_VALUE, MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER27_WRITE_MASK,  "Register27",                      },   

//{  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER28_OFFSET*4,      REGTEST_SIZE_32_BIT,          MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER28_RESET_VALUE, MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER28_WRITE_MASK,  "Register28",                      },   

//{  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER29_OFFSET*4,      REGTEST_SIZE_32_BIT,          MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER29_RESET_VALUE, MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER29_WRITE_MASK,  "Register29",                      },   

//{  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER30_OFFSET*4,      REGTEST_SIZE_32_BIT,          MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER30_RESET_VALUE, MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER30_WRITE_MASK,  "Register30",                      },   

//{  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER31_OFFSET*4,      REGTEST_SIZE_32_BIT,          MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER31_RESET_VALUE, MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER31_WRITE_MASK,  "Register31",                      },   

{  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER32_OFFSET*4,      REGTEST_SIZE_32_BIT,          MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER32_RESET_VALUE, MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER32_WRITE_MASK,  "Register32",                      },   

//{  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER33_OFFSET*4,      REGTEST_SIZE_32_BIT,          MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER33_RESET_VALUE, MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER33_WRITE_MASK,  "Register33",                      },   

//{  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER34_OFFSET*4,      REGTEST_SIZE_32_BIT,          MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER34_RESET_VALUE, MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER34_WRITE_MASK,  "Register34",                      },   

//{  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER35_OFFSET*4,      REGTEST_SIZE_32_BIT,          MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER35_RESET_VALUE, MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER35_WRITE_MASK,  "Register35",                      },   

//{  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER36_OFFSET*4,      REGTEST_SIZE_32_BIT,          MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER36_RESET_VALUE, MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER36_WRITE_MASK,  "Register36",                      },   

//{  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER37_OFFSET*4,      REGTEST_SIZE_32_BIT,          MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER37_RESET_VALUE, MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER37_WRITE_MASK,  "Register37",                      },   

//{  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER38_OFFSET*4,      REGTEST_SIZE_32_BIT,          MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER38_RESET_VALUE, MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER38_WRITE_MASK,  "Register38",                      },   

{  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER39_OFFSET*4,      REGTEST_SIZE_32_BIT,          MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER39_RESET_VALUE, MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER39_WRITE_MASK,  "Register39",                      },   

//{  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER40_OFFSET*4,      REGTEST_SIZE_32_BIT,          MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER40_RESET_VALUE, MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER40_WRITE_MASK,  "Register40",                      },   

//{  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER48_OFFSET*4,      REGTEST_SIZE_32_BIT,          MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER48_RESET_VALUE, MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER48_WRITE_MASK,  "Register48",                      },   

//{  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER49_OFFSET*4,      REGTEST_SIZE_32_BIT,          MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER49_RESET_VALUE, MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER49_WRITE_MASK,  "Register49",                      },   

//{  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER50_OFFSET*4,      REGTEST_SIZE_32_BIT,          MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER50_RESET_VALUE, MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER50_WRITE_MASK,  "Register50",                      },   

//{  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER51_OFFSET*4,      REGTEST_SIZE_32_BIT,          MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER51_RESET_VALUE, MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER51_WRITE_MASK,  "Register51",                      },   

//{  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER52_OFFSET*4,      REGTEST_SIZE_32_BIT,          MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER52_RESET_VALUE, MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER52_WRITE_MASK,  "Register52",                      },   

//{  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER53_OFFSET*4,      REGTEST_SIZE_32_BIT,          MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER53_RESET_VALUE, MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER53_WRITE_MASK,  "Register53",                      },   

//{  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER54_OFFSET*4,      REGTEST_SIZE_32_BIT,          MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER54_RESET_VALUE, MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER54_WRITE_MASK,  "Register54",                      },   

//{  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER56_OFFSET*4,      REGTEST_SIZE_32_BIT,          MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER56_RESET_VALUE, MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER56_WRITE_MASK,  "Register56",                      },   

//{  MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER57_OFFSET*4,      REGTEST_SIZE_32_BIT,          MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER57_RESET_VALUE, MVLS_TN7_HPDPLL_MAIN_MAIN_REGISTER57_WRITE_MASK,  "Register57",                      },   

   /* End List Delimiter */

{  REGTEST_END_OF_LIST,                              0,                            0,                                                0,                                                0,                                 }    

};  

