#ifndef EXCEPTION_CODES_H
#define EXCEPTION_CODES_H

typedef enum
{
    EXCEPTION_INSTRUCTION_ADDRESS_MISALIGNED = 0,
    EXCEPTION_INSTRUCTION_ACCESS_FAULT,
    EXCEPTION_ILLEGAL_INSTRUCTION,
    EXCEPTION_BREAKPOINT,
    EXCEPTION_LOAD_ADDRESS_MISALIGNED,
    EXCEPTION_LOAD_ACCESS_FAULT,
    EXCEPTION_STORE_AMO_ADDRESS_MISALIGNED,
    EXCEPTION_STORE_AMO_ACCESS_FAULT,
    EXCEPTION_ENVIRONMENT_CALL_FROM_U_MODE,
    EXCEPTION_ENVIRONMENT_CALL_FROM_S_MODE,
    EXCEPTION_RESERVED_A,
    EXCEPTION_ENVIRONMENT_CALL_FROM_M_MODE,
    EXCEPTION_INSTRUCTION_PAGE_FAULT,
    EXCEPTION_LOAD_PAGE_FAULT,
    EXCEPTION_RESERVED_E,
    EXCEPTION_STORE_AMO_PAGE_FAULT,
    EXCEPTION_UNKOWN_10,
    EXCEPTION_UNKOWN_11,
    EXCEPTION_UNKOWN_12,
    EXCEPTION_UNKOWN_13,
    EXCEPTION_UNKOWN_14,
    EXCEPTION_UNKOWN_15,
    EXCEPTION_UNKOWN_16,
    EXCEPTION_UNKOWN_17,
    EXCEPTION_UNKOWN_18,
    EXCEPTION_FETCH_BUS_ERROR,
    EXCEPTION_FETCH_ECC_ERROR,
    EXCEPTION_LOAD_PAGE_SPLIT_FAULT,
    EXCEPTION_STORE_PAGE_SPLIT_FAULT,
    EXCEPTION_BUS_ERROR,
    EXCEPTION_MCODE_INSTRUCTION,
    EXCEPTION_TXFMA_OFF,
} exception_t;

#endif
