#ifndef KERNEL_STATE_H
#define KERNEL_STATE_H

typedef enum {
    KERNEL_STATE_UNUSED = 0,
    KERNEL_STATE_LAUNCHED,
    KERNEL_STATE_RUNNING,
    KERNEL_STATE_ABORTED,
    KERNEL_STATE_ERROR,
    KERNEL_STATE_COMPLETE,
    KERNEL_STATE_UNKNOWN
} kernel_state_t;

#endif
