#ifndef LAYOUT_H
#define LAYOUT_H

// aligns an address to the next 64-byte cache line
#define CACHE_LINE_ALIGN(x) (((x + 63U) / 64U) * 64U)

#define NUM_SHIRES 33
#define HARTS_PER_SHIRE 64
#define NUM_HARTS (NUM_SHIRES * HARTS_PER_SHIRE)

#define MESSAGE_FLAG_SIZE 8
#define MESSAGE_BUFFER_SIZE 64

// M-mode firmware and stacks placed in R_L3_Mcode region, 2MB 0x8000000000 - 0x8000200000
#define FW_MACHINE_MMODE_ENTRY  0x8000001000ULL // Default reset vector
#define FW_MMODE_STACK_BASE     0x8000200000ULL
#define FW_MMODE_STACK_SIZE     768 // Large enough for reentrant M-mode traps, but small enough so all 2112 stacks + code fit in 2MB region

// S-mode firmware and U-mode kernel placed in R_L3_DRAM region, 28GB 0x8100000000 - 0x8800000000
#define FW_WORKER_TO_MASTER_MESSAGE_FLAGS            0x8100000000ULL
#define FW_WORKER_TO_MASTER_MESSAGE_FLAGS_SIZE       (NUM_SHIRES * MESSAGE_FLAG_SIZE)

#define FW_WORKER_TO_MASTER_MESSAGE_BUFFERS          CACHE_LINE_ALIGN(FW_WORKER_TO_MASTER_MESSAGE_FLAGS + FW_WORKER_TO_MASTER_MESSAGE_FLAGS_SIZE)
#define FW_WORKER_TO_MASTER_MESSAGE_BUFFERS_SIZE     (NUM_HARTS * MESSAGE_BUFFER_SIZE)

#define FW_MASTER_TO_WORKER_MESSAGE_BUFFERS          CACHE_LINE_ALIGN(FW_WORKER_TO_MASTER_MESSAGE_BUFFERS + FW_WORKER_TO_MASTER_MESSAGE_BUFFERS_SIZE)
#define FW_MASTER_TO_WORKER_MESSAGE_BUFFERS_SIZE     (NUM_HARTS * MESSAGE_BUFFER_SIZE)

#define FW_MASTER_TO_WORKER_BROADCAST_MESSAGE_BUFFER CACHE_LINE_ALIGN(FW_MASTER_TO_WORKER_MESSAGE_BUFFERS + FW_MASTER_TO_WORKER_MESSAGE_BUFFERS_SIZE)
#define FW_MASTER_TO_WORKER_BROADCAST_MESSAGE_BUFFER_SIZE MESSAGE_BUFFER_SIZE

#define FW_MASTER_SMODE_ENTRY   0x8100200000ULL
#define FW_WORKER_SMODE_ENTRY   0x8100400000ULL

#define FW_SMODE_STACK_BASE     0x8102000000ULL
#define FW_SMODE_STACK_SIZE     4096 // 4K for VM stack pages

#define KERNEL_UMODE_STACK_BASE 0x8103000000ULL
#define KERNEL_UMODE_STACK_SIZE 4096 // 4K for VM stack pages

#define KERNEL_UMODE_ENTRY      0x8104000000ULL
#endif
