#ifndef MAILBOX_ID_H
#define MAILBOX_ID_H

typedef uint64_t mbox_message_id_t;

typedef enum
{
    MBOX_MESSAGE_ID_NONE = 0,
    MBOX_MESSAGE_ID_KERNEL_LAUNCH,
    MBOX_MESSAGE_ID_KERNEL_LAUNCH_RESPONSE,
    MBOX_MESSAGE_ID_KERNEL_RESULT,
    MBOX_MESSAGE_ID_KERNEL_ABORT,
    MBOX_MESSAGE_ID_KERNEL_ABORT_RESPONSE,
    MBOX_MESSAGE_ID_GET_KERNEL_STATE,
    MBOX_MESSAGE_ID_GET_KERNEL_STATE_RESPONSE,
    MBOX_MESSAGE_ID_REFLECT_TEST
} mbox_message_id_e;


typedef uint64_t mbox_response_id_t;

typedef enum {
    MBOX_KERNEL_LAUNCH_RESPONSE_OK = 0,
    MBOX_KERNEL_LAUNCH_RESPONSE_ERROR_SHIRES_NOT_READY,
    MBOX_KERNEL_LAUNCH_RESPONSE_ERROR,
    MBOX_KERNEL_LAUNCH_RESPONSE_RESULT_OK,
    MBOX_KERNEL_LAUNCH_RESPONSE_RESULT_ERROR,
    MBOX_KERNEL_ABORT_RESPONSE_RESULT_OK,
    MBOX_KERNEL_ABORT_RESPONSE_RESULT_ERROR
} mbox_kernel_launch_reponse_e;

typedef enum {
    MBOX_KERNEL_RESULT_OK = 0,
    MBOX_KERNEL_RESULT_ERROR
} mbox_kernel_result_e;

#endif
