#ifndef __SERVICE_PROCESSOR_SPI_FLASH_H__
#define __SERVICE_PROCESSOR_SPI_FLASH_H__

typedef enum SPI_FLASH_ID {
    SPI_FLASH_INVALID,
    SPI_FLASH_ON_PACKAGE,
    SPI_FLASH_OFF_PACKAGE
} SPI_FLASH_ID_t;

#endif
