#ifndef SYSCALL_INTERNAL_H
#define SYSCALL_INTERNAL_H

#include <stdint.h>
#include "syscall.h"

enum {
    // From S-mode to M-mode [0-299]
    SYSCALL_BROADCAST_INT = 0,
    SYSCALL_IPI_TRIGGER_INT,
    SYSCALL_ENABLE_THREAD1_INT,
    SYSCALL_PRE_KERNEL_SETUP_INT,
    SYSCALL_POST_KERNEL_CLEANUP_INT,
    SYSCALL_GET_MTIME_INT,
    SYSCALL_CACHE_CONTROL_INT,
    SYSCALL_FLUSH_L3_INT,
    SYSCALL_EVICT_L3_INT,
    SYSCALL_SHIRE_CACHE_BANK_OP_INT,
    SYSCALL_EVICT_L1_INT,
};

#endif // SYSCALL_INTERNAL_H
