import:
  - path: '@ci@/ci-tools/templates/template-main-top-level.yaml'

parameters:
  SW_PLATFORM_BRANCH:
    description: SW-Platform branch to track
    type: string
    default_value: "origin/develop/system-sw"
  REPO_SSH_URL:
    description: Repository URL
    type: string
    default_value: "git@gitlab.esperanto.ai:software/et-driver.git"
  REPO_NAME:
    description: Repository name
    type: string
    default_value: "pcie-driver"
  RUN_OPS_PCIE_SYSEMU:
    description: Run OPS PCIE SysEMU job
    type: bool
    default_value: true
  RUN_MGMT_PCIE_SYSEMU:
    description: Run MGMT PCIE SysEMU job
    type: bool
    default_value: true
  RUN_VIRTUAL_PLATFORM:
    description: Run VIRTUAL_PLATFORM job
    type: bool
    default_value: true
  FORCE_CHILD_RETRIGGER:
    description: 'Forces all child jobs of the current job to retrigger even if smart-retrigger is being used'
    type: bool
    default_value: true

stages:
  CLANG_CHECK:
    cmds:
      - job: sw-platform/system-sw-integration/pipelines/linux-driver-clang-tests
        parameters:
          BRANCH: "${SW_PLATFORM_BRANCH}"
          COMPONENT_COMMITS: "${COMPONENT_COMMITS},host-software/linuxDriver/etsoc1-pcie-driver:${BRANCH}"
          NODE: WORKER
          TIMEOUT: "1"
    exec_before: [r"JOB_.*"]
    exec_after: ['DSL_JOB']

  DM_TESTS_RECOVERY_MODE_PCIE_SYSEMU:
    cmds:
      - job: sw-platform/virtual-platform/pipelines/dm-tests-recovery-mode-pcie-sysemu-1dev
        parameters:
          BRANCH: "${SW_PLATFORM_BRANCH}"
          COMPONENT_COMMITS: "${COMPONENT_COMMITS},host-software/linuxDriver/etsoc1-pcie-driver:${BRANCH}"
    exec_after: ['CLANG_CHECK']

  FIRMWARE_AND_DM_TESTS_PCIE_SYSEMU:
    cmds:
      - job: sw-platform/virtual-platform/pipelines/firmware-and-dm-tests-pcie-sysemu-1dev
        parameters:
          BRANCH: "${SW_PLATFORM_BRANCH}"
          COMPONENT_COMMITS: "${COMPONENT_COMMITS},host-software/linuxDriver/etsoc1-pcie-driver:${BRANCH}"
    exec_after: ['CLANG_CHECK']
