import:
  - path: '@ci@/ci-tools/templates/template-main-top-level.yaml'

parameters:
  SW_PLATFORM_BRANCH:
    description: SW-Platform branch to track
    type: string
    default_value: "origin/develop/system-sw"

  REPO_SSH_URL:
    description: Repository URL
    type: string
    default_value: "git@gitlab.esperanto.ai:software/test-compute-kernels.git"

  REPO_NAME:
    description: Repository name
    type: string
    default_value: "test-compute-kernels"

stages:
  JOB_CHECK_IN:
    cmds:
      - job: sw-platform/system-sw-integration/pipelines/test-compute-kernels-build
        parameters:
          BRANCH: "${SW_PLATFORM_BRANCH}"
          COMPONENT_COMMITS: "${COMPONENT_COMMITS},device-software/test-compute-kernels:${BRANCH}"

  JOB_FIRMWARE_TESTS_PCIE_SYSEMU:
    cmds:
      - job: sw-platform/virtual-platform/pipelines/firmware-tests-pcie-sysemu-1dev
        parameters:
          BRANCH: "${SW_PLATFORM_BRANCH}"
          COMPONENT_COMMITS: "${COMPONENT_COMMITS},device-software/test-compute-kernels:${BRANCH}"
