#ifndef INTERRUPT_H
#define INTERRUPT_H

//TODO FIXME generate these. Copied by hand by wearle 5/3/2019.
//See esperanto-soc/dv/tests/ioshire/sw/inc/pu_plic_intr_device.h

typedef enum {
    PU_PLIC_NO_INTERRUPT_INTR = 0,
    PU_PLIC_I2C_INTR,
    PU_PLIC_SPI_INTR,
    PU_PLIC_UART0_INTR,
    PU_PLIC_GPIO_INTR,
    PU_PLIC_WDT_INTR,
    PU_PLIC_TIMER0_INTR,
    PU_PLIC_TIMER1_INTR,
    PU_PLIC_TIMER2_INTR,
    PU_PLIC_TIMER3_INTR,
    PU_PLIC_TIMER4_INTR,
    PU_PLIC_TIMER5_INTR,
    PU_PLIC_TIMER6_INTR,
    PU_PLIC_TIMER7_INTR,
    PU_PLIC_I3C_INTR,
    PU_PLIC_UART1_INTR,
    PU_PLIC_PCIE0_DMA_DONE0_INTR,
    PU_PLIC_PCIE0_DMA_DONE1_INTR,
    PU_PLIC_PCIE0_DMA_DONE2_INTR,
    PU_PLIC_PCIE0_DMA_DONE3_INTR,
    PU_PLIC_PCIE0_DMA_DONE4_INTR,
    PU_PLIC_PCIE0_DMA_DONE5_INTR,
    PU_PLIC_PCIE0_DMA_DONE6_INTR,
    PU_PLIC_PCIE0_DMA_DONE7_INTR,
    PU_PLIC_PCIE_MSI_INTR,
    PU_PLIC_USB20_INTR,
    PU_PLIC_USB21_INTR,
    PU_PLIC_DMA_INTR,
    PU_PLIC_EMMC_INTR,
    PU_PLIC_PCIE_RADM_INTA_INTR,
    PU_PLIC_PCIE_RADM_INTB_INTR,
    PU_PLIC_PCIE_RADM_INTC_INTR,
    PU_PLIC_PCIE_RADM_INTD_INTR,
    PU_PLIC_PCIE_MESSAGE_INTR,
    PU_PLIC_RESERVED0_INTR,
    PU_PLIC_RESERVED1_INTR,
    PU_PLIC_RESERVED2_INTR,
    PU_PLIC_RESERVED3_INTR,
    PU_PLIC_RESERVED4_INTR,
    PU_PLIC_RESERVED5_INTR,
    PU_PLIC_RESERVED6_INTR,
    PU_PLIC_RESERVED7_INTR,
    PU_PLIC_INTR_CNT
} interrupt_t;

#endif
