/***********************************************************************
*
* Copyright (C) 2020 Esperanto Technologies Inc.
* The copyright to the computer program(s) herein is the
* property of Esperanto Technologies, Inc. All Rights Reserved.
* The program(s) may be used and/or copied only with
* the written permission of Esperanto Technologies and
* in accordance with the terms and conditions stipulated in the
* agreement/contract under which the program(s) have been supplied.
*
************************************************************************/
/*! \file interrupt.h
    \brief A C header that defines the interrupt controller's
    public interfaces. These interfaces provide services using which
    the host can enable/disable interrupts.
*/
/***********************************************************************/

#pragma once

#include <stdint.h>
#include <stdbool.h>

/* TODO FIXME generate these. Copied by hand by wearle 5/3/2019.
  See esperanto-soc/dv/tests/ioshire/sw/inc/pu_plic_intr_device.h
  and esperanto-soc/dv/tests/ioshire/sw/inc/spio_plic_intr_device.h */

/**
 * @enum interrupt_t
 * @brief Enum defining interrupts
 */
typedef enum {
    SPIO_PLIC_NO_INTERRUPT_INTR = 0,
    SPIO_PLIC_MINSHIRE_ERR0_INTR,
    SPIO_PLIC_MINSHIRE_ERR1_INTR,
    SPIO_PLIC_MINSHIRE_ERR2_INTR,
    SPIO_PLIC_MINSHIRE_ERR3_INTR,
    SPIO_PLIC_MINSHIRE_ERR4_INTR,
    SPIO_PLIC_MINSHIRE_ERR5_INTR,
    SPIO_PLIC_MINSHIRE_ERR6_INTR,
    SPIO_PLIC_MINSHIRE_ERR7_INTR,
    SPIO_PLIC_MINSHIRE_ERR8_INTR,
    SPIO_PLIC_MINSHIRE_ERR9_INTR,
    SPIO_PLIC_MINSHIRE_ERR10_INTR,
    SPIO_PLIC_MINSHIRE_ERR11_INTR,
    SPIO_PLIC_MINSHIRE_ERR12_INTR,
    SPIO_PLIC_MINSHIRE_ERR13_INTR,
    SPIO_PLIC_MINSHIRE_ERR14_INTR,
    SPIO_PLIC_MINSHIRE_ERR15_INTR,
    SPIO_PLIC_MINSHIRE_ERR16_INTR,
    SPIO_PLIC_MINSHIRE_ERR17_INTR,
    SPIO_PLIC_MINSHIRE_ERR18_INTR,
    SPIO_PLIC_MINSHIRE_ERR19_INTR,
    SPIO_PLIC_MINSHIRE_ERR20_INTR,
    SPIO_PLIC_MINSHIRE_ERR21_INTR,
    SPIO_PLIC_MINSHIRE_ERR22_INTR,
    SPIO_PLIC_MINSHIRE_ERR23_INTR,
    SPIO_PLIC_MINSHIRE_ERR24_INTR,
    SPIO_PLIC_MINSHIRE_ERR25_INTR,
    SPIO_PLIC_MINSHIRE_ERR26_INTR,
    SPIO_PLIC_MINSHIRE_ERR27_INTR,
    SPIO_PLIC_MINSHIRE_ERR28_INTR,
    SPIO_PLIC_MINSHIRE_ERR29_INTR,
    SPIO_PLIC_MINSHIRE_ERR30_INTR,
    SPIO_PLIC_MINSHIRE_ERR31_INTR,
    SPIO_PLIC_MINSHIRE_ERR32_INTR,
    SPIO_PLIC_MINSHIRE_ERR33_INTR,
    SPIO_PLIC_MINSHIRE_NOC0_INTR,
    SPIO_PLIC_MINSHIRE_NOC1_INTR,
    SPIO_PLIC_MINSHIRE_NOC2_INTR,
    SPIO_PLIC_MINSHIRE_NOC3_INTR,
    SPIO_PLIC_MINSHIRE_NOC4_INTR,
    SPIO_PLIC_MINSHIRE_NOC5_INTR,
    SPIO_PLIC_MINSHIRE_NOC6_INTR,
    SPIO_PLIC_MINSHIRE_NOC7_INTR,
    SPIO_PLIC_MINSHIRE_NOC8_INTR,
    SPIO_PLIC_MINSHIRE_NOC9_INTR,
    SPIO_PLIC_MINSHIRE_NOC10_INTR,
    SPIO_PLIC_MINSHIRE_NOC11_INTR,
    SPIO_PLIC_MINSHIRE_NOC12_INTR,
    SPIO_PLIC_MINSHIRE_NOC13_INTR,
    SPIO_PLIC_MINSHIRE_NOC14_INTR,
    SPIO_PLIC_MINSHIRE_NOC15_INTR,
    SPIO_PLIC_MINSHIRE_NOC16_INTR,
    SPIO_PLIC_MINSHIRE_NOC17_INTR,
    SPIO_PLIC_MINSHIRE_NOC18_INTR,
    SPIO_PLIC_MINSHIRE_NOC19_INTR,
    SPIO_PLIC_MINSHIRE_NOC20_INTR,
    SPIO_PLIC_MINSHIRE_NOC21_INTR,
    SPIO_PLIC_MINSHIRE_NOC22_INTR,
    SPIO_PLIC_MINSHIRE_NOC23_INTR,
    SPIO_PLIC_MINSHIRE_NOC24_INTR,
    SPIO_PLIC_MINSHIRE_NOC25_INTR,
    SPIO_PLIC_MINSHIRE_NOC26_INTR,
    SPIO_PLIC_MINSHIRE_NOC27_INTR,
    SPIO_PLIC_MINSHIRE_NOC28_INTR,
    SPIO_PLIC_MINSHIRE_NOC29_INTR,
    SPIO_PLIC_MINSHIRE_NOC30_INTR,
    SPIO_PLIC_MINSHIRE_NOC31_INTR,
    SPIO_PLIC_MINSHIRE_NOC32_INTR,
    SPIO_PLIC_MINSHIRE_NOC33_INTR,
    SPIO_PLIC_MAXSHIRE_ERR_INTR,
    SPIO_PLIC_MEMSHIRE_CRIT_E0_INTR,
    SPIO_PLIC_MEMSHIRE_CRIT_E1_INTR,
    SPIO_PLIC_MEMSHIRE_CRIT_E2_INTR,
    SPIO_PLIC_MEMSHIRE_CRIT_E3_INTR,
    SPIO_PLIC_MEMSHIRE_CRIT_W0_INTR,
    SPIO_PLIC_MEMSHIRE_CRIT_W1_INTR,
    SPIO_PLIC_MEMSHIRE_CRIT_W2_INTR,
    SPIO_PLIC_MEMSHIRE_CRIT_W3_INTR,
    SPIO_PLIC_MEMSHIRE_NOC_E0_INTR,
    SPIO_PLIC_MEMSHIRE_NOC_E1_INTR,
    SPIO_PLIC_MEMSHIRE_NOC_E2_INTR,
    SPIO_PLIC_MEMSHIRE_NOC_E3_INTR,
    SPIO_PLIC_MEMSHIRE_NOC_W0_INTR,
    SPIO_PLIC_MEMSHIRE_NOC_W1_INTR,
    SPIO_PLIC_MEMSHIRE_NOC_W2_INTR,
    SPIO_PLIC_MEMSHIRE_NOC_W3_INTR,
    SPIO_PLIC_MEMSHIRE_NORM_E0_INTR,
    SPIO_PLIC_MEMSHIRE_NORM_E1_INTR,
    SPIO_PLIC_MEMSHIRE_NORM_E2_INTR,
    SPIO_PLIC_MEMSHIRE_NORM_E3_INTR,
    SPIO_PLIC_MEMSHIRE_NORM_W0_INTR,
    SPIO_PLIC_MEMSHIRE_NORM_W1_INTR,
    SPIO_PLIC_MEMSHIRE_NORM_W2_INTR,
    SPIO_PLIC_MEMSHIRE_NORM_W3_INTR,
    SPIO_PLIC_PSHIRE_PCIE0_ERR_INTR,
    SPIO_PLIC_PSHIRE_PCIE1_ERR_INTR,
    SPIO_PLIC_PSHIRE_PCIE0_EDMA0_INTR,
    SPIO_PLIC_PSHIRE_PCIE0_EDMA1_INTR,
    SPIO_PLIC_PSHIRE_PCIE0_EDMA2_INTR,
    SPIO_PLIC_PSHIRE_PCIE0_EDMA3_INTR,
    SPIO_PLIC_PSHIRE_PCIE0_EDMA4_INTR,
    SPIO_PLIC_PSHIRE_PCIE0_EDMA5_INTR,
    SPIO_PLIC_PSHIRE_PCIE0_EDMA6_INTR,
    SPIO_PLIC_PSHIRE_PCIE0_EDMA7_INTR,
    SPIO_PLIC_PSHIRE_NOC_INTR,
    SPIO_PLIC_SPIO_NOC_INTR,
    SPIO_PLIC_PU_NOC_INTR,
    SPIO_PLIC_IOSHIRE_MESH_INTR,
    SPIO_PLIC_IOSHIRE_DBG_MESH_INTR,
    SPIO_PLIC_PU_PLIC0_INTR,
    SPIO_PLIC_PU_PLIC1_INTR,
    SPIO_PLIC_SP_ICACHE_ECC_INTR,
    SPIO_PLIC_DMA_INTR,
    SPIO_PLIC_MBOX_MXN_INTR,
    SPIO_PLIC_MBOX_MMIN_INTR,
    SPIO_PLIC_MBOX_HOST_INTR,
    SPIO_PLIC_I2C0_INTR,
    SPIO_PLIC_I2C1_INTR,
    SPIO_PLIC_SPI0_INTR,
    SPIO_PLIC_SPI1_INTR,
    SPIO_PLIC_UART0_INTR,
    SPIO_PLIC_UART1_INTR,
    SPIO_PLIC_GPIO_INTR,
    SPIO_PLIC_WDT_INTR,
    SPIO_PLIC_PU_WDT_INTR,
    SPIO_PLIC_TIMER0_INTR,
    SPIO_PLIC_TIMER1_INTR,
    SPIO_PLIC_TIMER2_INTR,
    SPIO_PLIC_TIMER3_INTR,
    SPIO_PLIC_TIMER4_INTR,
    SPIO_PLIC_TIMER5_INTR,
    SPIO_PLIC_TIMER6_INTR,
    SPIO_PLIC_TIMER7_INTR,
    SPIO_PLIC_CRU_INTR,
    SPIO_PLIC_CRU_SW_INTR,
    SPIO_PLIC_PVTC0_INTR,
    SPIO_PLIC_PVTC1_INTR,
    SPIO_PLIC_PVTC2_INTR,
    SPIO_PLIC_PVTC3_INTR,
    SPIO_PLIC_PVTC4_INTR,
    SPIO_PLIC_VAULT_SECURE_INTR,
    SPIO_PLIC_VAULT_INTR,
    SPIO_PLIC_US_DBG_UPSTR_INTR,
    SPIO_PLIC_US_DBG_DOWNSTR_INTR,
    SPIO_PLIC_SMS_SFP_READY_INTR,
    SPIO_PLIC_SMS_SFP_FAIL_INTR,
    SPIO_PLIC_PERSTN_ASSERT_INTR,
    SPIO_PLIC_PERSTN_DEASSERT_INTR,
    SPIO_PLIC_RESERVED0_INTR,
    SPIO_PLIC_RESERVED1_INTR,
    SPIO_PLIC_RESERVED2_INTR,
    SPIO_PLIC_RESERVED3_INTR,
    SPIO_PLIC_RESERVED4_INTR,
    SPIO_PLIC_RESERVED5_INTR,
    SPIO_PLIC_RESERVED6_INTR,
    SPIO_PLIC_RESERVED7_INTR,
    PU_PLIC_NO_INTERRUPT_INTR,
    PU_PLIC_I2C_INTR,
    PU_PLIC_SPI_INTR,
    PU_PLIC_UART0_INTR,
    PU_PLIC_GPIO_INTR,
    PU_PLIC_WDT_INTR,
    PU_PLIC_TIMER0_INTR,
    PU_PLIC_TIMER1_INTR,
    PU_PLIC_TIMER2_INTR,
    PU_PLIC_TIMER3_INTR,
    PU_PLIC_TIMER4_INTR,
    PU_PLIC_TIMER5_INTR,
    PU_PLIC_TIMER6_INTR,
    PU_PLIC_TIMER7_INTR,
    PU_PLIC_I3C_INTR,
    PU_PLIC_UART1_INTR,
    PU_PLIC_PCIE0_DMA_DONE0_INTR,
    PU_PLIC_PCIE0_DMA_DONE1_INTR,
    PU_PLIC_PCIE0_DMA_DONE2_INTR,
    PU_PLIC_PCIE0_DMA_DONE3_INTR,
    PU_PLIC_PCIE0_DMA_DONE4_INTR,
    PU_PLIC_PCIE0_DMA_DONE5_INTR,
    PU_PLIC_PCIE0_DMA_DONE6_INTR,
    PU_PLIC_PCIE0_DMA_DONE7_INTR,
    PU_PLIC_PCIE_MSI_INTR,
    PU_PLIC_USB20_INTR,
    PU_PLIC_USB21_INTR,
    PU_PLIC_DMA_INTR,
    PU_PLIC_EMMC_INTR,
    PU_PLIC_PCIE_RADM_INTA_INTR,
    PU_PLIC_PCIE_RADM_INTB_INTR,
    PU_PLIC_PCIE_RADM_INTC_INTR,
    PU_PLIC_PCIE_RADM_INTD_INTR,
    PU_PLIC_PCIE_MESSAGE_INTR,
    PU_PLIC_RESERVED0_INTR,
    PU_PLIC_RESERVED1_INTR,
    PU_PLIC_RESERVED2_INTR,
    PU_PLIC_RESERVED3_INTR,
    PU_PLIC_RESERVED4_INTR,
    PU_PLIC_RESERVED5_INTR,
    PU_PLIC_RESERVED6_INTR,
    PU_PLIC_RESERVED7_INTR,
} interrupt_t;

/*! \fn void INT_init(void)
    \brief This function initialized interrupt controller driver
    \param None flash device id
    \return none
*/
void INT_init(void);

/*! \fn void INT_enableInterrupt(interrupt_t interrupt, uint32_t priority, void (*isr)(void))
    \brief This function enables interrupt
    \param interrupt interrupt id
    \param priority - interrupt priority
    \param isr - interrupt service routine
    \return The function call status, pass/fail.
*/
void INT_enableInterrupt(interrupt_t interrupt, uint32_t priority, void (*isr)(void));

/*! \fn void INT_disableInterrupt(interrupt_t interrupt)
    \brief This function disables interrupt
    \param interrupt interrupt id
    \return The function call status, pass/fail.
*/
void INT_disableInterrupt(interrupt_t interrupt);

/*! \fn INT_Is_Trap_Context(void)
    \brief This function returns context state variable value to determine if it is 
           a trap context or not.
    \return None.
*/
bool INT_Is_Trap_Context(void);
