include:
  - project: esperantotech/software/gitlab-ci-common
    ref: 1be8a1ec31da665910e1b2b193fcfa1d05866299
    file:
      - 'pods/nano-pod.yaml'
      - 'jobs/generic-k8s-job.yaml'
      - 'rules/generic-workflow-conan.yaml'
  - project: esperantotech/software/gitlab-ci-common
    ref: master
    file:
      - 'jobs/conan-jobs.yaml'

stages:
  - generate_build
  - build
  - deploy

###############################################################################
###############################################################################
###############################################################################

generate_build:conan:
  extends:
    - .pod_nano
    - .template_job
    - .template-conan-linux-ubuntu18.04-gcc7
  stage: generate_build

  variables:
    TIMEOUT: 15m

    CMD_BUILD: |
      cd conan
      python3 -m pip install "ecpt>=2.0.0,<3.0.0" --index-url https://sc-artifactory1.esperanto.ai/artifactory/api/pypi/pypi-virtual/simple
      python3 -m ci_build
  artifacts:
    expire_in: 1h 
    paths:
      - conan/build_pipeline.yml
      - conan/lockfiles_info.json

###############################################################################
###############################################################################
###############################################################################

build:conan:
  needs:
  - generate_build:conan
  stage: build
  trigger:
    include:
    - artifact: conan/build_pipeline.yml
      job: generate_build:conan
    strategy: depend

###############################################################################
###############################################################################
###############################################################################

on_success:promote:
  extends:
    - .pod_nano
    - .template_job
    - .template-conan-linux-ubuntu18.04-gcc7
  stage: deploy
  needs:
    - generate_build:conan
    - build:conan
  variables:
    PYTHONIOENCODING: utf-8
    CMD_BUILD: |
      cd conan
      python3 -m pip install "ecpt>=2.0.0,<3.0.0" --index-url https://sc-artifactory1.esperanto.ai/artifactory/api/pypi/pypi-virtual/simple
      python3 -m ci_promote

###############################################################################
############################## Conan 2 ########################################
###############################################################################

build:conan2:
  extends:
    - .pod_nano
    - .template_job
    - .template-conan2-linux-ubuntu22.04-gcc11
  stage: build
  needs: []
  script:
    - conan lock create conanfile.py --profile linux-ubuntu22.04-x86_64-gcc11-release  # Create the lockfile with the profile
    - conan install . --build=missing # Install dependencies from the lockfile
  artifacts:
    paths:
      - conan.lock  # Keep the lockfile as an artifact for later stages

on_success:package2:
  extends:
    - .pod_nano
    - .template_job
    - .template-conan2-linux-ubuntu22.04-gcc11
  needs: 
    - build:conan2
  stage: package
  script:
    - mv conan.lock linux-ubuntu22.04-x86_64-gcc11-release.lock
    - conan create . --lockfile=linux-ubuntu22.04-x86_64-gcc11-release.lock --lockfile-out=linux-ubuntu22.04-x86_64-gcc11-release.lock --build=missing  # Create the package based on the lockfile
    - conan list "*:*" --format=json > pkglist-linux-ubuntu22.04-x86_64-gcc11-release.json
    - conan upload --list=pkglist-linux-ubuntu22.04-x86_64-gcc11-release.json --format=json -r=conan2-tmp --confirm # Upload package to Artifactory
    - if [ -n "$CI_MERGE_REQUEST_IID" ]; then
         - conan pkglist find-remote --format=json -r=conan2-tmp pkglist-linux-ubuntu22.04-x86_64-gcc11-release.json > pkglist-merged-with-remote.json
         - conan download --list=pkglist-merged-with-remote.json --format=json -r=conan2-tmp > pkglist-downloaded.json 
         - conan upload --list=pkglist-downloaded.json --format=json -r=conan2-develop --confirm > pkglist-uploaded.
      if  #Only upload into conan2-develop if it's NOT a MR pipeline
  artifacts:
    paths:
      - linux-ubuntu22.04-x86_64-gcc11-release.lock # Keep the lockfile updated with the build stage
      - pkglist-linux-ubuntu22.04-x86_64-gcc11-release.json
