/* Copyright (c) 2025 Ainekko, Co. */
/* SPDX-License-Identifier: Apache-2.0 */
/*                                                                         */
/*                                                                         */
/* Generated by Semifore, Inc. csrCompile                                  */
/*    C Header output                                                      */

#ifndef _MX_BUS_ERR0_H_
#define _MX_BUS_ERR0_H_



/* ####################################################################### */
/*        ADDRESS MACROS                                                   */
/* ####################################################################### */

/* Address Space for Addressmap: beu                                       */
/* Register: beu.current_value                                             */
#define BEU_CURRENT_VALUE_ADDRESS 0x0u
#define BEU_CURRENT_VALUE_BYTE_ADDRESS 0x0u
/* Register: beu.cause                                                     */
#define BEU_CAUSE_ADDRESS 0x8u
#define BEU_CAUSE_BYTE_ADDRESS 0x8u
/* Register: beu.accrued                                                   */
#define BEU_ACCRUED_ADDRESS 0x10u
#define BEU_ACCRUED_BYTE_ADDRESS 0x10u
/* Register: beu.overflow                                                  */
#define BEU_OVERFLOW_ADDRESS 0x18u
#define BEU_OVERFLOW_BYTE_ADDRESS 0x18u
/* Register: beu.enable                                                    */
#define BEU_ENABLE_ADDRESS 0x20u
#define BEU_ENABLE_BYTE_ADDRESS 0x20u
/* Register: beu.plic_interrupt                                            */
#define BEU_PLIC_INTERRUPT_ADDRESS 0x28u
#define BEU_PLIC_INTERRUPT_BYTE_ADDRESS 0x28u
/* Register: beu.local_interrupt                                           */
#define BEU_LOCAL_INTERRUPT_ADDRESS 0x30u
#define BEU_LOCAL_INTERRUPT_BYTE_ADDRESS 0x30u
/* Register: beu.mce_counter1_mask                                         */
#define BEU_MCE_COUNTER1_MASK_ADDRESS 0x38u
#define BEU_MCE_COUNTER1_MASK_BYTE_ADDRESS 0x38u
/* Register: beu.mce_counter2_mask                                         */
#define BEU_MCE_COUNTER2_MASK_ADDRESS 0x40u
#define BEU_MCE_COUNTER2_MASK_BYTE_ADDRESS 0x40u
/* Register: beu.mce_counter1                                              */
#define BEU_MCE_COUNTER1_ADDRESS 0x48u
#define BEU_MCE_COUNTER1_BYTE_ADDRESS 0x48u
/* Register: beu.mce_counter2                                              */
#define BEU_MCE_COUNTER2_ADDRESS 0x50u
#define BEU_MCE_COUNTER2_BYTE_ADDRESS 0x50u
/* Register: beu.force_value                                               */
#define BEU_FORCE_VALUE_ADDRESS 0x58u
#define BEU_FORCE_VALUE_BYTE_ADDRESS 0x58u
/* Register: beu.force_mce                                                 */
#define BEU_FORCE_MCE_ADDRESS 0x60u
#define BEU_FORCE_MCE_BYTE_ADDRESS 0x60u
/* Register: beu.selected_value                                            */
#define BEU_SELECTED_VALUE_ADDRESS 0x68u
#define BEU_SELECTED_VALUE_BYTE_ADDRESS 0x68u
/* Register: beu.select_index                                              */
#define BEU_SELECT_INDEX_ADDRESS 0x70u
#define BEU_SELECT_INDEX_BYTE_ADDRESS 0x70u


/* ####################################################################### */
/*        TEMPLATE MACROS                                                  */
/* ####################################################################### */

/* Addressmap type: beu                                                    */
/* Addressmap template: beu                                                */
#define BEU_SIZE 0x78u
#define BEU_BYTE_SIZE 0x78u
/* Register member: beu.current_value                                      */
/* Register type referenced: beu::current_value                            */
/* Register template referenced: beu::current_value                        */
#define BEU_CURRENT_VALUE_OFFSET 0x0u
#define BEU_CURRENT_VALUE_BYTE_OFFSET 0x0u
#define BEU_CURRENT_VALUE_READ_ACCESS 1u
#define BEU_CURRENT_VALUE_WRITE_ACCESS 1u
#define BEU_CURRENT_VALUE_RESET_VALUE 0x0000000000000000ull
#define BEU_CURRENT_VALUE_RESET_MASK 0xffff000000000000ull
#define BEU_CURRENT_VALUE_READ_MASK 0xffffffffffffffffull
#define BEU_CURRENT_VALUE_WRITE_MASK 0x0000ffffffffffffull
/* Register member: beu.cause                                              */
/* Register type referenced: beu::cause                                    */
/* Register template referenced: beu::cause                                */
#define BEU_CAUSE_OFFSET 0x8u
#define BEU_CAUSE_BYTE_OFFSET 0x8u
#define BEU_CAUSE_READ_ACCESS 1u
#define BEU_CAUSE_WRITE_ACCESS 1u
#define BEU_CAUSE_RESET_VALUE 0x0000000000000000ull
#define BEU_CAUSE_RESET_MASK 0xffffffffffffffffull
#define BEU_CAUSE_READ_MASK 0xffffffffffffffffull
#define BEU_CAUSE_WRITE_MASK 0x000000000000001full
/* Register member: beu.accrued                                            */
/* Register type referenced: beu::accrued                                  */
/* Register template referenced: beu::accrued                              */
#define BEU_ACCRUED_OFFSET 0x10u
#define BEU_ACCRUED_BYTE_OFFSET 0x10u
#define BEU_ACCRUED_READ_ACCESS 1u
#define BEU_ACCRUED_WRITE_ACCESS 1u
#define BEU_ACCRUED_RESET_VALUE 0x0000000000000000ull
#define BEU_ACCRUED_RESET_MASK 0xffffffffffffffffull
#define BEU_ACCRUED_READ_MASK 0xffffffffffffffffull
#define BEU_ACCRUED_WRITE_MASK 0x0000000001f0030eull
/* Register member: beu.overflow                                           */
/* Register type referenced: beu::overflow                                 */
/* Register template referenced: beu::overflow                             */
#define BEU_OVERFLOW_OFFSET 0x18u
#define BEU_OVERFLOW_BYTE_OFFSET 0x18u
#define BEU_OVERFLOW_READ_ACCESS 1u
#define BEU_OVERFLOW_WRITE_ACCESS 1u
#define BEU_OVERFLOW_RESET_VALUE 0x0000000000000000ull
#define BEU_OVERFLOW_RESET_MASK 0xffffffffffffffffull
#define BEU_OVERFLOW_READ_MASK 0xffffffffffffffffull
#define BEU_OVERFLOW_WRITE_MASK 0x0000000001f0030eull
/* Register member: beu.enable                                             */
/* Register type referenced: beu::enable                                   */
/* Register template referenced: beu::enable                               */
#define BEU_ENABLE_OFFSET 0x20u
#define BEU_ENABLE_BYTE_OFFSET 0x20u
#define BEU_ENABLE_READ_ACCESS 1u
#define BEU_ENABLE_WRITE_ACCESS 1u
#define BEU_ENABLE_RESET_VALUE 0x0000000001f0030eull
#define BEU_ENABLE_RESET_MASK 0xffffffffffffffffull
#define BEU_ENABLE_READ_MASK 0xffffffffffffffffull
#define BEU_ENABLE_WRITE_MASK 0x0000000001f0030eull
/* Register member: beu.plic_interrupt                                     */
/* Register type referenced: beu::plic_interrupt                           */
/* Register template referenced: beu::plic_interrupt                       */
#define BEU_PLIC_INTERRUPT_OFFSET 0x28u
#define BEU_PLIC_INTERRUPT_BYTE_OFFSET 0x28u
#define BEU_PLIC_INTERRUPT_READ_ACCESS 1u
#define BEU_PLIC_INTERRUPT_WRITE_ACCESS 1u
#define BEU_PLIC_INTERRUPT_RESET_VALUE 0x0000000000000000ull
#define BEU_PLIC_INTERRUPT_RESET_MASK 0xffffffffffffffffull
#define BEU_PLIC_INTERRUPT_READ_MASK 0xffffffffffffffffull
#define BEU_PLIC_INTERRUPT_WRITE_MASK 0x0000000001f0030eull
/* Register member: beu.local_interrupt                                    */
/* Register type referenced: beu::local_interrupt                          */
/* Register template referenced: beu::local_interrupt                      */
#define BEU_LOCAL_INTERRUPT_OFFSET 0x30u
#define BEU_LOCAL_INTERRUPT_BYTE_OFFSET 0x30u
#define BEU_LOCAL_INTERRUPT_READ_ACCESS 1u
#define BEU_LOCAL_INTERRUPT_WRITE_ACCESS 1u
#define BEU_LOCAL_INTERRUPT_RESET_VALUE 0x0000000000000000ull
#define BEU_LOCAL_INTERRUPT_RESET_MASK 0xffffffffffffffffull
#define BEU_LOCAL_INTERRUPT_READ_MASK 0xffffffffffffffffull
#define BEU_LOCAL_INTERRUPT_WRITE_MASK 0x0000000001f0030eull
/* Register member: beu.mce_counter1_mask                                  */
/* Register type referenced: beu::mce_counter1_mask                        */
/* Register template referenced: beu::mce_counter1_mask                    */
#define BEU_MCE_COUNTER1_MASK_OFFSET 0x38u
#define BEU_MCE_COUNTER1_MASK_BYTE_OFFSET 0x38u
#define BEU_MCE_COUNTER1_MASK_READ_ACCESS 1u
#define BEU_MCE_COUNTER1_MASK_WRITE_ACCESS 1u
#define BEU_MCE_COUNTER1_MASK_RESET_VALUE 0x0000000000000000ull
#define BEU_MCE_COUNTER1_MASK_RESET_MASK 0xfffffffffe0ffcf1ull
#define BEU_MCE_COUNTER1_MASK_READ_MASK 0xffffffffffffffffull
#define BEU_MCE_COUNTER1_MASK_WRITE_MASK 0x0000000001f0030eull
/* Register member: beu.mce_counter2_mask                                  */
/* Register type referenced: beu::mce_counter2_mask                        */
/* Register template referenced: beu::mce_counter2_mask                    */
#define BEU_MCE_COUNTER2_MASK_OFFSET 0x40u
#define BEU_MCE_COUNTER2_MASK_BYTE_OFFSET 0x40u
#define BEU_MCE_COUNTER2_MASK_READ_ACCESS 1u
#define BEU_MCE_COUNTER2_MASK_WRITE_ACCESS 1u
#define BEU_MCE_COUNTER2_MASK_RESET_VALUE 0x0000000000000000ull
#define BEU_MCE_COUNTER2_MASK_RESET_MASK 0xfffffffffe0ffcf1ull
#define BEU_MCE_COUNTER2_MASK_READ_MASK 0xffffffffffffffffull
#define BEU_MCE_COUNTER2_MASK_WRITE_MASK 0x0000000001f0030eull
/* Register member: beu.mce_counter1                                       */
/* Register type referenced: beu::mce_counter1                             */
/* Register template referenced: beu::mce_counter1                         */
#define BEU_MCE_COUNTER1_OFFSET 0x48u
#define BEU_MCE_COUNTER1_BYTE_OFFSET 0x48u
#define BEU_MCE_COUNTER1_READ_ACCESS 1u
#define BEU_MCE_COUNTER1_WRITE_ACCESS 1u
#define BEU_MCE_COUNTER1_RESET_VALUE 0x0000000000000000ull
#define BEU_MCE_COUNTER1_RESET_MASK 0xffffffffffff0000ull
#define BEU_MCE_COUNTER1_READ_MASK 0xffffffffffffffffull
#define BEU_MCE_COUNTER1_WRITE_MASK 0x000000000000ffffull
/* Register member: beu.mce_counter2                                       */
/* Register type referenced: beu::mce_counter2                             */
/* Register template referenced: beu::mce_counter2                         */
#define BEU_MCE_COUNTER2_OFFSET 0x50u
#define BEU_MCE_COUNTER2_BYTE_OFFSET 0x50u
#define BEU_MCE_COUNTER2_READ_ACCESS 1u
#define BEU_MCE_COUNTER2_WRITE_ACCESS 1u
#define BEU_MCE_COUNTER2_RESET_VALUE 0x0000000000000000ull
#define BEU_MCE_COUNTER2_RESET_MASK 0xffffffffffff0000ull
#define BEU_MCE_COUNTER2_READ_MASK 0xffffffffffffffffull
#define BEU_MCE_COUNTER2_WRITE_MASK 0x000000000000ffffull
/* Register member: beu.force_value                                        */
/* Register type referenced: beu::force_value                              */
/* Register template referenced: beu::force_value                          */
#define BEU_FORCE_VALUE_OFFSET 0x58u
#define BEU_FORCE_VALUE_BYTE_OFFSET 0x58u
#define BEU_FORCE_VALUE_READ_ACCESS 1u
#define BEU_FORCE_VALUE_WRITE_ACCESS 1u
#define BEU_FORCE_VALUE_RESET_VALUE 0x0000000000000000ull
#define BEU_FORCE_VALUE_RESET_MASK 0xffff000000000000ull
#define BEU_FORCE_VALUE_READ_MASK 0xffffffffffffffffull
#define BEU_FORCE_VALUE_WRITE_MASK 0x0000ffffffffffffull
/* Register member: beu.force_mce                                          */
/* Register type referenced: beu::force_mce                                */
/* Register template referenced: beu::force_mce                            */
#define BEU_FORCE_MCE_OFFSET 0x60u
#define BEU_FORCE_MCE_BYTE_OFFSET 0x60u
#define BEU_FORCE_MCE_READ_ACCESS 1u
#define BEU_FORCE_MCE_WRITE_ACCESS 1u
#define BEU_FORCE_MCE_RESET_VALUE 0x0000000000000000ull
#define BEU_FORCE_MCE_RESET_MASK 0xffffffffffffffffull
#define BEU_FORCE_MCE_READ_MASK 0xffffffffffffffffull
#define BEU_FORCE_MCE_WRITE_MASK 0x000000000000001full
/* Register member: beu.selected_value                                     */
/* Register type referenced: beu::selected_value                           */
/* Register template referenced: beu::selected_value                       */
#define BEU_SELECTED_VALUE_OFFSET 0x68u
#define BEU_SELECTED_VALUE_BYTE_OFFSET 0x68u
#define BEU_SELECTED_VALUE_READ_ACCESS 1u
#define BEU_SELECTED_VALUE_WRITE_ACCESS 1u
#define BEU_SELECTED_VALUE_RESET_VALUE 0x0000000000000000ull
#define BEU_SELECTED_VALUE_RESET_MASK 0xffff000000000000ull
#define BEU_SELECTED_VALUE_READ_MASK 0xffffffffffffffffull
#define BEU_SELECTED_VALUE_WRITE_MASK 0x0000ffffffffffffull
/* Register member: beu.select_index                                       */
/* Register type referenced: beu::select_index                             */
/* Register template referenced: beu::select_index                         */
#define BEU_SELECT_INDEX_OFFSET 0x70u
#define BEU_SELECT_INDEX_BYTE_OFFSET 0x70u
#define BEU_SELECT_INDEX_READ_ACCESS 1u
#define BEU_SELECT_INDEX_WRITE_ACCESS 1u
#define BEU_SELECT_INDEX_RESET_VALUE 0x0000000000000000ull
#define BEU_SELECT_INDEX_RESET_MASK 0xffffffffffffffffull
#define BEU_SELECT_INDEX_READ_MASK 0xffffffffffffffffull
#define BEU_SELECT_INDEX_WRITE_MASK 0x000000000000001full

/* Register type: beu::current_value                                       */
/* Register template: beu::current_value                                   */
/* Field member: beu::current_value.current_value_5                        */
#define BEU_CURRENT_VALUE_CURRENT_VALUE_5_MSB 47u
#define BEU_CURRENT_VALUE_CURRENT_VALUE_5_LSB 40u
#define BEU_CURRENT_VALUE_CURRENT_VALUE_5_WIDTH 8u
#define BEU_CURRENT_VALUE_CURRENT_VALUE_5_READ_ACCESS 1u
#define BEU_CURRENT_VALUE_CURRENT_VALUE_5_WRITE_ACCESS 1u
#define BEU_CURRENT_VALUE_CURRENT_VALUE_5_FIELD_MASK 0x0000ff0000000000ull
#define BEU_CURRENT_VALUE_CURRENT_VALUE_5_GET(x) \
   ((((uint64_t)x) & 0x0000ff0000000000ull) >> 40)
#define BEU_CURRENT_VALUE_CURRENT_VALUE_5_SET(x) \
   ((((uint64_t)x) << 40) & 0x0000ff0000000000ull)
#define BEU_CURRENT_VALUE_CURRENT_VALUE_5_MODIFY(r, x) \
   (((((uint64_t)x) << 40) & 0x0000ff0000000000ull) | ((r) & 0xffff00ffffffffffull))
/* Field member: beu::current_value.current_value_4                        */
#define BEU_CURRENT_VALUE_CURRENT_VALUE_4_MSB 39u
#define BEU_CURRENT_VALUE_CURRENT_VALUE_4_LSB 32u
#define BEU_CURRENT_VALUE_CURRENT_VALUE_4_WIDTH 8u
#define BEU_CURRENT_VALUE_CURRENT_VALUE_4_READ_ACCESS 1u
#define BEU_CURRENT_VALUE_CURRENT_VALUE_4_WRITE_ACCESS 1u
#define BEU_CURRENT_VALUE_CURRENT_VALUE_4_FIELD_MASK 0x000000ff00000000ull
#define BEU_CURRENT_VALUE_CURRENT_VALUE_4_GET(x) \
   ((((uint64_t)x) & 0x000000ff00000000ull) >> 32)
#define BEU_CURRENT_VALUE_CURRENT_VALUE_4_SET(x) \
   ((((uint64_t)x) << 32) & 0x000000ff00000000ull)
#define BEU_CURRENT_VALUE_CURRENT_VALUE_4_MODIFY(r, x) \
   (((((uint64_t)x) << 32) & 0x000000ff00000000ull) | ((r) & 0xffffff00ffffffffull))
/* Field member: beu::current_value.current_value_3                        */
#define BEU_CURRENT_VALUE_CURRENT_VALUE_3_MSB 31u
#define BEU_CURRENT_VALUE_CURRENT_VALUE_3_LSB 24u
#define BEU_CURRENT_VALUE_CURRENT_VALUE_3_WIDTH 8u
#define BEU_CURRENT_VALUE_CURRENT_VALUE_3_READ_ACCESS 1u
#define BEU_CURRENT_VALUE_CURRENT_VALUE_3_WRITE_ACCESS 1u
#define BEU_CURRENT_VALUE_CURRENT_VALUE_3_FIELD_MASK 0x00000000ff000000ull
#define BEU_CURRENT_VALUE_CURRENT_VALUE_3_GET(x) \
   ((((uint64_t)x) & 0x00000000ff000000ull) >> 24)
#define BEU_CURRENT_VALUE_CURRENT_VALUE_3_SET(x) \
   ((((uint64_t)x) << 24) & 0x00000000ff000000ull)
#define BEU_CURRENT_VALUE_CURRENT_VALUE_3_MODIFY(r, x) \
   (((((uint64_t)x) << 24) & 0x00000000ff000000ull) | ((r) & 0xffffffff00ffffffull))
/* Field member: beu::current_value.current_value_2                        */
#define BEU_CURRENT_VALUE_CURRENT_VALUE_2_MSB 23u
#define BEU_CURRENT_VALUE_CURRENT_VALUE_2_LSB 16u
#define BEU_CURRENT_VALUE_CURRENT_VALUE_2_WIDTH 8u
#define BEU_CURRENT_VALUE_CURRENT_VALUE_2_READ_ACCESS 1u
#define BEU_CURRENT_VALUE_CURRENT_VALUE_2_WRITE_ACCESS 1u
#define BEU_CURRENT_VALUE_CURRENT_VALUE_2_FIELD_MASK 0x0000000000ff0000ull
#define BEU_CURRENT_VALUE_CURRENT_VALUE_2_GET(x) \
   ((((uint64_t)x) & 0x0000000000ff0000ull) >> 16)
#define BEU_CURRENT_VALUE_CURRENT_VALUE_2_SET(x) \
   ((((uint64_t)x) << 16) & 0x0000000000ff0000ull)
#define BEU_CURRENT_VALUE_CURRENT_VALUE_2_MODIFY(r, x) \
   (((((uint64_t)x) << 16) & 0x0000000000ff0000ull) | ((r) & 0xffffffffff00ffffull))
/* Field member: beu::current_value.current_value_1                        */
#define BEU_CURRENT_VALUE_CURRENT_VALUE_1_MSB 15u
#define BEU_CURRENT_VALUE_CURRENT_VALUE_1_LSB 8u
#define BEU_CURRENT_VALUE_CURRENT_VALUE_1_WIDTH 8u
#define BEU_CURRENT_VALUE_CURRENT_VALUE_1_READ_ACCESS 1u
#define BEU_CURRENT_VALUE_CURRENT_VALUE_1_WRITE_ACCESS 1u
#define BEU_CURRENT_VALUE_CURRENT_VALUE_1_FIELD_MASK 0x000000000000ff00ull
#define BEU_CURRENT_VALUE_CURRENT_VALUE_1_GET(x) \
   ((((uint64_t)x) & 0x000000000000ff00ull) >> 8)
#define BEU_CURRENT_VALUE_CURRENT_VALUE_1_SET(x) \
   ((((uint64_t)x) << 8) & 0x000000000000ff00ull)
#define BEU_CURRENT_VALUE_CURRENT_VALUE_1_MODIFY(r, x) \
   (((((uint64_t)x) << 8) & 0x000000000000ff00ull) | ((r) & 0xffffffffffff00ffull))
/* Field member: beu::current_value.current_value_0                        */
#define BEU_CURRENT_VALUE_CURRENT_VALUE_0_MSB 7u
#define BEU_CURRENT_VALUE_CURRENT_VALUE_0_LSB 0u
#define BEU_CURRENT_VALUE_CURRENT_VALUE_0_WIDTH 8u
#define BEU_CURRENT_VALUE_CURRENT_VALUE_0_READ_ACCESS 1u
#define BEU_CURRENT_VALUE_CURRENT_VALUE_0_WRITE_ACCESS 1u
#define BEU_CURRENT_VALUE_CURRENT_VALUE_0_FIELD_MASK 0x00000000000000ffull
#define BEU_CURRENT_VALUE_CURRENT_VALUE_0_GET(x) \
   ((x) & 0x00000000000000ffull)
#define BEU_CURRENT_VALUE_CURRENT_VALUE_0_SET(x) \
   ((x) & 0x00000000000000ffull)
#define BEU_CURRENT_VALUE_CURRENT_VALUE_0_MODIFY(r, x) \
   (((x) & 0x00000000000000ffull) | ((r) & 0xffffffffffffff00ull))

/* Register type: beu::cause                                               */
/* Register template: beu::cause                                           */
/* Field member: beu::cause.cause_0                                        */
#define BEU_CAUSE_CAUSE_0_MSB 4u
#define BEU_CAUSE_CAUSE_0_LSB 0u
#define BEU_CAUSE_CAUSE_0_WIDTH 5u
#define BEU_CAUSE_CAUSE_0_READ_ACCESS 1u
#define BEU_CAUSE_CAUSE_0_WRITE_ACCESS 1u
#define BEU_CAUSE_CAUSE_0_RESET 0x00u
#define BEU_CAUSE_CAUSE_0_FIELD_MASK 0x000000000000001full
#define BEU_CAUSE_CAUSE_0_GET(x) ((x) & 0x000000000000001full)
#define BEU_CAUSE_CAUSE_0_SET(x) ((x) & 0x000000000000001full)
#define BEU_CAUSE_CAUSE_0_MODIFY(r, x) \
   (((x) & 0x000000000000001full) | ((r) & 0xffffffffffffffe0ull))

/* Register type: beu::accrued                                             */
/* Register template: beu::accrued                                         */
/* Field member: beu::accrued.accrued_24                                   */
#define BEU_ACCRUED_ACCRUED_24_MSB 24u
#define BEU_ACCRUED_ACCRUED_24_LSB 24u
#define BEU_ACCRUED_ACCRUED_24_WIDTH 1u
#define BEU_ACCRUED_ACCRUED_24_READ_ACCESS 1u
#define BEU_ACCRUED_ACCRUED_24_WRITE_ACCESS 1u
#define BEU_ACCRUED_ACCRUED_24_RESET 0x0u
#define BEU_ACCRUED_ACCRUED_24_FIELD_MASK 0x0000000001000000ull
#define BEU_ACCRUED_ACCRUED_24_GET((uint64_t)x) ((((uint64_t)x) & 0x0000000001000000ull) >> 24)
#define BEU_ACCRUED_ACCRUED_24_SET((uint64_t)x) ((((uint64_t)x) << 24) & 0x0000000001000000ull)
#define BEU_ACCRUED_ACCRUED_24_MODIFY(r, x) \
   (((((uint64_t)x) << 24) & 0x0000000001000000ull) | ((r) & 0xfffffffffeffffffull))
/* Field member: beu::accrued.accrued_23                                   */
#define BEU_ACCRUED_ACCRUED_23_MSB 23u
#define BEU_ACCRUED_ACCRUED_23_LSB 23u
#define BEU_ACCRUED_ACCRUED_23_WIDTH 1u
#define BEU_ACCRUED_ACCRUED_23_READ_ACCESS 1u
#define BEU_ACCRUED_ACCRUED_23_WRITE_ACCESS 1u
#define BEU_ACCRUED_ACCRUED_23_RESET 0x0u
#define BEU_ACCRUED_ACCRUED_23_FIELD_MASK 0x0000000000800000ull
#define BEU_ACCRUED_ACCRUED_23_GET((uint64_t)x) ((((uint64_t)x) & 0x0000000000800000ull) >> 23)
#define BEU_ACCRUED_ACCRUED_23_SET((uint64_t)x) ((((uint64_t)x) << 23) & 0x0000000000800000ull)
#define BEU_ACCRUED_ACCRUED_23_MODIFY(r, x) \
   (((((uint64_t)x) << 23) & 0x0000000000800000ull) | ((r) & 0xffffffffff7fffffull))
/* Field member: beu::accrued.accrued_22                                   */
#define BEU_ACCRUED_ACCRUED_22_MSB 22u
#define BEU_ACCRUED_ACCRUED_22_LSB 22u
#define BEU_ACCRUED_ACCRUED_22_WIDTH 1u
#define BEU_ACCRUED_ACCRUED_22_READ_ACCESS 1u
#define BEU_ACCRUED_ACCRUED_22_WRITE_ACCESS 1u
#define BEU_ACCRUED_ACCRUED_22_RESET 0x0u
#define BEU_ACCRUED_ACCRUED_22_FIELD_MASK 0x0000000000400000ull
#define BEU_ACCRUED_ACCRUED_22_GET((uint64_t)x) ((((uint64_t)x) & 0x0000000000400000ull) >> 22)
#define BEU_ACCRUED_ACCRUED_22_SET((uint64_t)x) ((((uint64_t)x) << 22) & 0x0000000000400000ull)
#define BEU_ACCRUED_ACCRUED_22_MODIFY(r, x) \
   (((((uint64_t)x) << 22) & 0x0000000000400000ull) | ((r) & 0xffffffffffbfffffull))
/* Field member: beu::accrued.accrued_21                                   */
#define BEU_ACCRUED_ACCRUED_21_MSB 21u
#define BEU_ACCRUED_ACCRUED_21_LSB 21u
#define BEU_ACCRUED_ACCRUED_21_WIDTH 1u
#define BEU_ACCRUED_ACCRUED_21_READ_ACCESS 1u
#define BEU_ACCRUED_ACCRUED_21_WRITE_ACCESS 1u
#define BEU_ACCRUED_ACCRUED_21_RESET 0x0u
#define BEU_ACCRUED_ACCRUED_21_FIELD_MASK 0x0000000000200000ull
#define BEU_ACCRUED_ACCRUED_21_GET((uint64_t)x) ((((uint64_t)x) & 0x0000000000200000ull) >> 21)
#define BEU_ACCRUED_ACCRUED_21_SET((uint64_t)x) ((((uint64_t)x) << 21) & 0x0000000000200000ull)
#define BEU_ACCRUED_ACCRUED_21_MODIFY(r, x) \
   (((((uint64_t)x) << 21) & 0x0000000000200000ull) | ((r) & 0xffffffffffdfffffull))
/* Field member: beu::accrued.accrued_20                                   */
#define BEU_ACCRUED_ACCRUED_20_MSB 20u
#define BEU_ACCRUED_ACCRUED_20_LSB 20u
#define BEU_ACCRUED_ACCRUED_20_WIDTH 1u
#define BEU_ACCRUED_ACCRUED_20_READ_ACCESS 1u
#define BEU_ACCRUED_ACCRUED_20_WRITE_ACCESS 1u
#define BEU_ACCRUED_ACCRUED_20_RESET 0x0u
#define BEU_ACCRUED_ACCRUED_20_FIELD_MASK 0x0000000000100000ull
#define BEU_ACCRUED_ACCRUED_20_GET((uint64_t)x) ((((uint64_t)x) & 0x0000000000100000ull) >> 20)
#define BEU_ACCRUED_ACCRUED_20_SET((uint64_t)x) ((((uint64_t)x) << 20) & 0x0000000000100000ull)
#define BEU_ACCRUED_ACCRUED_20_MODIFY(r, x) \
   (((((uint64_t)x) << 20) & 0x0000000000100000ull) | ((r) & 0xffffffffffefffffull))
/* Field member: beu::accrued.accrued_9                                    */
#define BEU_ACCRUED_ACCRUED_9_MSB 9u
#define BEU_ACCRUED_ACCRUED_9_LSB 9u
#define BEU_ACCRUED_ACCRUED_9_WIDTH 1u
#define BEU_ACCRUED_ACCRUED_9_READ_ACCESS 1u
#define BEU_ACCRUED_ACCRUED_9_WRITE_ACCESS 1u
#define BEU_ACCRUED_ACCRUED_9_RESET 0x0u
#define BEU_ACCRUED_ACCRUED_9_FIELD_MASK 0x0000000000000200ull
#define BEU_ACCRUED_ACCRUED_9_GET((uint64_t)x) ((((uint64_t)x) & 0x0000000000000200ull) >> 9)
#define BEU_ACCRUED_ACCRUED_9_SET((uint64_t)x) ((((uint64_t)x) << 9) & 0x0000000000000200ull)
#define BEU_ACCRUED_ACCRUED_9_MODIFY(r, x) \
   (((((uint64_t)x) << 9) & 0x0000000000000200ull) | ((r) & 0xfffffffffffffdffull))
/* Field member: beu::accrued.accrued_8                                    */
#define BEU_ACCRUED_ACCRUED_8_MSB 8u
#define BEU_ACCRUED_ACCRUED_8_LSB 8u
#define BEU_ACCRUED_ACCRUED_8_WIDTH 1u
#define BEU_ACCRUED_ACCRUED_8_READ_ACCESS 1u
#define BEU_ACCRUED_ACCRUED_8_WRITE_ACCESS 1u
#define BEU_ACCRUED_ACCRUED_8_RESET 0x0u
#define BEU_ACCRUED_ACCRUED_8_FIELD_MASK 0x0000000000000100ull
#define BEU_ACCRUED_ACCRUED_8_GET((uint64_t)x) ((((uint64_t)x) & 0x0000000000000100ull) >> 8)
#define BEU_ACCRUED_ACCRUED_8_SET((uint64_t)x) ((((uint64_t)x) << 8) & 0x0000000000000100ull)
#define BEU_ACCRUED_ACCRUED_8_MODIFY(r, x) \
   (((((uint64_t)x) << 8) & 0x0000000000000100ull) | ((r) & 0xfffffffffffffeffull))
/* Field member: beu::accrued.accrued_3                                    */
#define BEU_ACCRUED_ACCRUED_3_MSB 3u
#define BEU_ACCRUED_ACCRUED_3_LSB 3u
#define BEU_ACCRUED_ACCRUED_3_WIDTH 1u
#define BEU_ACCRUED_ACCRUED_3_READ_ACCESS 1u
#define BEU_ACCRUED_ACCRUED_3_WRITE_ACCESS 1u
#define BEU_ACCRUED_ACCRUED_3_RESET 0x0u
#define BEU_ACCRUED_ACCRUED_3_FIELD_MASK 0x0000000000000008ull
#define BEU_ACCRUED_ACCRUED_3_GET((uint64_t)x) ((((uint64_t)x) & 0x0000000000000008ull) >> 3)
#define BEU_ACCRUED_ACCRUED_3_SET((uint64_t)x) ((((uint64_t)x) << 3) & 0x0000000000000008ull)
#define BEU_ACCRUED_ACCRUED_3_MODIFY(r, x) \
   (((((uint64_t)x) << 3) & 0x0000000000000008ull) | ((r) & 0xfffffffffffffff7ull))
/* Field member: beu::accrued.accrued_2                                    */
#define BEU_ACCRUED_ACCRUED_2_MSB 2u
#define BEU_ACCRUED_ACCRUED_2_LSB 2u
#define BEU_ACCRUED_ACCRUED_2_WIDTH 1u
#define BEU_ACCRUED_ACCRUED_2_READ_ACCESS 1u
#define BEU_ACCRUED_ACCRUED_2_WRITE_ACCESS 1u
#define BEU_ACCRUED_ACCRUED_2_RESET 0x0u
#define BEU_ACCRUED_ACCRUED_2_FIELD_MASK 0x0000000000000004ull
#define BEU_ACCRUED_ACCRUED_2_GET((uint64_t)x) ((((uint64_t)x) & 0x0000000000000004ull) >> 2)
#define BEU_ACCRUED_ACCRUED_2_SET((uint64_t)x) ((((uint64_t)x) << 2) & 0x0000000000000004ull)
#define BEU_ACCRUED_ACCRUED_2_MODIFY(r, x) \
   (((((uint64_t)x) << 2) & 0x0000000000000004ull) | ((r) & 0xfffffffffffffffbull))
/* Field member: beu::accrued.accrued_1                                    */
#define BEU_ACCRUED_ACCRUED_1_MSB 1u
#define BEU_ACCRUED_ACCRUED_1_LSB 1u
#define BEU_ACCRUED_ACCRUED_1_WIDTH 1u
#define BEU_ACCRUED_ACCRUED_1_READ_ACCESS 1u
#define BEU_ACCRUED_ACCRUED_1_WRITE_ACCESS 1u
#define BEU_ACCRUED_ACCRUED_1_RESET 0x0u
#define BEU_ACCRUED_ACCRUED_1_FIELD_MASK 0x0000000000000002ull
#define BEU_ACCRUED_ACCRUED_1_GET((uint64_t)x) ((((uint64_t)x) & 0x0000000000000002ull) >> 1)
#define BEU_ACCRUED_ACCRUED_1_SET((uint64_t)x) ((((uint64_t)x) << 1) & 0x0000000000000002ull)
#define BEU_ACCRUED_ACCRUED_1_MODIFY(r, x) \
   (((((uint64_t)x) << 1) & 0x0000000000000002ull) | ((r) & 0xfffffffffffffffdull))

/* Register type: beu::overflow                                            */
/* Register template: beu::overflow                                        */
/* Field member: beu::overflow.overflow_24                                 */
#define BEU_OVERFLOW_OVERFLOW_24_MSB 24u
#define BEU_OVERFLOW_OVERFLOW_24_LSB 24u
#define BEU_OVERFLOW_OVERFLOW_24_WIDTH 1u
#define BEU_OVERFLOW_OVERFLOW_24_READ_ACCESS 1u
#define BEU_OVERFLOW_OVERFLOW_24_WRITE_ACCESS 1u
#define BEU_OVERFLOW_OVERFLOW_24_RESET 0x0u
#define BEU_OVERFLOW_OVERFLOW_24_FIELD_MASK 0x0000000001000000ull
#define BEU_OVERFLOW_OVERFLOW_24_GET((uint64_t)x) ((((uint64_t)x) & 0x0000000001000000ull) >> 24)
#define BEU_OVERFLOW_OVERFLOW_24_SET(x) \
   ((((uint64_t)x) << 24) & 0x0000000001000000ull)
#define BEU_OVERFLOW_OVERFLOW_24_MODIFY(r, x) \
   (((((uint64_t)x) << 24) & 0x0000000001000000ull) | ((r) & 0xfffffffffeffffffull))
/* Field member: beu::overflow.overflow_23                                 */
#define BEU_OVERFLOW_OVERFLOW_23_MSB 23u
#define BEU_OVERFLOW_OVERFLOW_23_LSB 23u
#define BEU_OVERFLOW_OVERFLOW_23_WIDTH 1u
#define BEU_OVERFLOW_OVERFLOW_23_READ_ACCESS 1u
#define BEU_OVERFLOW_OVERFLOW_23_WRITE_ACCESS 1u
#define BEU_OVERFLOW_OVERFLOW_23_RESET 0x0u
#define BEU_OVERFLOW_OVERFLOW_23_FIELD_MASK 0x0000000000800000ull
#define BEU_OVERFLOW_OVERFLOW_23_GET((uint64_t)x) ((((uint64_t)x) & 0x0000000000800000ull) >> 23)
#define BEU_OVERFLOW_OVERFLOW_23_SET(x) \
   ((((uint64_t)x) << 23) & 0x0000000000800000ull)
#define BEU_OVERFLOW_OVERFLOW_23_MODIFY(r, x) \
   (((((uint64_t)x) << 23) & 0x0000000000800000ull) | ((r) & 0xffffffffff7fffffull))
/* Field member: beu::overflow.overflow_22                                 */
#define BEU_OVERFLOW_OVERFLOW_22_MSB 22u
#define BEU_OVERFLOW_OVERFLOW_22_LSB 22u
#define BEU_OVERFLOW_OVERFLOW_22_WIDTH 1u
#define BEU_OVERFLOW_OVERFLOW_22_READ_ACCESS 1u
#define BEU_OVERFLOW_OVERFLOW_22_WRITE_ACCESS 1u
#define BEU_OVERFLOW_OVERFLOW_22_RESET 0x0u
#define BEU_OVERFLOW_OVERFLOW_22_FIELD_MASK 0x0000000000400000ull
#define BEU_OVERFLOW_OVERFLOW_22_GET((uint64_t)x) ((((uint64_t)x) & 0x0000000000400000ull) >> 22)
#define BEU_OVERFLOW_OVERFLOW_22_SET(x) \
   ((((uint64_t)x) << 22) & 0x0000000000400000ull)
#define BEU_OVERFLOW_OVERFLOW_22_MODIFY(r, x) \
   (((((uint64_t)x) << 22) & 0x0000000000400000ull) | ((r) & 0xffffffffffbfffffull))
/* Field member: beu::overflow.overflow_21                                 */
#define BEU_OVERFLOW_OVERFLOW_21_MSB 21u
#define BEU_OVERFLOW_OVERFLOW_21_LSB 21u
#define BEU_OVERFLOW_OVERFLOW_21_WIDTH 1u
#define BEU_OVERFLOW_OVERFLOW_21_READ_ACCESS 1u
#define BEU_OVERFLOW_OVERFLOW_21_WRITE_ACCESS 1u
#define BEU_OVERFLOW_OVERFLOW_21_RESET 0x0u
#define BEU_OVERFLOW_OVERFLOW_21_FIELD_MASK 0x0000000000200000ull
#define BEU_OVERFLOW_OVERFLOW_21_GET((uint64_t)x) ((((uint64_t)x) & 0x0000000000200000ull) >> 21)
#define BEU_OVERFLOW_OVERFLOW_21_SET(x) \
   ((((uint64_t)x) << 21) & 0x0000000000200000ull)
#define BEU_OVERFLOW_OVERFLOW_21_MODIFY(r, x) \
   (((((uint64_t)x) << 21) & 0x0000000000200000ull) | ((r) & 0xffffffffffdfffffull))
/* Field member: beu::overflow.overflow_20                                 */
#define BEU_OVERFLOW_OVERFLOW_20_MSB 20u
#define BEU_OVERFLOW_OVERFLOW_20_LSB 20u
#define BEU_OVERFLOW_OVERFLOW_20_WIDTH 1u
#define BEU_OVERFLOW_OVERFLOW_20_READ_ACCESS 1u
#define BEU_OVERFLOW_OVERFLOW_20_WRITE_ACCESS 1u
#define BEU_OVERFLOW_OVERFLOW_20_RESET 0x0u
#define BEU_OVERFLOW_OVERFLOW_20_FIELD_MASK 0x0000000000100000ull
#define BEU_OVERFLOW_OVERFLOW_20_GET((uint64_t)x) ((((uint64_t)x) & 0x0000000000100000ull) >> 20)
#define BEU_OVERFLOW_OVERFLOW_20_SET(x) \
   ((((uint64_t)x) << 20) & 0x0000000000100000ull)
#define BEU_OVERFLOW_OVERFLOW_20_MODIFY(r, x) \
   (((((uint64_t)x) << 20) & 0x0000000000100000ull) | ((r) & 0xffffffffffefffffull))
/* Field member: beu::overflow.overflow_9                                  */
#define BEU_OVERFLOW_OVERFLOW_9_MSB 9u
#define BEU_OVERFLOW_OVERFLOW_9_LSB 9u
#define BEU_OVERFLOW_OVERFLOW_9_WIDTH 1u
#define BEU_OVERFLOW_OVERFLOW_9_READ_ACCESS 1u
#define BEU_OVERFLOW_OVERFLOW_9_WRITE_ACCESS 1u
#define BEU_OVERFLOW_OVERFLOW_9_RESET 0x0u
#define BEU_OVERFLOW_OVERFLOW_9_FIELD_MASK 0x0000000000000200ull
#define BEU_OVERFLOW_OVERFLOW_9_GET((uint64_t)x) ((((uint64_t)x) & 0x0000000000000200ull) >> 9)
#define BEU_OVERFLOW_OVERFLOW_9_SET((uint64_t)x) ((((uint64_t)x) << 9) & 0x0000000000000200ull)
#define BEU_OVERFLOW_OVERFLOW_9_MODIFY(r, x) \
   (((((uint64_t)x) << 9) & 0x0000000000000200ull) | ((r) & 0xfffffffffffffdffull))
/* Field member: beu::overflow.overflow_8                                  */
#define BEU_OVERFLOW_OVERFLOW_8_MSB 8u
#define BEU_OVERFLOW_OVERFLOW_8_LSB 8u
#define BEU_OVERFLOW_OVERFLOW_8_WIDTH 1u
#define BEU_OVERFLOW_OVERFLOW_8_READ_ACCESS 1u
#define BEU_OVERFLOW_OVERFLOW_8_WRITE_ACCESS 1u
#define BEU_OVERFLOW_OVERFLOW_8_RESET 0x0u
#define BEU_OVERFLOW_OVERFLOW_8_FIELD_MASK 0x0000000000000100ull
#define BEU_OVERFLOW_OVERFLOW_8_GET((uint64_t)x) ((((uint64_t)x) & 0x0000000000000100ull) >> 8)
#define BEU_OVERFLOW_OVERFLOW_8_SET((uint64_t)x) ((((uint64_t)x) << 8) & 0x0000000000000100ull)
#define BEU_OVERFLOW_OVERFLOW_8_MODIFY(r, x) \
   (((((uint64_t)x) << 8) & 0x0000000000000100ull) | ((r) & 0xfffffffffffffeffull))
/* Field member: beu::overflow.overflow_3                                  */
#define BEU_OVERFLOW_OVERFLOW_3_MSB 3u
#define BEU_OVERFLOW_OVERFLOW_3_LSB 3u
#define BEU_OVERFLOW_OVERFLOW_3_WIDTH 1u
#define BEU_OVERFLOW_OVERFLOW_3_READ_ACCESS 1u
#define BEU_OVERFLOW_OVERFLOW_3_WRITE_ACCESS 1u
#define BEU_OVERFLOW_OVERFLOW_3_RESET 0x0u
#define BEU_OVERFLOW_OVERFLOW_3_FIELD_MASK 0x0000000000000008ull
#define BEU_OVERFLOW_OVERFLOW_3_GET((uint64_t)x) ((((uint64_t)x) & 0x0000000000000008ull) >> 3)
#define BEU_OVERFLOW_OVERFLOW_3_SET((uint64_t)x) ((((uint64_t)x) << 3) & 0x0000000000000008ull)
#define BEU_OVERFLOW_OVERFLOW_3_MODIFY(r, x) \
   (((((uint64_t)x) << 3) & 0x0000000000000008ull) | ((r) & 0xfffffffffffffff7ull))
/* Field member: beu::overflow.overflow_2                                  */
#define BEU_OVERFLOW_OVERFLOW_2_MSB 2u
#define BEU_OVERFLOW_OVERFLOW_2_LSB 2u
#define BEU_OVERFLOW_OVERFLOW_2_WIDTH 1u
#define BEU_OVERFLOW_OVERFLOW_2_READ_ACCESS 1u
#define BEU_OVERFLOW_OVERFLOW_2_WRITE_ACCESS 1u
#define BEU_OVERFLOW_OVERFLOW_2_RESET 0x0u
#define BEU_OVERFLOW_OVERFLOW_2_FIELD_MASK 0x0000000000000004ull
#define BEU_OVERFLOW_OVERFLOW_2_GET((uint64_t)x) ((((uint64_t)x) & 0x0000000000000004ull) >> 2)
#define BEU_OVERFLOW_OVERFLOW_2_SET((uint64_t)x) ((((uint64_t)x) << 2) & 0x0000000000000004ull)
#define BEU_OVERFLOW_OVERFLOW_2_MODIFY(r, x) \
   (((((uint64_t)x) << 2) & 0x0000000000000004ull) | ((r) & 0xfffffffffffffffbull))
/* Field member: beu::overflow.overflow_1                                  */
#define BEU_OVERFLOW_OVERFLOW_1_MSB 1u
#define BEU_OVERFLOW_OVERFLOW_1_LSB 1u
#define BEU_OVERFLOW_OVERFLOW_1_WIDTH 1u
#define BEU_OVERFLOW_OVERFLOW_1_READ_ACCESS 1u
#define BEU_OVERFLOW_OVERFLOW_1_WRITE_ACCESS 1u
#define BEU_OVERFLOW_OVERFLOW_1_RESET 0x0u
#define BEU_OVERFLOW_OVERFLOW_1_FIELD_MASK 0x0000000000000002ull
#define BEU_OVERFLOW_OVERFLOW_1_GET((uint64_t)x) ((((uint64_t)x) & 0x0000000000000002ull) >> 1)
#define BEU_OVERFLOW_OVERFLOW_1_SET((uint64_t)x) ((((uint64_t)x) << 1) & 0x0000000000000002ull)
#define BEU_OVERFLOW_OVERFLOW_1_MODIFY(r, x) \
   (((((uint64_t)x) << 1) & 0x0000000000000002ull) | ((r) & 0xfffffffffffffffdull))

/* Register type: beu::enable                                              */
/* Register template: beu::enable                                          */
/* Field member: beu::enable.enable_24                                     */
#define BEU_ENABLE_ENABLE_24_MSB 24u
#define BEU_ENABLE_ENABLE_24_LSB 24u
#define BEU_ENABLE_ENABLE_24_WIDTH 1u
#define BEU_ENABLE_ENABLE_24_READ_ACCESS 1u
#define BEU_ENABLE_ENABLE_24_WRITE_ACCESS 1u
#define BEU_ENABLE_ENABLE_24_RESET 0x1u
#define BEU_ENABLE_ENABLE_24_FIELD_MASK 0x0000000001000000ull
#define BEU_ENABLE_ENABLE_24_GET((uint64_t)x) ((((uint64_t)x) & 0x0000000001000000ull) >> 24)
#define BEU_ENABLE_ENABLE_24_SET((uint64_t)x) ((((uint64_t)x) << 24) & 0x0000000001000000ull)
#define BEU_ENABLE_ENABLE_24_MODIFY(r, x) \
   (((((uint64_t)x) << 24) & 0x0000000001000000ull) | ((r) & 0xfffffffffeffffffull))
/* Field member: beu::enable.enable_23                                     */
#define BEU_ENABLE_ENABLE_23_MSB 23u
#define BEU_ENABLE_ENABLE_23_LSB 23u
#define BEU_ENABLE_ENABLE_23_WIDTH 1u
#define BEU_ENABLE_ENABLE_23_READ_ACCESS 1u
#define BEU_ENABLE_ENABLE_23_WRITE_ACCESS 1u
#define BEU_ENABLE_ENABLE_23_RESET 0x1u
#define BEU_ENABLE_ENABLE_23_FIELD_MASK 0x0000000000800000ull
#define BEU_ENABLE_ENABLE_23_GET((uint64_t)x) ((((uint64_t)x) & 0x0000000000800000ull) >> 23)
#define BEU_ENABLE_ENABLE_23_SET((uint64_t)x) ((((uint64_t)x) << 23) & 0x0000000000800000ull)
#define BEU_ENABLE_ENABLE_23_MODIFY(r, x) \
   (((((uint64_t)x) << 23) & 0x0000000000800000ull) | ((r) & 0xffffffffff7fffffull))
/* Field member: beu::enable.enable_22                                     */
#define BEU_ENABLE_ENABLE_22_MSB 22u
#define BEU_ENABLE_ENABLE_22_LSB 22u
#define BEU_ENABLE_ENABLE_22_WIDTH 1u
#define BEU_ENABLE_ENABLE_22_READ_ACCESS 1u
#define BEU_ENABLE_ENABLE_22_WRITE_ACCESS 1u
#define BEU_ENABLE_ENABLE_22_RESET 0x1u
#define BEU_ENABLE_ENABLE_22_FIELD_MASK 0x0000000000400000ull
#define BEU_ENABLE_ENABLE_22_GET((uint64_t)x) ((((uint64_t)x) & 0x0000000000400000ull) >> 22)
#define BEU_ENABLE_ENABLE_22_SET((uint64_t)x) ((((uint64_t)x) << 22) & 0x0000000000400000ull)
#define BEU_ENABLE_ENABLE_22_MODIFY(r, x) \
   (((((uint64_t)x) << 22) & 0x0000000000400000ull) | ((r) & 0xffffffffffbfffffull))
/* Field member: beu::enable.enable_21                                     */
#define BEU_ENABLE_ENABLE_21_MSB 21u
#define BEU_ENABLE_ENABLE_21_LSB 21u
#define BEU_ENABLE_ENABLE_21_WIDTH 1u
#define BEU_ENABLE_ENABLE_21_READ_ACCESS 1u
#define BEU_ENABLE_ENABLE_21_WRITE_ACCESS 1u
#define BEU_ENABLE_ENABLE_21_RESET 0x1u
#define BEU_ENABLE_ENABLE_21_FIELD_MASK 0x0000000000200000ull
#define BEU_ENABLE_ENABLE_21_GET((uint64_t)x) ((((uint64_t)x) & 0x0000000000200000ull) >> 21)
#define BEU_ENABLE_ENABLE_21_SET((uint64_t)x) ((((uint64_t)x) << 21) & 0x0000000000200000ull)
#define BEU_ENABLE_ENABLE_21_MODIFY(r, x) \
   (((((uint64_t)x) << 21) & 0x0000000000200000ull) | ((r) & 0xffffffffffdfffffull))
/* Field member: beu::enable.enable_20                                     */
#define BEU_ENABLE_ENABLE_20_MSB 20u
#define BEU_ENABLE_ENABLE_20_LSB 20u
#define BEU_ENABLE_ENABLE_20_WIDTH 1u
#define BEU_ENABLE_ENABLE_20_READ_ACCESS 1u
#define BEU_ENABLE_ENABLE_20_WRITE_ACCESS 1u
#define BEU_ENABLE_ENABLE_20_RESET 0x1u
#define BEU_ENABLE_ENABLE_20_FIELD_MASK 0x0000000000100000ull
#define BEU_ENABLE_ENABLE_20_GET((uint64_t)x) ((((uint64_t)x) & 0x0000000000100000ull) >> 20)
#define BEU_ENABLE_ENABLE_20_SET((uint64_t)x) ((((uint64_t)x) << 20) & 0x0000000000100000ull)
#define BEU_ENABLE_ENABLE_20_MODIFY(r, x) \
   (((((uint64_t)x) << 20) & 0x0000000000100000ull) | ((r) & 0xffffffffffefffffull))
/* Field member: beu::enable.enable_9                                      */
#define BEU_ENABLE_ENABLE_9_MSB 9u
#define BEU_ENABLE_ENABLE_9_LSB 9u
#define BEU_ENABLE_ENABLE_9_WIDTH 1u
#define BEU_ENABLE_ENABLE_9_READ_ACCESS 1u
#define BEU_ENABLE_ENABLE_9_WRITE_ACCESS 1u
#define BEU_ENABLE_ENABLE_9_RESET 0x1u
#define BEU_ENABLE_ENABLE_9_FIELD_MASK 0x0000000000000200ull
#define BEU_ENABLE_ENABLE_9_GET((uint64_t)x) ((((uint64_t)x) & 0x0000000000000200ull) >> 9)
#define BEU_ENABLE_ENABLE_9_SET((uint64_t)x) ((((uint64_t)x) << 9) & 0x0000000000000200ull)
#define BEU_ENABLE_ENABLE_9_MODIFY(r, x) \
   (((((uint64_t)x) << 9) & 0x0000000000000200ull) | ((r) & 0xfffffffffffffdffull))
/* Field member: beu::enable.enable_8                                      */
#define BEU_ENABLE_ENABLE_8_MSB 8u
#define BEU_ENABLE_ENABLE_8_LSB 8u
#define BEU_ENABLE_ENABLE_8_WIDTH 1u
#define BEU_ENABLE_ENABLE_8_READ_ACCESS 1u
#define BEU_ENABLE_ENABLE_8_WRITE_ACCESS 1u
#define BEU_ENABLE_ENABLE_8_RESET 0x1u
#define BEU_ENABLE_ENABLE_8_FIELD_MASK 0x0000000000000100ull
#define BEU_ENABLE_ENABLE_8_GET((uint64_t)x) ((((uint64_t)x) & 0x0000000000000100ull) >> 8)
#define BEU_ENABLE_ENABLE_8_SET((uint64_t)x) ((((uint64_t)x) << 8) & 0x0000000000000100ull)
#define BEU_ENABLE_ENABLE_8_MODIFY(r, x) \
   (((((uint64_t)x) << 8) & 0x0000000000000100ull) | ((r) & 0xfffffffffffffeffull))
/* Field member: beu::enable.enable_3                                      */
#define BEU_ENABLE_ENABLE_3_MSB 3u
#define BEU_ENABLE_ENABLE_3_LSB 3u
#define BEU_ENABLE_ENABLE_3_WIDTH 1u
#define BEU_ENABLE_ENABLE_3_READ_ACCESS 1u
#define BEU_ENABLE_ENABLE_3_WRITE_ACCESS 1u
#define BEU_ENABLE_ENABLE_3_RESET 0x1u
#define BEU_ENABLE_ENABLE_3_FIELD_MASK 0x0000000000000008ull
#define BEU_ENABLE_ENABLE_3_GET((uint64_t)x) ((((uint64_t)x) & 0x0000000000000008ull) >> 3)
#define BEU_ENABLE_ENABLE_3_SET((uint64_t)x) ((((uint64_t)x) << 3) & 0x0000000000000008ull)
#define BEU_ENABLE_ENABLE_3_MODIFY(r, x) \
   (((((uint64_t)x) << 3) & 0x0000000000000008ull) | ((r) & 0xfffffffffffffff7ull))
/* Field member: beu::enable.enable_2                                      */
#define BEU_ENABLE_ENABLE_2_MSB 2u
#define BEU_ENABLE_ENABLE_2_LSB 2u
#define BEU_ENABLE_ENABLE_2_WIDTH 1u
#define BEU_ENABLE_ENABLE_2_READ_ACCESS 1u
#define BEU_ENABLE_ENABLE_2_WRITE_ACCESS 1u
#define BEU_ENABLE_ENABLE_2_RESET 0x1u
#define BEU_ENABLE_ENABLE_2_FIELD_MASK 0x0000000000000004ull
#define BEU_ENABLE_ENABLE_2_GET((uint64_t)x) ((((uint64_t)x) & 0x0000000000000004ull) >> 2)
#define BEU_ENABLE_ENABLE_2_SET((uint64_t)x) ((((uint64_t)x) << 2) & 0x0000000000000004ull)
#define BEU_ENABLE_ENABLE_2_MODIFY(r, x) \
   (((((uint64_t)x) << 2) & 0x0000000000000004ull) | ((r) & 0xfffffffffffffffbull))
/* Field member: beu::enable.enable_1                                      */
#define BEU_ENABLE_ENABLE_1_MSB 1u
#define BEU_ENABLE_ENABLE_1_LSB 1u
#define BEU_ENABLE_ENABLE_1_WIDTH 1u
#define BEU_ENABLE_ENABLE_1_READ_ACCESS 1u
#define BEU_ENABLE_ENABLE_1_WRITE_ACCESS 1u
#define BEU_ENABLE_ENABLE_1_RESET 0x1u
#define BEU_ENABLE_ENABLE_1_FIELD_MASK 0x0000000000000002ull
#define BEU_ENABLE_ENABLE_1_GET((uint64_t)x) ((((uint64_t)x) & 0x0000000000000002ull) >> 1)
#define BEU_ENABLE_ENABLE_1_SET((uint64_t)x) ((((uint64_t)x) << 1) & 0x0000000000000002ull)
#define BEU_ENABLE_ENABLE_1_MODIFY(r, x) \
   (((((uint64_t)x) << 1) & 0x0000000000000002ull) | ((r) & 0xfffffffffffffffdull))

/* Register type: beu::plic_interrupt                                      */
/* Register template: beu::plic_interrupt                                  */
/* Field member: beu::plic_interrupt.plic_interrupt_24                     */
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_24_MSB 24u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_24_LSB 24u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_24_WIDTH 1u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_24_READ_ACCESS 1u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_24_WRITE_ACCESS 1u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_24_RESET 0x0u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_24_FIELD_MASK 0x0000000001000000ull
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_24_GET(x) \
   ((((uint64_t)x) & 0x0000000001000000ull) >> 24)
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_24_SET(x) \
   ((((uint64_t)x) << 24) & 0x0000000001000000ull)
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_24_MODIFY(r, x) \
   (((((uint64_t)x) << 24) & 0x0000000001000000ull) | ((r) & 0xfffffffffeffffffull))
/* Field member: beu::plic_interrupt.plic_interrupt_23                     */
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_23_MSB 23u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_23_LSB 23u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_23_WIDTH 1u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_23_READ_ACCESS 1u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_23_WRITE_ACCESS 1u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_23_RESET 0x0u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_23_FIELD_MASK 0x0000000000800000ull
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_23_GET(x) \
   ((((uint64_t)x) & 0x0000000000800000ull) >> 23)
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_23_SET(x) \
   ((((uint64_t)x) << 23) & 0x0000000000800000ull)
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_23_MODIFY(r, x) \
   (((((uint64_t)x) << 23) & 0x0000000000800000ull) | ((r) & 0xffffffffff7fffffull))
/* Field member: beu::plic_interrupt.plic_interrupt_22                     */
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_22_MSB 22u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_22_LSB 22u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_22_WIDTH 1u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_22_READ_ACCESS 1u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_22_WRITE_ACCESS 1u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_22_RESET 0x0u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_22_FIELD_MASK 0x0000000000400000ull
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_22_GET(x) \
   ((((uint64_t)x) & 0x0000000000400000ull) >> 22)
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_22_SET(x) \
   ((((uint64_t)x) << 22) & 0x0000000000400000ull)
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_22_MODIFY(r, x) \
   (((((uint64_t)x) << 22) & 0x0000000000400000ull) | ((r) & 0xffffffffffbfffffull))
/* Field member: beu::plic_interrupt.plic_interrupt_21                     */
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_21_MSB 21u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_21_LSB 21u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_21_WIDTH 1u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_21_READ_ACCESS 1u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_21_WRITE_ACCESS 1u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_21_RESET 0x0u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_21_FIELD_MASK 0x0000000000200000ull
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_21_GET(x) \
   ((((uint64_t)x) & 0x0000000000200000ull) >> 21)
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_21_SET(x) \
   ((((uint64_t)x) << 21) & 0x0000000000200000ull)
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_21_MODIFY(r, x) \
   (((((uint64_t)x) << 21) & 0x0000000000200000ull) | ((r) & 0xffffffffffdfffffull))
/* Field member: beu::plic_interrupt.plic_interrupt_20                     */
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_20_MSB 20u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_20_LSB 20u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_20_WIDTH 1u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_20_READ_ACCESS 1u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_20_WRITE_ACCESS 1u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_20_RESET 0x0u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_20_FIELD_MASK 0x0000000000100000ull
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_20_GET(x) \
   ((((uint64_t)x) & 0x0000000000100000ull) >> 20)
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_20_SET(x) \
   ((((uint64_t)x) << 20) & 0x0000000000100000ull)
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_20_MODIFY(r, x) \
   (((((uint64_t)x) << 20) & 0x0000000000100000ull) | ((r) & 0xffffffffffefffffull))
/* Field member: beu::plic_interrupt.plic_interrupt_9                      */
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_9_MSB 9u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_9_LSB 9u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_9_WIDTH 1u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_9_READ_ACCESS 1u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_9_WRITE_ACCESS 1u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_9_RESET 0x0u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_9_FIELD_MASK 0x0000000000000200ull
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_9_GET(x) \
   ((((uint64_t)x) & 0x0000000000000200ull) >> 9)
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_9_SET(x) \
   ((((uint64_t)x) << 9) & 0x0000000000000200ull)
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_9_MODIFY(r, x) \
   (((((uint64_t)x) << 9) & 0x0000000000000200ull) | ((r) & 0xfffffffffffffdffull))
/* Field member: beu::plic_interrupt.plic_interrupt_8                      */
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_8_MSB 8u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_8_LSB 8u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_8_WIDTH 1u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_8_READ_ACCESS 1u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_8_WRITE_ACCESS 1u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_8_RESET 0x0u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_8_FIELD_MASK 0x0000000000000100ull
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_8_GET(x) \
   ((((uint64_t)x) & 0x0000000000000100ull) >> 8)
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_8_SET(x) \
   ((((uint64_t)x) << 8) & 0x0000000000000100ull)
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_8_MODIFY(r, x) \
   (((((uint64_t)x) << 8) & 0x0000000000000100ull) | ((r) & 0xfffffffffffffeffull))
/* Field member: beu::plic_interrupt.plic_interrupt_3                      */
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_3_MSB 3u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_3_LSB 3u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_3_WIDTH 1u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_3_READ_ACCESS 1u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_3_WRITE_ACCESS 1u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_3_RESET 0x0u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_3_FIELD_MASK 0x0000000000000008ull
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_3_GET(x) \
   ((((uint64_t)x) & 0x0000000000000008ull) >> 3)
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_3_SET(x) \
   ((((uint64_t)x) << 3) & 0x0000000000000008ull)
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_3_MODIFY(r, x) \
   (((((uint64_t)x) << 3) & 0x0000000000000008ull) | ((r) & 0xfffffffffffffff7ull))
/* Field member: beu::plic_interrupt.plic_interrupt_2                      */
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_2_MSB 2u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_2_LSB 2u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_2_WIDTH 1u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_2_READ_ACCESS 1u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_2_WRITE_ACCESS 1u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_2_RESET 0x0u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_2_FIELD_MASK 0x0000000000000004ull
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_2_GET(x) \
   ((((uint64_t)x) & 0x0000000000000004ull) >> 2)
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_2_SET(x) \
   ((((uint64_t)x) << 2) & 0x0000000000000004ull)
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_2_MODIFY(r, x) \
   (((((uint64_t)x) << 2) & 0x0000000000000004ull) | ((r) & 0xfffffffffffffffbull))
/* Field member: beu::plic_interrupt.plic_interrupt_1                      */
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_1_MSB 1u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_1_LSB 1u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_1_WIDTH 1u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_1_READ_ACCESS 1u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_1_WRITE_ACCESS 1u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_1_RESET 0x0u
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_1_FIELD_MASK 0x0000000000000002ull
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_1_GET(x) \
   ((((uint64_t)x) & 0x0000000000000002ull) >> 1)
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_1_SET(x) \
   ((((uint64_t)x) << 1) & 0x0000000000000002ull)
#define BEU_PLIC_INTERRUPT_PLIC_INTERRUPT_1_MODIFY(r, x) \
   (((((uint64_t)x) << 1) & 0x0000000000000002ull) | ((r) & 0xfffffffffffffffdull))

/* Register type: beu::local_interrupt                                     */
/* Register template: beu::local_interrupt                                 */
/* Field member: beu::local_interrupt.local_interrupt_24                   */
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_24_MSB 24u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_24_LSB 24u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_24_WIDTH 1u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_24_READ_ACCESS 1u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_24_WRITE_ACCESS 1u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_24_RESET 0x0u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_24_FIELD_MASK 0x0000000001000000ull
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_24_GET(x) \
   ((((uint64_t)x) & 0x0000000001000000ull) >> 24)
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_24_SET(x) \
   ((((uint64_t)x) << 24) & 0x0000000001000000ull)
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_24_MODIFY(r, x) \
   (((((uint64_t)x) << 24) & 0x0000000001000000ull) | ((r) & 0xfffffffffeffffffull))
/* Field member: beu::local_interrupt.local_interrupt_23                   */
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_23_MSB 23u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_23_LSB 23u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_23_WIDTH 1u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_23_READ_ACCESS 1u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_23_WRITE_ACCESS 1u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_23_RESET 0x0u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_23_FIELD_MASK 0x0000000000800000ull
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_23_GET(x) \
   ((((uint64_t)x) & 0x0000000000800000ull) >> 23)
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_23_SET(x) \
   ((((uint64_t)x) << 23) & 0x0000000000800000ull)
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_23_MODIFY(r, x) \
   (((((uint64_t)x) << 23) & 0x0000000000800000ull) | ((r) & 0xffffffffff7fffffull))
/* Field member: beu::local_interrupt.local_interrupt_22                   */
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_22_MSB 22u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_22_LSB 22u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_22_WIDTH 1u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_22_READ_ACCESS 1u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_22_WRITE_ACCESS 1u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_22_RESET 0x0u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_22_FIELD_MASK 0x0000000000400000ull
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_22_GET(x) \
   ((((uint64_t)x) & 0x0000000000400000ull) >> 22)
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_22_SET(x) \
   ((((uint64_t)x) << 22) & 0x0000000000400000ull)
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_22_MODIFY(r, x) \
   (((((uint64_t)x) << 22) & 0x0000000000400000ull) | ((r) & 0xffffffffffbfffffull))
/* Field member: beu::local_interrupt.local_interrupt_21                   */
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_21_MSB 21u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_21_LSB 21u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_21_WIDTH 1u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_21_READ_ACCESS 1u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_21_WRITE_ACCESS 1u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_21_RESET 0x0u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_21_FIELD_MASK 0x0000000000200000ull
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_21_GET(x) \
   ((((uint64_t)x) & 0x0000000000200000ull) >> 21)
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_21_SET(x) \
   ((((uint64_t)x) << 21) & 0x0000000000200000ull)
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_21_MODIFY(r, x) \
   (((((uint64_t)x) << 21) & 0x0000000000200000ull) | ((r) & 0xffffffffffdfffffull))
/* Field member: beu::local_interrupt.local_interrupt_20                   */
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_20_MSB 20u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_20_LSB 20u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_20_WIDTH 1u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_20_READ_ACCESS 1u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_20_WRITE_ACCESS 1u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_20_RESET 0x0u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_20_FIELD_MASK 0x0000000000100000ull
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_20_GET(x) \
   ((((uint64_t)x) & 0x0000000000100000ull) >> 20)
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_20_SET(x) \
   ((((uint64_t)x) << 20) & 0x0000000000100000ull)
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_20_MODIFY(r, x) \
   (((((uint64_t)x) << 20) & 0x0000000000100000ull) | ((r) & 0xffffffffffefffffull))
/* Field member: beu::local_interrupt.local_interrupt_9                    */
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_9_MSB 9u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_9_LSB 9u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_9_WIDTH 1u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_9_READ_ACCESS 1u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_9_WRITE_ACCESS 1u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_9_RESET 0x0u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_9_FIELD_MASK 0x0000000000000200ull
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_9_GET(x) \
   ((((uint64_t)x) & 0x0000000000000200ull) >> 9)
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_9_SET(x) \
   ((((uint64_t)x) << 9) & 0x0000000000000200ull)
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_9_MODIFY(r, x) \
   (((((uint64_t)x) << 9) & 0x0000000000000200ull) | ((r) & 0xfffffffffffffdffull))
/* Field member: beu::local_interrupt.local_interrupt_8                    */
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_8_MSB 8u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_8_LSB 8u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_8_WIDTH 1u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_8_READ_ACCESS 1u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_8_WRITE_ACCESS 1u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_8_RESET 0x0u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_8_FIELD_MASK 0x0000000000000100ull
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_8_GET(x) \
   ((((uint64_t)x) & 0x0000000000000100ull) >> 8)
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_8_SET(x) \
   ((((uint64_t)x) << 8) & 0x0000000000000100ull)
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_8_MODIFY(r, x) \
   (((((uint64_t)x) << 8) & 0x0000000000000100ull) | ((r) & 0xfffffffffffffeffull))
/* Field member: beu::local_interrupt.local_interrupt_3                    */
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_3_MSB 3u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_3_LSB 3u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_3_WIDTH 1u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_3_READ_ACCESS 1u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_3_WRITE_ACCESS 1u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_3_RESET 0x0u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_3_FIELD_MASK 0x0000000000000008ull
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_3_GET(x) \
   ((((uint64_t)x) & 0x0000000000000008ull) >> 3)
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_3_SET(x) \
   ((((uint64_t)x) << 3) & 0x0000000000000008ull)
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_3_MODIFY(r, x) \
   (((((uint64_t)x) << 3) & 0x0000000000000008ull) | ((r) & 0xfffffffffffffff7ull))
/* Field member: beu::local_interrupt.local_interrupt_2                    */
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_2_MSB 2u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_2_LSB 2u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_2_WIDTH 1u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_2_READ_ACCESS 1u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_2_WRITE_ACCESS 1u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_2_RESET 0x0u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_2_FIELD_MASK 0x0000000000000004ull
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_2_GET(x) \
   ((((uint64_t)x) & 0x0000000000000004ull) >> 2)
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_2_SET(x) \
   ((((uint64_t)x) << 2) & 0x0000000000000004ull)
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_2_MODIFY(r, x) \
   (((((uint64_t)x) << 2) & 0x0000000000000004ull) | ((r) & 0xfffffffffffffffbull))
/* Field member: beu::local_interrupt.local_interrupt_1                    */
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_1_MSB 1u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_1_LSB 1u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_1_WIDTH 1u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_1_READ_ACCESS 1u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_1_WRITE_ACCESS 1u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_1_RESET 0x0u
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_1_FIELD_MASK 0x0000000000000002ull
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_1_GET(x) \
   ((((uint64_t)x) & 0x0000000000000002ull) >> 1)
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_1_SET(x) \
   ((((uint64_t)x) << 1) & 0x0000000000000002ull)
#define BEU_LOCAL_INTERRUPT_LOCAL_INTERRUPT_1_MODIFY(r, x) \
   (((((uint64_t)x) << 1) & 0x0000000000000002ull) | ((r) & 0xfffffffffffffffdull))

/* Register type: beu::mce_counter1_mask                                   */
/* Register template: beu::mce_counter1_mask                               */
/* Field member: beu::mce_counter1_mask.mce_counter1_mask_24               */
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_24_MSB 24u
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_24_LSB 24u
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_24_WIDTH 1u
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_24_READ_ACCESS 1u
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_24_WRITE_ACCESS 1u
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_24_FIELD_MASK 0x0000000001000000ull
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_24_GET(x) \
   ((((uint64_t)x) & 0x0000000001000000ull) >> 24)
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_24_SET(x) \
   ((((uint64_t)x) << 24) & 0x0000000001000000ull)
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_24_MODIFY(r, x) \
   (((((uint64_t)x) << 24) & 0x0000000001000000ull) | ((r) & 0xfffffffffeffffffull))
/* Field member: beu::mce_counter1_mask.mce_counter1_mask_23               */
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_23_MSB 23u
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_23_LSB 23u
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_23_WIDTH 1u
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_23_READ_ACCESS 1u
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_23_WRITE_ACCESS 1u
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_23_FIELD_MASK 0x0000000000800000ull
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_23_GET(x) \
   ((((uint64_t)x) & 0x0000000000800000ull) >> 23)
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_23_SET(x) \
   ((((uint64_t)x) << 23) & 0x0000000000800000ull)
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_23_MODIFY(r, x) \
   (((((uint64_t)x) << 23) & 0x0000000000800000ull) | ((r) & 0xffffffffff7fffffull))
/* Field member: beu::mce_counter1_mask.mce_counter1_mask_22               */
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_22_MSB 22u
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_22_LSB 22u
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_22_WIDTH 1u
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_22_READ_ACCESS 1u
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_22_WRITE_ACCESS 1u
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_22_FIELD_MASK 0x0000000000400000ull
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_22_GET(x) \
   ((((uint64_t)x) & 0x0000000000400000ull) >> 22)
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_22_SET(x) \
   ((((uint64_t)x) << 22) & 0x0000000000400000ull)
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_22_MODIFY(r, x) \
   (((((uint64_t)x) << 22) & 0x0000000000400000ull) | ((r) & 0xffffffffffbfffffull))
/* Field member: beu::mce_counter1_mask.mce_counter1_mask_21               */
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_21_MSB 21u
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_21_LSB 21u
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_21_WIDTH 1u
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_21_READ_ACCESS 1u
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_21_WRITE_ACCESS 1u
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_21_FIELD_MASK 0x0000000000200000ull
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_21_GET(x) \
   ((((uint64_t)x) & 0x0000000000200000ull) >> 21)
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_21_SET(x) \
   ((((uint64_t)x) << 21) & 0x0000000000200000ull)
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_21_MODIFY(r, x) \
   (((((uint64_t)x) << 21) & 0x0000000000200000ull) | ((r) & 0xffffffffffdfffffull))
/* Field member: beu::mce_counter1_mask.mce_counter1_mask_20               */
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_20_MSB 20u
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_20_LSB 20u
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_20_WIDTH 1u
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_20_READ_ACCESS 1u
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_20_WRITE_ACCESS 1u
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_20_FIELD_MASK 0x0000000000100000ull
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_20_GET(x) \
   ((((uint64_t)x) & 0x0000000000100000ull) >> 20)
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_20_SET(x) \
   ((((uint64_t)x) << 20) & 0x0000000000100000ull)
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_20_MODIFY(r, x) \
   (((((uint64_t)x) << 20) & 0x0000000000100000ull) | ((r) & 0xffffffffffefffffull))
/* Field member: beu::mce_counter1_mask.mce_counter1_mask_9                */
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_9_MSB 9u
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_9_LSB 9u
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_9_WIDTH 1u
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_9_READ_ACCESS 1u
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_9_WRITE_ACCESS 1u
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_9_FIELD_MASK 0x0000000000000200ull
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_9_GET(x) \
   ((((uint64_t)x) & 0x0000000000000200ull) >> 9)
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_9_SET(x) \
   ((((uint64_t)x) << 9) & 0x0000000000000200ull)
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_9_MODIFY(r, x) \
   (((((uint64_t)x) << 9) & 0x0000000000000200ull) | ((r) & 0xfffffffffffffdffull))
/* Field member: beu::mce_counter1_mask.mce_counter1_mask_8                */
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_8_MSB 8u
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_8_LSB 8u
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_8_WIDTH 1u
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_8_READ_ACCESS 1u
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_8_WRITE_ACCESS 1u
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_8_FIELD_MASK 0x0000000000000100ull
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_8_GET(x) \
   ((((uint64_t)x) & 0x0000000000000100ull) >> 8)
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_8_SET(x) \
   ((((uint64_t)x) << 8) & 0x0000000000000100ull)
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_8_MODIFY(r, x) \
   (((((uint64_t)x) << 8) & 0x0000000000000100ull) | ((r) & 0xfffffffffffffeffull))
/* Field member: beu::mce_counter1_mask.mce_counter1_mask_3                */
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_3_MSB 3u
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_3_LSB 3u
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_3_WIDTH 1u
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_3_READ_ACCESS 1u
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_3_WRITE_ACCESS 1u
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_3_FIELD_MASK 0x0000000000000008ull
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_3_GET(x) \
   ((((uint64_t)x) & 0x0000000000000008ull) >> 3)
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_3_SET(x) \
   ((((uint64_t)x) << 3) & 0x0000000000000008ull)
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_3_MODIFY(r, x) \
   (((((uint64_t)x) << 3) & 0x0000000000000008ull) | ((r) & 0xfffffffffffffff7ull))
/* Field member: beu::mce_counter1_mask.mce_counter1_mask_2                */
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_2_MSB 2u
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_2_LSB 2u
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_2_WIDTH 1u
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_2_READ_ACCESS 1u
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_2_WRITE_ACCESS 1u
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_2_FIELD_MASK 0x0000000000000004ull
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_2_GET(x) \
   ((((uint64_t)x) & 0x0000000000000004ull) >> 2)
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_2_SET(x) \
   ((((uint64_t)x) << 2) & 0x0000000000000004ull)
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_2_MODIFY(r, x) \
   (((((uint64_t)x) << 2) & 0x0000000000000004ull) | ((r) & 0xfffffffffffffffbull))
/* Field member: beu::mce_counter1_mask.mce_counter1_mask_1                */
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_1_MSB 1u
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_1_LSB 1u
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_1_WIDTH 1u
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_1_READ_ACCESS 1u
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_1_WRITE_ACCESS 1u
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_1_FIELD_MASK 0x0000000000000002ull
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_1_GET(x) \
   ((((uint64_t)x) & 0x0000000000000002ull) >> 1)
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_1_SET(x) \
   ((((uint64_t)x) << 1) & 0x0000000000000002ull)
#define BEU_MCE_COUNTER1_MASK_MCE_COUNTER1_MASK_1_MODIFY(r, x) \
   (((((uint64_t)x) << 1) & 0x0000000000000002ull) | ((r) & 0xfffffffffffffffdull))

/* Register type: beu::mce_counter2_mask                                   */
/* Register template: beu::mce_counter2_mask                               */
/* Field member: beu::mce_counter2_mask.mce_counter2_mask_24               */
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_24_MSB 24u
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_24_LSB 24u
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_24_WIDTH 1u
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_24_READ_ACCESS 1u
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_24_WRITE_ACCESS 1u
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_24_FIELD_MASK 0x0000000001000000ull
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_24_GET(x) \
   ((((uint64_t)x) & 0x0000000001000000ull) >> 24)
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_24_SET(x) \
   ((((uint64_t)x) << 24) & 0x0000000001000000ull)
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_24_MODIFY(r, x) \
   (((((uint64_t)x) << 24) & 0x0000000001000000ull) | ((r) & 0xfffffffffeffffffull))
/* Field member: beu::mce_counter2_mask.mce_counter2_mask_23               */
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_23_MSB 23u
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_23_LSB 23u
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_23_WIDTH 1u
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_23_READ_ACCESS 1u
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_23_WRITE_ACCESS 1u
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_23_FIELD_MASK 0x0000000000800000ull
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_23_GET(x) \
   ((((uint64_t)x) & 0x0000000000800000ull) >> 23)
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_23_SET(x) \
   ((((uint64_t)x) << 23) & 0x0000000000800000ull)
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_23_MODIFY(r, x) \
   (((((uint64_t)x) << 23) & 0x0000000000800000ull) | ((r) & 0xffffffffff7fffffull))
/* Field member: beu::mce_counter2_mask.mce_counter2_mask_22               */
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_22_MSB 22u
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_22_LSB 22u
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_22_WIDTH 1u
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_22_READ_ACCESS 1u
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_22_WRITE_ACCESS 1u
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_22_FIELD_MASK 0x0000000000400000ull
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_22_GET(x) \
   ((((uint64_t)x) & 0x0000000000400000ull) >> 22)
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_22_SET(x) \
   ((((uint64_t)x) << 22) & 0x0000000000400000ull)
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_22_MODIFY(r, x) \
   (((((uint64_t)x) << 22) & 0x0000000000400000ull) | ((r) & 0xffffffffffbfffffull))
/* Field member: beu::mce_counter2_mask.mce_counter2_mask_21               */
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_21_MSB 21u
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_21_LSB 21u
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_21_WIDTH 1u
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_21_READ_ACCESS 1u
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_21_WRITE_ACCESS 1u
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_21_FIELD_MASK 0x0000000000200000ull
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_21_GET(x) \
   ((((uint64_t)x) & 0x0000000000200000ull) >> 21)
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_21_SET(x) \
   ((((uint64_t)x) << 21) & 0x0000000000200000ull)
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_21_MODIFY(r, x) \
   (((((uint64_t)x) << 21) & 0x0000000000200000ull) | ((r) & 0xffffffffffdfffffull))
/* Field member: beu::mce_counter2_mask.mce_counter2_mask_20               */
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_20_MSB 20u
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_20_LSB 20u
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_20_WIDTH 1u
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_20_READ_ACCESS 1u
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_20_WRITE_ACCESS 1u
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_20_FIELD_MASK 0x0000000000100000ull
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_20_GET(x) \
   ((((uint64_t)x) & 0x0000000000100000ull) >> 20)
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_20_SET(x) \
   ((((uint64_t)x) << 20) & 0x0000000000100000ull)
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_20_MODIFY(r, x) \
   (((((uint64_t)x) << 20) & 0x0000000000100000ull) | ((r) & 0xffffffffffefffffull))
/* Field member: beu::mce_counter2_mask.mce_counter2_mask_9                */
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_9_MSB 9u
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_9_LSB 9u
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_9_WIDTH 1u
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_9_READ_ACCESS 1u
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_9_WRITE_ACCESS 1u
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_9_FIELD_MASK 0x0000000000000200ull
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_9_GET(x) \
   ((((uint64_t)x) & 0x0000000000000200ull) >> 9)
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_9_SET(x) \
   ((((uint64_t)x) << 9) & 0x0000000000000200ull)
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_9_MODIFY(r, x) \
   (((((uint64_t)x) << 9) & 0x0000000000000200ull) | ((r) & 0xfffffffffffffdffull))
/* Field member: beu::mce_counter2_mask.mce_counter2_mask_8                */
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_8_MSB 8u
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_8_LSB 8u
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_8_WIDTH 1u
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_8_READ_ACCESS 1u
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_8_WRITE_ACCESS 1u
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_8_FIELD_MASK 0x0000000000000100ull
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_8_GET(x) \
   ((((uint64_t)x) & 0x0000000000000100ull) >> 8)
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_8_SET(x) \
   ((((uint64_t)x) << 8) & 0x0000000000000100ull)
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_8_MODIFY(r, x) \
   (((((uint64_t)x) << 8) & 0x0000000000000100ull) | ((r) & 0xfffffffffffffeffull))
/* Field member: beu::mce_counter2_mask.mce_counter2_mask_3                */
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_3_MSB 3u
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_3_LSB 3u
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_3_WIDTH 1u
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_3_READ_ACCESS 1u
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_3_WRITE_ACCESS 1u
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_3_FIELD_MASK 0x0000000000000008ull
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_3_GET(x) \
   ((((uint64_t)x) & 0x0000000000000008ull) >> 3)
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_3_SET(x) \
   ((((uint64_t)x) << 3) & 0x0000000000000008ull)
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_3_MODIFY(r, x) \
   (((((uint64_t)x) << 3) & 0x0000000000000008ull) | ((r) & 0xfffffffffffffff7ull))
/* Field member: beu::mce_counter2_mask.mce_counter2_mask_2                */
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_2_MSB 2u
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_2_LSB 2u
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_2_WIDTH 1u
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_2_READ_ACCESS 1u
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_2_WRITE_ACCESS 1u
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_2_FIELD_MASK 0x0000000000000004ull
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_2_GET(x) \
   ((((uint64_t)x) & 0x0000000000000004ull) >> 2)
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_2_SET(x) \
   ((((uint64_t)x) << 2) & 0x0000000000000004ull)
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_2_MODIFY(r, x) \
   (((((uint64_t)x) << 2) & 0x0000000000000004ull) | ((r) & 0xfffffffffffffffbull))
/* Field member: beu::mce_counter2_mask.mce_counter2_mask_1                */
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_1_MSB 1u
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_1_LSB 1u
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_1_WIDTH 1u
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_1_READ_ACCESS 1u
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_1_WRITE_ACCESS 1u
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_1_FIELD_MASK 0x0000000000000002ull
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_1_GET(x) \
   ((((uint64_t)x) & 0x0000000000000002ull) >> 1)
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_1_SET(x) \
   ((((uint64_t)x) << 1) & 0x0000000000000002ull)
#define BEU_MCE_COUNTER2_MASK_MCE_COUNTER2_MASK_1_MODIFY(r, x) \
   (((((uint64_t)x) << 1) & 0x0000000000000002ull) | ((r) & 0xfffffffffffffffdull))

/* Register type: beu::mce_counter1                                        */
/* Register template: beu::mce_counter1                                    */
/* Field member: beu::mce_counter1.MCE_counter_1_1                         */
#define BEU_MCE_COUNTER1_MCE_COUNTER_1_1_MSB 15u
#define BEU_MCE_COUNTER1_MCE_COUNTER_1_1_LSB 8u
#define BEU_MCE_COUNTER1_MCE_COUNTER_1_1_WIDTH 8u
#define BEU_MCE_COUNTER1_MCE_COUNTER_1_1_READ_ACCESS 1u
#define BEU_MCE_COUNTER1_MCE_COUNTER_1_1_WRITE_ACCESS 1u
#define BEU_MCE_COUNTER1_MCE_COUNTER_1_1_FIELD_MASK 0x000000000000ff00ull
#define BEU_MCE_COUNTER1_MCE_COUNTER_1_1_GET(x) \
   ((((uint64_t)x) & 0x000000000000ff00ull) >> 8)
#define BEU_MCE_COUNTER1_MCE_COUNTER_1_1_SET(x) \
   ((((uint64_t)x) << 8) & 0x000000000000ff00ull)
#define BEU_MCE_COUNTER1_MCE_COUNTER_1_1_MODIFY(r, x) \
   (((((uint64_t)x) << 8) & 0x000000000000ff00ull) | ((r) & 0xffffffffffff00ffull))
/* Field member: beu::mce_counter1.MCE_counter_1_0                         */
#define BEU_MCE_COUNTER1_MCE_COUNTER_1_0_MSB 7u
#define BEU_MCE_COUNTER1_MCE_COUNTER_1_0_LSB 0u
#define BEU_MCE_COUNTER1_MCE_COUNTER_1_0_WIDTH 8u
#define BEU_MCE_COUNTER1_MCE_COUNTER_1_0_READ_ACCESS 1u
#define BEU_MCE_COUNTER1_MCE_COUNTER_1_0_WRITE_ACCESS 1u
#define BEU_MCE_COUNTER1_MCE_COUNTER_1_0_FIELD_MASK 0x00000000000000ffull
#define BEU_MCE_COUNTER1_MCE_COUNTER_1_0_GET(x) ((x) & 0x00000000000000ffull)
#define BEU_MCE_COUNTER1_MCE_COUNTER_1_0_SET(x) ((x) & 0x00000000000000ffull)
#define BEU_MCE_COUNTER1_MCE_COUNTER_1_0_MODIFY(r, x) \
   (((x) & 0x00000000000000ffull) | ((r) & 0xffffffffffffff00ull))

/* Register type: beu::mce_counter2                                        */
/* Register template: beu::mce_counter2                                    */
/* Field member: beu::mce_counter2.MCE_counter_2_1                         */
#define BEU_MCE_COUNTER2_MCE_COUNTER_2_1_MSB 15u
#define BEU_MCE_COUNTER2_MCE_COUNTER_2_1_LSB 8u
#define BEU_MCE_COUNTER2_MCE_COUNTER_2_1_WIDTH 8u
#define BEU_MCE_COUNTER2_MCE_COUNTER_2_1_READ_ACCESS 1u
#define BEU_MCE_COUNTER2_MCE_COUNTER_2_1_WRITE_ACCESS 1u
#define BEU_MCE_COUNTER2_MCE_COUNTER_2_1_FIELD_MASK 0x000000000000ff00ull
#define BEU_MCE_COUNTER2_MCE_COUNTER_2_1_GET(x) \
   ((((uint64_t)x) & 0x000000000000ff00ull) >> 8)
#define BEU_MCE_COUNTER2_MCE_COUNTER_2_1_SET(x) \
   ((((uint64_t)x) << 8) & 0x000000000000ff00ull)
#define BEU_MCE_COUNTER2_MCE_COUNTER_2_1_MODIFY(r, x) \
   (((((uint64_t)x) << 8) & 0x000000000000ff00ull) | ((r) & 0xffffffffffff00ffull))
/* Field member: beu::mce_counter2.MCE_counter_2_0                         */
#define BEU_MCE_COUNTER2_MCE_COUNTER_2_0_MSB 7u
#define BEU_MCE_COUNTER2_MCE_COUNTER_2_0_LSB 0u
#define BEU_MCE_COUNTER2_MCE_COUNTER_2_0_WIDTH 8u
#define BEU_MCE_COUNTER2_MCE_COUNTER_2_0_READ_ACCESS 1u
#define BEU_MCE_COUNTER2_MCE_COUNTER_2_0_WRITE_ACCESS 1u
#define BEU_MCE_COUNTER2_MCE_COUNTER_2_0_FIELD_MASK 0x00000000000000ffull
#define BEU_MCE_COUNTER2_MCE_COUNTER_2_0_GET(x) ((x) & 0x00000000000000ffull)
#define BEU_MCE_COUNTER2_MCE_COUNTER_2_0_SET(x) ((x) & 0x00000000000000ffull)
#define BEU_MCE_COUNTER2_MCE_COUNTER_2_0_MODIFY(r, x) \
   (((x) & 0x00000000000000ffull) | ((r) & 0xffffffffffffff00ull))

/* Register type: beu::force_value                                         */
/* Register template: beu::force_value                                     */
/* Field member: beu::force_value.force_value_5                            */
#define BEU_FORCE_VALUE_FORCE_VALUE_5_MSB 47u
#define BEU_FORCE_VALUE_FORCE_VALUE_5_LSB 40u
#define BEU_FORCE_VALUE_FORCE_VALUE_5_WIDTH 8u
#define BEU_FORCE_VALUE_FORCE_VALUE_5_READ_ACCESS 1u
#define BEU_FORCE_VALUE_FORCE_VALUE_5_WRITE_ACCESS 1u
#define BEU_FORCE_VALUE_FORCE_VALUE_5_FIELD_MASK 0x0000ff0000000000ull
#define BEU_FORCE_VALUE_FORCE_VALUE_5_GET(x) \
   ((((uint64_t)x) & 0x0000ff0000000000ull) >> 40)
#define BEU_FORCE_VALUE_FORCE_VALUE_5_SET(x) \
   ((((uint64_t)x) << 40) & 0x0000ff0000000000ull)
#define BEU_FORCE_VALUE_FORCE_VALUE_5_MODIFY(r, x) \
   (((((uint64_t)x) << 40) & 0x0000ff0000000000ull) | ((r) & 0xffff00ffffffffffull))
/* Field member: beu::force_value.force_value_4                            */
#define BEU_FORCE_VALUE_FORCE_VALUE_4_MSB 39u
#define BEU_FORCE_VALUE_FORCE_VALUE_4_LSB 32u
#define BEU_FORCE_VALUE_FORCE_VALUE_4_WIDTH 8u
#define BEU_FORCE_VALUE_FORCE_VALUE_4_READ_ACCESS 1u
#define BEU_FORCE_VALUE_FORCE_VALUE_4_WRITE_ACCESS 1u
#define BEU_FORCE_VALUE_FORCE_VALUE_4_FIELD_MASK 0x000000ff00000000ull
#define BEU_FORCE_VALUE_FORCE_VALUE_4_GET(x) \
   ((((uint64_t)x) & 0x000000ff00000000ull) >> 32)
#define BEU_FORCE_VALUE_FORCE_VALUE_4_SET(x) \
   ((((uint64_t)x) << 32) & 0x000000ff00000000ull)
#define BEU_FORCE_VALUE_FORCE_VALUE_4_MODIFY(r, x) \
   (((((uint64_t)x) << 32) & 0x000000ff00000000ull) | ((r) & 0xffffff00ffffffffull))
/* Field member: beu::force_value.force_value_3                            */
#define BEU_FORCE_VALUE_FORCE_VALUE_3_MSB 31u
#define BEU_FORCE_VALUE_FORCE_VALUE_3_LSB 24u
#define BEU_FORCE_VALUE_FORCE_VALUE_3_WIDTH 8u
#define BEU_FORCE_VALUE_FORCE_VALUE_3_READ_ACCESS 1u
#define BEU_FORCE_VALUE_FORCE_VALUE_3_WRITE_ACCESS 1u
#define BEU_FORCE_VALUE_FORCE_VALUE_3_FIELD_MASK 0x00000000ff000000ull
#define BEU_FORCE_VALUE_FORCE_VALUE_3_GET(x) \
   ((((uint64_t)x) & 0x00000000ff000000ull) >> 24)
#define BEU_FORCE_VALUE_FORCE_VALUE_3_SET(x) \
   ((((uint64_t)x) << 24) & 0x00000000ff000000ull)
#define BEU_FORCE_VALUE_FORCE_VALUE_3_MODIFY(r, x) \
   (((((uint64_t)x) << 24) & 0x00000000ff000000ull) | ((r) & 0xffffffff00ffffffull))
/* Field member: beu::force_value.force_value_2                            */
#define BEU_FORCE_VALUE_FORCE_VALUE_2_MSB 23u
#define BEU_FORCE_VALUE_FORCE_VALUE_2_LSB 16u
#define BEU_FORCE_VALUE_FORCE_VALUE_2_WIDTH 8u
#define BEU_FORCE_VALUE_FORCE_VALUE_2_READ_ACCESS 1u
#define BEU_FORCE_VALUE_FORCE_VALUE_2_WRITE_ACCESS 1u
#define BEU_FORCE_VALUE_FORCE_VALUE_2_FIELD_MASK 0x0000000000ff0000ull
#define BEU_FORCE_VALUE_FORCE_VALUE_2_GET(x) \
   ((((uint64_t)x) & 0x0000000000ff0000ull) >> 16)
#define BEU_FORCE_VALUE_FORCE_VALUE_2_SET(x) \
   ((((uint64_t)x) << 16) & 0x0000000000ff0000ull)
#define BEU_FORCE_VALUE_FORCE_VALUE_2_MODIFY(r, x) \
   (((((uint64_t)x) << 16) & 0x0000000000ff0000ull) | ((r) & 0xffffffffff00ffffull))
/* Field member: beu::force_value.force_value_1                            */
#define BEU_FORCE_VALUE_FORCE_VALUE_1_MSB 15u
#define BEU_FORCE_VALUE_FORCE_VALUE_1_LSB 8u
#define BEU_FORCE_VALUE_FORCE_VALUE_1_WIDTH 8u
#define BEU_FORCE_VALUE_FORCE_VALUE_1_READ_ACCESS 1u
#define BEU_FORCE_VALUE_FORCE_VALUE_1_WRITE_ACCESS 1u
#define BEU_FORCE_VALUE_FORCE_VALUE_1_FIELD_MASK 0x000000000000ff00ull
#define BEU_FORCE_VALUE_FORCE_VALUE_1_GET(x) \
   ((((uint64_t)x) & 0x000000000000ff00ull) >> 8)
#define BEU_FORCE_VALUE_FORCE_VALUE_1_SET(x) \
   ((((uint64_t)x) << 8) & 0x000000000000ff00ull)
#define BEU_FORCE_VALUE_FORCE_VALUE_1_MODIFY(r, x) \
   (((((uint64_t)x) << 8) & 0x000000000000ff00ull) | ((r) & 0xffffffffffff00ffull))
/* Field member: beu::force_value.force_value_0                            */
#define BEU_FORCE_VALUE_FORCE_VALUE_0_MSB 7u
#define BEU_FORCE_VALUE_FORCE_VALUE_0_LSB 0u
#define BEU_FORCE_VALUE_FORCE_VALUE_0_WIDTH 8u
#define BEU_FORCE_VALUE_FORCE_VALUE_0_READ_ACCESS 1u
#define BEU_FORCE_VALUE_FORCE_VALUE_0_WRITE_ACCESS 1u
#define BEU_FORCE_VALUE_FORCE_VALUE_0_FIELD_MASK 0x00000000000000ffull
#define BEU_FORCE_VALUE_FORCE_VALUE_0_GET(x) ((x) & 0x00000000000000ffull)
#define BEU_FORCE_VALUE_FORCE_VALUE_0_SET(x) ((x) & 0x00000000000000ffull)
#define BEU_FORCE_VALUE_FORCE_VALUE_0_MODIFY(r, x) \
   (((x) & 0x00000000000000ffull) | ((r) & 0xffffffffffffff00ull))

/* Register type: beu::force_mce                                           */
/* Register template: beu::force_mce                                       */
/* Field member: beu::force_mce.force_mce_0                                */
#define BEU_FORCE_MCE_FORCE_MCE_0_MSB 4u
#define BEU_FORCE_MCE_FORCE_MCE_0_LSB 0u
#define BEU_FORCE_MCE_FORCE_MCE_0_WIDTH 5u
#define BEU_FORCE_MCE_FORCE_MCE_0_READ_ACCESS 1u
#define BEU_FORCE_MCE_FORCE_MCE_0_WRITE_ACCESS 1u
#define BEU_FORCE_MCE_FORCE_MCE_0_RESET 0x00u
#define BEU_FORCE_MCE_FORCE_MCE_0_FIELD_MASK 0x000000000000001full
#define BEU_FORCE_MCE_FORCE_MCE_0_GET(x) ((x) & 0x000000000000001full)
#define BEU_FORCE_MCE_FORCE_MCE_0_SET(x) ((x) & 0x000000000000001full)
#define BEU_FORCE_MCE_FORCE_MCE_0_MODIFY(r, x) \
   (((x) & 0x000000000000001full) | ((r) & 0xffffffffffffffe0ull))

/* Register type: beu::selected_value                                      */
/* Register template: beu::selected_value                                  */
/* Field member: beu::selected_value.selected_value_5                      */
#define BEU_SELECTED_VALUE_SELECTED_VALUE_5_MSB 47u
#define BEU_SELECTED_VALUE_SELECTED_VALUE_5_LSB 40u
#define BEU_SELECTED_VALUE_SELECTED_VALUE_5_WIDTH 8u
#define BEU_SELECTED_VALUE_SELECTED_VALUE_5_READ_ACCESS 1u
#define BEU_SELECTED_VALUE_SELECTED_VALUE_5_WRITE_ACCESS 1u
#define BEU_SELECTED_VALUE_SELECTED_VALUE_5_FIELD_MASK 0x0000ff0000000000ull
#define BEU_SELECTED_VALUE_SELECTED_VALUE_5_GET(x) \
   ((((uint64_t)x) & 0x0000ff0000000000ull) >> 40)
#define BEU_SELECTED_VALUE_SELECTED_VALUE_5_SET(x) \
   ((((uint64_t)x) << 40) & 0x0000ff0000000000ull)
#define BEU_SELECTED_VALUE_SELECTED_VALUE_5_MODIFY(r, x) \
   (((((uint64_t)x) << 40) & 0x0000ff0000000000ull) | ((r) & 0xffff00ffffffffffull))
/* Field member: beu::selected_value.selected_value_4                      */
#define BEU_SELECTED_VALUE_SELECTED_VALUE_4_MSB 39u
#define BEU_SELECTED_VALUE_SELECTED_VALUE_4_LSB 32u
#define BEU_SELECTED_VALUE_SELECTED_VALUE_4_WIDTH 8u
#define BEU_SELECTED_VALUE_SELECTED_VALUE_4_READ_ACCESS 1u
#define BEU_SELECTED_VALUE_SELECTED_VALUE_4_WRITE_ACCESS 1u
#define BEU_SELECTED_VALUE_SELECTED_VALUE_4_FIELD_MASK 0x000000ff00000000ull
#define BEU_SELECTED_VALUE_SELECTED_VALUE_4_GET(x) \
   ((((uint64_t)x) & 0x000000ff00000000ull) >> 32)
#define BEU_SELECTED_VALUE_SELECTED_VALUE_4_SET(x) \
   ((((uint64_t)x) << 32) & 0x000000ff00000000ull)
#define BEU_SELECTED_VALUE_SELECTED_VALUE_4_MODIFY(r, x) \
   (((((uint64_t)x) << 32) & 0x000000ff00000000ull) | ((r) & 0xffffff00ffffffffull))
/* Field member: beu::selected_value.selected_value_3                      */
#define BEU_SELECTED_VALUE_SELECTED_VALUE_3_MSB 31u
#define BEU_SELECTED_VALUE_SELECTED_VALUE_3_LSB 24u
#define BEU_SELECTED_VALUE_SELECTED_VALUE_3_WIDTH 8u
#define BEU_SELECTED_VALUE_SELECTED_VALUE_3_READ_ACCESS 1u
#define BEU_SELECTED_VALUE_SELECTED_VALUE_3_WRITE_ACCESS 1u
#define BEU_SELECTED_VALUE_SELECTED_VALUE_3_FIELD_MASK 0x00000000ff000000ull
#define BEU_SELECTED_VALUE_SELECTED_VALUE_3_GET(x) \
   ((((uint64_t)x) & 0x00000000ff000000ull) >> 24)
#define BEU_SELECTED_VALUE_SELECTED_VALUE_3_SET(x) \
   ((((uint64_t)x) << 24) & 0x00000000ff000000ull)
#define BEU_SELECTED_VALUE_SELECTED_VALUE_3_MODIFY(r, x) \
   (((((uint64_t)x) << 24) & 0x00000000ff000000ull) | ((r) & 0xffffffff00ffffffull))
/* Field member: beu::selected_value.selected_value_2                      */
#define BEU_SELECTED_VALUE_SELECTED_VALUE_2_MSB 23u
#define BEU_SELECTED_VALUE_SELECTED_VALUE_2_LSB 16u
#define BEU_SELECTED_VALUE_SELECTED_VALUE_2_WIDTH 8u
#define BEU_SELECTED_VALUE_SELECTED_VALUE_2_READ_ACCESS 1u
#define BEU_SELECTED_VALUE_SELECTED_VALUE_2_WRITE_ACCESS 1u
#define BEU_SELECTED_VALUE_SELECTED_VALUE_2_FIELD_MASK 0x0000000000ff0000ull
#define BEU_SELECTED_VALUE_SELECTED_VALUE_2_GET(x) \
   ((((uint64_t)x) & 0x0000000000ff0000ull) >> 16)
#define BEU_SELECTED_VALUE_SELECTED_VALUE_2_SET(x) \
   ((((uint64_t)x) << 16) & 0x0000000000ff0000ull)
#define BEU_SELECTED_VALUE_SELECTED_VALUE_2_MODIFY(r, x) \
   (((((uint64_t)x) << 16) & 0x0000000000ff0000ull) | ((r) & 0xffffffffff00ffffull))
/* Field member: beu::selected_value.selected_value_1                      */
#define BEU_SELECTED_VALUE_SELECTED_VALUE_1_MSB 15u
#define BEU_SELECTED_VALUE_SELECTED_VALUE_1_LSB 8u
#define BEU_SELECTED_VALUE_SELECTED_VALUE_1_WIDTH 8u
#define BEU_SELECTED_VALUE_SELECTED_VALUE_1_READ_ACCESS 1u
#define BEU_SELECTED_VALUE_SELECTED_VALUE_1_WRITE_ACCESS 1u
#define BEU_SELECTED_VALUE_SELECTED_VALUE_1_FIELD_MASK 0x000000000000ff00ull
#define BEU_SELECTED_VALUE_SELECTED_VALUE_1_GET(x) \
   ((((uint64_t)x) & 0x000000000000ff00ull) >> 8)
#define BEU_SELECTED_VALUE_SELECTED_VALUE_1_SET(x) \
   ((((uint64_t)x) << 8) & 0x000000000000ff00ull)
#define BEU_SELECTED_VALUE_SELECTED_VALUE_1_MODIFY(r, x) \
   (((((uint64_t)x) << 8) & 0x000000000000ff00ull) | ((r) & 0xffffffffffff00ffull))
/* Field member: beu::selected_value.selected_value_0                      */
#define BEU_SELECTED_VALUE_SELECTED_VALUE_0_MSB 7u
#define BEU_SELECTED_VALUE_SELECTED_VALUE_0_LSB 0u
#define BEU_SELECTED_VALUE_SELECTED_VALUE_0_WIDTH 8u
#define BEU_SELECTED_VALUE_SELECTED_VALUE_0_READ_ACCESS 1u
#define BEU_SELECTED_VALUE_SELECTED_VALUE_0_WRITE_ACCESS 1u
#define BEU_SELECTED_VALUE_SELECTED_VALUE_0_FIELD_MASK 0x00000000000000ffull
#define BEU_SELECTED_VALUE_SELECTED_VALUE_0_GET(x) \
   ((x) & 0x00000000000000ffull)
#define BEU_SELECTED_VALUE_SELECTED_VALUE_0_SET(x) \
   ((x) & 0x00000000000000ffull)
#define BEU_SELECTED_VALUE_SELECTED_VALUE_0_MODIFY(r, x) \
   (((x) & 0x00000000000000ffull) | ((r) & 0xffffffffffffff00ull))

/* Register type: beu::select_index                                        */
/* Register template: beu::select_index                                    */
/* Field member: beu::select_index.select_index_0                          */
#define BEU_SELECT_INDEX_SELECT_INDEX_0_MSB 4u
#define BEU_SELECT_INDEX_SELECT_INDEX_0_LSB 0u
#define BEU_SELECT_INDEX_SELECT_INDEX_0_WIDTH 5u
#define BEU_SELECT_INDEX_SELECT_INDEX_0_READ_ACCESS 1u
#define BEU_SELECT_INDEX_SELECT_INDEX_0_WRITE_ACCESS 1u
#define BEU_SELECT_INDEX_SELECT_INDEX_0_RESET 0x00u
#define BEU_SELECT_INDEX_SELECT_INDEX_0_FIELD_MASK 0x000000000000001full
#define BEU_SELECT_INDEX_SELECT_INDEX_0_GET(x) ((x) & 0x000000000000001full)
#define BEU_SELECT_INDEX_SELECT_INDEX_0_SET(x) ((x) & 0x000000000000001full)
#define BEU_SELECT_INDEX_SELECT_INDEX_0_MODIFY(r, x) \
   (((x) & 0x000000000000001full) | ((r) & 0xffffffffffffffe0ull))

/* ####################################################################### */
/*        TYPE DEFINITIONS                                                 */
/* ####################################################################### */

/* Typedef for Addressmap: beu                                             */
typedef struct {
   volatile uint64_t current_value; /**< Offset 0x0 (R/W) */
   volatile uint64_t cause; /**< Offset 0x8 (R/W) */
   volatile uint64_t accrued; /**< Offset 0x10 (R/W) */
   volatile uint64_t overflow; /**< Offset 0x18 (R/W) */
   volatile uint64_t enable; /**< Offset 0x20 (R/W) */
   volatile uint64_t plic_interrupt; /**< Offset 0x28 (R/W) */
   volatile uint64_t local_interrupt; /**< Offset 0x30 (R/W) */
   volatile uint64_t mce_counter1_mask; /**< Offset 0x38 (R/W) */
   volatile uint64_t mce_counter2_mask; /**< Offset 0x40 (R/W) */
   volatile uint64_t mce_counter1; /**< Offset 0x48 (R/W) */
   volatile uint64_t mce_counter2; /**< Offset 0x50 (R/W) */
   volatile uint64_t force_value; /**< Offset 0x58 (R/W) */
   volatile uint64_t force_mce; /**< Offset 0x60 (R/W) */
   volatile uint64_t selected_value; /**< Offset 0x68 (R/W) */
   volatile uint64_t select_index; /**< Offset 0x70 (R/W) */
} Beu, *PTR_Beu;

#endif
