/* Copyright (C) 2021, Esperanto Technologies Inc.                         */
/* The copyright to the computer program(s) herein is the                  */
/* property of Esperanto Technologies, Inc. All Rights Reserved.           */
/* The program(s) may be used and/or copied only with                      */
/* the written permission of Esperanto Technologies and                    */
/* in accordance with the terms and conditions stipulated in the           */
/* agreement/contract under which the program(s) have been supplied.       */
/*                                                                         */
/*                                                                         */
/* Generated by Semifore, Inc. csrCompile                                  */
/*    C Header output                                                      */

#ifndef _PU_TRG_MAX_H_
#define _PU_TRG_MAX_H_



/* ####################################################################### */
/*        ADDRESS MACROS                                                   */
/* ####################################################################### */

/* Address Space for Addressmap: ipi_trigger                               */
/* Register: ipi_trigger.ipi_trigger                                       */
#define IPI_TRIGGER_IPI_TRIGGER_ADDRESS 0x0u
#define IPI_TRIGGER_IPI_TRIGGER_BYTE_ADDRESS 0x0u


/* ####################################################################### */
/*        TEMPLATE MACROS                                                  */
/* ####################################################################### */

/* Addressmap type: ipi_trigger                                            */
/* Addressmap template: ipi_trigger                                        */
#define IPI_TRIGGER_SIZE 0x4u
#define IPI_TRIGGER_BYTE_SIZE 0x4u
/* Register member: ipi_trigger.ipi_trigger                                */
/* Register type referenced: ipi_trigger::ipi_trigger                      */
/* Register template referenced: ipi_trigger::ipi_trigger                  */
#define IPI_TRIGGER_IPI_TRIGGER_OFFSET 0x0u
#define IPI_TRIGGER_IPI_TRIGGER_BYTE_OFFSET 0x0u
#define IPI_TRIGGER_IPI_TRIGGER_READ_ACCESS 1u
#define IPI_TRIGGER_IPI_TRIGGER_WRITE_ACCESS 1u
#define IPI_TRIGGER_IPI_TRIGGER_RESET_VALUE 0x00000000ul
#define IPI_TRIGGER_IPI_TRIGGER_RESET_MASK 0xfffffffful
#define IPI_TRIGGER_IPI_TRIGGER_READ_MASK 0xfffffffful
#define IPI_TRIGGER_IPI_TRIGGER_WRITE_MASK 0xfffffffful

/* Register type: ipi_trigger::ipi_trigger                                 */
/* Register template: ipi_trigger::ipi_trigger                             */
/* Field member: ipi_trigger::ipi_trigger.ipi_trigger                      */
#define IPI_TRIGGER_IPI_TRIGGER_IPI_TRIGGER_MSB 31u
#define IPI_TRIGGER_IPI_TRIGGER_IPI_TRIGGER_LSB 0u
#define IPI_TRIGGER_IPI_TRIGGER_IPI_TRIGGER_WIDTH 32u
#define IPI_TRIGGER_IPI_TRIGGER_IPI_TRIGGER_READ_ACCESS 1u
#define IPI_TRIGGER_IPI_TRIGGER_IPI_TRIGGER_WRITE_ACCESS 1u
#define IPI_TRIGGER_IPI_TRIGGER_IPI_TRIGGER_RESET 0x00000000ul
#define IPI_TRIGGER_IPI_TRIGGER_IPI_TRIGGER_FIELD_MASK 0xfffffffful
#define IPI_TRIGGER_IPI_TRIGGER_IPI_TRIGGER_GET(x) ((x) & 0xfffffffful)
#define IPI_TRIGGER_IPI_TRIGGER_IPI_TRIGGER_SET(x) ((x) & 0xfffffffful)
#define IPI_TRIGGER_IPI_TRIGGER_IPI_TRIGGER_MODIFY(r, x) ((x) & 0xfffffffful)

/* ####################################################################### */
/*        TYPE DEFINITIONS                                                 */
/* ####################################################################### */

/* Typedef for Addressmap: ipi_trigger                                     */
typedef struct {
   volatile uint32_t ipi_trigger; /**< Offset 0x0 (R/W) */
} Ipi_trigger, *PTR_Ipi_trigger;

#endif
