/* Copyright (C) 2021, Esperanto Technologies Inc.                         */
/* The copyright to the computer program(s) herein is the                  */
/* property of Esperanto Technologies, Inc. All Rights Reserved.           */
/* The program(s) may be used and/or copied only with                      */
/* the written permission of Esperanto Technologies and                    */
/* in accordance with the terms and conditions stipulated in the           */
/* agreement/contract under which the program(s) have been supplied.       */
/*                                                                         */
/*                                                                         */
/* Generated by Semifore, Inc. csrCompile                                  */
/*    C Header output                                                      */

#ifndef _PVTC_SDA_H_
#define _PVTC_SDA_H_



/* ####################################################################### */
/*        ADDRESS MACROS                                                   */
/* ####################################################################### */

/* Address Space for Addressmap: pvtc_sda                                  */
/* Register: pvtc_sda.ip_ctrl                                              */
#define PVTC_SDA_IP_CTRL_ADDRESS 0x0u
#define PVTC_SDA_IP_CTRL_BYTE_ADDRESS 0x0u
/* Register: pvtc_sda.ip_cfg                                               */
#define PVTC_SDA_IP_CFG_ADDRESS 0x1u
#define PVTC_SDA_IP_CFG_BYTE_ADDRESS 0x4u
/* Register: pvtc_sda.ip_cfga                                              */
#define PVTC_SDA_IP_CFGA_ADDRESS 0x2u
#define PVTC_SDA_IP_CFGA_BYTE_ADDRESS 0x8u
/* Register: pvtc_sda.ip_data                                              */
#define PVTC_SDA_IP_DATA_ADDRESS 0x3u
#define PVTC_SDA_IP_DATA_BYTE_ADDRESS 0xcu
/* Register: pvtc_sda.ip_pol                                               */
#define PVTC_SDA_IP_POL_ADDRESS 0x4u
#define PVTC_SDA_IP_POL_BYTE_ADDRESS 0x10u
/* Register: pvtc_sda.ip_tmr                                               */
#define PVTC_SDA_IP_TMR_ADDRESS 0x5u
#define PVTC_SDA_IP_TMR_BYTE_ADDRESS 0x14u


/* ####################################################################### */
/*        TEMPLATE MACROS                                                  */
/* ####################################################################### */

/* Addressmap type: pvtc_sda                                               */
/* Addressmap template: pvtc_sda                                           */
#define PVTC_SDA_SIZE 0x6u
#define PVTC_SDA_BYTE_SIZE 0x18u
/* Register member: pvtc_sda.ip_ctrl                                       */
/* Register type referenced: pvtc_sda::ip_ctrl                             */
/* Register template referenced: pvtc_sda::ip_ctrl                         */
#define PVTC_SDA_IP_CTRL_OFFSET 0x0u
#define PVTC_SDA_IP_CTRL_BYTE_OFFSET 0x0u
#define PVTC_SDA_IP_CTRL_READ_ACCESS 1u
#define PVTC_SDA_IP_CTRL_WRITE_ACCESS 1u
#define PVTC_SDA_IP_CTRL_RESET_VALUE 0x00000001ul
#define PVTC_SDA_IP_CTRL_RESET_MASK 0xfffffffful
#define PVTC_SDA_IP_CTRL_READ_MASK 0xfffffdebul
#define PVTC_SDA_IP_CTRL_WRITE_MASK 0x0000071ful
/* Register member: pvtc_sda.ip_cfg                                        */
/* Register type referenced: pvtc_sda::ip_cfg                              */
/* Register template referenced: pvtc_sda::ip_cfg                          */
#define PVTC_SDA_IP_CFG_OFFSET 0x1u
#define PVTC_SDA_IP_CFG_BYTE_OFFSET 0x4u
#define PVTC_SDA_IP_CFG_READ_ACCESS 1u
#define PVTC_SDA_IP_CFG_WRITE_ACCESS 1u
#define PVTC_SDA_IP_CFG_RESET_VALUE 0x00000000ul
#define PVTC_SDA_IP_CFG_RESET_MASK 0xfffffffful
#define PVTC_SDA_IP_CFG_READ_MASK 0xfffffffful
#define PVTC_SDA_IP_CFG_WRITE_MASK 0x00fffffful
/* Register member: pvtc_sda.ip_cfga                                       */
/* Register type referenced: pvtc_sda::ip_cfga                             */
/* Register template referenced: pvtc_sda::ip_cfga                         */
#define PVTC_SDA_IP_CFGA_OFFSET 0x2u
#define PVTC_SDA_IP_CFGA_BYTE_OFFSET 0x8u
#define PVTC_SDA_IP_CFGA_READ_ACCESS 1u
#define PVTC_SDA_IP_CFGA_WRITE_ACCESS 1u
#define PVTC_SDA_IP_CFGA_RESET_VALUE 0x00000000ul
#define PVTC_SDA_IP_CFGA_RESET_MASK 0xfffffffful
#define PVTC_SDA_IP_CFGA_READ_MASK 0xfffffffful
#define PVTC_SDA_IP_CFGA_WRITE_MASK 0x000001fful
/* Register member: pvtc_sda.ip_data                                       */
/* Register type referenced: pvtc_sda::ip_data                             */
/* Register template referenced: pvtc_sda::ip_data                         */
#define PVTC_SDA_IP_DATA_OFFSET 0x3u
#define PVTC_SDA_IP_DATA_BYTE_OFFSET 0xcu
#define PVTC_SDA_IP_DATA_READ_ACCESS 1u
#define PVTC_SDA_IP_DATA_WRITE_ACCESS 0u
#define PVTC_SDA_IP_DATA_RESET_VALUE 0x00000000ul
#define PVTC_SDA_IP_DATA_RESET_MASK 0xfffffffful
#define PVTC_SDA_IP_DATA_READ_MASK 0xfffffffful
#define PVTC_SDA_IP_DATA_WRITE_MASK 0x00000000ul
/* Register member: pvtc_sda.ip_pol                                        */
/* Register type referenced: pvtc_sda::ip_pol                              */
/* Register template referenced: pvtc_sda::ip_pol                          */
#define PVTC_SDA_IP_POL_OFFSET 0x4u
#define PVTC_SDA_IP_POL_BYTE_OFFSET 0x10u
#define PVTC_SDA_IP_POL_READ_ACCESS 1u
#define PVTC_SDA_IP_POL_WRITE_ACCESS 1u
#define PVTC_SDA_IP_POL_RESET_VALUE 0x00000000ul
#define PVTC_SDA_IP_POL_RESET_MASK 0xfffffffful
#define PVTC_SDA_IP_POL_READ_MASK 0xffcffffful
#define PVTC_SDA_IP_POL_WRITE_MASK 0x003ffc00ul
/* Register member: pvtc_sda.ip_tmr                                        */
/* Register type referenced: pvtc_sda::ip_tmr                              */
/* Register template referenced: pvtc_sda::ip_tmr                          */
#define PVTC_SDA_IP_TMR_OFFSET 0x5u
#define PVTC_SDA_IP_TMR_BYTE_OFFSET 0x14u
#define PVTC_SDA_IP_TMR_READ_ACCESS 1u
#define PVTC_SDA_IP_TMR_WRITE_ACCESS 1u
#define PVTC_SDA_IP_TMR_RESET_VALUE 0x00000000ul
#define PVTC_SDA_IP_TMR_RESET_MASK 0xfffffffful
#define PVTC_SDA_IP_TMR_READ_MASK 0xfffffffful
#define PVTC_SDA_IP_TMR_WRITE_MASK 0x0000fffful

/* Register type: pvtc_sda::ip_ctrl                                        */
/* Register template: pvtc_sda::ip_ctrl                                    */
/* Field member: pvtc_sda::ip_ctrl.ip_vm_mode                              */
#define PVTC_SDA_IP_CTRL_IP_VM_MODE_MSB 10u
#define PVTC_SDA_IP_CTRL_IP_VM_MODE_LSB 10u
#define PVTC_SDA_IP_CTRL_IP_VM_MODE_WIDTH 1u
#define PVTC_SDA_IP_CTRL_IP_VM_MODE_READ_ACCESS 1u
#define PVTC_SDA_IP_CTRL_IP_VM_MODE_WRITE_ACCESS 1u
#define PVTC_SDA_IP_CTRL_IP_VM_MODE_RESET 0x0u
#define PVTC_SDA_IP_CTRL_IP_VM_MODE_FIELD_MASK 0x00000400ul
#define PVTC_SDA_IP_CTRL_IP_VM_MODE_GET(x) (((x) & 0x00000400ul) >> 10)
#define PVTC_SDA_IP_CTRL_IP_VM_MODE_SET(x) (((x) << 10) & 0x00000400ul)
#define PVTC_SDA_IP_CTRL_IP_VM_MODE_MODIFY(r, x) \
   ((((x) << 10) & 0x00000400ul) | ((r) & 0xfffffbfful))
/* Field member: pvtc_sda::ip_ctrl.ip_stop                                 */
#define PVTC_SDA_IP_CTRL_IP_STOP_MSB 9u
#define PVTC_SDA_IP_CTRL_IP_STOP_LSB 9u
#define PVTC_SDA_IP_CTRL_IP_STOP_WIDTH 1u
#define PVTC_SDA_IP_CTRL_IP_STOP_READ_ACCESS 0u
#define PVTC_SDA_IP_CTRL_IP_STOP_WRITE_ACCESS 1u
#define PVTC_SDA_IP_CTRL_IP_STOP_RESET 0x0u
#define PVTC_SDA_IP_CTRL_IP_STOP_FIELD_MASK 0x00000200ul
#define PVTC_SDA_IP_CTRL_IP_STOP_GET(x) (((x) & 0x00000200ul) >> 9)
#define PVTC_SDA_IP_CTRL_IP_STOP_SET(x) (((x) << 9) & 0x00000200ul)
#define PVTC_SDA_IP_CTRL_IP_STOP_MODIFY(r, x) \
   ((((x) << 9) & 0x00000200ul) | ((r) & 0xfffffdfful))
/* Field member: pvtc_sda::ip_ctrl.ip_auto                                 */
#define PVTC_SDA_IP_CTRL_IP_AUTO_MSB 8u
#define PVTC_SDA_IP_CTRL_IP_AUTO_LSB 8u
#define PVTC_SDA_IP_CTRL_IP_AUTO_WIDTH 1u
#define PVTC_SDA_IP_CTRL_IP_AUTO_READ_ACCESS 1u
#define PVTC_SDA_IP_CTRL_IP_AUTO_WRITE_ACCESS 1u
#define PVTC_SDA_IP_CTRL_IP_AUTO_RESET 0x0u
#define PVTC_SDA_IP_CTRL_IP_AUTO_FIELD_MASK 0x00000100ul
#define PVTC_SDA_IP_CTRL_IP_AUTO_GET(x) (((x) & 0x00000100ul) >> 8)
#define PVTC_SDA_IP_CTRL_IP_AUTO_SET(x) (((x) << 8) & 0x00000100ul)
#define PVTC_SDA_IP_CTRL_IP_AUTO_MODIFY(r, x) \
   ((((x) << 8) & 0x00000100ul) | ((r) & 0xfffffefful))
/* Field member: pvtc_sda::ip_ctrl.ip_cload                                */
#define PVTC_SDA_IP_CTRL_IP_CLOAD_MSB 4u
#define PVTC_SDA_IP_CTRL_IP_CLOAD_LSB 4u
#define PVTC_SDA_IP_CTRL_IP_CLOAD_WIDTH 1u
#define PVTC_SDA_IP_CTRL_IP_CLOAD_READ_ACCESS 0u
#define PVTC_SDA_IP_CTRL_IP_CLOAD_WRITE_ACCESS 1u
#define PVTC_SDA_IP_CTRL_IP_CLOAD_RESET 0x0u
#define PVTC_SDA_IP_CTRL_IP_CLOAD_FIELD_MASK 0x00000010ul
#define PVTC_SDA_IP_CTRL_IP_CLOAD_GET(x) (((x) & 0x00000010ul) >> 4)
#define PVTC_SDA_IP_CTRL_IP_CLOAD_SET(x) (((x) << 4) & 0x00000010ul)
#define PVTC_SDA_IP_CTRL_IP_CLOAD_MODIFY(r, x) \
   ((((x) << 4) & 0x00000010ul) | ((r) & 0xffffffeful))
/* Field member: pvtc_sda::ip_ctrl.ip_run_cont                             */
#define PVTC_SDA_IP_CTRL_IP_RUN_CONT_MSB 3u
#define PVTC_SDA_IP_CTRL_IP_RUN_CONT_LSB 3u
#define PVTC_SDA_IP_CTRL_IP_RUN_CONT_WIDTH 1u
#define PVTC_SDA_IP_CTRL_IP_RUN_CONT_READ_ACCESS 1u
#define PVTC_SDA_IP_CTRL_IP_RUN_CONT_WRITE_ACCESS 1u
#define PVTC_SDA_IP_CTRL_IP_RUN_CONT_RESET 0x0u
#define PVTC_SDA_IP_CTRL_IP_RUN_CONT_FIELD_MASK 0x00000008ul
#define PVTC_SDA_IP_CTRL_IP_RUN_CONT_GET(x) (((x) & 0x00000008ul) >> 3)
#define PVTC_SDA_IP_CTRL_IP_RUN_CONT_SET(x) (((x) << 3) & 0x00000008ul)
#define PVTC_SDA_IP_CTRL_IP_RUN_CONT_MODIFY(r, x) \
   ((((x) << 3) & 0x00000008ul) | ((r) & 0xfffffff7ul))
/* Field member: pvtc_sda::ip_ctrl.ip_run_once                             */
#define PVTC_SDA_IP_CTRL_IP_RUN_ONCE_MSB 2u
#define PVTC_SDA_IP_CTRL_IP_RUN_ONCE_LSB 2u
#define PVTC_SDA_IP_CTRL_IP_RUN_ONCE_WIDTH 1u
#define PVTC_SDA_IP_CTRL_IP_RUN_ONCE_READ_ACCESS 0u
#define PVTC_SDA_IP_CTRL_IP_RUN_ONCE_WRITE_ACCESS 1u
#define PVTC_SDA_IP_CTRL_IP_RUN_ONCE_RESET 0x0u
#define PVTC_SDA_IP_CTRL_IP_RUN_ONCE_FIELD_MASK 0x00000004ul
#define PVTC_SDA_IP_CTRL_IP_RUN_ONCE_GET(x) (((x) & 0x00000004ul) >> 2)
#define PVTC_SDA_IP_CTRL_IP_RUN_ONCE_SET(x) (((x) << 2) & 0x00000004ul)
#define PVTC_SDA_IP_CTRL_IP_RUN_ONCE_MODIFY(r, x) \
   ((((x) << 2) & 0x00000004ul) | ((r) & 0xfffffffbul))
/* Field member: pvtc_sda::ip_ctrl.ip_rstn                                 */
#define PVTC_SDA_IP_CTRL_IP_RSTN_MSB 1u
#define PVTC_SDA_IP_CTRL_IP_RSTN_LSB 1u
#define PVTC_SDA_IP_CTRL_IP_RSTN_WIDTH 1u
#define PVTC_SDA_IP_CTRL_IP_RSTN_READ_ACCESS 1u
#define PVTC_SDA_IP_CTRL_IP_RSTN_WRITE_ACCESS 1u
#define PVTC_SDA_IP_CTRL_IP_RSTN_RESET 0x0u
#define PVTC_SDA_IP_CTRL_IP_RSTN_FIELD_MASK 0x00000002ul
#define PVTC_SDA_IP_CTRL_IP_RSTN_GET(x) (((x) & 0x00000002ul) >> 1)
#define PVTC_SDA_IP_CTRL_IP_RSTN_SET(x) (((x) << 1) & 0x00000002ul)
#define PVTC_SDA_IP_CTRL_IP_RSTN_MODIFY(r, x) \
   ((((x) << 1) & 0x00000002ul) | ((r) & 0xfffffffdul))
/* Field member: pvtc_sda::ip_ctrl.ip_pd                                   */
#define PVTC_SDA_IP_CTRL_IP_PD_MSB 0u
#define PVTC_SDA_IP_CTRL_IP_PD_LSB 0u
#define PVTC_SDA_IP_CTRL_IP_PD_WIDTH 1u
#define PVTC_SDA_IP_CTRL_IP_PD_READ_ACCESS 1u
#define PVTC_SDA_IP_CTRL_IP_PD_WRITE_ACCESS 1u
#define PVTC_SDA_IP_CTRL_IP_PD_RESET 0x1u
#define PVTC_SDA_IP_CTRL_IP_PD_FIELD_MASK 0x00000001ul
#define PVTC_SDA_IP_CTRL_IP_PD_GET(x) ((x) & 0x00000001ul)
#define PVTC_SDA_IP_CTRL_IP_PD_SET(x) ((x) & 0x00000001ul)
#define PVTC_SDA_IP_CTRL_IP_PD_MODIFY(r, x) \
   (((x) & 0x00000001ul) | ((r) & 0xfffffffeul))

/* Register type: pvtc_sda::ip_cfg                                         */
/* Register template: pvtc_sda::ip_cfg                                     */
/* Field member: pvtc_sda::ip_cfg.ip_cfg                                   */
#define PVTC_SDA_IP_CFG_IP_CFG_MSB 7u
#define PVTC_SDA_IP_CFG_IP_CFG_LSB 0u
#define PVTC_SDA_IP_CFG_IP_CFG_WIDTH 8u
#define PVTC_SDA_IP_CFG_IP_CFG_READ_ACCESS 1u
#define PVTC_SDA_IP_CFG_IP_CFG_WRITE_ACCESS 1u
#define PVTC_SDA_IP_CFG_IP_CFG_RESET 0x00u
#define PVTC_SDA_IP_CFG_IP_CFG_ARRAY_INDEX_MIN 0x0ull
#define PVTC_SDA_IP_CFG_IP_CFG_ARRAY_INDEX_MAX 0x2ull
#define PVTC_SDA_IP_CFG_IP_CFG_FIELD_MASK 0x000000fful
#define PVTC_SDA_IP_CFG_IP_CFG_GET(x) ((x) & 0x000000fful)
#define PVTC_SDA_IP_CFG_IP_CFG_SET(x) ((x) & 0x000000fful)
#define PVTC_SDA_IP_CFG_IP_CFG_MODIFY(r, x) \
   (((x) & 0x000000fful) | ((r) & 0xffffff00ul))

/* Register type: pvtc_sda::ip_cfga                                        */
/* Register template: pvtc_sda::ip_cfga                                    */
/* Field member: pvtc_sda::ip_cfga.ip_cfga_en                              */
#define PVTC_SDA_IP_CFGA_IP_CFGA_EN_MSB 8u
#define PVTC_SDA_IP_CFGA_IP_CFGA_EN_LSB 8u
#define PVTC_SDA_IP_CFGA_IP_CFGA_EN_WIDTH 1u
#define PVTC_SDA_IP_CFGA_IP_CFGA_EN_READ_ACCESS 1u
#define PVTC_SDA_IP_CFGA_IP_CFGA_EN_WRITE_ACCESS 1u
#define PVTC_SDA_IP_CFGA_IP_CFGA_EN_RESET 0x0u
#define PVTC_SDA_IP_CFGA_IP_CFGA_EN_FIELD_MASK 0x00000100ul
#define PVTC_SDA_IP_CFGA_IP_CFGA_EN_GET(x) (((x) & 0x00000100ul) >> 8)
#define PVTC_SDA_IP_CFGA_IP_CFGA_EN_SET(x) (((x) << 8) & 0x00000100ul)
#define PVTC_SDA_IP_CFGA_IP_CFGA_EN_MODIFY(r, x) \
   ((((x) << 8) & 0x00000100ul) | ((r) & 0xfffffefful))
/* Field member: pvtc_sda::ip_cfga.ip_cfga                                 */
#define PVTC_SDA_IP_CFGA_IP_CFGA_MSB 7u
#define PVTC_SDA_IP_CFGA_IP_CFGA_LSB 0u
#define PVTC_SDA_IP_CFGA_IP_CFGA_WIDTH 8u
#define PVTC_SDA_IP_CFGA_IP_CFGA_READ_ACCESS 1u
#define PVTC_SDA_IP_CFGA_IP_CFGA_WRITE_ACCESS 1u
#define PVTC_SDA_IP_CFGA_IP_CFGA_RESET 0x00u
#define PVTC_SDA_IP_CFGA_IP_CFGA_FIELD_MASK 0x000000fful
#define PVTC_SDA_IP_CFGA_IP_CFGA_GET(x) ((x) & 0x000000fful)
#define PVTC_SDA_IP_CFGA_IP_CFGA_SET(x) ((x) & 0x000000fful)
#define PVTC_SDA_IP_CFGA_IP_CFGA_MODIFY(r, x) \
   (((x) & 0x000000fful) | ((r) & 0xffffff00ul))

/* Register type: pvtc_sda::ip_data                                        */
/* Register template: pvtc_sda::ip_data                                    */
/* Field member: pvtc_sda::ip_data.ip_ch                                   */
#define PVTC_SDA_IP_DATA_IP_CH_MSB 23u
#define PVTC_SDA_IP_DATA_IP_CH_LSB 20u
#define PVTC_SDA_IP_DATA_IP_CH_WIDTH 4u
#define PVTC_SDA_IP_DATA_IP_CH_READ_ACCESS 1u
#define PVTC_SDA_IP_DATA_IP_CH_WRITE_ACCESS 0u
#define PVTC_SDA_IP_DATA_IP_CH_RESET 0x0u
#define PVTC_SDA_IP_DATA_IP_CH_FIELD_MASK 0x00f00000ul
#define PVTC_SDA_IP_DATA_IP_CH_GET(x) (((x) & 0x00f00000ul) >> 20)
#define PVTC_SDA_IP_DATA_IP_CH_SET(x) (((x) << 20) & 0x00f00000ul)
#define PVTC_SDA_IP_DATA_IP_CH_MODIFY(r, x) \
   ((((x) << 20) & 0x00f00000ul) | ((r) & 0xff0ffffful))
/* Field member: pvtc_sda::ip_data.ip_done                                 */
#define PVTC_SDA_IP_DATA_IP_DONE_MSB 18u
#define PVTC_SDA_IP_DATA_IP_DONE_LSB 18u
#define PVTC_SDA_IP_DATA_IP_DONE_WIDTH 1u
#define PVTC_SDA_IP_DATA_IP_DONE_READ_ACCESS 1u
#define PVTC_SDA_IP_DATA_IP_DONE_WRITE_ACCESS 0u
#define PVTC_SDA_IP_DATA_IP_DONE_RESET 0x0u
#define PVTC_SDA_IP_DATA_IP_DONE_FIELD_MASK 0x00040000ul
#define PVTC_SDA_IP_DATA_IP_DONE_GET(x) (((x) & 0x00040000ul) >> 18)
#define PVTC_SDA_IP_DATA_IP_DONE_SET(x) (((x) << 18) & 0x00040000ul)
#define PVTC_SDA_IP_DATA_IP_DONE_MODIFY(r, x) \
   ((((x) << 18) & 0x00040000ul) | ((r) & 0xfffbfffful))
/* Field member: pvtc_sda::ip_data.ip_fault                                */
#define PVTC_SDA_IP_DATA_IP_FAULT_MSB 17u
#define PVTC_SDA_IP_DATA_IP_FAULT_LSB 17u
#define PVTC_SDA_IP_DATA_IP_FAULT_WIDTH 1u
#define PVTC_SDA_IP_DATA_IP_FAULT_READ_ACCESS 1u
#define PVTC_SDA_IP_DATA_IP_FAULT_WRITE_ACCESS 0u
#define PVTC_SDA_IP_DATA_IP_FAULT_RESET 0x0u
#define PVTC_SDA_IP_DATA_IP_FAULT_FIELD_MASK 0x00020000ul
#define PVTC_SDA_IP_DATA_IP_FAULT_GET(x) (((x) & 0x00020000ul) >> 17)
#define PVTC_SDA_IP_DATA_IP_FAULT_SET(x) (((x) << 17) & 0x00020000ul)
#define PVTC_SDA_IP_DATA_IP_FAULT_MODIFY(r, x) \
   ((((x) << 17) & 0x00020000ul) | ((r) & 0xfffdfffful))
/* Field member: pvtc_sda::ip_data.ip_type                                 */
#define PVTC_SDA_IP_DATA_IP_TYPE_MSB 16u
#define PVTC_SDA_IP_DATA_IP_TYPE_LSB 16u
#define PVTC_SDA_IP_DATA_IP_TYPE_WIDTH 1u
#define PVTC_SDA_IP_DATA_IP_TYPE_READ_ACCESS 1u
#define PVTC_SDA_IP_DATA_IP_TYPE_WRITE_ACCESS 0u
#define PVTC_SDA_IP_DATA_IP_TYPE_RESET 0x0u
#define PVTC_SDA_IP_DATA_IP_TYPE_FIELD_MASK 0x00010000ul
#define PVTC_SDA_IP_DATA_IP_TYPE_GET(x) (((x) & 0x00010000ul) >> 16)
#define PVTC_SDA_IP_DATA_IP_TYPE_SET(x) (((x) << 16) & 0x00010000ul)
#define PVTC_SDA_IP_DATA_IP_TYPE_MODIFY(r, x) \
   ((((x) << 16) & 0x00010000ul) | ((r) & 0xfffefffful))
/* Field member: pvtc_sda::ip_data.ip_dat                                  */
#define PVTC_SDA_IP_DATA_IP_DAT_MSB 15u
#define PVTC_SDA_IP_DATA_IP_DAT_LSB 0u
#define PVTC_SDA_IP_DATA_IP_DAT_WIDTH 16u
#define PVTC_SDA_IP_DATA_IP_DAT_READ_ACCESS 1u
#define PVTC_SDA_IP_DATA_IP_DAT_WRITE_ACCESS 0u
#define PVTC_SDA_IP_DATA_IP_DAT_RESET 0x0000u
#define PVTC_SDA_IP_DATA_IP_DAT_FIELD_MASK 0x0000fffful
#define PVTC_SDA_IP_DATA_IP_DAT_GET(x) ((x) & 0x0000fffful)
#define PVTC_SDA_IP_DATA_IP_DAT_SET(x) ((x) & 0x0000fffful)
#define PVTC_SDA_IP_DATA_IP_DAT_MODIFY(r, x) \
   (((x) & 0x0000fffful) | ((r) & 0xffff0000ul))

/* Register type: pvtc_sda::ip_pol                                         */
/* Register template: pvtc_sda::ip_pol                                     */
/* Field member: pvtc_sda::ip_pol.vm_ch_req                                */
#define PVTC_SDA_IP_POL_VM_CH_REQ_MSB 21u
#define PVTC_SDA_IP_POL_VM_CH_REQ_LSB 21u
#define PVTC_SDA_IP_POL_VM_CH_REQ_WIDTH 1u
#define PVTC_SDA_IP_POL_VM_CH_REQ_READ_ACCESS 0u
#define PVTC_SDA_IP_POL_VM_CH_REQ_WRITE_ACCESS 1u
#define PVTC_SDA_IP_POL_VM_CH_REQ_RESET 0x0u
#define PVTC_SDA_IP_POL_VM_CH_REQ_FIELD_MASK 0x00200000ul
#define PVTC_SDA_IP_POL_VM_CH_REQ_GET(x) (((x) & 0x00200000ul) >> 21)
#define PVTC_SDA_IP_POL_VM_CH_REQ_SET(x) (((x) << 21) & 0x00200000ul)
#define PVTC_SDA_IP_POL_VM_CH_REQ_MODIFY(r, x) \
   ((((x) << 21) & 0x00200000ul) | ((r) & 0xffdffffful))
/* Field member: pvtc_sda::ip_pol.vm_ch_init                               */
#define PVTC_SDA_IP_POL_VM_CH_INIT_MSB 20u
#define PVTC_SDA_IP_POL_VM_CH_INIT_LSB 20u
#define PVTC_SDA_IP_POL_VM_CH_INIT_WIDTH 1u
#define PVTC_SDA_IP_POL_VM_CH_INIT_READ_ACCESS 0u
#define PVTC_SDA_IP_POL_VM_CH_INIT_WRITE_ACCESS 1u
#define PVTC_SDA_IP_POL_VM_CH_INIT_RESET 0x0u
#define PVTC_SDA_IP_POL_VM_CH_INIT_FIELD_MASK 0x00100000ul
#define PVTC_SDA_IP_POL_VM_CH_INIT_GET(x) (((x) & 0x00100000ul) >> 20)
#define PVTC_SDA_IP_POL_VM_CH_INIT_SET(x) (((x) << 20) & 0x00100000ul)
#define PVTC_SDA_IP_POL_VM_CH_INIT_MODIFY(r, x) \
   ((((x) << 20) & 0x00100000ul) | ((r) & 0xffeffffful))
/* Field member: pvtc_sda::ip_pol.vm_ch_sel                                */
#define PVTC_SDA_IP_POL_VM_CH_SEL_MSB 19u
#define PVTC_SDA_IP_POL_VM_CH_SEL_LSB 16u
#define PVTC_SDA_IP_POL_VM_CH_SEL_WIDTH 4u
#define PVTC_SDA_IP_POL_VM_CH_SEL_READ_ACCESS 1u
#define PVTC_SDA_IP_POL_VM_CH_SEL_WRITE_ACCESS 1u
#define PVTC_SDA_IP_POL_VM_CH_SEL_RESET 0x0u
#define PVTC_SDA_IP_POL_VM_CH_SEL_FIELD_MASK 0x000f0000ul
#define PVTC_SDA_IP_POL_VM_CH_SEL_GET(x) (((x) & 0x000f0000ul) >> 16)
#define PVTC_SDA_IP_POL_VM_CH_SEL_SET(x) (((x) << 16) & 0x000f0000ul)
#define PVTC_SDA_IP_POL_VM_CH_SEL_MODIFY(r, x) \
   ((((x) << 16) & 0x000f0000ul) | ((r) & 0xfff0fffful))
/* Field member: pvtc_sda::ip_pol.vm_ch_ena                                */
#define PVTC_SDA_IP_POL_VM_CH_ENA_MSB 15u
#define PVTC_SDA_IP_POL_VM_CH_ENA_LSB 10u
#define PVTC_SDA_IP_POL_VM_CH_ENA_WIDTH 6u
#define PVTC_SDA_IP_POL_VM_CH_ENA_READ_ACCESS 1u
#define PVTC_SDA_IP_POL_VM_CH_ENA_WRITE_ACCESS 1u
#define PVTC_SDA_IP_POL_VM_CH_ENA_RESET 0x00u
#define PVTC_SDA_IP_POL_VM_CH_ENA_FIELD_MASK 0x0000fc00ul
#define PVTC_SDA_IP_POL_VM_CH_ENA_GET(x) (((x) & 0x0000fc00ul) >> 10)
#define PVTC_SDA_IP_POL_VM_CH_ENA_SET(x) (((x) << 10) & 0x0000fc00ul)
#define PVTC_SDA_IP_POL_VM_CH_ENA_MODIFY(r, x) \
   ((((x) << 10) & 0x0000fc00ul) | ((r) & 0xffff03fful))

/* Register type: pvtc_sda::ip_tmr                                         */
/* Register template: pvtc_sda::ip_tmr                                     */
/* Field member: pvtc_sda::ip_tmr.ip_pu_dly                                */
#define PVTC_SDA_IP_TMR_IP_PU_DLY_MSB 15u
#define PVTC_SDA_IP_TMR_IP_PU_DLY_LSB 0u
#define PVTC_SDA_IP_TMR_IP_PU_DLY_WIDTH 16u
#define PVTC_SDA_IP_TMR_IP_PU_DLY_READ_ACCESS 1u
#define PVTC_SDA_IP_TMR_IP_PU_DLY_WRITE_ACCESS 1u
#define PVTC_SDA_IP_TMR_IP_PU_DLY_RESET 0x0000u
#define PVTC_SDA_IP_TMR_IP_PU_DLY_FIELD_MASK 0x0000fffful
#define PVTC_SDA_IP_TMR_IP_PU_DLY_GET(x) ((x) & 0x0000fffful)
#define PVTC_SDA_IP_TMR_IP_PU_DLY_SET(x) ((x) & 0x0000fffful)
#define PVTC_SDA_IP_TMR_IP_PU_DLY_MODIFY(r, x) \
   (((x) & 0x0000fffful) | ((r) & 0xffff0000ul))

/* ####################################################################### */
/*        TYPE DEFINITIONS                                                 */
/* ####################################################################### */

/* Typedef for Addressmap: pvtc_sda                                        */
typedef struct {
   volatile uint32_t ip_ctrl; /**< Offset 0x0 (R/W) */
   volatile uint32_t ip_cfg; /**< Offset 0x4 (R/W) */
   volatile uint32_t ip_cfga; /**< Offset 0x8 (R/W) */
   volatile uint32_t ip_data; /**< Offset 0xc (R) */
   volatile uint32_t ip_pol; /**< Offset 0x10 (R/W) */
   volatile uint32_t ip_tmr; /**< Offset 0x14 (R/W) */
} Pvtc_sda, *PTR_Pvtc_sda;

#endif
