/* Copyright (c) 2025 Ainekko, Co. */
/* SPDX-License-Identifier: Apache-2.0 */
/*                                                                         */
/*                                                                         */
/* Generated by Semifore, Inc. csrCompile                                  */
/*    C Header output                                                      */

#ifndef _SHIRE_BCCTRL_H_
#define _SHIRE_BCCTRL_H_



/* ####################################################################### */
/*        ADDRESS MACROS                                                   */
/* ####################################################################### */

/* Address Space for Addressmap: shire_bcctrl                              */
/* Register: shire_bcctrl.UC_Broadcast_Ctrl                                */
#define SHIRE_BCCTRL_UC_BROADCAST_CTRL_ADDRESS 0x0u
#define SHIRE_BCCTRL_UC_BROADCAST_CTRL_BYTE_ADDRESS 0x0u


/* ####################################################################### */
/*        TEMPLATE MACROS                                                  */
/* ####################################################################### */

/* Addressmap type: shire_bcctrl                                           */
/* Addressmap template: shire_bcctrl                                       */
#define SHIRE_BCCTRL_SIZE 0x8u
#define SHIRE_BCCTRL_BYTE_SIZE 0x8u
/* Register member: shire_bcctrl.UC_Broadcast_Ctrl                         */
/* Register type referenced: shire_bcctrl::UC_Broadcast_Ctrl               */
/* Register template referenced: shire_bcctrl::UC_Broadcast_Ctrl           */
#define SHIRE_BCCTRL_UC_BROADCAST_CTRL_OFFSET 0x0u
#define SHIRE_BCCTRL_UC_BROADCAST_CTRL_BYTE_OFFSET 0x0u
#define SHIRE_BCCTRL_UC_BROADCAST_CTRL_READ_ACCESS 1u
#define SHIRE_BCCTRL_UC_BROADCAST_CTRL_WRITE_ACCESS 1u
#define SHIRE_BCCTRL_UC_BROADCAST_CTRL_RESET_VALUE 0x0000000000000000ull
#define SHIRE_BCCTRL_UC_BROADCAST_CTRL_RESET_MASK 0xffffffffffffffffull
#define SHIRE_BCCTRL_UC_BROADCAST_CTRL_READ_MASK 0xffffffffffffffffull
#define SHIRE_BCCTRL_UC_BROADCAST_CTRL_WRITE_MASK 0x07ffffffffffffffull

/* Register type: shire_bcctrl::UC_Broadcast_Ctrl                          */
/* Register template: shire_bcctrl::UC_Broadcast_Ctrl                      */
/* Field member: shire_bcctrl::UC_Broadcast_Ctrl.UCBroadcast_Ctrl          */
#define SHIRE_BCCTRL_UC_BROADCAST_CTRL_UCBROADCAST_CTRL_MSB 58u
#define SHIRE_BCCTRL_UC_BROADCAST_CTRL_UCBROADCAST_CTRL_LSB 0u
#define SHIRE_BCCTRL_UC_BROADCAST_CTRL_UCBROADCAST_CTRL_WIDTH 59u
#define SHIRE_BCCTRL_UC_BROADCAST_CTRL_UCBROADCAST_CTRL_READ_ACCESS 1u
#define SHIRE_BCCTRL_UC_BROADCAST_CTRL_UCBROADCAST_CTRL_WRITE_ACCESS 1u
#define SHIRE_BCCTRL_UC_BROADCAST_CTRL_UCBROADCAST_CTRL_RESET 0x000000000000000ull
#define SHIRE_BCCTRL_UC_BROADCAST_CTRL_UCBROADCAST_CTRL_FIELD_MASK 0x07ffffffffffffffull
#define SHIRE_BCCTRL_UC_BROADCAST_CTRL_UCBROADCAST_CTRL_GET(x) \
   ((x) & 0x07ffffffffffffffull)
#define SHIRE_BCCTRL_UC_BROADCAST_CTRL_UCBROADCAST_CTRL_SET(x) \
   ((x) & 0x07ffffffffffffffull)
#define SHIRE_BCCTRL_UC_BROADCAST_CTRL_UCBROADCAST_CTRL_MODIFY(r, x) \
   (((x) & 0x07ffffffffffffffull) | ((r) & 0xf800000000000000ull))

/* ####################################################################### */
/*        TYPE DEFINITIONS                                                 */
/* ####################################################################### */

/* Typedef for Addressmap: shire_bcctrl                                    */
typedef struct {
   volatile uint64_t UC_Broadcast_Ctrl; /**< Offset 0x0 (R/W) */
} Shire_bcctrl, *PTR_Shire_bcctrl;

#endif
