/* Copyright (C) 2021, Esperanto Technologies Inc.                         */
/* The copyright to the computer program(s) herein is the                  */
/* property of Esperanto Technologies, Inc. All Rights Reserved.           */
/* The program(s) may be used and/or copied only with                      */
/* the written permission of Esperanto Technologies and                    */
/* in accordance with the terms and conditions stipulated in the           */
/* agreement/contract under which the program(s) have been supplied.       */
/*                                                                         */
/*                                                                         */
/* Generated by Semifore, Inc. csrCompile                                  */
/*    C Header output                                                      */

#ifndef _SHIRE_BCDATA_H_
#define _SHIRE_BCDATA_H_



/* ####################################################################### */
/*        ADDRESS MACROS                                                   */
/* ####################################################################### */

/* Address Space for Addressmap: shire_bcdata                              */
/* Register: shire_bcdata.UC_Broadcast_Data                                */
#define SHIRE_BCDATA_UC_BROADCAST_DATA_ADDRESS 0x0u
#define SHIRE_BCDATA_UC_BROADCAST_DATA_BYTE_ADDRESS 0x0u


/* ####################################################################### */
/*        TEMPLATE MACROS                                                  */
/* ####################################################################### */

/* Addressmap type: shire_bcdata                                           */
/* Addressmap template: shire_bcdata                                       */
#define SHIRE_BCDATA_SIZE 0x8u
#define SHIRE_BCDATA_BYTE_SIZE 0x8u
/* Register member: shire_bcdata.UC_Broadcast_Data                         */
/* Register type referenced: shire_bcdata::UC_Broadcast_Data               */
/* Register template referenced: shire_bcdata::UC_Broadcast_Data           */
#define SHIRE_BCDATA_UC_BROADCAST_DATA_OFFSET 0x0u
#define SHIRE_BCDATA_UC_BROADCAST_DATA_BYTE_OFFSET 0x0u
#define SHIRE_BCDATA_UC_BROADCAST_DATA_READ_ACCESS 1u
#define SHIRE_BCDATA_UC_BROADCAST_DATA_WRITE_ACCESS 1u
#define SHIRE_BCDATA_UC_BROADCAST_DATA_RESET_VALUE 0x0000000000000000ull
#define SHIRE_BCDATA_UC_BROADCAST_DATA_RESET_MASK 0xffffffffffffffffull
#define SHIRE_BCDATA_UC_BROADCAST_DATA_READ_MASK 0xffffffffffffffffull
#define SHIRE_BCDATA_UC_BROADCAST_DATA_WRITE_MASK 0xffffffffffffffffull

/* Register type: shire_bcdata::UC_Broadcast_Data                          */
/* Register template: shire_bcdata::UC_Broadcast_Data                      */
/* Field member: shire_bcdata::UC_Broadcast_Data.UCBroadcast_Data          */
#define SHIRE_BCDATA_UC_BROADCAST_DATA_UCBROADCAST_DATA_MSB 63u
#define SHIRE_BCDATA_UC_BROADCAST_DATA_UCBROADCAST_DATA_LSB 0u
#define SHIRE_BCDATA_UC_BROADCAST_DATA_UCBROADCAST_DATA_WIDTH 64u
#define SHIRE_BCDATA_UC_BROADCAST_DATA_UCBROADCAST_DATA_READ_ACCESS 1u
#define SHIRE_BCDATA_UC_BROADCAST_DATA_UCBROADCAST_DATA_WRITE_ACCESS 1u
#define SHIRE_BCDATA_UC_BROADCAST_DATA_UCBROADCAST_DATA_RESET 0x0000000000000000ull
#define SHIRE_BCDATA_UC_BROADCAST_DATA_UCBROADCAST_DATA_FIELD_MASK 0xffffffffffffffffull
#define SHIRE_BCDATA_UC_BROADCAST_DATA_UCBROADCAST_DATA_GET(x) \
   ((x) & 0xffffffffffffffffull)
#define SHIRE_BCDATA_UC_BROADCAST_DATA_UCBROADCAST_DATA_SET(x) \
   ((x) & 0xffffffffffffffffull)
#define SHIRE_BCDATA_UC_BROADCAST_DATA_UCBROADCAST_DATA_MODIFY(r, x) \
   ((x) & 0xffffffffffffffffull)

/* ####################################################################### */
/*        TYPE DEFINITIONS                                                 */
/* ####################################################################### */

/* Typedef for Addressmap: shire_bcdata                                    */
typedef struct {
   volatile uint64_t UC_Broadcast_Data; /**< Offset 0x0 (R/W) */
} Shire_bcdata, *PTR_Shire_bcdata;

#endif
