/* Copyright (c) 2025 Ainekko, Co. */
/* SPDX-License-Identifier: Apache-2.0 */
/*                                                                         */
/*                                                                         */
/* Generated by Semifore, Inc. csrCompile                                  */
/*    C Header output                                                      */

#ifndef _SP_RVTIM_H_
#define _SP_RVTIM_H_



/* ####################################################################### */
/*        ADDRESS MACROS                                                   */
/* ####################################################################### */

/* Address Space for Addressmap: rvtimer                                   */
/* Register: rvtimer.mtime                                                 */
#define RVTIMER_MTIME_ADDRESS 0x0u
#define RVTIMER_MTIME_BYTE_ADDRESS 0x0u
/* Register: rvtimer.mtimecmp                                              */
#define RVTIMER_MTIMECMP_ADDRESS 0x8u
#define RVTIMER_MTIMECMP_BYTE_ADDRESS 0x8u


/* ####################################################################### */
/*        TEMPLATE MACROS                                                  */
/* ####################################################################### */

/* Addressmap type: rvtimer                                                */
/* Addressmap template: rvtimer                                            */
#define RVTIMER_SIZE 0x10u
#define RVTIMER_BYTE_SIZE 0x10u
/* Register member: rvtimer.mtime                                          */
/* Register type referenced: rvtimer::mtime                                */
/* Register template referenced: rvtimer::mtime                            */
#define RVTIMER_MTIME_OFFSET 0x0u
#define RVTIMER_MTIME_BYTE_OFFSET 0x0u
#define RVTIMER_MTIME_READ_ACCESS 1u
#define RVTIMER_MTIME_WRITE_ACCESS 1u
#define RVTIMER_MTIME_RESET_VALUE 0x0000000000000000ull
#define RVTIMER_MTIME_RESET_MASK 0xffffffffffffffffull
#define RVTIMER_MTIME_READ_MASK 0xffffffffffffffffull
#define RVTIMER_MTIME_WRITE_MASK 0xffffffffffffffffull
/* Register member: rvtimer.mtimecmp                                       */
/* Register type referenced: rvtimer::mtimecmp                             */
/* Register template referenced: rvtimer::mtimecmp                         */
#define RVTIMER_MTIMECMP_OFFSET 0x8u
#define RVTIMER_MTIMECMP_BYTE_OFFSET 0x8u
#define RVTIMER_MTIMECMP_READ_ACCESS 1u
#define RVTIMER_MTIMECMP_WRITE_ACCESS 1u
#define RVTIMER_MTIMECMP_RESET_VALUE 0xfffffffffffffffeull
#define RVTIMER_MTIMECMP_RESET_MASK 0xffffffffffffffffull
#define RVTIMER_MTIMECMP_READ_MASK 0xffffffffffffffffull
#define RVTIMER_MTIMECMP_WRITE_MASK 0xffffffffffffffffull

/* Register type: rvtimer::mtime                                           */
/* Register template: rvtimer::mtime                                       */
/* Field member: rvtimer::mtime.value                                      */
#define RVTIMER_MTIME_VALUE_MSB 63u
#define RVTIMER_MTIME_VALUE_LSB 0u
#define RVTIMER_MTIME_VALUE_WIDTH 64u
#define RVTIMER_MTIME_VALUE_READ_ACCESS 1u
#define RVTIMER_MTIME_VALUE_WRITE_ACCESS 1u
#define RVTIMER_MTIME_VALUE_RESET 0x0000000000000000ull
#define RVTIMER_MTIME_VALUE_FIELD_MASK 0xffffffffffffffffull
#define RVTIMER_MTIME_VALUE_GET(x) ((x) & 0xffffffffffffffffull)
#define RVTIMER_MTIME_VALUE_SET(x) ((x) & 0xffffffffffffffffull)
#define RVTIMER_MTIME_VALUE_MODIFY(r, x) ((x) & 0xffffffffffffffffull)

/* Register type: rvtimer::mtimecmp                                        */
/* Register template: rvtimer::mtimecmp                                    */
/* Field member: rvtimer::mtimecmp.value                                   */
#define RVTIMER_MTIMECMP_VALUE_MSB 63u
#define RVTIMER_MTIMECMP_VALUE_LSB 0u
#define RVTIMER_MTIMECMP_VALUE_WIDTH 64u
#define RVTIMER_MTIMECMP_VALUE_READ_ACCESS 1u
#define RVTIMER_MTIMECMP_VALUE_WRITE_ACCESS 1u
#define RVTIMER_MTIMECMP_VALUE_RESET 0xfffffffffffffffeull
#define RVTIMER_MTIMECMP_VALUE_FIELD_MASK 0xffffffffffffffffull
#define RVTIMER_MTIMECMP_VALUE_GET(x) ((x) & 0xffffffffffffffffull)
#define RVTIMER_MTIMECMP_VALUE_SET(x) ((x) & 0xffffffffffffffffull)
#define RVTIMER_MTIMECMP_VALUE_MODIFY(r, x) ((x) & 0xffffffffffffffffull)

/* ####################################################################### */
/*        TYPE DEFINITIONS                                                 */
/* ####################################################################### */

/* Typedef for Addressmap: rvtimer                                         */
typedef struct {
   volatile uint64_t mtime; /**< Offset 0x0 (R/W) */
   volatile uint64_t mtimecmp; /**< Offset 0x8 (R/W) */
} Rvtimer, *PTR_Rvtimer;

#endif
