/* Copyright (C) 2021, Esperanto Technologies Inc.                         */
/* The copyright to the computer program(s) herein is the                  */
/* property of Esperanto Technologies, Inc. All Rights Reserved.           */
/* The program(s) may be used and/or copied only with                      */
/* the written permission of Esperanto Technologies and                    */
/* in accordance with the terms and conditions stipulated in the           */
/* agreement/contract under which the program(s) have been supplied.       */
/*                                                                         */
/*                                                                         */
/* Generated by Semifore, Inc. csrCompile                                  */
/*    C Header output                                                      */

#ifndef _SP_ROM_H_
#define _SP_ROM_H_



/* ####################################################################### */
/*        ADDRESS MACROS                                                   */
/* ####################################################################### */

/* Address Space for Addressmap: sp_rom                                    */
/* Memory: sp_rom.sp_128kB_rom                                             */
#define SP_ROM_SP_128KB_ROM_ADDRESS 0x0ul
#define SP_ROM_SP_128KB_ROM_BYTE_ADDRESS 0x0ul


/* ####################################################################### */
/*        TEMPLATE MACROS                                                  */
/* ####################################################################### */

/* Addressmap type: sp_rom                                                 */
/* Addressmap template: sp_rom                                             */
#define SP_ROM_SIZE 0x20000ul
#define SP_ROM_BYTE_SIZE 0x20000ul
/* Memory member: sp_rom.sp_128kB_rom                                      */
/* Memory type referenced: sp_rom::sp_128kB_rom                            */
/* Memory template referenced: sp_rom::sp_128kB_rom                        */
#define SP_ROM_SP_128KB_ROM_OFFSET 0x0ul
#define SP_ROM_SP_128KB_ROM_BYTE_OFFSET 0x0ul
#define SP_ROM_SP_128KB_ROM_READ_ACCESS 1u
#define SP_ROM_SP_128KB_ROM_WRITE_ACCESS 0u
#define SP_ROM_SP_128KB_ROM_READ_MASK 0xfffffffful
#define SP_ROM_SP_128KB_ROM_WRITE_MASK 0x00000000ul

/* Memory type: sp_rom::sp_128kB_rom                                       */
/* Memory template: sp_rom::sp_128kB_rom                                   */
#define SP_ROM_SP_128KB_ROM_SIZE 0x20000ul
#define SP_ROM_SP_128KB_ROM_BYTE_SIZE 0x20000ul
#define SP_ROM_SP_128KB_ROM_ENTRIES 0x8000ull
#define SP_ROM_SP_128KB_ROM_MSB 31u
#define SP_ROM_SP_128KB_ROM_LSB 0u
#define SP_ROM_SP_128KB_ROM_WIDTH 32u
#define SP_ROM_SP_128KB_ROM_MASK 0xfffffffful
#define SP_ROM_SP_128KB_ROM_GET(x) ((x) & 0xfffffffful)
#define SP_ROM_SP_128KB_ROM_SET(x) ((x) & 0xfffffffful)

/* ####################################################################### */
/*        TYPE DEFINITIONS                                                 */
/* ####################################################################### */

/* Typedef for Memory: sp_rom::sp_128kB_rom                                */
typedef struct {
   uint8_t _pad0[0x20000];
} Sp_rom_sp_128kB_rom, *PTR_Sp_rom_sp_128kB_rom;

/* Typedef for Addressmap: sp_rom                                          */
typedef struct {
   Sp_rom_sp_128kB_rom sp_128kB_rom; /**< Offset 0x0 (R) */
} Sp_rom, *PTR_Sp_rom;

#endif
