/* Copyright (C) 2021, Esperanto Technologies Inc.                         */
/* The copyright to the computer program(s) herein is the                  */
/* property of Esperanto Technologies, Inc. All Rights Reserved.           */
/* The program(s) may be used and/or copied only with                      */
/* the written permission of Esperanto Technologies and                    */
/* in accordance with the terms and conditions stipulated in the           */
/* agreement/contract under which the program(s) have been supplied.       */
/*                                                                         */
/*                                                                         */
/* Generated by Semifore, Inc. csrCompile                                  */
/*    C Header output                                                      */

#ifndef _SP_VAULT_H_
#define _SP_VAULT_H_



/* ####################################################################### */
/*        ADDRESS MACROS                                                   */
/* ####################################################################### */

/* Address Space for Addressmap: spio_128kram                              */
/* Register: spio_128kram.mailbox1_data                                    */
#define SPIO_128KRAM_MAILBOX1_DATA_ADDRESS 0x0u
#define SPIO_128KRAM_MAILBOX1_DATA_BYTE_ADDRESS 0x0u
#define SPIO_128KRAM_MAILBOX1_DATA_ARRAY_ELEMENT_SIZE 0x4ull
#define SPIO_128KRAM_MAILBOX1_DATA_ARRAY_COUNT 0x100ull
#define SPIO_128KRAM_MAILBOX1_DATA_ARRAY_INDEX_MAX 0xffull
#define SPIO_128KRAM_MAILBOX1_DATA_ARRAY_INDEX_MIN 0x0ull
/* Register: spio_128kram.mailbox2_data                                    */
#define SPIO_128KRAM_MAILBOX2_DATA_ADDRESS 0x400u
#define SPIO_128KRAM_MAILBOX2_DATA_BYTE_ADDRESS 0x400u
#define SPIO_128KRAM_MAILBOX2_DATA_ARRAY_ELEMENT_SIZE 0x4ull
#define SPIO_128KRAM_MAILBOX2_DATA_ARRAY_COUNT 0x100ull
#define SPIO_128KRAM_MAILBOX2_DATA_ARRAY_INDEX_MAX 0xffull
#define SPIO_128KRAM_MAILBOX2_DATA_ARRAY_INDEX_MIN 0x0ull
/* Register: spio_128kram.mailbox3_data                                    */
#define SPIO_128KRAM_MAILBOX3_DATA_ADDRESS 0x800u
#define SPIO_128KRAM_MAILBOX3_DATA_BYTE_ADDRESS 0x800u
#define SPIO_128KRAM_MAILBOX3_DATA_ARRAY_ELEMENT_SIZE 0x4ull
#define SPIO_128KRAM_MAILBOX3_DATA_ARRAY_COUNT 0x100ull
#define SPIO_128KRAM_MAILBOX3_DATA_ARRAY_INDEX_MAX 0xffull
#define SPIO_128KRAM_MAILBOX3_DATA_ARRAY_INDEX_MIN 0x0ull
/* Register: spio_128kram.mailbox4_data                                    */
#define SPIO_128KRAM_MAILBOX4_DATA_ADDRESS 0xc00u
#define SPIO_128KRAM_MAILBOX4_DATA_BYTE_ADDRESS 0xc00u
#define SPIO_128KRAM_MAILBOX4_DATA_ARRAY_ELEMENT_SIZE 0x4ull
#define SPIO_128KRAM_MAILBOX4_DATA_ARRAY_COUNT 0x100ull
#define SPIO_128KRAM_MAILBOX4_DATA_ARRAY_INDEX_MAX 0xffull
#define SPIO_128KRAM_MAILBOX4_DATA_ARRAY_INDEX_MIN 0x0ull


/* ####################################################################### */
/*        TEMPLATE MACROS                                                  */
/* ####################################################################### */

/* Addressmap type: spio_128kram                                           */
/* Addressmap template: spio_128kram                                       */
#define SPIO_128KRAM_SIZE 0x1000u
#define SPIO_128KRAM_BYTE_SIZE 0x1000u
/* Register member: spio_128kram.mailbox1_data                             */
/* Register type referenced: spio_128kram::mailbox1_data                   */
/* Register template referenced: spio_128kram::mailbox1_data               */
#define SPIO_128KRAM_MAILBOX1_DATA_OFFSET 0x0u
#define SPIO_128KRAM_MAILBOX1_DATA_BYTE_OFFSET 0x0u
#define SPIO_128KRAM_MAILBOX1_DATA_READ_ACCESS 1u
#define SPIO_128KRAM_MAILBOX1_DATA_WRITE_ACCESS 1u
#define SPIO_128KRAM_MAILBOX1_DATA_READ_MASK 0xfffffffful
#define SPIO_128KRAM_MAILBOX1_DATA_WRITE_MASK 0xfffffffful
/* Register member: spio_128kram.mailbox2_data                             */
/* Register type referenced: spio_128kram::mailbox2_data                   */
/* Register template referenced: spio_128kram::mailbox2_data               */
#define SPIO_128KRAM_MAILBOX2_DATA_OFFSET 0x400u
#define SPIO_128KRAM_MAILBOX2_DATA_BYTE_OFFSET 0x400u
#define SPIO_128KRAM_MAILBOX2_DATA_READ_ACCESS 1u
#define SPIO_128KRAM_MAILBOX2_DATA_WRITE_ACCESS 1u
#define SPIO_128KRAM_MAILBOX2_DATA_READ_MASK 0xfffffffful
#define SPIO_128KRAM_MAILBOX2_DATA_WRITE_MASK 0xfffffffful
/* Register member: spio_128kram.mailbox3_data                             */
/* Register type referenced: spio_128kram::mailbox3_data                   */
/* Register template referenced: spio_128kram::mailbox3_data               */
#define SPIO_128KRAM_MAILBOX3_DATA_OFFSET 0x800u
#define SPIO_128KRAM_MAILBOX3_DATA_BYTE_OFFSET 0x800u
#define SPIO_128KRAM_MAILBOX3_DATA_READ_ACCESS 1u
#define SPIO_128KRAM_MAILBOX3_DATA_WRITE_ACCESS 1u
#define SPIO_128KRAM_MAILBOX3_DATA_READ_MASK 0xfffffffful
#define SPIO_128KRAM_MAILBOX3_DATA_WRITE_MASK 0xfffffffful
/* Register member: spio_128kram.mailbox4_data                             */
/* Register type referenced: spio_128kram::mailbox4_data                   */
/* Register template referenced: spio_128kram::mailbox4_data               */
#define SPIO_128KRAM_MAILBOX4_DATA_OFFSET 0xc00u
#define SPIO_128KRAM_MAILBOX4_DATA_BYTE_OFFSET 0xc00u
#define SPIO_128KRAM_MAILBOX4_DATA_READ_ACCESS 1u
#define SPIO_128KRAM_MAILBOX4_DATA_WRITE_ACCESS 1u
#define SPIO_128KRAM_MAILBOX4_DATA_READ_MASK 0xfffffffful
#define SPIO_128KRAM_MAILBOX4_DATA_WRITE_MASK 0xfffffffful

/* Register type: spio_128kram::mailbox1_data                              */
/* Register template: spio_128kram::mailbox1_data                          */
/* Field member: spio_128kram::mailbox1_data.data                          */
#define SPIO_128KRAM_MAILBOX1_DATA_DATA_MSB 31u
#define SPIO_128KRAM_MAILBOX1_DATA_DATA_LSB 0u
#define SPIO_128KRAM_MAILBOX1_DATA_DATA_WIDTH 32u
#define SPIO_128KRAM_MAILBOX1_DATA_DATA_READ_ACCESS 1u
#define SPIO_128KRAM_MAILBOX1_DATA_DATA_WRITE_ACCESS 1u
#define SPIO_128KRAM_MAILBOX1_DATA_DATA_FIELD_MASK 0xfffffffful
#define SPIO_128KRAM_MAILBOX1_DATA_DATA_GET(x) ((x) & 0xfffffffful)
#define SPIO_128KRAM_MAILBOX1_DATA_DATA_SET(x) ((x) & 0xfffffffful)
#define SPIO_128KRAM_MAILBOX1_DATA_DATA_MODIFY(r, x) ((x) & 0xfffffffful)

/* Register type: spio_128kram::mailbox2_data                              */
/* Register template: spio_128kram::mailbox2_data                          */
/* Field member: spio_128kram::mailbox2_data.data                          */
#define SPIO_128KRAM_MAILBOX2_DATA_DATA_MSB 31u
#define SPIO_128KRAM_MAILBOX2_DATA_DATA_LSB 0u
#define SPIO_128KRAM_MAILBOX2_DATA_DATA_WIDTH 32u
#define SPIO_128KRAM_MAILBOX2_DATA_DATA_READ_ACCESS 1u
#define SPIO_128KRAM_MAILBOX2_DATA_DATA_WRITE_ACCESS 1u
#define SPIO_128KRAM_MAILBOX2_DATA_DATA_FIELD_MASK 0xfffffffful
#define SPIO_128KRAM_MAILBOX2_DATA_DATA_GET(x) ((x) & 0xfffffffful)
#define SPIO_128KRAM_MAILBOX2_DATA_DATA_SET(x) ((x) & 0xfffffffful)
#define SPIO_128KRAM_MAILBOX2_DATA_DATA_MODIFY(r, x) ((x) & 0xfffffffful)

/* Register type: spio_128kram::mailbox3_data                              */
/* Register template: spio_128kram::mailbox3_data                          */
/* Field member: spio_128kram::mailbox3_data.data                          */
#define SPIO_128KRAM_MAILBOX3_DATA_DATA_MSB 31u
#define SPIO_128KRAM_MAILBOX3_DATA_DATA_LSB 0u
#define SPIO_128KRAM_MAILBOX3_DATA_DATA_WIDTH 32u
#define SPIO_128KRAM_MAILBOX3_DATA_DATA_READ_ACCESS 1u
#define SPIO_128KRAM_MAILBOX3_DATA_DATA_WRITE_ACCESS 1u
#define SPIO_128KRAM_MAILBOX3_DATA_DATA_FIELD_MASK 0xfffffffful
#define SPIO_128KRAM_MAILBOX3_DATA_DATA_GET(x) ((x) & 0xfffffffful)
#define SPIO_128KRAM_MAILBOX3_DATA_DATA_SET(x) ((x) & 0xfffffffful)
#define SPIO_128KRAM_MAILBOX3_DATA_DATA_MODIFY(r, x) ((x) & 0xfffffffful)

/* Register type: spio_128kram::mailbox4_data                              */
/* Register template: spio_128kram::mailbox4_data                          */
/* Field member: spio_128kram::mailbox4_data.data                          */
#define SPIO_128KRAM_MAILBOX4_DATA_DATA_MSB 31u
#define SPIO_128KRAM_MAILBOX4_DATA_DATA_LSB 0u
#define SPIO_128KRAM_MAILBOX4_DATA_DATA_WIDTH 32u
#define SPIO_128KRAM_MAILBOX4_DATA_DATA_READ_ACCESS 1u
#define SPIO_128KRAM_MAILBOX4_DATA_DATA_WRITE_ACCESS 1u
#define SPIO_128KRAM_MAILBOX4_DATA_DATA_FIELD_MASK 0xfffffffful
#define SPIO_128KRAM_MAILBOX4_DATA_DATA_GET(x) ((x) & 0xfffffffful)
#define SPIO_128KRAM_MAILBOX4_DATA_DATA_SET(x) ((x) & 0xfffffffful)
#define SPIO_128KRAM_MAILBOX4_DATA_DATA_MODIFY(r, x) ((x) & 0xfffffffful)

/* ####################################################################### */
/*        TYPE DEFINITIONS                                                 */
/* ####################################################################### */

/* Typedef for Addressmap: spio_128kram                                    */
typedef struct {
   volatile uint32_t mailbox1_data[0x100]; /**< Offset 0x0 (R/W) */
   volatile uint32_t mailbox2_data[0x100]; /**< Offset 0x400 (R/W) */
   volatile uint32_t mailbox3_data[0x100]; /**< Offset 0x800 (R/W) */
   volatile uint32_t mailbox4_data[0x100]; /**< Offset 0xc00 (R/W) */
} Spio_128kram, *PTR_Spio_128kram;

#endif
