import:
  - path: '@ci@/ci-tools/templates/template-main-top-level.yaml'

parameters:
  SW_PLATFORM_BRANCH:
    description: SW-Platform branch to track
    type: string
    default_value: "origin/develop/system-sw"
  REPO_SSH_URL:
    description: Repository URL
    type: string
    default_value: "git@gitlab.esperanto.ai:software/device-bootloaders.git"
  REPO_NAME:
    description: Repository name
    type: string
    default_value: "device-bootloaders"
  RUN_ZEBU:
    description: Run Zebu Job
    type: bool
    default_value: true

stages:
  JOB_CODE_QUALITY:
    cmds:
      - job: sw-platform/code-analysis/device-bootloaders-sonarqube
        parameters:
          BRANCH: "${SW_PLATFORM_BRANCH}"
          GITLAB_SOURCE_BRANCH:
            raw_cmd: '"${env.gitlabSourceBranch}"'
          GITLAB_TARGET_BRANCH: 
            raw_cmd: '"${env.gitlabTargetBranch}"'
          GITLAB_MR_ID: 
            raw_cmd: '"${env.gitlabMergeRequestIid}"'
          COMPONENT_COMMITS: "${COMPONENT_COMMITS},device-software/device-bootloaders:${BRANCH}"

  JOB_RUNTIME:
    cmds:
      - job: sw-platform/runtime-integration/pipelines/runtime-checkin-tests
        parameters:
          BRANCH: "${SW_PLATFORM_BRANCH}"
          COMPONENT_COMMITS: "${COMPONENT_COMMITS},device-software/device-bootloaders:${BRANCH}"

  JOB_DEVICE_MANAGEMENT_ZEBU:
    cmds:
      - job: sw-platform/system-sw-integration/pipelines/device-management-zebu-tests
        parameters:
          BRANCH: "${SW_PLATFORM_BRANCH}"
          COMPONENT_COMMITS: "${COMPONENT_COMMITS},device-software/device-bootloaders:${BRANCH}"

  JOB_DEVICE_MANAGEMENT_SYSEMU:
    cmds:
      - job: sw-platform/system-sw-integration/pipelines/device-management-checkin-tests
        parameters:
          BRANCH: "${SW_PLATFORM_BRANCH}"
          COMPONENT_COMMITS: "${COMPONENT_COMMITS},device-software/device-bootloaders:${BRANCH}"
