import:
  - path: '@ci@/ci-tools/templates/template-main-top-level.yaml'

parameters:
  SW_PLATFORM_BRANCH:
    description: SW-Platform branch to track
    type: string
    default_value: "origin/develop/system-sw"
  REPO_SSH_URL:
    description: Repository URL
    type: string
    default_value: "git@gitlab.esperanto.ai:software/device-bootloaders.git"
  REPO_NAME:
    description: Repository name
    type: string
    default_value: "device-bootloaders"
  RUN_ZEBU:
    description: Run Zebu Job
    type: bool
    default_value: true
  FORCE_CHILD_RETRIGGER:
    description: 'Forces all child jobs of the current job to retrigger even if smart-retrigger is being used'
    type: bool
    default_value: true

stages:
  CHECKOUT_SCM:
    cmds:
      - raw_cmd: |-
          script {
            currentBuild.getRawBuild().getExecutor().interrupt(Result.UNSTABLE)
            sleep(1)   // Interrupt is not blocking and does not take effect immediately.
          }
    exec_before: [r".*"]
