#!/bin/bash

set -e

elf_filename=$1
hdr_filename=$2

echo "/* This is autogenerated file by gen_entry_points.sh script */" > $hdr_filename
echo "#ifndef _KERNELS_OFFSETS_H_" >> $hdr_filename
echo "#define _KERNELS_OFFSETS_H_" >> $hdr_filename

readelf -sW $elf_filename | grep --color=none "_ETKERNEL_entry_point$" | while read i; do
printf "static const long ETKERNEL_%s = 0x%s;\n" `echo $i | awk -F ' ' '{print $8}' | awk -F _ETKERNEL_entry_point '{print $1}'` `echo $i | awk -F ' ' '{print $2}'` >> $hdr_filename
done

readelf -sW $elf_filename | grep --color=none "_ETSOC_entry_point$" | while read i; do
printf "static const long ETSOC_%s = 0x%s;\n" `echo $i | awk -F ' ' '{print $8}' | awk -F _ETSOC_entry_point '{print $1}'` `echo $i | awk -F ' ' '{print $2}'` >> $hdr_filename
done

echo "#endif" >> $hdr_filename
