stages:
  - build
  - package

include:
  - project: 'software/conan/conan-ci-pipelines-common'
    file: 'conan-config.yaml'
  - project: 'software/conan/conan-ci-pipelines-common'
    file: 'build.yaml'
  - project: 'software/conan/conan-ci-pipelines-common'
    file: 'package.yaml'

#### build

build:system_pkg_manager:
  stage: build
  tags:
    - docker
  image: ubuntu:latest
  variables:
    DEBIAN_FRONTEND: noninteractive
  parallel:
    matrix:
      - COMPILER: [ gcc ]
        COMPILER_VERSION: [ 7 ]
        BUILD_TYPE: [ Release, Debug ]
        PROFILING: [ 1 ]
        BACKTRACE: [ 1 ]
  before_script:
    - apt-get update -qq
    - apt-get install -qq -y --no-install-recommends ninja-build build-essential gcc-${COMPILER_VERSION} g++-${COMPILER_VERSION} cmake libunwind-dev libgoogle-glog-dev
    - mkdir build
    - cd build
  script:
    - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DPROFILING=${PROFILING} -DBACKGRACE=${BACKTRACE} -G Ninja ..
    - ninja
  allow_failure: true

build:conan:
  stage: build
  variables:
    DOCKER_IMAGE: conanio/${COMPILER}
  parallel:
    matrix:
      - COMPILER: [ gcc7 ]
        BUILD_TYPE: [ Release, Debug ]
        PROFILING: [ 'False', 'True' ]
        BACKTRACE: [ 'False', 'True' ]
      - COMPILER: [ clang10 ]
        BUILD_TYPE: [ Release, Debug ]
        PROFILING: [ 'False' ]
        BACKTRACE: [ 'False' ]
  script:
    - conan install .. -s build_type=${BUILD_TYPE} -o sw-sysemu:profiling=${PROFILING} -o sw-sysemu:backtrace=${BACKTRACE} --build missing
    - cmake -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -G Ninja ..
    - ninja

#### package

package:
  stage: package
  variables:
    DOCKER_IMAGE: conanio/${COMPILER}${COMPILER_VERSION}
    CONAN_STABLE_BRANCH_PATTERN: "develop/sw-sysemu"
  parallel:
    matrix:
      - COMPILER: [ gcc ]
        COMPILER_VERSION: [ 7 ]
        CONAN_GCC_VERSIONS: [ 7 ]
      - COMPILER: [ clang ]
        COMPILER_VERSION: [ 10 ]
        CONAN_CLANG_VERSIONS: [ 10 ]
  script:
    - ./conan/ci/package.sh


