include:
  - project: 'software/gitlab-ci-common'
    ref: master
    file:
      - 'pods/nano-pod.yaml'
      - 'misc/retries.yaml'

stages:
  - generate_build
  - build
  - test
  - deploy

###############################################################################
###############################################################################
###############################################################################

generate_build:conan:
  extends:
    - .retries
    - .pod_nano
  stage: generate_build
  tags:
    - k8s
  image: docker-sw-team.sc-artifactory1.esperanto.ai/convoke/ubuntu-18.04-gcc7-conan:0.0.7
  script:
    - cd conan
    - python3 -m ci_build
    - mv build_pipeline.yml ..
  artifacts:
    expire_in: 1h 
    paths:
      - build_pipeline.yml

###############################################################################
###############################################################################
###############################################################################

build:conan:
  needs:
  - generate_build:conan
  stage: build
  trigger:
    include:
    - artifact: build_pipeline.yml
      job: generate_build:conan
    strategy: depend

###############################################################################
###############################################################################
###############################################################################

# hypotetical unit tests would go here

###############################################################################
###############################################################################
###############################################################################

# on_success:promote:
#   extends: .template_job_k8s_with_conan_ci_pipelines_common_on_success_perform_promote
#   stage: deploy
#   needs:
#     - build:conan
#   script:
#     - cd conan


