include:
  - project: 'software/gitlab-ci-common'
    ref: master
    file:
      - 'pods/nano-pod.yaml'
      - 'misc/retries.yaml'
      - 'jobs/conan-jobs.yaml'

stages:
  - generate_build
  - build
  - test
  - deploy

###############################################################################
###############################################################################
###############################################################################

generate_build:conan:
  extends:
    - .retries
    - .pod_nano
    - .template-conan-linux-ubuntu18.04-gcc7
  stage: generate_build
  tags:
    - k8s
  before_script:
    - cd conan
  script:
    - python3 -m ci_build
  artifacts:
    expire_in: 1h 
    paths:
      - conan/build_pipeline.yml
      - conan/lockfiles_info.json

###############################################################################
###############################################################################
###############################################################################

build:conan:
  needs:
  - generate_build:conan
  stage: build
  trigger:
    include:
    - artifact: conan/build_pipeline.yml
      job: generate_build:conan
    strategy: depend

###############################################################################
###############################################################################
###############################################################################

# hypotetical unit tests would go here

###############################################################################
###############################################################################
###############################################################################

on_success:promote:
  extends:
    - .retries
    - .pod_nano
    - .template-conan-linux-ubuntu18.04-gcc7
  stage: deploy
  needs:
    - generate_build:conan
    - build:conan
  tags:
    - k8s
  variables:
    PYTHONIOENCODING: utf-8
  before_script:
    - cd conan
  script:
    - python3 -m ci_promote


