emu_hdrs := \
	atomics.h \
	csrs.h \
	decode.h \
	emu.h \
	emu_casts.h \
	emu_defines.h \
	emu_gio.h \
	emu_memop.h \
	esrs.h \
	gold.h \
	insn.h \
	insn_func.h \
	lazy_array.h \
	literals.h \
	memmap.h \
	mmu.h \
	processor.h \
	rbox.h \
	rbox_pi.h \
	state.h \
	tbox_emu.h \
	tbox_pi.h \
	traps.h \
	txs.h \
	utility.h \
	memory/dense_region.h \
	memory/dump_data.h \
	memory/load.h \
	memory/main_memory.h \
	memory/memory_region.h \
	memory/scratch_region.h \
	memory/sparse_region.h \
	memory/sysreg_region.h

emu_cpp_srcs := \
	decode.cpp \
	emu.cpp \
	emu_gio.cpp \
	emu_memop.cpp \
	esrs.cpp \
	gold.cpp \
	insn_exec_func.cpp \
	mmu.cpp \
	rbox.cpp \
	tbox_emu.cpp \
	txs.cpp \
	insns/arith.cpp \
	insns/arith_atomic.cpp \
	insns/arith_graphics.cpp \
	insns/arith_loadstore.cpp \
	insns/branch.cpp \
	insns/c_arith.cpp \
	insns/c_branch.cpp \
	insns/c_loadstore.cpp \
	insns/coherent_arith_loadstore.cpp \
	insns/coherent_packed_loadstore.cpp \
	insns/float.cpp \
	insns/float_loadstore.cpp \
	insns/muldiv.cpp \
	insns/packed_arith.cpp \
	insns/packed_atomic.cpp \
	insns/packed_float.cpp \
	insns/packed_graphics.cpp \
	insns/packed_loadstore.cpp \
	insns/packed_mask.cpp \
	insns/packed_trans.cpp \
	insns/zifencei.cpp \
	memory/load.cpp
