stages:
  - build
  - package

include:
  - project: 'software/conan/conan-ci-pipelines-common'
    file: 'conan-config.yaml'
  - project: 'software/conan/conan-ci-pipelines-common'
    file: 'build.yaml'
  - project: 'software/conan/conan-ci-pipelines-common'
    file: 'package.yaml'

#### build

build:conan:
  stage: build
  except:
    - master
    - tags
  variables:
    DOCKER_IMAGE: conanio/${COMPILER}
  parallel:
    matrix:
      - COMPILER: [ gcc7 ]
        BUILD_TYPE: [ Release, Debug ]
      - COMPILER: [ clang10 ]
        BUILD_TYPE: [ Release, Debug ]
  script:
    - conan install .. -s build_type=${BUILD_TYPE} -o g3log:use_dynamic_logging_levels=True --build missing
    - cmake -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -G Ninja ..
    - ninja

#### package

package:
  stage: package
  only:
    - master
    - tags
  variables:
    DOCKER_IMAGE: conanio/${COMPILER}${COMPILER_VERSION}
    CONAN_OPTIONS: "g3log:use_dynamic_logging_levels=True"
  parallel:
    matrix:
      - COMPILER: [ gcc ]
        COMPILER_VERSION: [ 7 ]
        CONAN_GCC_VERSIONS: [ 7 ]
      - COMPILER: [ clang ]
        COMPILER_VERSION: [ 10 ]
        CONAN_CLANG_VERSIONS: [ 10 ]
  script:
    - ./conan/ci/package.sh
