#ifndef __BL2_TASK_PRIORITIES_H__
#define __BL2_TASK_PRIORITIES_H__

#define FLASHFS_DRIVER_TASK_PRIORITY 1
#define VAULTIP_DRIVER_TASK_PRIORITY 1
#define MAIN_TASK_PRIORITY           1
#define SMBUS_TASK_PRIORITY          1

#endif
