#!/bin/bash -ex

export REPOROOT=`pwd`
echo "REPOROOT is $REPOROOT"

# Update and clean the repo
#git pull -r --prune --recurse-submodules
git clean -fdx

# FIXME SW-1770 that should be automated as part of device-fw build
# build the tools
# Code Signing Tool
cd ${REPOROOT}/firmware-tools/code-signing-tools
mkdir -p build && cd build
cmake ..
make -j

# FIXME SW-1771 the below should be done as part of the regular device-fw buidl
# ET Flash tool
cd ${REPOROOT}/firmware-tools/esperanto-flash-tool
mkdir -p build && cd build
cmake ..
make -j

# Build the Firwmare
cd ${REPOROOT}
mkdir -p build install && cd build
cmake .. -DCMAKE_INSTALL_PREFIX=../install
make doc
make -j $(nproc)
make -j $(nproc) install

# Sign the Image
cd ${REPOROOT}
scripts/sign_flash_image
