#ifndef __ESPERANTO_FLASH_TOOL_H__
#define __ESPERANTO_FLASH_TOOL_H__

#include <stdint.h>
#include <stdbool.h>

//#define offsetof(st, m) ((size_t)&(((st *)0)->m))

typedef enum ESPERANTO_FLASH_TOOL_COMMAND {
    ESPERANTO_FLASH_TOOL_COMMAND_INVALID = 0,
    ESPERANTO_FLASH_TOOL_COMMAND_CREATE,
    ESPERANTO_FLASH_TOOL_COMMAND_VIEW,
    ESPERANTO_FLASH_TOOL_COMMAND_EXTRACT_FILE,
    ESPERANTO_FLASH_TOOL_COMMAND_EXTRACT_ALL_FILES,
    ESPERANTO_FLASH_TOOL_COMMAND_REPLACE
} ESPERANTO_FLASH_TOOL_COMMAND_t;

typedef enum CREATE_IMAGE_ARGS {
    CREATE_IMAGE_ARGS_COMMAND,
    CREATE_IMAGE_ARGS_PARTITION_FILE_PATH,
    CREATE_IMAGE_ARGS_TEMPLATE_PATH,
    CREATE_IMAGE_ARGS_TOTAL_COUNT
} CREATE_IMAGE_ARGS_t;

typedef enum VIEW_IMAGE_ARGS {
    VIEW_IMAGE_ARGS_COMMAND,
    VIEW_IMAGE_ARGS_IMAGE_FILE_PATH,
    VIEW_IMAGE_ARGS_TOTAL_COUNT
} VIEW_IMAGE_ARGS_t;

typedef enum EXTRACT_FILE_ARGS {
    EXTRACT_FILE_IMAGE_ARGS_COMMAND,
    EXTRACT_FILE_ARGS_IMAGE_FILE_PATH,
    EXTRACT_FILE_ARGS_BASE_COUNT
} EXTRACT_FILE_ARGS_t;

typedef enum EXTRACT_ALL_FILES_ARGS {
    EXTRACT_ALL_FILES_IMAGE_ARGS_COMMAND,
    EXTRACT_ALL_FILES_ARGS_IMAGE_FILE_PATH,
    EXTRACT_ALL_FILES_ARGS_EXTRACTED_FILES_FOLDER_PATH,
    EXTRACT_ALL_FILES_ARGS_TOTAL_COUNT
} EXTRACT_ALL_FILES_ARGS_t;

typedef enum REPLACE_FILE_ARGS {
    REPLACE_FILE_IMAGE_ARGS_COMMAND,
    REPLACE_FILE_ARGS_IMAGE_FILE_PATH,
    REPLACE_FILE_ARGS_BASE_COUNT
} REPLACE_FILE_ARGS_t;

typedef struct ARGUMENTS {
    ESPERANTO_FLASH_TOOL_COMMAND_t command;
    uint32_t args_max_count;
    uint32_t args_count;
    char **args;
    bool silent;
    bool verbose;
    bool partition_mode;
    bool use_region_ids;
    char * partition_index;
    char * output_path;
} ARGUMENTS_t;

extern ARGUMENTS_t g_arguments;

#endif // __ESPERANTO_FLASH_TOOL_H__
