softfloat_hdrs = \
	softfloat/internals.h \
	softfloat/platform.h \
	softfloat/primitives.h \
	softfloat/primitiveTypes.h \
	softfloat/softfloat.h \
	softfloat/softfloat_types.h \
	softfloat/specialize.h

softfloat_c_srcs = \
	softfloat/f128_add.c \
	softfloat/f128_classify.c \
	softfloat/f128_div.c \
	softfloat/f128_eq.c \
	softfloat/f128_eq_signaling.c \
	softfloat/f128_isSignalingNaN.c \
	softfloat/f128_le.c \
	softfloat/f128_le_quiet.c \
	softfloat/f128_lt.c \
	softfloat/f128_lt_quiet.c \
	softfloat/f128_mulAdd.c \
	softfloat/f128_mul.c \
	softfloat/f128_rem.c \
	softfloat/f128_roundToInt.c \
	softfloat/f128_sqrt.c \
	softfloat/f128_sub.c \
	softfloat/f128_to_f16.c \
	softfloat/f128_to_f32.c \
	softfloat/f128_to_f64.c \
	softfloat/f128_to_i32.c \
	softfloat/f128_to_i32_r_minMag.c \
	softfloat/f128_to_i64.c \
	softfloat/f128_to_i64_r_minMag.c \
	softfloat/f128_to_ui32.c \
	softfloat/f128_to_ui32_r_minMag.c \
	softfloat/f128_to_ui64.c \
	softfloat/f128_to_ui64_r_minMag.c \
	softfloat/f16_add.c \
	softfloat/f16_div.c \
	softfloat/f16_eq.c \
	softfloat/f16_eq_signaling.c \
	softfloat/f16_isSignalingNaN.c \
	softfloat/f16_le.c \
	softfloat/f16_le_quiet.c \
	softfloat/f16_lt.c \
	softfloat/f16_lt_quiet.c \
	softfloat/f16_mulAdd.c \
	softfloat/f16_mul.c \
	softfloat/f16_rem.c \
	softfloat/f16_roundToInt.c \
	softfloat/f16_sqrt.c \
	softfloat/f16_sub.c \
	softfloat/f16_to_f128.c \
	softfloat/f16_to_f32.c \
	softfloat/f16_to_f64.c \
	softfloat/f16_to_i32.c \
	softfloat/f16_to_i32_r_minMag.c \
	softfloat/f16_to_i64.c \
	softfloat/f16_to_i64_r_minMag.c \
	softfloat/f16_to_ui32.c \
	softfloat/f16_to_ui32_r_minMag.c \
	softfloat/f16_to_ui64.c \
	softfloat/f16_to_ui64_r_minMag.c \
	softfloat/f32_add.c \
	softfloat/f32_classify.c \
	softfloat/f32_div.c \
	softfloat/f32_eq.c \
	softfloat/f32_eq_signaling.c \
	softfloat/f32_isSignalingNaN.c \
	softfloat/f32_le.c \
	softfloat/f32_le_quiet.c \
	softfloat/f32_lt.c \
	softfloat/f32_lt_quiet.c \
	softfloat/f32_mul.c \
	softfloat/f32_mulAdd.c \
	softfloat/f32_rem.c \
	softfloat/f32_roundToInt.c \
	softfloat/f32_sqrt.c \
	softfloat/f32_sub.c \
	softfloat/f32_to_f128.c \
	softfloat/f32_to_f16.c \
	softfloat/f32_to_f64.c \
	softfloat/f32_to_i32.c \
	softfloat/f32_to_i32_r_minMag.c \
	softfloat/f32_to_i64.c \
	softfloat/f32_to_i64_r_minMag.c \
	softfloat/f32_to_ui32.c \
	softfloat/f32_to_ui32_r_minMag.c \
	softfloat/f32_to_ui64.c \
	softfloat/f32_to_ui64_r_minMag.c \
	softfloat/f64_add.c \
	softfloat/f64_classify.c \
	softfloat/f64_div.c \
	softfloat/f64_eq.c \
	softfloat/f64_eq_signaling.c \
	softfloat/f64_isSignalingNaN.c \
	softfloat/f64_le.c \
	softfloat/f64_le_quiet.c \
	softfloat/f64_lt.c \
	softfloat/f64_lt_quiet.c \
	softfloat/f64_mulAdd.c \
	softfloat/f64_mul.c \
	softfloat/f64_rem.c \
	softfloat/f64_roundToInt.c \
	softfloat/f64_sqrt.c \
	softfloat/f64_sub.c \
	softfloat/f64_to_f128.c \
	softfloat/f64_to_f16.c \
	softfloat/f64_to_f32.c \
	softfloat/f64_to_i32.c \
	softfloat/f64_to_i32_r_minMag.c \
	softfloat/f64_to_i64.c \
	softfloat/f64_to_i64_r_minMag.c \
	softfloat/f64_to_ui32.c \
	softfloat/f64_to_ui32_r_minMag.c \
	softfloat/f64_to_ui64.c \
	softfloat/f64_to_ui64_r_minMag.c \
	softfloat/i32_to_f128.c \
	softfloat/i32_to_f16.c \
	softfloat/i32_to_f32.c \
	softfloat/i32_to_f64.c \
	softfloat/i64_to_f128.c \
	softfloat/i64_to_f16.c \
	softfloat/i64_to_f32.c \
	softfloat/i64_to_f64.c \
	softfloat/s_add128.c \
	softfloat/s_add256M.c \
	softfloat/s_addCarryM.c \
	softfloat/s_addComplCarryM.c \
	softfloat/s_addMagsF128.c \
	softfloat/s_addMagsF16.c \
	softfloat/s_addMagsF32.c \
	softfloat/s_addMagsF64.c \
	softfloat/s_addM.c \
	softfloat/s_approxRecip_1Ks.c \
	softfloat/s_approxRecip32_1.c \
	softfloat/s_approxRecipSqrt_1Ks.c \
	softfloat/s_approxRecipSqrt32_1.c \
	softfloat/s_compare128M.c \
	softfloat/s_compare96M.c \
	softfloat/s_countLeadingZeros16.c \
	softfloat/s_countLeadingZeros32.c \
	softfloat/s_countLeadingZeros64.c \
	softfloat/s_countLeadingZeros8.c \
	softfloat/s_eq128.c \
	softfloat/s_le128.c \
	softfloat/s_lt128.c \
	softfloat/s_mul128By32.c \
	softfloat/s_mul128MTo256M.c \
	softfloat/s_mul128To256M.c \
	softfloat/s_mul64ByShifted32To128.c \
	softfloat/s_mul64To128.c \
	softfloat/s_mul64To128M.c \
	softfloat/s_mulAddF128.c \
	softfloat/s_mulAddF16.c \
	softfloat/s_mulAddF32.c \
	softfloat/s_mulAddF64.c \
	softfloat/s_negXM.c \
	softfloat/s_normRoundPackToF128.c \
	softfloat/s_normRoundPackToF16.c \
	softfloat/s_normRoundPackToF32.c \
	softfloat/s_normRoundPackToF64.c \
	softfloat/s_normSubnormalF128Sig.c \
	softfloat/s_normSubnormalF16Sig.c \
	softfloat/s_normSubnormalF32Sig.c \
	softfloat/s_normSubnormalF64Sig.c \
	softfloat/softfloat_raiseFlags.c \
	softfloat/softfloat_state.c \
	softfloat/s_propagateNaNF16UI.c \
	softfloat/s_propagateNaNF32UI.c \
	softfloat/s_propagateNaNF64UI.c \
	softfloat/s_propagateNaNF128UI.c \
	softfloat/s_remStepMBy32.c \
	softfloat/s_roundMToI64.c \
	softfloat/s_roundMToUI64.c \
	softfloat/s_roundPackMToI64.c \
	softfloat/s_roundPackMToUI64.c \
	softfloat/s_roundPackToF128.c \
	softfloat/s_roundPackToF16.c \
	softfloat/s_roundPackToF32.c \
	softfloat/s_roundPackToF64.c \
	softfloat/s_roundPackToI32.c \
	softfloat/s_roundPackToI64.c \
	softfloat/s_roundPackToUI32.c \
	softfloat/s_roundPackToUI64.c \
	softfloat/s_roundToI32.c \
	softfloat/s_roundToI64.c \
	softfloat/s_roundToUI32.c \
	softfloat/s_roundToUI64.c \
	softfloat/s_shiftRightJam128.c \
	softfloat/s_shiftRightJam128Extra.c \
	softfloat/s_shiftRightJam256M.c \
	softfloat/s_shiftRightJam32.c \
	softfloat/s_shiftRightJam64.c \
	softfloat/s_shiftRightJam64Extra.c \
	softfloat/s_shortShiftLeft128.c \
	softfloat/s_shortShiftLeft64To96M.c \
	softfloat/s_shortShiftRight128.c \
	softfloat/s_shortShiftRightExtendM.c \
	softfloat/s_shortShiftRightJam128.c \
	softfloat/s_shortShiftRightJam128Extra.c \
	softfloat/s_shortShiftRightJam64.c \
	softfloat/s_shortShiftRightJam64Extra.c \
	softfloat/s_shortShiftRightM.c \
	softfloat/s_sub128.c \
	softfloat/s_sub1XM.c \
	softfloat/s_sub256M.c \
	softfloat/s_subMagsF128.c \
	softfloat/s_subMagsF16.c \
	softfloat/s_subMagsF32.c \
	softfloat/s_subMagsF64.c \
	softfloat/s_subM.c \
	softfloat/ui32_to_f128.c \
	softfloat/ui32_to_f16.c \
	softfloat/ui32_to_f32.c \
	softfloat/ui32_to_f64.c \
	softfloat/ui64_to_f128.c \
	softfloat/ui64_to_f16.c \
	softfloat/ui64_to_f32.c \
	softfloat/ui64_to_f64.c
