include:
  - project: 'software/gitlab-ci-common'
    ref: eaa145e684411db579462b41feb7736c6ed0028c
    file:
      - 'pods/nano-pod.yaml'
      - 'pods/medium-pod.yaml'
      - 'jobs/generic-k8s-job.yaml'

  - project: 'software/gitlab-ci-common'
    ref: master
    file:
      - 'jobs/conan-jobs.yaml'

stages:
  - generate_build
  - build
  - test
  - deploy


###############################################################################
###############################################################################
###############################################################################

generate_build:conan:
  extends:
    - .pod_nano
    - .template_job
    - .template-conan-linux-ubuntu18.04-gcc7
  stage: generate_build

  variables:
    TIMEOUT: 15m

    CMD_BUILD: |
      cd conan
      python3 -m ci_build
  artifacts:
    expire_in: 1h 
    paths:
      - conan/build_pipeline.yml
      - conan/lockfiles_info.json

###############################################################################
###############################################################################
###############################################################################

build:conan:
  needs:
  - generate_build:conan
  stage: build
  trigger:
    include:
    - artifact: conan/build_pipeline.yml
      job: generate_build:conan
    strategy: depend

###############################################################################
###############################################################################
###############################################################################

test:conan:
  extends:
    - .pod_medium
    - .template_job
    - .template-conan-linux-ubuntu18.04-gcc7
  stage: test
  needs:
    - build:conan
  variables:
    TIMEOUT: 15m
    CMD_BUILD: |
      mkdir cmake-build-release
      cd cmake-build-release
      conan install .. -pr:b default -pr:h linux-ubuntu18.04-x86_64-gcc7-release -o esperantoTrace:with_tests=True
      cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake
      cmake --build .
      ctest . --verbose


###############################################################################
###############################################################################
###############################################################################

on_success:promote:
  extends:
    - .pod_nano
    - .template_job
    - .template-conan-linux-ubuntu18.04-gcc7
  stage: deploy
  needs:
    - generate_build:conan
    - build:conan
    - test:conan
  variables:
    PYTHONIOENCODING: utf-8
    CMD_BUILD: |
      cd conan
      python3 -m ci_promote