import:
  - path: '@ci@/ci-tools/templates/template-main-top-level.yaml'

parameters:
  SW_PLATFORM_BRANCH:
    description: SW-Platform branch to track
    type: string
    default_value: "origin/develop/system-sw"
  REPO_SSH_URL:
    description: Repository URL
    type: string
    default_value: "git@gitlab.esperanto.ai:software/device-minion-runtime.git"
  REPO_NAME:
    description: Repository name
    type: string
    default_value: "device-minion-runtime"
  RUN_ZEBU:
    description: Run Zebu Job
    type: bool
    default_value: true
  FORCE_CHILD_RETRIGGER:
    description: 'Forces all child jobs of the current job to retrigger even if smart-retrigger is being used'
    type: bool
    default_value: false

stages:
  CHECK_IN:
    cmds:
      - job: sw-platform/system-sw-integration/pipelines/device-firmware-checkin-tests
        parameters:
          BRANCH: "${SW_PLATFORM_BRANCH}"
          COMPONENT_COMMITS: "${COMPONENT_COMMITS},device-software/device-minion-runtime:${BRANCH}"
    exec_after: [DSL_JOB]

  FIRMWARE_TESTS_ZEBU_BEMU:
    cmds:
      - job: sw-platform/system-sw-integration/pipelines/firmware-tests-zebu-bemu
        parameters:
          BRANCH: "${SW_PLATFORM_BRANCH}"
          COMPONENT_COMMITS: "${COMPONENT_COMMITS},device-software/device-minion-runtime:${BRANCH}"
    exec_after: [CHECK_IN]

  FIRMWARE_AND_DM_TESTS_PCIE_SYSEMU:
    cmds:
      - job: sw-platform/virtual-platform/pipelines/firmware-and-dm-tests-pcie-sysemu-1dev
        parameters:
          BRANCH: "${SW_PLATFORM_BRANCH}"
          COMPONENT_COMMITS: "${COMPONENT_COMMITS},device-software/device-minion-runtime:${BRANCH}"
    exec_after: [CHECK_IN]

  JOB_RUNTIME:
    cmds:
      - job: sw-platform/runtime-integration/pipelines/runtime-checkin-tests-release
        parameters:
          BRANCH: "${SW_PLATFORM_BRANCH}"
          COMPONENT_COMMITS: "${COMPONENT_COMMITS},device-software/device-minion-runtime:${BRANCH}"
    exec_after: [CHECK_IN]


  JOB_CODE_QUALITY:
    cmds:
      - job: sw-platform/code-analysis/device-minion-runtime-sonarqube
        parameters:
          BRANCH: "${SW_PLATFORM_BRANCH}"
          GITLAB_SOURCE_BRANCH:
            raw_cmd: '"${env.gitlabSourceBranch}"'
          GITLAB_TARGET_BRANCH: 
            raw_cmd: '"${env.gitlabTargetBranch}"'
          GITLAB_MR_ID: 
            raw_cmd: '"${env.gitlabMergeRequestIid}"'
          COMPONENT_COMMITS: "${COMPONENT_COMMITS},device-software/device-minion-runtime:${BRANCH}"
    exec_after: [CHECK_IN]

  CLANG_CHECK:
    cmds:
      - job: sw-platform/system-sw-integration/pipelines/device-minion-runtime-clang-tests
        parameters:
          BRANCH: "${SW_PLATFORM_BRANCH}"
          COMPONENT_COMMITS: "${COMPONENT_COMMITS},device-software/device-minion-runtime:${BRANCH}"
    exec_after: [CHECK_IN]