import:
  - path: '@ci@/ci-tools/templates/template-main-top-level.yaml'

parameters:
  SW_PLATFORM_BRANCH:
    description: SW-Platform branch to track
    type: string
    default_value: "origin/master"

  REPO_SSH_URL:
    description: Repository URL
    type: string
    default_value: "git@gitlab.esperanto.ai:software/device-minion-runtime.git"

  REPO_NAME:
    description: Repository name
    type: string
    default_value: "device-minion-runtime"

stages:
  CHECK_IN:
    cmds:
      - job: sw-platform/system-sw-integration/pipelines/device-firmware-checkin-tests
        parameters:
          BRANCH: "${SW_PLATFORM_BRANCH}"
          COMPONENT_COMMITS: "${COMPONENT_COMMITS},device-software/device-minion-runtime:${BRANCH}"
    exec_after: [DSL_JOB]

  SW_PLATFORM:
    cmds:
      - job: sw-platform/sw-platform-checkin-top-level
        parameters:
          BRANCH: "${SW_PLATFORM_BRANCH}"
          COMPONENT_COMMITS: "${COMPONENT_COMMITS},device-software/device-minion-runtime:${BRANCH}"
    exec_after: [CHECK_IN]

