import:
  - path: '@ci@/ci-tools/templates/template-main-top-level.yaml'

parameters:
  SW_PLATFORM_BRANCH:
    description: SW-Platform branch to track
    type: string
    default_value: "origin/develop/runtime"
  REPO_SSH_URL:
    description: Repository URL
    type: string
    default_value: "git@gitlab.esperanto.ai:software/esperanto-tools-libs.git"
  REPO_NAME:
    description: Repository name
    type: string
    default_value: "esperanto-tools-libs"
  RUN_ZEBU:
    description: Run Zebu Job
    type: bool
    default_value: true

stages:
  CHECKOUT_SCM:
    cmds:
      - raw_cmd: |-
          script {
            currentBuild.getRawBuild().getExecutor().interrupt(Result.UNSTABLE)
            sleep(1)   // Interrupt is not blocking and does not take effect immediately.
          }
    exec_before: [r".*"]