import:
  - path: '@ci@/ci-tools/templates/template-main-top-level.yaml'

parameters:
  SW_PLATFORM_BRANCH:
    description: SW-Platform branch to track
    type: string
    default_value: "origin/develop/system-sw"
  REPO_SSH_URL:
    description: Repository URL
    type: string
    default_value: "git@gitlab.esperanto.ai:software/esperanto-tools-libs.git"
  REPO_NAME:
    description: Repository name
    type: string
    default_value: "esperanto-tools-libs"
  RUN_ZEBU:
    description: Run Zebu Job
    type: bool
    default_value: true

stages:
  JOB_RUNTIME:
    cmds:
      - job: sw-platform/runtime-integration/pipelines/runtime-checkin-tests
        parameters:
          BRANCH: "${SW_PLATFORM_BRANCH}"
          COMPONENT_COMMITS: "${COMPONENT_COMMITS},host-software/esperanto-tools-libs:${BRANCH}"
          PYTEST_RETRIES: "2"

  # to be enabled again with SW-4451; when the old runtime is wiped out
  # JOB_COVERAGE:
  #   cmds:
  #     - job: sw-platform/runtime-integration/pipelines/runtime-coverage-tests
  #       parameters:
  #         BRANCH: "${SW_PLATFORM_BRANCH}"
  #         COMPONENT_COMMITS: "${COMPONENT_COMMITS},host-software/esperanto-tools-libs:${BRANCH}"
  #         PYTEST_RETRIES: "2"

  # JOB_SANITIZER:
  #   cmds:
  #     - job: sw-platform/runtime-integration/pipelines/runtime-sanitizer-tests
  #       parameters:
  #         BRANCH: "${SW_PLATFORM_BRANCH}"
  #         COMPONENT_COMMITS: "${COMPONENT_COMMITS},host-software/esperanto-tools-libs:${BRANCH}"
  #         PYTEST_RETRIES: "2"

  JOB_DEVICE_MANAGEMENT:
    cmds:
      - job: sw-platform/system-sw-integration/pipelines/device-management-checkin-tests/
        parameters:
          BRANCH: "${SW_PLATFORM_BRANCH}"
          COMPONENT_COMMITS: "${COMPONENT_COMMITS},host-software/esperanto-tools-libs:${BRANCH}"
          PYTEST_RETRIES: "2"

  JOB_DEVICE_LAYER:
    cmds:
      - job: sw-platform/system-sw-integration/pipelines/device-layer-checkin-tests/
        parameters:
          BRANCH: "${SW_PLATFORM_BRANCH}"
          COMPONENT_COMMITS: "${COMPONENT_COMMITS},host-software/esperanto-tools-libs:${BRANCH}"
          PYTEST_RETRIES: "2"

  # Disable Zebu jobs in the checkin as default run
  # JOB_ZEBU:
  #  when:
  #    jenkins:
  #      all:
  #        - ${RUN_ZEBU}
  #    default:
  #      false
  #  cmds:
  #    - job: sw-platform/zebu/zebu-checkin-top-level
  #      parameters:
  #        BRANCH: "${SW_PLATFORM_BRANCH}"
  #        COMPONENT_COMMITS: "${COMPONENT_COMMITS},host-software/esperanto-tools-libs:${BRANCH}"
  #        TIMEOUT: "4"
  #        RUN_ZEBU: ${RUN_ZEBU}


