include:
  - project: 'software/gitlab-ci-common'
    ref: e30678edaf6fee2245513234e8d325fcf5f92baf
    file:
      - 'pods/nano-pod.yaml'
      - 'jobs/generic-k8s-job.yaml'
      - 'jobs/conan-jobs.yaml'
      - 'jobs/sw-platform-trigger.yaml'
      - 'jobs/check-top-of-master.yaml'

  - project: 'software/sw-platform'
    ref: develop/system-sw
    file:
      - 'gitlab-ci/system-sw/misc/verify-merge-request.yaml'

stages:
  - generate_build
  - build
  - test
  - deploy

workflow:
  rules:
    # Run this job when a tag is created manually
    - if: $CI_COMMIT_TAG
    # Do not execute the pipeline on a push event that doesn't happen to the master or main branch
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH'
      when: never
    # If any of the previous conditions are met, then execute the pipeline
    - when: always

variables:
  # These variables are consumed by the jobs from /jobs/sw-platform-trigger.yaml
  SW_PLATFORM_BRANCH: develop/system-sw
  PIPELINE_CI_SUBPROJECT: et-driver
  TRIG_ON_TAGS_PUSH: 'true'
  EXTRA_OPTION_SUBPROJECT: $CI_PIPELINE_SOURCE

###############################################################################
###############################################################################
###############################################################################

verify_project_changes:
  extends:
    - .template_job
    - .pod_nano
    - .verify_merge_request
  image: docker-sw-team.sc-artifactory1.esperanto.ai/convoke/centos-7.9.2009-et-sw-platform:0.3.7
  stage: .pre
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  variables:
    PROJ_VER_FILE_NAME: VERSION

###############################################################################
###############################################################################
###############################################################################

generate_build:conan:
  extends:
    - .pod_nano
    - .template_job
    - .template-conan-linux-ubuntu18.04-gcc7
  stage: generate_build

  variables:
    TIMEOUT: 15m

    CMD_BUILD: |
      cd conan
      python3 -m ci_build
  artifacts:
    expire_in: 4h
    paths:
      - conan/build_pipeline.yml
      - conan/lockfiles_info.json


###############################################################################
###############################################################################
###############################################################################

build:conan:
  needs:
  - generate_build:conan
  stage: build
  trigger:
    include:
    - artifact: conan/build_pipeline.yml
      job: generate_build:conan
    strategy: depend

###############################################################################
###############################################################################
###############################################################################

# integration testing with sw-platform
#
# This is automatically done thanks to this included file:
#   /jobs/sw-platform-trigger.yaml

###############################################################################
###############################################################################
###############################################################################

on_success:promote:
  extends:
    - .pod_nano
    - .template_job
    - .template-conan-linux-ubuntu18.04-gcc7
  stage: deploy
  needs:
    - generate_build:conan
    - build:conan
    - meta-trigger
  variables:
    PYTHONIOENCODING: utf-8
    CMD_BUILD: |
      cd conan
      python3 -m ci_promote
