include:
  - project: 'software/gitlab-ci-common'
    ref: d5cdfe0b106402d8c897d418ac8a226d0a0cafab
    file:
      - rules/generic-workflow-conan.yaml
      - pods/nano-pod.yaml
      - jobs/generic-k8s-job.yaml
      - rules/exec_maybe_interactively.yaml
      - jobs/check-top-of-master.yaml
      - jobs/sw-platform-trigger.yaml
  
  - project: 'software/gitlab-ci-common'
    ref: master
    file:
      - 'jobs/conan-jobs.yaml'
  
  - project: 'software/sw-platform'
    ref: develop/system-sw
    file:
      - 'gitlab-ci/system-sw/misc/verify-merge-request.yaml'

stages:
  - generate_build
  - build
  - test
  - deploy

default:
  interruptible: true

variables:
  # These two variables are consumed by the jobs from /jobs/sw-platform-trigger.yaml
  SW_PLATFORM_BRANCH: develop/system-sw
  PIPELINE_CI_SUBPROJECT: deviceManagementApplication

###############################################################################
###############################################################################
###############################################################################

verify_project_changes:
  extends:
    - .template_job
    - .pod_nano
    - .verify_merge_request
  image: docker-sw-team.sc-artifactory1.esperanto.ai/convoke/centos-7.9.2009-et-sw-platform:0.3.7
  stage: .pre
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  variables:
    PROJ_VER_FILE_NAME: CMakeLists.txt


clang-format:
  extends:
    - .template_job
    - .pod_nano
  image: docker-sw-team.sc-artifactory1.esperanto.ai/convoke/centos-7.9.2009-et-sw-platform:0.3.7
  stage: .pre
  variables:
    CMD_SCRIPT: |
      git fetch origin master
      git clang-format --style file --diff origin/master --extensions cc,cpp,h
      git clang-format --style file --diff origin/master --extensions cc,cpp,h | grep -q -e "clang-format did not modify any files$" -e "^no modified files to format$"


###############################################################################
###############################################################################
###############################################################################

generate_build:conan:
  extends:
    - .pod_nano
    - .template_job
    - .template-conan-linux-ubuntu18.04-gcc7
  stage: generate_build

  variables:
    TIMEOUT: 15m
    PYTHONIOENCODING: utf-8

    CMD_BUILD: |
      cd conan
      python3 -m ci_build

  artifacts:
    expire_in: 1h
    paths:
      - conan/build_pipeline.yml
      - conan/lockfiles_info.json

###############################################################################
###############################################################################
###############################################################################

build:conan:
  extends:
    - .exec_maybe_interactively
  stage: build
  needs:
    - generate_build:conan
  trigger:
    include:
    - artifact: conan/build_pipeline.yml
      job: generate_build:conan
    strategy: depend

###############################################################################
###############################################################################
###############################################################################

# integration testing with sw-platform
#
# This is automatically done thanks to this included file:
#   /jobs/sw-platform-trigger.yaml

###############################################################################
###############################################################################
###############################################################################

on_success:promote:
  extends:
    - .pod_nano
    - .template_job
    - .template-conan-linux-ubuntu18.04-gcc7
  stage: deploy
  needs:
    - generate_build:conan
    - build:conan
    - meta-trigger

  variables:
    PYTHONIOENCODING: utf-8
    CMD_BUILD: |
      cd conan
      python3 -m ci_promote
