include:
  - project: 'software/gitlab-ci-common'
    ref: d5cdfe0b106402d8c897d418ac8a226d0a0cafab
    file:
      - rules/generic-workflow-conan.yaml
      - pods/nano-pod.yaml
      - jobs/generic-k8s-job.yaml
      - rules/exec_maybe_interactively.yaml
      - jobs/check-top-of-master.yaml
      - jobs/sw-platform-trigger.yaml

stages:
  - generate_build
  - build
  - test
  - deploy

default:
  interruptible: true

variables:
  # These two variables are consumed by the jobs from /jobs/sw-platform-trigger.yaml
  SW_PLATFORM_BRANCH: develop/system-sw
  PIPELINE_CI_SUBPROJECT: deviceManagementApplication

###############################################################################
###############################################################################
###############################################################################

clang-format:
  extends:
    - .template_job
    - .pod_nano
  image: docker-sw-team.sc-artifactory1.esperanto.ai/convoke/centos-7.9.2009-et-sw-platform:0.3.7
  stage: .pre
  variables:
    CMD_SCRIPT: |
      git fetch origin master
      git clang-format --style file --diff origin/master --extensions cpp,h
      git clang-format --style file --diff origin/master --extensions cpp,h | grep -q -e "clang-format did not modify any files$" -e "^no modified files to format$"

###############################################################################
###############################################################################
###############################################################################

# integration testing with sw-platform
#
# This is automatically done thanks to this included file:
#   /jobs/sw-platform-trigger.yaml

###############################################################################
###############################################################################
###############################################################################
